### ISSUE TITLE
Using "Chosen" jQuery plugin in backend combobox

### ISSUE THREAD

**Issue by ghazispeakserve** [forkcms/forkcms#1007]
We have implemented [Chosen jQuery plugin](https://github.com/harvesthq/chosen) in some backend action to enable live filtering and we found it quiet useful.

Do you think is worth to add it to the open source tree?

![chosen](https://cloud.githubusercontent.com/assets/4991088/5460718/5dc92826-8565-11e4-89aa-bfdae31e901c.png)

**Comment by jeroendesloovere** [comment]
I propose integrating it
and letting the developer activate it in his custom modules, by adding a pre-defined CSS class to a dropdown.

**Comment by guytarded** [comment]
+1!

**Comment by tijsverkoyen** [comment]
I will close this issue, as someone is busy implementing Bootstrap in the backend. If this is completed we can reopen the discussion.
