### ISSUE TITLE
User API and Backend acces logic separation

### ISSUE THREAD

**Issue by ghazispeakserve** [forkcms/forkcms#1017]
Actually when a user call "Core.GetApiKey" API method he is not active he gets "Can't authenticate you."

Actually Core\Engine\Api.php call Authentication::loginUser with that code 

```php
        // check in database (is the user active and not deleted, are the email and password correct?)
        $userId = (int) $db->getVar(
            'SELECT u.id
             FROM users AS u
             WHERE u.email = ? AND u.password = ? AND u.active = ? AND u.deleted = ?
             LIMIT 1',
            array($login, $passwordEncrypted, 'Y', 'N')
        );
```

Instead of checking "u.active" the "api_access" settings should be checked and should be separated from active logic. A user can have only an API access and he does not need to have backend access to user the API.

**Comment by WouterSioen** [comment]
Those core calls are implemented to be used by persons who have access to the backend. If you want a custom authentication system in your project, you're totally free to implement this, but we won't change this in the Fork Core.
