### ISSUE TITLE
Can't install ForkCMS onto vagrant scotch-box

### ISSUE THREAD

**Issue by thegreatanon** [forkcms/forkcms#1020]
Hi, 
I'm trying to install ForkCMS onto a (clean) [vagrant scotch-box](https://scotch.io/bar-talk/introducing-scotch-box-a-vagrant-lamp-stack-that-just-works), but I'm stuck in an installation loop. I get to the last page and get redirected to the start of the installer wizard.

I've tried using the three different suggested installation methods:
* `composer create-project forkcms/forkcms .`
* downloading from git and running `composer install -o`
* Downloading the .zip file.

I can access my MySQL database with my supplied credentials, but ForkCMS doesn't seem to write anything into it. If I enter the wrong credentials, it correctly identifies them as incorrect. 

When running the `composer` command I first got some permission denied errors. `chmod`-ing didn't work, I had to edit the vagrantfile to set the permissions there, and reboot. I've set file and folder permissions to 777, but the problem persists.

I've tried this on both a Mac and a Win7, (but this shouldn't matter because vagrant == VM).
I've posted this issue to [ForkCMS forum](http://www.fork-cms.com/community/forum/detail/unable-to-install-forkcms-on-vagrant-scotch-box) where Jesse confirmed the issue.

**Comment by ghazispeakserve** [comment]
Hello,
What version of PHP are you using?

**Comment by jessedobbelaere** [comment]
Scotch box uses php 5.5.

I also tried to install Fork CMS into scotch box and got the same issue. After the last installation step, the database stays empty and no parameters.yml file is created. So you'll get redirected back to the installer when you visit the website. I imported a new Fork CMS database dump + parameters.yml file and I got to see the website. But when you try to login into the backend, you're stuck at the login panel. If you try to clear the cache, symfony console throws a "can't establish database connection" error. 

Scotch box seems like a solid LAMP vagrant box though.

**Comment by thegreatanon** [comment]
On the last screen of the installation, you are shown your email and password. Using scotch-box these fields are empty. Probably because these are loaded from the DB?

I've tried the installation using [OpenMinds Sneakers](https://github.com/openminds/sneakers) vagrant setup and this works without problems (As Jesse suggested on the [ForkCMS support forum](http://www.fork-cms.com/community/forum/detail/unable-to-install-forkcms-on-vagrant-scotch-box)).

**Comment by WouterSioen** [comment]
I guess that it is a permissions issue. 
In the last visible step of the installation, Fork writes the parameters.yml file. Then, it redirects to an action (that doesn't give any output) and installs Fork based on the data in the parameters.yml file.

I don't have time to look into it right now, but It looks like Fork isn't able to write the parameters.yml file in the app/config folder.

**Comment by thegreatanon** [comment]
Hi Wouter,
I've checked the app/config folder and there is no `parameters.yml` file. Only a `parameters_install.yml` and a `parameters.yml.dist`file.

In the vragrantfile there's the line:
`config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=777"]`
Which sets the permissions of all files/folders to 777 (just for testing). When I SSH into the box I can confirm that every file and folder in the /var/www directory has all permissions.

**Comment by dubgeiser** [comment]
There is idd some form of permission problem going on when using scotchbox.
I really don't know the tool, chmod -R 777 everything does not yield the desired result, that's for sure... BUT; you can change Apache's User and Group values in /etc/apache2/apache2.conf so it that it runs as the vagrant user, so in /etc/apache2/apache2.conf change:

    User ${APACHE_RUN_USER}
    Group ${APACHE_RUN_GROUP}

into:

    User vagrant
    Group vagrant

then restart apache:

    sudo /etc/init.d/apache2 restart

Good luck and have fun!
