### ISSUE TITLE
Use Symfony2 Intl Component

### ISSUE THREAD

**Issue by ghazispeakserve** [forkcms/forkcms#1021]
Don't ForkCMS need to use Symfony2 Intl component instead of the outdated Spoon? As example for fetching countries and languages.

**Comment by WouterSioen** [comment]
That would be awesome.

**Comment by ghazispeakserve** [comment]
What if I prepare a pull request for that? or will we need to wait until Doctrine intergation?

**Comment by WouterSioen** [comment]
I think you can already create a pull request without doctrine integration.

**Comment by ghazispeakserve** [comment]
A question about languages.

Actually when calling this method:

```php
Intl::getLanguageBundle()->getLanguageNames(BL::getInterfaceLanguage());
```

we get more languages than ones installed in Fork CMS. Should we keep it like it is or add a filter?

**Comment by ghazispeakserve** [comment]
My question has no sense because ForkCMS supports more languages than Spoon.
