### ISSUE TITLE
selecting module-actie in instellingen makes the page invisible in front-end

### ISSUE THREAD

**Issue by bramds** [forkcms/forkcms#1023]
If you selected "Gebruik deze pagina als module-actie." in the "instellingen" tab of a page, this page disappears in the frontend navigation.

**Comment by WouterSioen** [comment]
I think thats exactly the exactly the point of this checkbox.

**Comment by bramds** [comment]
My mistake, i had the use of this feature mixed up.  I clicked the feature in the mainpage and not the detail page.

**Comment by WouterSioen** [comment]
No problem. Thanks for the clarification.
