### ISSUE TITLE
Page internal link not redirecting

### ISSUE THREAD

**Issue by ghazispeakserve** [forkcms/forkcms#1024]
In backend after a page redirection is set to "internal link", when trying to navigate to this page it does not get redirected to the selected one.

![redirect](https://cloud.githubusercontent.com/assets/4991088/5677515/ef3b1bd6-97e7-11e4-9913-719c475e70c6.png)

**Comment by jeroendesloovere** [comment]
Hi @ghazispeakserve 
Sorry to hear that it doesn't work.
Did you already tried to clear the browser cache? These things get stuck in there.
If that didn't work for you, can you answer these:
* What Fork CMS version are you using?
* Is debugging enabled?

**Comment by ghazispeakserve** [comment]
Hi,

I am using Fork CMS 3.8.4 with cleaned cache and debug is enabled. I have tried the same thing under prod environment and debug disabled but I have the same issue.

**Comment by WouterSioen** [comment]
It are permanent redirects so it's possible that your browser has cached some of these.
We'll need to look into this. Have you checked if the redirect is available in the navigation cache file?

**Comment by ghazispeakserve** [comment]
I am sure it is not a browser problem. I have made the same tests under Opera and Chrome and I obtain the same result. And in the menu link I get the original link instead of the redirection one.

**Comment by WouterSioen** [comment]
Have you checked if the redirect is available in the navigation cache file?

**Comment by ghazispeakserve** [comment]
How can I check it? What value should I find?

**Comment by WouterSioen** [comment]
You can find it in src/Frontend/Cache/Navigation/navigation_<language>.php It should state 'redirect_page_id'

**Comment by ghazispeakserve** [comment]
There is no "redirect_page_id" in the concerned entry but there is a "tree_type" with "redirect" value

```php
$navigation['page'][426][486]['page_id'] = 486;
$navigation['page'][426][486]['url'] = 'contact-us';
$navigation['page'][426][486]['full_url'] = '/support/contact-us';
$navigation['page'][426][486]['title'] = 'Contact Us';
$navigation['page'][426][486]['navigation_title'] = 'Contact Us';
$navigation['page'][426][486]['has_extra'] = false;
$navigation['page'][426][486]['no_follow'] = false;
$navigation['page'][426][486]['hidden'] = false;
$navigation['page'][426][486]['extra_blocks'] = array();
$navigation['page'][426][486]['has_children'] = false;
$navigation['page'][426][486]['tree_type'] = 'redirect';
```

**Comment by WouterSioen** [comment]
Looks like a bug in the cache builder class.

**Comment by ghazispeakserve** [comment]
The issue in CacheBuider is found, fixed and tested.

**Comment by WouterSioen** [comment]
Thanks for fixing this, will be included in the next release.
