### ISSUE TITLE
"RecursiveDirectoryIterator too many open files" while editing a user group

### ISSUE THREAD

**Issue by jacob-v-dam** [forkcms/forkcms#1025]
When you want to edit a group you gat the error "RecursiveDirectoryIterator too many open files"

![RecursiveDirectoryIterator too many open files](https://cloud.githubusercontent.com/assets/310526/5678565/22506510-97f4-11e4-8fa1-8c3e61a4b32c.png)

**Comment by tijsverkoyen** [comment]
@jacob-v-dam poke

**Comment by jacob-v-dam** [comment]
It seems to work right now. I removed unnecessary modules and did something with ulimit (removed a file).
