### ISSUE TITLE
Feature: Formbuilder captcha & layout

### ISSUE THREAD

**Issue by vytenizs** [forkcms/forkcms#1026]
Fork CMS form builder lacks captcha. Whole formbuilder module code looks like crap. Should be refactored. And should be cool to have layouts for FormBuilder because very often designers offers solutions that fields are floated left or right.

**Comment by jessedobbelaere** [comment]
I integrated a captcha once, but it was hardcoded, not as an element that you can insert into formbuilder. It also lacks placeholder text for each input field. I agree that the formbuilder could be a lot better/advanced. I just remembered that I have a pull request that I need to finish that integrates date & time fields into formbuilder... Adding placeholders shouldn't be that hard too

**Comment by vytenizs** [comment]
I think form builder is a cool module, but it needs total refactoring. Yep in some cases CSS does its job. For example if i want to put my fields scattered into 3 separate columns. And if u want clean HTML u wont get away with CSS solution :). I saw there is some timeout protection for FormBuilder, so captcha is not very high priority.

**Comment by bart-lysander** [comment]
Please don't integrate a captcha. ForkCMS is a user frendly CMS. Captcha's are not. There are other not-well known (luckily) ways to prevent bot posting.

**Comment by vytenizs** [comment]
I do not say that captcha should be required field. It should exist and should be optional. Some clients just request captcha and you cant argue with them. :)

**Comment by bart-lysander** [comment]
No need for a captcha to exists. Use something better.

1 - simple:

* Put a text input field inside the form.
* Make this field "invisible using CSS style".
* In the form validation check that the field is still empty.

This is a simple way and I have seen bots that get around this that randomly select fields to fill in a form and leave some untouched.

2 - advanced:
* Generate some kind of token, put it in a hidden form field called "serial".
* Make a javascript function that appends a " " (space) character at the end of the name for the serial input field.
* This javascript function should only be executed once and only when the user puts focus on a text input field (or use some other client event that bots don't have, like keypress).
* In the form validation check for a field called "serial_" (the space gets converted to an underscore in php) and validate the token/serial.

If a bot developer is debugging this kind of form post, he is most likely to miss an extra space that is added to the serial field.
I have used this technique in non-forkcms websites for the past years with very good results. When I tell a client that using a captcha is not safe and that there is a better replacement for it, they don't want the captcha anymore.

For statistics you should count hams/spams and keep record of all post data (or at least the last 14 days or so).

(I will erase this info tomorrow this to prevent bot developers from knowing this)

**Comment by vytenizs** [comment]
Thanks for info :) Ofc there are lots of ways to deal with bots...

**Comment by WouterSioen** [comment]
I completely agree that the FormBuilder module should be refactored. I think some kind of strategy pattern would be a great help here to clean this up.

**Comment by ghazispeakserve** [comment]
I was telling myself the same thing days ago but for another reason. I did not find form validation very hand and I think we should take a look at https://github.com/Respect/Validation to see how we can add it to Fork.

**Comment by WouterSioen** [comment]
I think it would be better to use the Symfony validator (https://github.com/symfony/Validator) Since we're moving towards the Symfony framework.

**Comment by vytenizs** [comment]
I think while fork wont be full symfony2 integrated, there will be only waste of time with module refactoring. Because after that everything will change. All features i suggest is long term and should be placed after symfony2 integration.
