### ISSUE TITLE
Responsive backend for mobile devices

### ISSUE THREAD

**Issue by vytenizs** [forkcms/forkcms#1027]
Hi. It is impossible to use Fork CMS with mobile devices. A lot of clients complaining. I just wanna know if u guys considering changing backend design or at least make it more responsive. I could help, but i wanna know that my job wont go to the garbage can. So we need a discussion.

- [x] Core (Requires testing: High)
- [x] Authentication (Requires testing: Low)
- [x] Dashboard (Requires testing: High)
- [x] Extensions (Requires testing: Medium)
- [x] Groups (Requires testing: Low)
- [x] Locale (Requires testing: Medium)
- [x] Pages (Requires testing: High)
- [x] Settings (Requires testing: Low)
- [x] Users (Requires testing: Low)
- [x] Analytics (Requires testing: Low)
- [x] Blog (Requires testing: Low)
- [x] ContentBlocks (Requires testing: Low)
- [x] Error (Requires testing: Low)
- [x] Faq (Requires testing: Low)
- [x] FormBuilder (Requires testing: Medium)
- [x] Location (Requires testing: Low)
- [x] Mailmotor (Requires testing: High)
- [x] Profiles (Requires testing: Low)
- [x] Search (Requires testing: Low)
- [x] Tags (Requires testing: Low)

**Comment by jessedobbelaere** [comment]
The core dev's are working on Symfony components in their spare time. But [This is what WouterSioen said in another issue.](https://github.com/forkcms/forkcms/issues/939#issuecomment-62405153)

So I guess after the whole Symfony migration, there will be time to work on the backend theme. Maybe then it's time to rewrite the whole backend (and frontend?) theme with up-to-date code and maybe relying on a framework (bootstrap, zurb, ...) so it's easier for developers to modify things. 

But if you can make the backend responsive, whether it is very basic or thorough, I think that would make a nice update until there's time for a major overhaul. GhaziSpeakServe also wanted to help to make the backend a bit responsive (see issue thread from link above).

**Comment by vytenizs** [comment]
I personally dislike bootstrap and i love Foundation. However would love to see more modern and responsive backend. Ofc Forks has to switch to TWIG first, otherwise it would be huge waste of time. I just wanted to create an issue for later to discuss.

**Comment by vytenizs** [comment]
What do you think about ZURB foundation? I will refactor whole backend no matter what, because we need responsive solution for our clients. So if you help me decide what solution to go for i would be able to share my work with u. I would prefer totally uncustomized ZURB Foundation or at least https://www.foundationdeck.com/templates/smarteradmin/. Please reply ASAP.

**Comment by WouterSioen** [comment]
With the Fork Core developers, we're more tempted to use Twitter Boostrap, because it's by far the most popular frontend framework at the moment.

**Comment by vytenizs** [comment]
No problem. Any templates u guys have in mind? What about Generic Bootstrap 3 http://vinceg.github.io/Bootstrap-Admin-Theme-3/index.html

**Comment by vytenizs** [comment]
Maybe i just wasting my time and u wanna do it by urselves?

**Comment by WouterSioen** [comment]
I think the default bootstrap theme could be a great start? What do others think? @forkcms/developers ?

I don't have time at the moment to do such an implementation, but feel free to do a pull request!

**Comment by vytenizs** [comment]
I will do it anyway and if we will find a compromise i will make PR. Just hand me link to template u wish to use as your backend design. Waiting for reply.

**Comment by WouterSioen** [comment]
I'd just use the default bootstrap3 theme to begin with. We can always change the theme after implementation too, if the default bootstrap classes are used.

**Comment by vytenizs** [comment]
I think default bootstrap would be a best solution. Because u can implement anything u want after classes are used as u say. I tried to make current backend responsive, but its not worth it.

**Comment by MathiasDewelde** [comment]
Default bootstrap theme would be great!

We could even make a setting to modify the look and feel by compiling the (bootstrap) less file with lessphp.

**Comment by ghazispeakserve** [comment]
Please note of some considerations to take like we are using JQuery UI components. A link http://stackoverflow.com/questions/9782622/twitter-bootstrap-vs-jquery-ui

**Comment by vytenizs** [comment]
Yep, that could be a problem... :)

**Comment by ghazispeakserve** [comment]
Another comment about this issue, we have chosen Fork CMS because its backend is not in bootstrap. We have gone through a lot of CMS testing before we make our choice, we realy disliked the fact that a lot of them uses a bootstrap backend in its minimal format.

That does not mean that bootstrap is not good, but that means that you have to add a lot of jQuery and bootstrap plug-ins to have a decent user experience, and that it what he have done in another pure PHP project.

We really like jQuery, a solution would be https://github.com/jquery-ui-bootstrap/jquery-ui-bootstrap

I have also worked with Zurb Foundation, it is well known CSS framework and widely used, its JavaScript library is more powerful than boostrap one and it is compatible with jQuery UI.

If the final decision taken by the community was to choose a CSS framework I really suggest not keeping the default theme and at least consider migrating the light bluish current interface, this is what we should be done in terms of users experience, updates should be noticeable but not shocking.

**Comment by vytenizs** [comment]
I personally dislike Bootstrap and i would choose ZURB Foundation, but Fork CMS chooses to use bootstrap.

**Comment by davelens** [comment]
I no longer use Fork on a daily basis, but these are my €0.02. My personal preference has reverted from Bootstrap to Foundation recently (JS reasons, it's been mentioned here earlier and I back that). I know most core devs have mostly Bootstrap experience, so that will probably weigh in a lot.
But really, either one would result in one less thing for the core team to maintain, both frameworks are developer-friendly, and people can easily theme it if they want to change look & feel.

Practically, both are very flexible and will render quick results for about 80-90% of the backend. Having the menu, sidebar and content boxes in a responsive grid won't be hard work. I'd try and save various JS features like the tagbox until last, and keep their markup separate of the backend as much as possible.

I suspect the Pages module might give a bit of a headache. The dynamic tree is made with JStree, which has [a Bootstrap 3 theme](https://github.com/orangehill/jstree-bootstrap-theme). Choosing Bootstrap would probably save work here.

**Comment by jessedobbelaere** [comment]
I think over the years developers & clients are gotten used to the backend interface, so I'm not a fan of drastic visual changes in UI (different theme and such). Ideally, the new backend could be a polished version of the current backend. A backend based upon Boostrap or Zurb & with responsive design, but using the same layout structure, color palette, etc. And someone can easily make a totally different theme if he wants by using Zurb/Bootstrap. 

Either way, like vytenizs said, this should probably wait until twig is implemented? (Or do things now and convert the backend to twig when it's implemented.)

**Comment by vytenizs** [comment]
Thought about that... But i thought that this can wait and it cant and will not be as hard to implement TWIG. Here is what ive done so far.
![settings - my website - fork cms - mozilla firefox_003](https://cloud.githubusercontent.com/assets/3973894/5808294/9c0058d2-a034-11e4-8c4a-5cbc2cb2009a.png)

**Comment by WouterSioen** [comment]
Thats actually not bad :+1:

Op maandag 19 januari 2015 heeft vytenizs <notifications@github.com> het
volgende geschreven:

**Comment by vytenizs** [comment]
Some progress...
![settings - forkcms com - fork cms - mozilla firefox_004](https://cloud.githubusercontent.com/assets/3973894/5810223/78bb3920-a04b-11e4-9ca6-2d2dc64c5fd7.png)
![settings - forkcms com - fork cms - mozilla firefox_005](https://cloud.githubusercontent.com/assets/3973894/5810221/78ba41b4-a04b-11e4-86d8-5fc199ecb541.png)
![settings - forkcms com - fork cms - mozilla firefox_006](https://cloud.githubusercontent.com/assets/3973894/5810222/78ba7a6c-a04b-11e4-9e40-99717d4ed3d7.png)

**Comment by MathiasDewelde** [comment]
:+1:

**Comment by vytenizs** [comment]
Settings -> General is almost done. Have faced some huge JavaScript hardcodes, so i leave those for later... Another mission will be Pages page and its tree.

**Comment by vytenizs** [comment]
Authentication->Index
![authentication - forkcms com - fork cms - mozilla firefox_008](https://cloud.githubusercontent.com/assets/3973894/5818968/87e9be7c-a0c2-11e4-97f3-c0663e195c5e.png)
![selection_007](https://cloud.githubusercontent.com/assets/3973894/5818969/87ed706c-a0c2-11e4-91bc-fdcc19053257.png)

**Comment by vytenizs** [comment]
Dashboard
![dashboard - forkcms com - fork cms - mozilla firefox_009](https://cloud.githubusercontent.com/assets/3973894/5834510/2684da5e-a167-11e4-8915-b4c5176e813b.png)
![dashboard - forkcms com - fork cms - mozilla firefox_010](https://cloud.githubusercontent.com/assets/3973894/5834509/26842c44-a167-11e4-80ad-1facb4923ef6.png)

**Comment by MathiasDewelde** [comment]
"But still cant imagine dashboard functionality on mobile devices :D"
Suggestion: You could make an accordion interface

**Comment by vytenizs** [comment]
We will see. Currently im not interested in changing functionality. Trying to keep as much of old structure as i can :)

**Comment by WouterSioen** [comment]
Thats good. The clients who get a new Fork site should still feel at home in the new interface.

**Comment by vytenizs** [comment]
Exactly what im trying to achieve :)

**Comment by vytenizs** [comment]
Some more screenshots
![selection_011](https://cloud.githubusercontent.com/assets/3973894/5858812/bbb7091a-a25e-11e4-81b3-9acd5a8c19c9.png)
![selection_012](https://cloud.githubusercontent.com/assets/3973894/5858811/bbb57a3c-a25e-11e4-964b-77267e415388.png)

**Comment by vytenizs** [comment]
Some modals
![pages - forkcms com - fork cms - mozilla firefox_013](https://cloud.githubusercontent.com/assets/3973894/5876275/a94a0974-a31e-11e4-88f4-2806bd37e8ea.png)
![pages - forkcms com - fork cms - mozilla firefox_014](https://cloud.githubusercontent.com/assets/3973894/5876277/a94bf874-a31e-11e4-949e-520c5c9d72fe.png)
![pages - forkcms com - fork cms - mozilla firefox_015](https://cloud.githubusercontent.com/assets/3973894/5876276/a94be0e6-a31e-11e4-8a8c-92a331e4ca03.png)
![pages - forkcms com - fork cms - mozilla firefox_017](https://cloud.githubusercontent.com/assets/3973894/5876278/a94d54a8-a31e-11e4-9e8b-54b8d11fc31d.png)

**Comment by jessedobbelaere** [comment]
Keep up the good work :-)!

**Comment by vytenizs** [comment]
I think pages is the hardest part of all :D

**Comment by vytenizs** [comment]
Pages module is done (No testing)
![pages - forkcms com - fork cms - mozilla firefox_020](https://cloud.githubusercontent.com/assets/3973894/5900439/e69554f0-a571-11e4-8f80-f55af93c159a.png)
![pages - forkcms com - fork cms - mozilla firefox_021](https://cloud.githubusercontent.com/assets/3973894/5900440/e699760c-a571-11e4-9633-989f73090d25.png)
![pages - forkcms com - fork cms - mozilla firefox_022](https://cloud.githubusercontent.com/assets/3973894/5900442/e69be450-a571-11e4-94b5-e2ea30559c49.png)
![pages - forkcms com - fork cms - mozilla firefox_023](https://cloud.githubusercontent.com/assets/3973894/5900441/e6999830-a571-11e4-8ef4-b12790d68952.png)
![pages - forkcms com - fork cms - mozilla firefox_024](https://cloud.githubusercontent.com/assets/3973894/5900443/e6aa8a0a-a571-11e4-9e42-8a3accca96c9.png)
![pages - forkcms com - fork cms - mozilla firefox_025](https://cloud.githubusercontent.com/assets/3973894/5900444/e6aed13c-a571-11e4-9a40-6bd8f79cfb0e.png)

**Comment by WouterSioen** [comment]
Awesome! And using the Bootstrap modals instead off the jQuery UI Dialogs will also allow us to upgrade CKEditor!

**Comment by vytenizs** [comment]
Next part will be settings.

**Comment by vytenizs** [comment]
Yep i try to deprecate jQuery UI as much as possible.

**Comment by WouterSioen** [comment]
:+1:

**Comment by vytenizs** [comment]
I tried to update jsTree, but with no results :) That thing will need much more work to be done. So lets leave it for future.

**Comment by WouterSioen** [comment]
I agree. This PR will make it easier to do those changes later, but they should not really be included in here.

**Comment by vytenizs** [comment]
I think that i can restyle tree, but that would be a waste of time. So lets just leave it as it is for now.

**Comment by WouterSioen** [comment]
I fully agree.

**Comment by vytenizs** [comment]
As i can see lots of JS needs more or less refactoring. But its good that the main part and architecture is pretty good.

**Comment by jessedobbelaere** [comment]
Looks great already! Some things that come to my mind:
* What happens when the website name get's very long? I recently made a website with a long name like "XXXXXXXX Meeting and Event Venue". The header will get packed by using such a name?
* Maybe use mostly gray buttons like Fork currently uses? Only the primary action button "Save" on the pages section is blue in Fork.
* I'm kinda used to the blue background in Fork, with the lightgrey container in the middle. But that's more a personal preference. Another personal preference is the grey divider line and spacing between tabs (like currently in fork) to make it easier to see the individual tabs. I know that bootstrap by default uses the tab style in your screenshots, but maybe we can add some css to make them look a bit more like the current fork interface.
* Oh and on the pages section, normally the "Content" tab is left aligned and all the others are aligned to the right. But those are small details.

Overall, it seems like a very promising addition to the cms :+1:

**Comment by vytenizs** [comment]
It is early stage of this PR. Im not a person that goes into small details, i think i will leave those details for Fork official fork team, cuz im bad at noticing details in design :D im a programmer. Ill try to do my best. About headers, yeah ill test that i saw some glitches on mobile, but i think its fixable :D For now im trying to stick with default bootstrap as much as possible, cuz im not an author of Fork CMS, ill leave details for authors :)

**Comment by vytenizs** [comment]
More pages and some minor fixes of previous work for today.
![locale - forkcms com - fork cms - mozilla firefox_028](https://cloud.githubusercontent.com/assets/3973894/5943943/b98ccfd6-a72b-11e4-915d-38da5df2c06e.png)
![settings - forkcms com - fork cms - mozilla firefox_026](https://cloud.githubusercontent.com/assets/3973894/5943944/b9934e2e-a72b-11e4-86ca-c4bfa91a729d.png)
![settings - forkcms com - fork cms - mozilla firefox_027](https://cloud.githubusercontent.com/assets/3973894/5943945/b9944fd6-a72b-11e4-93da-6c1c77f2d6ea.png)

**Comment by vytenizs** [comment]
Currently facing this bug :D https://github.com/twbs/bootstrap/issues/8761 and cant get rid of it. Settings is almost complete.

**Comment by WouterSioen** [comment]
Hmm, if I follow the "Duplicate from" links, I get here https://github.com/twbs/bootstrap/issues/8638. This states that it should be fixed in bootstrap v3 (https://github.com/twbs/bootstrap/issues/8638#issuecomment-21678297)

**Comment by vytenizs** [comment]
Yeah it should be, but im using bootstrap 3+ and errors still exists... It crashes whole application all links become inactive.

**Comment by vytenizs** [comment]
Maybe some jquery plugins or jquery ui conflicts with bootstrap. I was unable to find problem yet... :) But i will :D

**Comment by vytenizs** [comment]
Finally found a problem. I dunno why but some module JS files binds click event on whole .container and tries to execute e.preventDefault(); this method throws that warning and inits preventDefault to all elements.

**Comment by vytenizs** [comment]
Settings/Groups is done with 1 exception. Groups.js needs refactoring.

**Comment by WouterSioen** [comment]
good job, man :)

**Comment by tijsverkoyen** [comment]
This is really a good thing! Thx mate!

**Comment by vytenizs** [comment]
Some more screenshots
![extensions - forkcms com - fork cms - mozilla firefox_044](https://cloud.githubusercontent.com/assets/3973894/6158989/e4c62548-b258-11e4-8bcf-b538e3e718b4.png)
![extensions - forkcms com - fork cms - mozilla firefox_045](https://cloud.githubusercontent.com/assets/3973894/6158990/e4c6f87e-b258-11e4-8483-324912b0a799.png)
![extensions - forkcms com - fork cms - mozilla firefox_046](https://cloud.githubusercontent.com/assets/3973894/6158991/e4c87654-b258-11e4-911e-44ce23027dcd.png)
![extensions - forkcms com - fork cms - mozilla firefox_047](https://cloud.githubusercontent.com/assets/3973894/6158992/e4caadde-b258-11e4-9e39-79cf4d799a71.png)
![extensions - forkcms com - fork cms - mozilla firefox_048](https://cloud.githubusercontent.com/assets/3973894/6158993/e4dbdf5a-b258-11e4-989e-3eb98dc29dd7.png)
![extensions - forkcms com - fork cms - mozilla firefox_049](https://cloud.githubusercontent.com/assets/3973894/6158995/e4de76ca-b258-11e4-9a52-b0086250d69b.png)
![extensions - forkcms com - fork cms - mozilla firefox_050](https://cloud.githubusercontent.com/assets/3973894/6158994/e4de16a8-b258-11e4-8ead-b288df9b0f19.png)
![extensions - forkcms com - fork cms - mozilla firefox_051](https://cloud.githubusercontent.com/assets/3973894/6158996/e4e16696-b258-11e4-880d-55833bf9247a.png)
![groups - forkcms com - fork cms - mozilla firefox_036](https://cloud.githubusercontent.com/assets/3973894/6158997/e4f3ebf4-b258-11e4-97bc-f3219f4fdfb9.png)
![groups - forkcms com - fork cms - mozilla firefox_037](https://cloud.githubusercontent.com/assets/3973894/6158998/e4f44522-b258-11e4-942e-cbe3d56eb7df.png)
![groups - forkcms com - fork cms - mozilla firefox_038](https://cloud.githubusercontent.com/assets/3973894/6158999/e4f5ef58-b258-11e4-95a5-66b3cec995c0.png)
![groups - forkcms com - fork cms - mozilla firefox_039](https://cloud.githubusercontent.com/assets/3973894/6159000/e4f7a71c-b258-11e4-899b-e25f1d6ae9ba.png)
![groups - forkcms com - fork cms - mozilla firefox_040](https://cloud.githubusercontent.com/assets/3973894/6159001/e507f7ac-b258-11e4-9c9c-4e143a3a6465.png)
![groups - forkcms com - fork cms - mozilla firefox_041](https://cloud.githubusercontent.com/assets/3973894/6159002/e509ef08-b258-11e4-8f80-2d0d7b562365.png)
![groups - forkcms com - fork cms - mozilla firefox_042](https://cloud.githubusercontent.com/assets/3973894/6159003/e50cfcde-b258-11e4-8b9c-dd2a39ea6200.png)
![groups - forkcms com - fork cms - mozilla firefox_043](https://cloud.githubusercontent.com/assets/3973894/6159004/e50e8b94-b258-11e4-9bdf-29bd1c1b5f76.png)
![users - forkcms com - fork cms - mozilla firefox_031](https://cloud.githubusercontent.com/assets/3973894/6159005/e51d95e4-b258-11e4-89a6-160498364f55.png)
![users - forkcms com - fork cms - mozilla firefox_032](https://cloud.githubusercontent.com/assets/3973894/6159006/e51fdde0-b258-11e4-9773-4f5fd58d5c0f.png)
![users - forkcms com - fork cms - mozilla firefox_033](https://cloud.githubusercontent.com/assets/3973894/6159007/e52506c6-b258-11e4-94a2-ede3fbdf123a.png)
![users - forkcms com - fork cms - mozilla firefox_034](https://cloud.githubusercontent.com/assets/3973894/6159008/e5251080-b258-11e4-9aa8-f0f32e091782.png)
![users - forkcms com - fork cms - mozilla firefox_035](https://cloud.githubusercontent.com/assets/3973894/6159009/e535554e-b258-11e4-8582-05c7e1924672.png)

**Comment by vytenizs** [comment]
Some screens are messed up, because i zoomed out for full view. I showed radio buttons on themes because did not wanted to couple fork with bootstrap default theme, tried to maintain as much default style as possible, for possibility to change bootstrap theme and keep JS files clean (No coupling with bootstrap).

**Comment by WouterSioen** [comment]
Good! Have you any idea how much time you'll still need for this to finish? We would really like to add this to our 3.9 release.

**Comment by vytenizs** [comment]
I dont think this should be released as fast as possible. I would test it, refactor some JS, test it again and just then release. I think think its 40 - 50 % done right now.
Modules done:
*Authentication (Partly done)
*Dashboard
*Extensions (Will be done soon)
*Groups (Needs JS refactoring)
*Locale
*Pages
*Settings
*Users

Modules to be done:
*Analytics
*Blog
*ContentBlocks
*Error
*Faq
*FormBuilder
*Location
*Mailmotor
*Profiles
*Search
*Tags

Ofcourse base part of fork is done. When will 3.9 release come out? With some help in testing and fixing bugs i think we can do this in month maybe.

**Comment by WouterSioen** [comment]
We will of course help testing and improving this before we will release Fork containing these changes. We're planning on releasing 3.8.7 first, so there will be some time available.

**Comment by Thijzer** [comment]
Awesome work @vytenizs!

**Comment by vytenizs** [comment]
Extensions module is done.
![extensions - forkcms com - fork cms - mozilla firefox_053](https://cloud.githubusercontent.com/assets/3973894/6164524/b592ae5e-b2a8-11e4-8b98-eb711397c624.png)
![extensions - forkcms com - fork cms - mozilla firefox_054](https://cloud.githubusercontent.com/assets/3973894/6164525/b599592a-b2a8-11e4-9c4b-26cb3c17c1c6.png)
![extensions - forkcms com - fork cms - mozilla firefox_055](https://cloud.githubusercontent.com/assets/3973894/6164526/b599e818-b2a8-11e4-9fab-aa747cde37fb.png)
![Uploading Extensions - ForkCMS.com - Fork CMS - Mozilla Firefox_056.png . . .]()

**Comment by vytenizs** [comment]
Now i will work on all modules settings.

**Comment by WouterSioen** [comment]
@vytenizs I've added a checklist in the issue (https://github.com/forkcms/forkcms/issues/1027#issue-53970377) This will make it easier to follow the progress of this.

**Comment by vytenizs** [comment]
Ok good.

**Comment by vytenizs** [comment]
Ok Search, Content Blocks, Location and Tags modules are done.

**Comment by ikoene** [comment]
@vytenizs Keep up the good work! I already love the look of it.
Looking forward to finally upgrade CKEditor now that you're using the Bootstrap modals.

**Comment by vytenizs** [comment]
Im trying to turn jquery ui completely off, but cannot find DatePicker and TimePicker for bootstrap 3. Any suggestions?

**Comment by ghazispeakserve** [comment]
How about this http://eonasdan.github.io/bootstrap-datetimepicker/ ? and this https://github.com/jdewit/bootstrap-timepicker ?

**Comment by WouterSioen** [comment]
I was just going to link the first one (http://eonasdan.github.io/bootstrap-datetimepicker/)

**Comment by vytenizs** [comment]
I tried http://eonasdan.github.io/bootstrap-datetimepicker/, but i dont see html data- attributes support. And that timepicker is for Bootstrap 2. Ive found http://bootstrapformhelpers.com/ looks neat, but not free.

**Comment by WouterSioen** [comment]
why do you need data-attributes?

**Comment by vytenizs** [comment]
It is useful when u need to set format or other field related options. Its just more flexible.

**Comment by WouterSioen** [comment]
You can set the format from within JavaScript. (see http://eonasdan.github.io/bootstrap-datetimepicker/Options/)

**Comment by WouterSioen** [comment]
These are the possible format options: http://momentjs.com/docs/#/displaying/format/

**Comment by vytenizs** [comment]
Yeah i saw that. But if for example want one date input be one format and other one different format, then u have to implement your own data attributes support. Ok ill try to implement this.

**Comment by WouterSioen** [comment]
You can also just stick to jQuery UI for now, and let this be done in a follow up PR, so it won't slow down your work on bootstrap integration.

**Comment by vytenizs** [comment]
Ok ill leave this for now, because it works well with jquery UI.

**Comment by WouterSioen** [comment]
:+1:

**Comment by vytenizs** [comment]
Ok 6 modules left :D and im very afraid of Mailmotor module :D

**Comment by vytenizs** [comment]
Added fixed top menu for large and medium screens. Fixed lots of bugs. Fixed required field icons.

**Comment by vytenizs** [comment]
Ok Formbuilder dialogs are replaced with Bootstrap modals.

**Comment by Thijzer** [comment]
Does this mean no more jquery.ui?

**Comment by vytenizs** [comment]
Some elements are used, like datetime, drag and drop. But dialogs i think will be removed soon.

**Comment by vytenizs** [comment]
Ok FormBuilder is done. It will need very good testing. Next job is analytics, with analytics i will totaly remove jQuery UI dialogs from Fork CMS.

**Comment by WouterSioen** [comment]
Thats awesome

![Awesome](http://media.giphy.com/media/y8Mz1yj13s3kI/giphy.gif)

**Comment by jeroendesloovere** [comment]
Keep up the good work :+1:

**Comment by vytenizs** [comment]
Ok last jQuery UI .dialog() call was removed. Analytics module is done, but was unable to reach detail page. Now its time for biggest module "Mailmotor" and i have never used it :D

**Comment by vytenizs** [comment]
Ok im stuck with MailMotor :D cant get through step 3, CM throws "400: HTML Content URL required". And that iframe thing on step 3 is buggy as shit.

**Comment by davelens** [comment]
@vytenizs it has been years since I've written that code, but if I recall correctly you get that error because you're trying to send mail info to CM from a local domain (ie. CM is looking to get data from http://forkcms.dev/... or something). You simply can't send locally with Fork and CM.

Maybe the CM API works differently nowadays and a workaround is possible, but I wouldn't know about that.

**Comment by vytenizs** [comment]
Yeah i thought about that. I will try to work around that issue. But everything else looks good and i think ill be done with mailmotor this week.

**Comment by vytenizs** [comment]
Ok MailMotor almost done. What left is Statistics and 4 step of campaign sending. How everything will be after i finish everything?

**Comment by WouterSioen** [comment]
If everything is finished, you should do a pull request containing the changes. Then we'll review the code, and ask for some changes if necessary. We'll also test the implementation, and merge it if no bugs are found.

**Comment by vytenizs** [comment]
I just wonder, how someone will be able to update from older versions of Fork CMS?

**Comment by WouterSioen** [comment]
We don't really provide an update mechanism. What I do is this: when I create a new website on Fork, I do a git clone of Fork and keep the git history. I add my repository as origin remote, and add the Fork repo as an upstream remote. This way I can do `git fetch upstream && git merge upstream/master` to get the newest Fork changes in my project.

**Comment by WouterSioen** [comment]
Btw, I always do this in a separate branch, to be sure to be able to revert everything easily when something goes wrong.

**Comment by vytenizs** [comment]
Ok, ill try to finish ASAP. Cuz as i can see there will be a lot of cleaning work to be done :D

**Comment by vytenizs** [comment]
Will there be any new branch for this feature? Should i make PR directly to master?

**Comment by vytenizs** [comment]
So i will be waiting for instructions :) See ya.

**Comment by Thijzer** [comment]
Epic! Enjoy your weekend @vytenizs.

**Comment by vytenizs** [comment]
Thanks, you too @Thijzer

**Comment by WouterSioen** [comment]
I've created a 3.9 branch, you can do a pull request to this branch.

**Comment by vytenizs** [comment]
Ok.

**Comment by vytenizs** [comment]
Can we create sub issues for this issue or smth. It will be hard to read comments and fix code, because i think there will be lots of comments :D

**Comment by WouterSioen** [comment]
That were the only issues I found for now (but I still have to test it, I only went trough the code)

**Comment by vytenizs** [comment]
That is what im saying :D how u will test this? Will it be publicly available?

**Comment by vytenizs** [comment]
I made some follow ups.

**Comment by Thijzer** [comment]
sidenote :: don't know where else to put this info.

Now thanks to @vytenizs we will have a working default bootstrap backend which is amazing.
It might be nice to addition to add a layer of personal polish/touch on top of this default bootstrap. 
This custom stylesheet could be a themable option in the settings making it very easy to switch  customize/ personalize your backend the way you want. Maybe a user setting instead of a system setting.

I'm imagining my backend all pink with comic sans, just because I can.

:)

**Comment by vytenizs** [comment]
Yeah i love pink with comic sans :D. Changing backend theme should be implemented, because its easy to implement and its huge and unique feature.

**Comment by timvanwolfswinkel** [comment]
Bootstrap :heart_eyes:! Good job :+1: !

**Comment by vytenizs** [comment]
I would also implement something like these:
https://github.com/flatlogic/bootstrap-tabcollapse (for tabs)
http://jsfiddle.net/panchroma/7fYVD/ (for all button groups inside content heading)
http://bootstrapformhelpers.com/ (or something familiar)

But i was unsure about third party unconfirmed sources and forks. So ill leave it to fork dev to decide what libs should be used.

**Comment by vytenizs** [comment]
Hi, how things are going here? :) Need any help?

**Comment by WouterSioen** [comment]
It's merged in the 3.10 branch, and @jessedobbelaere is looking to fix some formbuilder issues.

**Comment by WouterSioen** [comment]
Thanks for all the work, it's nearly done! (see https://github.com/forkcms/forkcms/pull/1366)
