### ISSUE TITLE
Password forgot restricting profiles by status

### ISSUE THREAD

**Issue by ghazispeakserve** [forkcms/forkcms#1042]
Hi there,

Taking a look at `Frontend\Modules\Profiles\Actions\ForgotPassword` class, there is no restriction sending on profile status when sending a forgot password email. Shouldn't this email be sent to active and inactive users only? Blocked and deleted users shouldn't be able to receive this email. Am I missing something?

**Comment by WouterSioen** [comment]
I don't think this can do any harm, since resetting a password doesn't change the password of a profile. A blocked user will still be blocked after resetting his password.
