### ISSUE TITLE
Send email and access Kernel from an API class

### ISSUE THREAD

**Issue by ghazispeakserve** [forkcms/forkcms#1043]
Hi there,

I did not find any way to access Kernel properties when calling an API class. A simple example I want to send an email using Mailer class, but Api class method are static. Any idea?

**Comment by WouterSioen** [comment]
You probably can fetch the container from the backendmodel.

    // service
    Backend\Core\Engine\Model::get('<service_name>');

    // parameter
    Backend\Core\Engine\Model::getContainer()->getParameter('<parameter_name>);
