### ISSUE TITLE
Accessing locales wihtin API classes

### ISSUE THREAD

**Issue by ghazispeakserve** [forkcms/forkcms#1048]
Why localisations are not loaded when working within an API class? Is there anyway to do it?

**Comment by ghazispeakserve** [comment]
The solution I found is to add the line below before fetching any locale string

```php
// locale loading should be dynamic depending on your configuration
$locale = 'en';
// Don't forget to set FRONTEND_LANGUAGE or BACKEND_LANGUAGE if you will be sending emails and depending on the email templates you will use
DEFINE('FRONTEND_LANGUAGE', $locale);
// or
DEFINE('BACKEND_LANGUAGE', $locale);

// then
FL::setLocale($locale);
// FL or BL, depending on what you need
BL::setLocale($locale);

// then you can use
$about = FL::getLabel('AboutUs');
```

I don't know if it is the recommended way to do it. @WouterSioen is it good to like that or is there any better way?

**Comment by WouterSioen** [comment]
The BACKEND_LANGUAGE can be dropped, this constant is never used.

I guess using the ::setLocale method is the only way to enable translations, yes.

**Comment by ghazispeakserve** [comment]
Ok it works and it is the good way to do it.
