### ISSUE TITLE
HTML5 image uploader

### ISSUE THREAD

**Issue by jacob-v-dam** [forkcms/forkcms#1049]
It would be nice to have a HTML5 image uploader. But this image uploader will contain some extra features like:
* Preview
* Crop
* Resize

By this users can upload any image and decide what is needed to display. I know Wordpress has something like this.

**Comment by WouterSioen** [comment]
@jacob-v-dam That would be nice,  but we aren't planning to do such (a big) integration right now. We're mainly working on Symfony integration and bug fixing. Feel free to create something like this though. I also thought @jeroendesloovere had a media library module with some of these functionalities?
