### ISSUE TITLE
Locale module: ajax SaveTranslation fails 

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1050]
## Problem

When you search for "SearchTerm", you see that the application column is empty.
![schermafbeelding 2015-01-30 om 10 28 54](https://cloud.githubusercontent.com/assets/588616/5973623/d8eb18a2-a86a-11e4-844e-dbd4cd511761.png)

So, if you edit the translation, no application is send to the ajax function. Which results in an error.
![schermafbeelding 2015-01-30 om 10 30 04](https://cloud.githubusercontent.com/assets/588616/5973632/fa43e880-a86a-11e4-8434-8a234443096d.png)

## Solution

Add backend or frontend in the table "application" column.

**Comment by tijsverkoyen** [comment]
Feel free to PR a bug fix ;-)

**Comment by jeroendesloovere** [comment]
@tijsverkoyen Yep!

**Comment by WouterSioen** [comment]
@megasnort will fix this
