### ISSUE TITLE
Problem with Analytics module

### ISSUE THREAD

**Issue by timvanwolfswinkel** [forkcms/forkcms#1051]
Hi,

I'm having trouble with the Analytics module and can't seem to figure out what is wrong. I've looked trough the Fork CMS forum and Github issues and there are [others] (http://www.fork-cms.com/community/forum/detail/an-infinite-loop-has-been-detected-while-getting-data-from-cache-for-the-action-quot-index-quot-.) having the same problem, however still no solutions.

### Problem:
It is possible to connect with the API key, I'm getting all the profiles from Analytics. When I visit the marketing tab it gives me the loading visuals and this keeps on going. In the logfile I'm getting the following exception:
```
[2015-02-02 15:51:05] request.CRITICAL: Uncaught PHP Exception Backend\Core\Engine\Exception: "An infinite loop has been detected while getting data from cache for the action "Index"." at /var/www/vhosts/domain.nl/httpdocs/src/Backend/Modules/Analytics/Engine/Model.php line 1171 {"exception":"[object] (Backend\\Core\\Engine\\Exception: An infinite loop has been detected while getting data from cache for the action \"Index\". at /var/www/vhosts/domain.nl/httpdocs/src/Backend/Modules/Analytics/Engine/Model.php:1171)"} []
```

I find it strange that it is working on my development (centos, debug-off) and local (wamp, debug-on) environment but not on the production (ubuntu 12.04, debug-off) environment.

The only difference in my approach is that I selected Universal Analytics on the production environment, in my first attempt. I then deleted the API key/module settings and tried it again with the Classic Analytics. On the development and local environment I directly used the Classic Analytics.

I deleted the cache allready and all folder permissions seem to be ok. 

I am working on Fork CMS version 3.8.2.

Hope one of you guys can give me a solution :wink:, Thanks!

**Comment by timvanwolfswinkel** [comment]
By the way, I connected Analytics on all enviroments apart from each other. So the issue is not generated by exporting/importing the database.

**Comment by jeroendesloovere** [comment]
[Possible related bug](https://github.com/forkcms/forkcms/issues/973)

**Comment by WouterSioen** [comment]
Possible problems:

* your site_url could be wrong in the parameters.yml (should have www, if thats in your domain and no trailing slash)
* only classic analytics seems to work.

**Comment by timvanwolfswinkel** [comment]
My site_url was without the www, fixed that and it's working again :+1:  :relaxed:

**Comment by WouterSioen** [comment]
You're welcome!
