### ISSUE TITLE
Automatically redirecting old Page URL's

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1052]
## Problem

When a customer changes the title of the page, the URL is often automatically changed as well. Which could give broken links on other pages. This is so old skool, s*cks and should be fixed fur sure with user-friendliness ahead.

## Solution 1: integrated in pages

Integrate a smart function in Frontend Pages Module which detects that an old URL is being visited. We intercept this and fetch the Redirect page, so we know where they are coming from. Then we could find that page in our database, load in the texts and change URL's automatically. While the user is just being redirected 301 to the new URL.

## Solution 2: a module

We could generate a module that tests all pages in the website for missing links.
As discussed in [this previous issue](https://github.com/forkcms/forkcms/issues/656#issuecomment-74052478).

**Comment by bart-lysander** [comment]
The table containing the redirect links should be cleaned in some easy way. For example remove all redirects that are not used for last x time.
Do we also redirect module item? Can we use de meta record update for this?

A broken link detector should be added anyway (when time permits).

**Comment by carakas** [comment]
Be careful when implementing this that you don't overwrite new pages that have the old url

**Comment by WouterSioen** [comment]
We won't fix this for now.
