### ISSUE TITLE
Formbuilder confirmation mail

### ISSUE THREAD

**Issue by megasnort** [forkcms/forkcms#1053]
I'm have been working with the formbuilder a couple of times, for different projects and a question I often get is to add a confirmation mail after submitting the form.

So, I have implemented this feature in a couple of websites already, and I thought it might be a good addition to Fork CMS.

Right now it works like this:
- When an e-mail field was present
- And when it is filled in
- And when the subject and content field in the backend (screenshot) were filled

The confirmation mail is send to the e-mailadres in the (first) e-mail field in the list of fields.

So, two questions:
- Would this be a good addition to Fork?
- Is the implementation ok like this? (I'm thinking a more explicit option checkbox "send confirmation mail" might make the backend a bit more user friendly)

![schermafbeelding 2015-02-04 om 08 10 50](https://cloud.githubusercontent.com/assets/736827/6036502/11bad5da-ac46-11e4-8252-b334f7b85a09.png)

**Comment by timvanwolfswinkel** [comment]
:+1:

**Comment by WouterSioen** [comment]
I've never needed this myself but I can imagine this could be useful sometimes.

I would add a checkbox "send confirmation mail" (like you suggest) and only show the subject and  content fields that are required if this checkbox is checked.

**Comment by bart-lysander** [comment]
Please remember security!
Anyone can fill any email address in the form and submit it. Including bots!

Please consider adding:
* a verification function. The end user gets a verification email with a link. When the user clicks the link, he is marked as "trusted" and he will receive the confirmation email.
* a check-box for adding the form data fields to the email body.

**Comment by jessedobbelaere** [comment]
I definitely would want this feature :+1: But make it possible to enable/disable the feature (checkbox).

**Comment by tijsverkoyen** [comment]
@me I think we have an implementation of this in our own fork of Fork.

**Comment by jonasdekeukelaere** [comment]
@tijsverkoyen I don't think it is implemented in the Fork of Sumocoders, but I implemented this in one of the projects.

**Comment by WouterSioen** [comment]
@megasnort feel free to go wild and implement this;

**Comment by jessedobbelaere** [comment]
@megasnort Any news on this implementation? I could already use it in a project :smiley: 
I think it's best like Wouter said. Add a checkbox "send confirmation mail". If that's checked, the title and textarea field become visible (with some javascript).

**Comment by megasnort** [comment]
I will try to do this the coming week.

**Comment by WouterSioen** [comment]
ready to merge in 3.10

**Comment by carakas** [comment]
is fixed by #1602
