### ISSUE TITLE
Error when opening locale/translations in backend

### ISSUE THREAD

**Issue by jessedobbelaere** [forkcms/forkcms#1054]
### Problem:
I got the following error when I open the translations section in Fork CMS 3.8.6 on PHP 5.3.28:

`FatalErrorException: Error: Using $this when not in object context in /XXX/forkdev/src/Backend/Modules/Locale/Actions/Index.php line 334`

This is the faulty piece of code:

        // only allow languages from our language checkboxes to be set
        $this->filter['language'] = array_filter(
            $this->filter['language'],
            function ($language) {
                return array_key_exists(
                    $language,
                    BackendLocaleModel::getLanguagesForMultiCheckbox($this->isGod)   ----> throws error
                );
            }
        );

### Solution:
Maybe just fetch the isGod parameter with the static getUser method:
`BackendLocaleModel::getLanguagesForMultiCheckbox(BackendAuthentication::getUser()->isGod())` . This works, but isn't really DRY because the isGod variable is already set in the beginning with this same static method. What do you guys think?

**Comment by WouterSioen** [comment]
Fixed in b5b9e7b7b90fbfa0a8512e841b6eac05d11f3dc7

**Comment by jessedobbelaere** [comment]
Works great! Thanks

**Comment by WouterSioen** [comment]
I thought this was more elegant then using then fetching the isGod var again.
