### ISSUE TITLE
Slow backend datagrid

### ISSUE THREAD

**Issue by glenncoppens** [forkcms/forkcms#1056]
Hi. 

**Issue:** When using no pagination (ca 250 records) in a backend datagrid which has three columns containing a parsed date, the page loads quite slow. This is due to the datagrid column functions `date()` or `getLongDate()`.

*Yes i needed the possibility to* ***not*** *use pagination*

These methods use the Fork CMS locale and therefore makes it a bottleneck for quick timestamp formatting. **Is there any chance that this will/can be improved? Or is there an alternative way to do this?**

I already used the PHP Intl extension but this requires the Intl extension to be loaded. And that is not often the case on many webservers (i guess), so this might not be a suitable approach to use this in the core. Or maybe it is, using a setting or check whether the extension is loaded?

A custom modifier I wrote is this one (using the Intl extension):
```
public static function formatDate($var = null, $format = null)
{
    $var = (int) $var;

    // invalid timestamp
    if($var == 0) return '';
    
    // create Intl formatter
    $formatter = new \IntlDateFormatter(\Locale::getDefault(), \IntlDateFormatter::NONE, IntlDateFormatter::NONE);
    $formatter->setPattern($format);

    // set datetime
    $dt = new DateTime();
    $dt->setTimestamp($var);    

    // return the formatted date string
    return $formatter->format($dt);
}
```

Thanks, Glenn

**Comment by WouterSioen** [comment]
Hi @glenncoppens 

Moving towards Intl is a good thing to do. We already use Symfony's intl component to load stuff like localized countries. I think moving to Intl for date localisation is also a good thing to do.

In your modifier, you'd better use FRONTEND_LANGUAGE (in the frontend) or BL::getWorkingLanguage() (in the backend) though. \Locale::getDefault() won't return the correct result in Fork.

**Comment by WouterSioen** [comment]
Btw,

The intl extension isn't required anymore using the Symfony Intl component. It creates fallbacks for the functionality (http://symfony.com/doc/current/components/intl.html)

**Comment by glenncoppens** [comment]
Tnx @WouterSioen for the tips.

I have rewritten the method/modifier. Since Symfony's partial Intl layer only supports the 'en' locale (and not all of the format symbols), i have used a third parameter which is used with SpoonDate when the intl extension isn't loaded. 
I'll post it here in case someone has similar "issues".

```
/**
 * Format a given timestamp, using Intl extension or use SpoonDate as a fallback.
 *
 * @param string $timestamp A UNIX-timestamp.
 * @param string] $intlFormat An Intl date format. This is different than the php date format.
 * @param string $dateFormat A traditional PHP date format.
 * @return string
 */
public static function formatTimestamp($timestamp = null, $intlFormat = null, $dateFormat = null)
{
    // variables
    $timestamp = (int)$timestamp;
    $dt = new DateTime();
    $formatter = null;
    $return = null;

    // invalid timestamp/formats
    if($timestamp === 0 || $timestamp === null) return time();
    if($intlFormat === null) throw new Exception('You must provide an Intl date format.');
    if($dateFormat === null) throw new Exception('You must provide a date format.');

    // set the provided timestamp
    $dt->setTimestamp($timestamp);

    // if the Intl extension isn't loaded, it will throw an exception
    try {

        // try locale with the frontend language
        $formatter = new IntlDateFormatter(
            FRONTEND_LANGUAGE,
            IntlDateFormatter::NONE,
            IntlDateFormatter::NONE,
            null,
            IntlDateFormatter::GREGORIAN,
            $intlFormat
        );

        // format timestamp
        $return = $formatter->format($dt);

    } catch(Exception $e) {

        // try Symfony fallback Intl 'en' locale
        try {

            $formatter = new IntlDateFormatter(
                'en',
                IntlDateFormatter::NONE,
                IntlDateFormatter::NONE,
                null,
                IntlDateFormatter::GREGORIAN,
                $intlFormat
            );

            // format timestamp
            $return = $formatter->format($dt);

        } catch(Exception $e) {

            // This was the last Intl resort. We need to use SpoonDate now.
            $return = SpoonDate::getDate($dateFormat, $timestamp, FRONTEND_LANGUAGE);
        }
    }

    return $return;
}
```
