### ISSUE TITLE
Installing Fork CMS 3.8.6 download from website

### ISSUE THREAD

**Issue by timvanwolfswinkel** [forkcms/forkcms#1059]
The download of 3.8.6 on the website contains install cache which will generate an error when you want to install Fork CMS. I removed the cache and the steps are working again..

However in step four I'm getting a javascript disabled error, having javascript enabled in browser. Console gives a ```unexpected token <``` might be something wrong with generating HTML? Anybody else experiencing this?

**Comment by WouterSioen** [comment]
I'm rewriting the release script to not include the install cache. I can't reproduce the unexpected token though.

**Comment by WouterSioen** [comment]
I have also fixed the latest release now. Can you test if you get this unexpected token with this updated file?

**Comment by timvanwolfswinkel** [comment]
Cool @WouterSioen, will test this asap :+1:

**Comment by timvanwolfswinkel** [comment]
Working great again :smiley:! Not sure what caused the unexpected token, might be something in my own environment. Thanks for fixing the cache!

**Comment by WouterSioen** [comment]
You're welcome!
