### ISSUE TITLE
Twig running on Frontend forkcms

### ISSUE THREAD

**Issue by Thijzer** [forkcms/forkcms#1062]
Okay, gonna keep this first discussion short and sweet.

I had mild success on converting SpoonTemplate into twig.
I somewhat replaced SpoonTemplate without touching it (almost), extending the Core Template with a twig version :)
It started as an experiment, looking if the Template parses all the tpl and it does (kinda).

Why?
Twig is a Symfony component, is in development, is more secure, faster if you use it correctly, easier to read and write, has much more options, will attract more developers.
My point is only to replace the SpoonTemplate leaving all other Spoon libraries untouched and working. You should be able to switch between Twig or Spoon somehow.

But...
My focus is on twig at the moment, not on other Symfony components that are related to twig.

#PROGRESS

So whats working
- Base head/ footer templates are loading from Page or template is working
- All data is passed global or page or action is passed.
- parsing editors

Whats working (kinda/hacked)
- Locale is also passed but without lbl,msg,error in front of them.
- navigation is working but needs extra work
- form made some great process, it looks like this {{ form.search.hid.Utf8 | raw }}
- parsing actions or widgets, working somewhat, I got it too parse,  but not fully dynamically

Untouched Parts
- all modifiers,  twig has an solution for this, ill keep it for last, see where it fits best
- dynamic header, js, css
- overwriting templates
- FormBuilder, epic final test
- emails 
- the backend, ( who cares :) )
- more stuff I'm forgetting

Some other stuff in progress
I have a concept tpl -> twig file converter working, we need to build it project wide and some modifiers are missing.

That's it for now, I'm not very chatty so I'll return ones a while reporting on the progress I made.

**Comment by WouterSioen** [comment]
Hi @Thijzer,

Great to hear progress in moving to twig! It would be awesome if you could create a [WIP] Twig pull request, so we could follow the progress, give feedback, and maybe even help contribute to it. I'd love to move to twig asap :smile:

**Comment by Thijzer** [comment]
Hi Wouter. I promise I will in time. Right now I still want to finnish a couple of things and clean up my code before I push it into the world. Probably Will leave the modifiers and the backend for the community to figure out.

**Comment by Thijzer** [comment]
Pull request send, of course  please mind the my uncommented behaviour here. Also it's still a work in progress but it's working!!

**Comment by tijsverkoyen** [comment]
Note to self: see https://github.com/forkcms/forkcms/pull/1076

**Comment by WouterSioen** [comment]
Working on it in branch 3.10
