### ISSUE TITLE
Validation of Installer - example data required

### ISSUE THREAD

**Issue by jessedobbelaere** [forkcms/forkcms#1065]
I pulled the recent changes from Fork CMS and was installing Fork CMS but:

* I want to install without example data, however [the html5 validation won't let me continue](http://cl.ly/image/1A2w2y3F2u1f) so I had to dig into the html code with the webdev tools to remove the required attribute.
* When I check "example data", [I'm forced to select "use a specific debug email"](http://cl.ly/image/3d2V2y021Y1b)
* The buttons at the bottom are not consistent :grin: 
* I also get the ["Javascript should be enabled"](http://cl.ly/image/1l1l0m1g2P1t) warning on the next step, but I've read that someone had a similar issue here on github. Not sure if it's fixed already? Javascript is of course enabled in my browser
* The email address page shows [all the possible password feedback states](http://cl.ly/image/2e2V2e2Y0W2g). Seems like a javascript issue
* The "installation complete" window has a checkbox to show the password, but that doesn't work too (again: the javascript issue)?

**Comment by jessedobbelaere** [comment]
Works fine in a brand new install, nvm

**Comment by WouterSioen** [comment]
Yes, the after install scripts in the composer.json file make sure the assets and some other stuff is initialized correctly.
