### ISSUE TITLE
SpoonEmail still used

### ISSUE THREAD

**Issue by ghazispeakserve** [forkcms/forkcms#1066]
After the SwiftMailer implementation I have seen that SpoonEmail is still used here https://github.com/forkcms/forkcms/blob/master/src/Backend/Modules/Settings/Ajax/TestEmailConnection.php

**Comment by WouterSioen** [comment]
Good catch, I'll fix this.

**Comment by ghazispeakserve** [comment]
Yes please I am having some issues with SMTP connection I don't know if it is coming from SwiftMailer or from the server itself. Thanks Wouter.

**Comment by ghazispeakserve** [comment]
Have SwiftMailer been tested with an SMTP connection? ( I guess the answer is yest ). Do you think it will be fixed today? ( we are both busy I know :smile:  )

**Comment by WouterSioen** [comment]
Fixed :) And yes, sending emails trough smtp has been tested (and works on my machine™)

**Comment by WouterSioen** [comment]
@ghazispeakserve still troubles after upgrading to the newest master?

**Comment by ghazispeakserve** [comment]
I confirm that using "smtp.googlemail.com" with an SSL connection is not working. But I can't tell if it a Fork issue or not. Can you please test with a google account using SMTP/SSL connection?

**Comment by WouterSioen** [comment]
I will (but I will probably not be able to do it today).

**Comment by WouterSioen** [comment]
@ghazispeakserve I've made some time for it. Can you test if it works now?

**Comment by ghazispeakserve** [comment]
not working for me and when using TLS I get 

```json
{"code":500,"data":null,"message":"Expected response code 250 but got code \"530\", with message \"530 5.7.0 Must issue a STARTTLS command first. v16sm15912178wib.5 - gsmtp\r\n\""}
```

**Comment by WouterSioen** [comment]
Hmm, I've tested it with ssl and this worked. I'll look into it

**Comment by WouterSioen** [comment]
You probably get this when choosing TLS. I think google accounts use SSL though. This it work using ssl?

**Comment by ghazispeakserve** [comment]
The commit 726f49171336ffde202c3862af3ef6732753c067 fixed the issue? What is it a gift for me? Ohhh thank you :sweat_smile:

**Comment by WouterSioen** [comment]
You're very welcome :smile:

Op maandag 16 februari 2015 heeft Ghazi Triki <notifications@github.com>
het volgende geschreven:
