### ISSUE TITLE
error : jdorn/sql-formatter put in require-dev but should stay in require

### ISSUE THREAD

**Issue by ghazispeakserve** [forkcms/forkcms#1069]
In commit 525b81bc50810ab51734db58a9071a02365edf8b I have seen that jdorn/sql-formatter has been moved to require-dev but it is a production dependency.

The correct use of require-dev is https://getcomposer.org/doc/04-schema.md#require-dev

jdorn/sql-formatter should stay in in require because as an exmaple navigation to backend is no more possible

in production we use the command composer update -o --no-dev and when running this command require-dev dependencies are not installed

**Comment by WouterSioen** [comment]
Why is it a production dependency? It is only used when debug mode is on (which should not be the case in production).

**Comment by ghazispeakserve** [comment]
Is the class DatabaseDataCollector used only in dev?

**Comment by WouterSioen** [comment]
Yes, it is used by the Symfony Web Profiler bar (the bar on the bottom of your screen containing request info)

**Comment by WouterSioen** [comment]
You can see here: https://github.com/forkcms/forkcms/blob/master/app/config/config_dev.yml#L10-L16 that it's only included in the dev environment.

**Comment by ghazispeakserve** [comment]
Tested and working
