### ISSUE TITLE
Page set to redirect doesn't redirect.

### ISSUE THREAD

**Issue by jacob-v-dam** [forkcms/forkcms#1072]
I created page which should redirect to another page. This is needed before a new website goes online and you want the preserve the existing pages in Google.

But when you create a redirect and visit the page, you aren't redirected to the given page/url.

![Create a redirect](https://cloud.githubusercontent.com/assets/310526/6224884/94460a28-b683-11e4-976e-734d36c007cc.png)

**Comment by bart-webleads** [comment]
What version?

**Comment by jacob-v-dam** [comment]
It was in version 3.8.5 so I updated to 3.8.7 but the same issue exists.

**Comment by bart-webleads** [comment]
Hmm, my 3.8.5 does not redirect also

**Comment by WouterSioen** [comment]
This should be fixed when upgrading to a newer version! Don't forget to remove your cache (since it was a problem in the Pages cache)

**Comment by ghazispeakserve** [comment]
Wasn't a fixed in this #1024 ?

**Comment by WouterSioen** [comment]
It was actually fixed here: https://github.com/speakserve/forkcms/commit/b0bd22c7e0e6637a216435b5092fe79b93829047

**Comment by jacob-v-dam** [comment]
Yes it was fixed. I forgot to update the page module (had some modifications in this module)

**Comment by WouterSioen** [comment]
@jacob-v-dam While you're here, can you please confirm if this issue https://github.com/forkcms/forkcms/issues/1025 should still be open or not?
