### ISSUE TITLE
Update hicharts library.

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#1074]
How if we update hicharts library?

**Comment by WouterSioen** [comment]
Seems like a good idea!

**Comment by carakas** [comment]
I will do this

**Comment by carakas** [comment]
I will do this

**Comment by carakas** [comment]
see https://github.com/vytenizs/forkcms/pull/7

**Comment by jeroendesloovere** [comment]
[Merged](https://github.com/vytenizs/forkcms/commit/fa2e8780de8ab39f09e8fb8b0cdab3e47fad9f22)
