### ISSUE TITLE
Upgrade from 3.8.5 to 3.8.7 causes the mailer to fail

### ISSUE THREAD

**Issue by jacob-v-dam** [forkcms/forkcms#1080]
I upgraded from Fork 3.8.5 to 3.8.7 by removing all files and adding the required only. But now i'm not able to use the MailerService anymore.

The reason for this is the following:
`return $this->services['mailer'] = new \Common\Mailer($this->get('database'));`

Must be:
`return $this->services['mailer'] = new \Common\Mailer($this->get('logger'));`

Is this a known issue? I updated the vendors with `composer update`

**Comment by WouterSioen** [comment]
You should never do `new \Common\Mailer($this->get('logger'));`

We use the Dependency injection container for this. You can do it like this:

````
// in controllers
$mailer = $this->get('mailer');

// in models or other singleton/static stuff
$mailer = \Frontend\Core\Engine\Model->get('mailer');

**Comment by jacob-v-dam** [comment]
No this is created in the app/cache/dev/appDevDebugProjectContainer.php. It automatically sets the 'database' even after cleaning.

**Comment by WouterSioen** [comment]
That's trange. Can you manually remove the app/cache folder with `rm -rf app/cache`?

**Comment by jacob-v-dam** [comment]
Still the same problem. I tried the code from the master branch and that worked. So i'll try to replace all the files and see what happens.

**Comment by jacob-v-dam** [comment]
I found the problem. It had something to do with my configuration.yml. Most of the time i don not update these.

**Comment by WouterSioen** [comment]
Aha, I'm glad you found it!
