### ISSUE TITLE
Formbuilder placeholders & classnames

### ISSUE THREAD

**Issue by jessedobbelaere** [forkcms/forkcms#1083]
I often use formbuilder, but one of the features that it lacks is placeholders. Would it be a good idea if I add an input field "placeholder" to each field where you can enter a placeholder text? 

I also find it hard to style a form. The form widget gets an id like `#form3` but that's not really useful in CSS because it could change. Maybe add a general form css class(es) input field to the form? The [Extra tab](http://cl.ly/image/2L2X2U342S1G) is probably the best place for this.

I would also find it useful to have a CSS class input field in the properties panel of each field. (I would then add that css class name on the wrapper div of the field including the label and input field, so you can use the wrapper classname to target the label or input field). 

If I add some of these options, then it would be way easier to create a more visually appealing layout for your form using CSS. I don't think that this is much work to implement? Other suggestions to improve formbuilder?

**Comment by WouterSioen** [comment]
The problem with adding such items is that it adds more clutter to the FormBuilder module, which is already fairly cluttered.

It seems like a good addition, but it should maybe be hidden by default, or put in an extra tab "advanced options" thats only shown to god users or something.

**Comment by jessedobbelaere** [comment]
Yup, formbuilder should be kept simple. But I often wished I could set a CSS class for additional styling because now you can barely target the form in a selector. And the possibility to define a placeholder text would increase the usability for visitors I think. If this would be only available for god users, that would be OK for me.

**Comment by WouterSioen** [comment]
Even for god users, I would add it in an extra tab in the popup.

**Comment by jessedobbelaere** [comment]
Hmm. The formbuilder uses `<p>` tags to wrap a label and input field. Maybe don't add a css class field to the module, but parse a css class automatically in the frontend based on label name. 

The module could add a css class (with prefix `field-`) based on the name/label of the field (e.g. "surname"), onto this wrapper element. Then someone can use a css selector `form .field-surname { } `  to style a field of the form. And you don't clutter the formbuilder module with additional input fields.

**Comment by WouterSioen** [comment]
This seems like a better solution to me. Less code in the FormBuilder means less possible issues and less stuff to maintain.
