### ISSUE TITLE
Add test coverage

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#1107]
Hi Guys,

It is geat that you have implemented tests so far. How about adding test coverage and sending results to coveralls?

**Comment by WouterSioen** [comment]
We're keeping track of the test coverage in scrutinizer: https://scrutinizer-ci.com/g/forkcms/forkcms/

This is our coverage so far: [![Code Coverage](https://scrutinizer-ci.com/g/forkcms/forkcms/badges/coverage.png?b=master)](https://scrutinizer-ci.com/g/forkcms/forkcms/?branch=master)

**Comment by ghazispeakserve** [comment]
Can you add the coverage rate to README please?

**Comment by WouterSioen** [comment]
We're still working on adding more coverage. When we have some more, we'll add it to our readme.

**Comment by ghazispeakserve** [comment]
thank you :)

**Comment by tijsverkoyen** [comment]
fixed: https://github.com/forkcms/forkcms/commit/076df115b39bc41d333c3833c45b2a121f92f97e
