### ISSUE TITLE
When adding a blog post, ping services crashes. (when SPOON_DEBUG is on)

### ISSUE THREAD

**Issue by WouterSioen** [forkcms/forkcms#1112]
![error](http://oi60.tinypic.com/dcig.jpg)

Is ping services still supported? If it does not work, shouldn't we remove it?

**Comment by tijsverkoyen** [comment]
I think the ping services should be removed in favor of Symfony-events.

**Comment by tijsverkoyen** [comment]
I can't reproduce this error. The only thing I can think of to explain this error is that the service that was pinged returned something unexpected.
