### ISSUE TITLE
Installer indicates wrong path when showing permissions errors

### ISSUE THREAD

**Issue by markseddon** [forkcms/forkcms#1113]
![screen shot 2015-03-04 at 6 43 20 pm](https://cloud.githubusercontent.com/assets/1563895/6479740/5b2381f4-c29e-11e4-87d2-c37ab9006581.png)

I've just tried a fresh install on Ubuntu 14.04 and I had a few issues with the installer. Most of the checks were fine but when it tells me about permissions it indicates the app/src directory but it should be the /src directory which was a little confusing. 

I can see the service is using the rootDir variable which is passed in via the [services.xml](https://github.com/forkcms/forkcms/blob/master/src/ForkCMS/Bundle/InstallerBundle/Resources/config/services.xml#L12) file but it might not be working for some reason?

Anyway it's no major issue as I worked it out but thought I'd let you guys know.

**Comment by WouterSioen** [comment]
Did you install Fork using git (so cloning from this repository or compser create-project) or did you download the package from the website and unpack the zip file?

**Comment by markseddon** [comment]
I ran 

```composer create-project forkcms/forkcms .```

Now I remember I also ran into an issue with the 

```php app/console assetic:dump . && cd tools && ./remove_cache```

command which failed with an permissions error. I ran composer create-project as the same user which owned the current directory.

**Comment by WouterSioen** [comment]
Do you use a vagrant box?

**Comment by markseddon** [comment]
Nope. It was a fresh Ubuntu EC2 instance.

**Comment by WouterSioen** [comment]
Fixed in #1123
