### ISSUE TITLE
Use page as module-action usage unclear

### ISSUE THREAD

**Issue by ghazispeakserve** [forkcms/forkcms#1116]
The result of checking the box "Use this page as a module action." in page "Settings" tab is unclear. What are the implications? Don't we need to add help text to explain about what it is?

**Comment by jessedobbelaere** [comment]
Yeah tis could use some extra information. Either add an information icon which displays a tooltip with info on hover, or maybe we should add a step-by-step guide in the Fork CMS documentation. 

**You can use it to make a specific layout for one of the module actions**. Let's say you have a blog page with the blog module attached. Then all pages will look the same. For example, you want a blog index page with only a list of articles and absolutely nothing in the right sidebar of your template. But you want to have a different blog detail page: in the right sidebar there should now be a widget with recent articles, tags, archive etc... Normally, If you would add a widget in the right column of your blog module page, then this widget would appear on all blog pages! You can solve this problem by using the `use pages as a module action` option. Then you can make a blog detail page, add it as a child of your Blog page, add the blog module and add some widgets in the right column. Then these widgets will only appear on the detail page. So you can have different page content for different module actions.

There's a short tutorial [here](http://www.bubblefish.be/blog/post/fork-cms-tip-pagina-als-module-actie-gebruiken) but it's in dutch. I guess you can translate it from dutch to english with google translate.

**Comment by WouterSioen** [comment]
@ghazispeakserve is this explanation clear for you?

**Comment by ghazispeakserve** [comment]
It is not very clear yet. The same result can be achieved by having different layouts. Right.

**Comment by jessedobbelaere** [comment]
@ghazispeakserve Hmm don't think so... Let's say you create a new page "Blog". You add the blog module on that page. That page uses a specific template, for example "Default". But you can't choose a different page template for one of the many views (Detail, Archive, ...). There's only one Blog page in the Pages section and it uses one template. 

So if you want to have a different layout or different content on a module view, then you can follow the tutorial from above and add a "page as module action".

But yes, It's confusing. I didn't know what it was, until I saw the tutorial and tried it for myself.
