### ISSUE TITLE
Mailer class undefined variable $message

### ISSUE THREAD

**Issue by ghazispeakserve** [forkcms/forkcms#1118]
In lines 84 and 101 of Mailer class there 

```php
84.  $message->attach(\Swift_Attachment::fromPath($attachment));
...
101. $message->addPart($content, 'text/plain');
```

Shouldn't $message be replaced with $this?

**Comment by WouterSioen** [comment]
Oops, fixed in 58f58aa

**Comment by ghazispeakserve** [comment]
Thanks, sorry for not creating a pull request. Busy updating with latest release of Fork and making it all work.

**Comment by WouterSioen** [comment]
It's great that somebody's testing this ;) We always release a .1 version really soon after a .0 version, because of such things.

Note to self: add a functional test that sends emails.

**Comment by ghazispeakserve** [comment]
Nice. I have seen that we are using swiftmailer bundle. Can we now use 'virutal' email sending?

**Comment by WouterSioen** [comment]
It's not possible out of the box, but we could add this as an extra backend setting. (or by manually changing these lines of code for now: https://github.com/forkcms/forkcms/blob/master/src/Common/Mailer/Configurator.php#L24-L35)

**Comment by ghazispeakserve** [comment]
Thank. I will take some time and think about how can we do this.
