### ISSUE TITLE
README typo in running the tests

### ISSUE THREAD

**Issue by ghazispeakserve** [forkcms/forkcms#1119]
Folder name should be "vendor" not "vender"

**Comment by WouterSioen** [comment]
Fixed!

**Comment by ghazispeakserve** [comment]
When I run tests I get the following message:

../phpunit/phpunit/composer/bin

Any idea? There is no such file after I do a composer install.

My vendor/bin/phpunit contains

```shell
#!/usr/bin/env sh
SRC_DIR="`pwd`"
cd "`dirname "$0"`"
cd '../phpunit/phpunit/composer/bin'
BIN_TARGET="`pwd`/phpunit"
cd "$SRC_DIR"
"$BIN_TARGET" "$@"
```

**Comment by WouterSioen** [comment]
Hmmm, thats a real strange message. It can help to fully remove the vendors directory with `rm -rf vendor` and doing a new `composer install`.

The phpunit executable will be in the bin directory then, and you'll be able to run it with `./bin/phpunit -c app/`

**Comment by WouterSioen** [comment]
@ghazispeakserve you got your tests running without errors?

**Comment by ghazispeakserve** [comment]
Test running with a lot of error because we have a lot of tuning.

**Comment by ghazispeakserve** [comment]
The changelog needs a date for 3.9 instead of XX

**Comment by WouterSioen** [comment]
fixed
