### ISSUE TITLE
Icons are missing in Fork CMS 3.9.0

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1121]
![schermafbeelding 2015-03-06 om 09 47 02](https://cloud.githubusercontent.com/assets/588616/6522503/c4c0f4dc-c3e5-11e4-97ea-2c6c61e3a386.png)

**Comment by jeroendesloovere** [comment]
This occurs when we are in production;
when FORK_DEBUG and FORK_ENV are not enabled.

**Comment by WouterSioen** [comment]
It seems like the css minifier doesn't rewrite image paths anymore? poke @matthiasmullie

**Comment by WouterSioen** [comment]
We've updated the minifier from 1.3.19 to 1.3.20

**Comment by matthiasmullie** [comment]
Yup, I broke it. Recursive relative paths weren't properly being fixed.
Just released 1.3.21, which fixes that.

**Comment by WouterSioen** [comment]
fixed in master and in the 3.9.1 release that will probably be released next week!

**Comment by WouterSioen** [comment]
and thanks @matthiasmullie for the quick fix :+1:
