### ISSUE TITLE
Mailmotor statistics widget show $lblDashboardSubscribedOn

### ISSUE THREAD

**Issue by ghazispeakserve** [forkcms/forkcms#1126]
There is a missing label in Statistics widget of mailmotor.

![missing_label](https://cloud.githubusercontent.com/assets/4991088/6573083/bfd49c1e-c717-11e4-86d1-66b285109b45.png)

**Comment by WouterSioen** [comment]
Do you have time to create a PR? It's only a little effort to fix this one :smiley:

**Comment by ghazispeakserve** [comment]
I know !!! Overbooked !!! But yes I can do that easy one. In which locale.xml do we need it? Dashboard? Mailmotor?

**Comment by WouterSioen** [comment]
I'd put it in Mailmotor. If you just add it under locale > Backend > Core, it should be available in the dashboard module.
