### ISSUE TITLE
New feature: adding Arabic language support

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#1127]
I know it is not an easy one to implement. We RTL support for the layout and all labels and messages translated to Arabic. It is my mother tongue so I can do something for that.

**Comment by WouterSioen** [comment]
That would be awesome!

**Comment by ghazispeakserve** [comment]
I will start it once the backoffice boostrap is merged to master and not before April. I am away for the last two weeks of March.

**Comment by WouterSioen** [comment]
That's great! Looking forward to it.

**Comment by jeroendesloovere** [comment]
Hi @GhaziTriki, I was wondering if there should be added a "text right-to-left" layout-setting for this? Since Arabic is written from right to left, right?

**Comment by GhaziTriki** [comment]
Absolutely yes, Arabic should be displayed in a RTL layout.

**Comment by wouterverstuyf** [comment]
Hi @GhaziTriki, I was wondering what's the status of the translation? Is it already available?
I need to make a site with Arabic language enabled, so it would be wonderful.

**Comment by GhaziTriki** [comment]
Hi @wouterverstuyf,

I am discussing internally with my team to implement Arabic support and RTL for ForkCMS. It should be started soon. But I can't give a date when it will be available. I will follow up with updates as soon as possible.

**Comment by jeroendesloovere** [comment]
Should Arabic language require the database to be in utf8mb4?
See issue https://github.com/forkcms/forkcms/issues/1299

**Comment by GhaziTriki** [comment]
Utf8 database encoding is required for storing Arabic content in the database and of course utf8mb4 is advised agains the utf8 encoding

**Comment by jeroendesloovere** [comment]
@GhaziTriki and is it required to have "utf8mb4"
or will your Arabic locales also work with the current "utf8"?

**Comment by WouterSioen** [comment]
utf8 and general/unicode character set should be enough to store arabic. But it can't be a problem to bump to utf8mb4 ;)

**Comment by wouterverstuyf** [comment]
@GhaziTriki Thx, looking forward to it :)

**Comment by GhaziTriki** [comment]
We will start it when the twig implementation is fully ready for version 4, as implementing RTL to the current backend is too much effort.

**Comment by WouterSioen** [comment]
:+1:

**Comment by WouterSioen** [comment]
I'll close this as there is no progress in here.
