### ISSUE TITLE
SqlFormatter not found

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1132]
When installing the latest Fork CMS:
```
FatalErrorException: Error: Class 'SqlFormatter' not found in /xxx/src/Common/DataCollector/DatabaseDataCollector.php line 26
```

**Comment by WouterSioen** [comment]
did you do a composer install with the --no-dev flag?

**Comment by jeroendesloovere** [comment]
Debugging was enabled in my .htaccess. Removing this solved the problem.

**Comment by WouterSioen** [comment]
When setting debug on, you should also install dev dependencies, thus don't add the `--no-dev` flag.

**Comment by jeroendesloovere** [comment]
**Problem**

Debugging was enabled in my .htaccess.
```
FatalErrorException: Error: Class 'SqlFormatter' not found in /xxx/src/Common/DataCollector/DatabaseDataCollector.php line 26
```

**Solution 1: debugging disabled**

Removing debugging from ```.htaccess``` solved the problem.

**Solution 2: with debugging enabled**

Add debugging in your .htaccess and execute ```composer install``` . Then the dev dependencies are loaded in.

**Solution 3: with debugging enabled**
Moving ```sql-formatter``` in ```composer.json``` from ```require-dev```  to ```require```.
