### ISSUE TITLE
Refactor static function outputXML and outputJSON in API

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1142]
## Problem
When replacing SPOON_CHARSET by $container->getParameter('kernel.charset'),
Issue: #1138 
PR: #1140
We saw that we had to use BackendModel just for getting the container in a static function.

## Solution from @WouterSioen 
We can remove that ```use Backend\Core\Engine\Model as BackendModel``` again if we change these static functions to normal functions if we use ```$this->output in outputXML and outputJSON```

**Comment by WouterSioen** [comment]
The static isAuthorized and isValidRequestMethod methods are kind of a deal breaker.

I'd try to put the api in the container, so you could do `BackendModel::get('api')->isAuthorized()`, instead off `BaseApi::isAuthorized`. (and the same for isValidRequestMethod).

This way, all methods that call self::output could be made non-static!

**Comment by carakas** [comment]
@jeroendesloovere is this still an issue or was his solved already

**Comment by jeroendesloovere** [comment]
@WouterSioen Can you take a look at this, since you are more aware of the issue. I just found it :-P

**Comment by WouterSioen** [comment]
The API needs to be deprecated and altered by an easy way to add new API endpoints. This will also fix the usage of SpoonTemplate.
