### ISSUE TITLE
Cloud Filesystem Integration

### ISSUE THREAD

**Issue by markseddon** [forkcms/forkcms#1145]
ForkCMS looks pretty good but there's one killer feature that we need, S3 integration. 

The main limitation to this seems to be the integration with CKFinder which does not, in of itself, support S3 without a connector. There is a connector:

https://github.com/colonelchlorine/ckfinder-amazon-s3

but it's not very well maintained. We've got some experience with [Redactor](http://imperavi.com/redactor/) which is a newer and (IMHO) better editor. What's the appetite for changing the editor and / or including S3 integration? Happy to pitch in if the appetite is there.

**Comment by WouterSioen** [comment]
I like the layout and ease of use of this redactor editor, and it looks like it's extensible enough to provide all the functionality we use. I'd like to see an integration before putting money in something like this though.

I'm also not the only person to decide wether we'll want to change this editor. @forkcms/core-contributors what do you think?

**Comment by tijsverkoyen** [comment]
I agree with @WouterSioen

**Comment by WouterSioen** [comment]
poke @markseddon have you looked into this?
