### ISSUE TITLE
Deprecated calls used in the campaignmonitor integration.

### ISSUE THREAD

**Issue by WouterSioen** [forkcms/forkcms#1149]
Hi there! My name's Mercer and I'm the integrations specialist at Campaign Monitor. I recently ran into some trouble with one of my customers here having to do with adding a client in via your integration! In Campaign Monitor we have two different states that clients under the main account can be in: they can either send for themselves, or the main account can send for them. In the event that someone tries to connect a client account that is sending for themselves via your integration they get a 400: API deprecated message. It seems that you might be using some of our old code, and I just wanted to reach out and see if we might be able to work together to get that fixed.
Thanks!

**Comment by WouterSioen** [comment]
As a reference, this is our campaignmonitor library: https://github.com/forkcms/forkcms/blob/master/library/external/campaignmonitor.php

**Comment by davelens** [comment]
All of that code is relying on the state of the CM API of early 2011, so I'm not surprised. ^^
Ideally you'd want to use the official @campaignmonitor [PHP wrapper](http://campaignmonitor.github.io/createsend-php/)

**Comment by mercersmith** [comment]
Hi there, you asked that I provide a bit more information about what's going on with this. Unfortunately, as it was a client reporting the issue that's a bit tricky, but I suspect that the issue is underlying with @davelens' point above. Connecting the Client that is sending for themselves is where the 400 is popping, so looking into authentication there could be good.

**Comment by WouterSioen** [comment]
Ok, we'll look into migrating towards the official PHP wrapper.

**Comment by WouterSioen** [comment]
I guess we should wait for the bootstrap integration to be merged, to fix this, since it will need some changes in the backend (especially the mailmotor/settings action). Migrating won't be that hard though. Authenticating using an API key looks not that hard.

**Comment by WouterSioen** [comment]
This will be fixed with the upcoming version of the mailmotor module ( @jeroendesloovere )

**Comment by WouterSioen** [comment]
will be fixed with #1164
