### ISSUE TITLE
Bug: Spoon Date crashes when getTimeAgo is called

### ISSUE THREAD

**Issue by vytenizs** [forkcms/forkcms#1152]
Hello. I have used 3.10 branch for my project and when i try to enter "Pages" i get this error: "ContextErrorException: Notice: Undefined index: time in /media/storage/workstation/servers/http/www/vytsci.lt/vendor/spoon/library/spoon/date/date.php line 125". Anyone knows about this, any proper solutions?

**Comment by bart-webleads** [comment]
See: https://github.com/forkcms/library/commit/9d21f2ae912efeb5b7ab6f2702d407c9894e4707

**Comment by WouterSioen** [comment]
A PR with a fix is ready: https://github.com/forkcms/library/pull/17

**Comment by WouterSioen** [comment]
Fixed in both the master and the 3.10 branch

**Comment by vytenizs** [comment]
Thanks.
