### ISSUE TITLE
Hooks not working locally

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1154]
## Problem

Note: only on **localhost** they are not working 
Hooks are being added to the table ```hooks_queue``` with status ```queued``` and are not executed.

## Manually execute hooks

When manually visiting ```http://domainname.tld/backend/cronjob?module=Core&action=ProcessQueuedHooks``` in your browser the hooks are getting executed.

**Comment by WouterSioen** [comment]
I believe you should add this as a cronjob to execute your hooks.

I'm refactoring this thing to use the Symfony Event Dispatcher though (see #1125), so I don't think too much effort should be put in this.

**Comment by jeroendesloovere** [comment]
@WouterSioen 
This thing is so powerful that we have build modules to rely on this functionality.
So for me, this has **TOP PRIORITY**

**Comment by WouterSioen** [comment]
well, I guess you can just install the cronjob to run every minute?
