### ISSUE TITLE
Move FrontendModel and BackendModel shared methods to BaseModel

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#1165]
I have been checking FrontendModel and BackendModel classes, and I have found that some methods are just duplicated instead of being directly implemented to BaseModel. Is there any reason preventing those methods to be in the BaseModel class? The general rule is that the less duplicate we have the less duplicated bugs we have the code maintainability will increase.

The concerned methods are: addNumber, generatePassword, generateThumbnails, getUTCDate, getUTCTimestamp, subscribeToEvent and triggerEvent

getThumbnailFolders have slightly different implementations

**Comment by WouterSioen** [comment]
It would be great to have some of these in a BaseModel class!

**Comment by GhaziTriki** [comment]
I will handle this and propose some pull requests to remove as much duplicate code as possible.

**Comment by WouterSioen** [comment]
Great to hear!

**Comment by GhaziTriki** [comment]
A quick question. There is a lot of inheritance behaviour to add caused but duplicate code. Should the new classes be place in src/Common?

**Comment by GhaziTriki** [comment]
After a first commit it looks like that now inhanx@305bd5a in https://github.com/inhanx/forkcms/tree/better-inheritance

**Comment by WouterSioen** [comment]
@ikoene will check your pull request soon!

**Comment by ikoene** [comment]
@GhaziTriki Running into an error... Probably has something to do with the \SpoonTemplate instance used in /src/Frontend/Core/Engine/Form.php.

    ContextErrorException: Runtime Notice: Declaration of Frontend\Core\Engine\Form::parse() should be compatible with SpoonForm::parse($template) in /src/Frontend/Core/Engine/Form.php line 22

**Comment by GhaziTriki** [comment]
The issue have has been fixed here https://github.com/forkcms/forkcms/pull/1189

**Comment by ikoene** [comment]
Tested all common methods and they function as expected.

**Comment by GhaziTriki** [comment]
Is this pull request ready to be merged?

**Comment by ikoene** [comment]
afaik yes

**Comment by WouterSioen** [comment]
IMO, yes

**Comment by WouterSioen** [comment]
This has been merged
