### ISSUE TITLE
Update module translations in a single click

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#1168]
I am suggesting a new feature, update a module translations in a single click, the locale.xml file would be found automatically. It would help a lot of a module is updated, some labels are no more used and others are added.

**Comment by jeroendesloovere** [comment]
:+1:

**Comment by WouterSioen** [comment]
That would be great! PR's are welcome any time ;)

**Comment by WouterSioen** [comment]
You can now use `app/console locale:import -m locale` to achieve this result from the command line. (note, a version of Fork containing this is not released yet, but it's available in the master version)

**Comment by GhaziTriki** [comment]
Could this feature be added to the official documentation? I suggest adding a new tag "need documentation", I think it will make updating documentation easy and iterative. It is better than thinking about updating it all and doing nothing at the end.

**Comment by carakas** [comment]
there is already a `needs documentation PR` label
for new features
