### ISSUE TITLE
Use json_encode/json_decode instead of serialize/unserialize for better database portablity

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#1169]
I have seen that a lot of code portions ```serialize``` and ```unserialize``` are used to store database values. Why don't use ```json_encode``` and ```json_decode``` instead?

A database should always be portable and not dependant on the coding language. The programmer has to adapt himself to the database, not the code has to impose his philosophy to the database.

**Comment by WouterSioen** [comment]
I can't agree more to this!

**Comment by GhaziTriki** [comment]
Users are free to create a third party application (Java or Ruby daemon as example) to process database values. What will happen to that case? I am suggesting this because we are working on a project that took big proportions.

**Comment by WouterSioen** [comment]
This should not cause problems with Fork, as long as no invalid data will be created (like pages without meta-data, blogposts without category,...)

**Comment by WouterSioen** [comment]
A pull request for this would be very welcome!

**Comment by GhaziTriki** [comment]
Will do this.

**Comment by WouterSioen** [comment]
@GhaziTriki any news on this?

Note that this could cause issues with for example DateTime objects.

**Comment by GhaziTriki** [comment]
I have started this, it contains too much updates than my expectations. I know that I am proposing an interesting update from an architectural point of view because, it will take some time to be finished as I do not have too much time for open source contribution in the coming weeks.

**Comment by WouterSioen** [comment]
Ok, thanks for the update!

**Comment by WouterSioen** [comment]
We won't have time to do this soon, and it would cause problems with objects (like DateTimes). If you have a solution, feel free to PR.
