### ISSUE TITLE
Move tables engine to InnoDB

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#1170]
I have come to an issue where I have business process flow that needs to use database transactions to maintain the database integrity. I have figured out that all tables are using MyISAM engine. Isn't it better to move all of them to InnoDB?

**Comment by WouterSioen** [comment]
We use MyISAM to be able to use full text search in the search module. I guess it shouldn't be a problem to use InnoDB for other tables though.

**Comment by GhaziTriki** [comment]
Along with the general phasing out of MyISAM, InnoDB full-text search (FTS) is finally available in MySQL 5.6.4 release.

http://dev.mysql.com/doc/refman/5.6/en/innodb-table-and-index.html#innodb-fulltext-index

**Comment by WouterSioen** [comment]
I don't think we can force users to use the latest MySQL version. Most Fork users have shared hosting and can't choose to upgrade themselves.

**Comment by WouterSioen** [comment]
I'll close this because it can only be done with too new MySQL versions.
