### ISSUE TITLE
Doctrine: forget $language, here is Translatable

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1171]
When Doctrine is integrated, maby we can see if we can integrate multi-language in a more advanced way using Translatable, [see this Category Entity example](https://github.com/Atlantic18/DoctrineExtensions/blob/master/example/app/Entity/Category.php)

**Comment by WouterSioen** [comment]
I've used it in real life projects™ and it's not 100% documented how you can get it to work, but once it works, it's pretty good :)

**Comment by WouterSioen** [comment]
It's mentioned in the original Translation issue, so this extra issue isn't needed anymore.

**Comment by jeroendesloovere** [comment]
@WouterSioen My reference was wrong and I removed it now. 

This issue is actually a "request" to use "Translatable" for our modules with "multiple languages".

**Comment by WouterSioen** [comment]
Every time I use the "Translatable" behavioural extension, I find it really frustrating to get it to work very well. We could look out if there are better ways to implement this.

**Comment by jeroendesloovere** [comment]
This is my "[Translatable](https://gist.github.com/jeroendesloovere/0e339b0c90449e507066d84933411639)" installation guide.
Works perfectly.

**Comment by carakas** [comment]
BC Break because of database changes caused by using translatable
