### ISSUE TITLE
Analytics module <-> Google not working anymore since 20 april

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1173]
**Problem**

Google has disabled connections from deprecated Google Apps APIs, since 20 april.
So it is impossible to connect the Analytics module using Google API Console server key.
[More info Google gives you](https://support.google.com/a/answer/6201352)

**Solution**

We need to use the new Google API and AUTH 2.0

**Comment by jeroendesloovere** [comment]
Hi @annelyze,
I see that you have coded the cronjobs for this Analytics module.
Would you find some time to update this module for the latest Google API,
since the old Google API is deprecated.

**Comment by WouterSioen** [comment]
I'll rewrite this module.

**Comment by WouterSioen** [comment]
Note to self: only use cached data in the widget, don't fetch data in there.

**Comment by annelyze** [comment]
No longer in the development business I'm afraid. Full confidence in Wouter to fix it swiftly and smoothly :+1:

**Comment by WouterSioen** [comment]
I'll try to do it asap!
