### ISSUE TITLE
Backend Bug for User who logs out.

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1175]
**Problem**

Steps to reproduce:
* Add a new user which has no rights for the **groups** nor **users** module.
* Click **Log out** at the top right button
* Log in as that new user.

Then you see the error.
![schermafbeelding 2015-05-05 om 10 28 32](https://cloud.githubusercontent.com/assets/588616/7469259/7fb75844-f311-11e4-92b7-0df4bc882e25.png)

**Solution**

Fixing the method which checks which module to redirect to.

**Comment by WouterSioen** [comment]
@Landerstraeten didn't you change something about this?

**Comment by Landerstraeten** [comment]
@WouterSioen yes. Will check!

**Comment by Landerstraeten** [comment]
I don't think this is a bug. I created a new project with a new test user. This user only have permissions on the index action of the pages module. When I log out as god user, and try to log in as the test user, it automatically redirects to the index action of pages.
I recommend to give the group of the user at lease the rights to the default action. I this case, I gave the test user the right index of the pages module.

**Comment by jeroendesloovere** [comment]
@Landerstraeten 
In my setup, the user has "index" permissions for the "pages" module.
![schermafbeelding 2015-05-05 om 14 37 18](https://cloud.githubusercontent.com/assets/588616/7472580/5110630a-f334-11e4-9e5d-9dea80e16cba.png)
![schermafbeelding 2015-05-05 om 14 37 08](https://cloud.githubusercontent.com/assets/588616/7472578/510bb530-f334-11e4-8143-581433a47d36.png)
![schermafbeelding 2015-05-05 om 14 36 58](https://cloud.githubusercontent.com/assets/588616/7472579/51104690-f334-11e4-856a-0f98516deb68.png)

Seems like the backend logs me in and then tries to connect to /users/index as you can see in this redirect ```http://www.domainname.tld/private/nl/error?type=action-not-allowed&querystring=%2Fprivate%2Fnl%2Fusers%2Findex%3Ftoken%3Di1jsontqg0```

**Comment by Landerstraeten** [comment]
This is the problem:
/private/en -> looks for the first allowed module -> users -> looks for the first allowed action -> Edit -> redirects to /private/en/Edit -> id is not set = not existing -> private/en/users/index?token=abc..&error=non-existing -> action (index) not allowed -> private/en/error?type=action-not-allowed&querystring ... -> displays the error You have insufficient rights for this action.

**Comment by WouterSioen** [comment]
If you give rights to one action of a module, always make sure it also works without extra parameters, since the CMS could redirect you to it.

It's possible to build a fix for this but it would require a lot of work for just a small problem.

**Comment by jeroendesloovere** [comment]
I reopened this because this BUG really annoys me. When I'm testing things. I mostly log out as "admin" and then log in as a "user with less rights". And every time I get to see that error page. Not very user friendly that is...

**Comment by WouterSioen** [comment]
@jeroendesloovere can you test this? A fix for this should be merged (and the functional tests say it should work)
