### ISSUE TITLE
New Core Functionality: Exporting titles/texts/locale

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1177]
**Example**

A customer wants another language on its website **and a copyrighter has to translate all texts**.
What we now have to do is copy/paste all titles and texts from **all modules** to a .doc document, so the copyrighter can give us a price offer.

**Problem**

Jeezus. That is a lot of time-consuming, especially on large website projects with plenty of modules and content.

**Solution**

Their should somewhere be a button **export** in the core, which exports title/texts/locale/... from all modules, for example:
* Module Pages
    * title
    * ? meta title
    * ? meta description
    * ? meta keywords
    * ? custom URL
    * editor blocks
    * content blocks
* Module ContentBlocks
* Module Locale
* Module Blog
* Module Faq
* ... any other module should be able to hook into this module

But thats not all, if every page dumps their meta keywords. We would pay the copyrighter a lot for all those same (duplicated) words. It should be nice if there should be created a meta keywords table, containing the unique keywords.

Also their should be a way to hook up all custom modules to this export.
So other modules like blog, jobs, products, catalog, ... can take advantage of this as well.

Love to see some feedback on this. @forkcms/moderators @forkcms/owners @forkcms/website @forkcms/core-contributors

**Comment by WouterSioen** [comment]
That would be awesome. Implementation would be hard though, because of the meta tables. Feel free to give a proposition on how you would make a (generic) solutions for this.

And what kind of file would you import/export? We'd like a file structure that's rather decoupled from the data structure in Fork. This would make it easier to use this for a long time.

**Comment by carakas** [comment]
@jeroendesloovere any update on this?

**Comment by jeroendesloovere** [comment]
@carakas you are setting the right steps in your PR for Doctrine + ContentBlocks with a CopyContentBlockToOtherLocale Command. Such a feature could/should be written for every module. Then we can use these...

**Comment by jeroendesloovere** [comment]
No further update on this, since I'm waiting for Doctrine integration and Entities.

**Comment by carakas** [comment]
ok, feel free to create a PR for this when possible
