### ISSUE TITLE
Search module shows hidden FAQ pages

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#1179]
When doing a search, hidden pages are in the list of results. Then we click on of the results we get a 404 error page.

**Comment by GhaziTriki** [comment]
@WouterSioen Is this issue confirmed? Did you reproduce it?

**Comment by WouterSioen** [comment]
I didn't have time to test this right now, but when I look in the code, we're definitely filtering on hidden pages in the query (https://github.com/forkcms/forkcms/blob/master/src/Frontend/Modules/Pages/Engine/Model.php#L124)

**Comment by GhaziTriki** [comment]
Sorry, I correctly renamed this issue, it is about FAQ questions not about pages.

**Comment by WouterSioen** [comment]
There's also a check in there to avoid hidden faq questions to be shown: https://github.com/forkcms/forkcms/blob/master/src/Frontend/Modules/Faq/Engine/Model.php#L335

**Comment by GhaziTriki** [comment]
After checking the reason is the following: The page having the FAQ module has been hidden. Does it make a better sense now?

**Comment by WouterSioen** [comment]
If you don't have a visible page with the Faq module attached to, you should disable the faq in the search module. You can do this in the backend in /private/\<language\>/search/settings

**Comment by GhaziTriki** [comment]
I agree. It is completely logcial.
