### ISSUE TITLE
No styles in backend after installation

### ISSUE THREAD

**Issue by sguse** [forkcms/forkcms#1181]
This is a continuation from [Fork Support Forum](http://www.fork-cms.com/community/forum/detail/styles-and-backgroundimages-only-in-debug-mode).

After installation i went to backend login and found many 404 Errors while loading the css-files from a non existent path e.g. this: `http://fork.local/src/Core/Layout/Css/imports/typography.css`.

In debug-mode the same style where loading from another source and find under `/src/Backend/Core/`.

I've installed on a local Windows Client, with Zend Server, Apache2 and PHP FPM 5.5, and MySQL 5.5.

I've downloaded fork-3.9.1.tar.gz from website and followed the step-by-step guide, then i clone the master from github, after that i checkout the 3.9.0 tag - every time the installation wizard runs without any erros, but the styles was not loading.

**Comment by WouterSioen** [comment]
We'll look into this. Thanks for the bug report.

**Comment by WouterSioen** [comment]
This will be fixed in our upcoming release (and in the master branch)

**Comment by sguse** [comment]
Great :thumbsup:

**Comment by ciryk** [comment]
I still have thesame problem. @Mac MAMP it's working, but on Windows MAMP it isn't. I tried through composer and manually from the zip on fork cms website and also tried overwriting it with github files. Nothing is working so far..
