### ISSUE TITLE
BUG: backend mailer is not using {include:

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1184]
**Problem**
BUG: backend mailer is not using {include:
So the emails are getting send without HTML.

**Example**
This is how the mail comes into my mailbox:
```html
{include:/Core/Layout/Templates/Mails/Header.tpl}

... Message ...

{include:/Core/Layout/Templates/Mails/Footer.tpl}
```

**Comment by jeroendesloovere** [comment]
@WouterSioen Any news about this?

**Comment by WouterSioen** [comment]
In which email do you have this issue? there is not "Backend" or "Frontend" Mailer anymore ;) It's probably just one template not containing include tags?

**Comment by WouterSioen** [comment]
poke @jeroendesloovere

**Comment by WouterSioen** [comment]
poke @jeroendesloovere

**Comment by jeroendesloovere** [comment]
This happened when I used the #971 branch.

**Comment by WouterSioen** [comment]
This probably means that you should add the includes in the templates in that branch ;)

**Comment by jeroendesloovere** [comment]
Probably happened once in an old dev-Fork CMS-version.
