### ISSUE TITLE
To much memory usage in Locale module

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1185]
**Problem**

The Backend Locale module uses to much memory. On some servers I need to increase the memory limit, because it otherwise throws a white page on the /index page.

**Solution**

Rewrite this module.

**Comment by WouterSioen** [comment]
Nice solution :p

**Comment by Thijzer** [comment]
Where is the code of this epic rewrite :D :D

**Comment by guytarded** [comment]
Could that be solved with the xliff thingy? Maybe rewrite the module so it generates xliff's when save is pressed if users want to alter labels or something

**Comment by jeroendesloovere** [comment]
Should be fixed when refactor this module (#408).

**Comment by WouterSioen** [comment]
Closing in favor of #408
