### ISSUE TITLE
3.9.1 production backend css path broken

### ISSUE THREAD

**Issue by MathiasDewelde** [forkcms/forkcms#1186]
I just switched a project on Fork CMS 3.9.1in production mode.
The frontend is fine but the backend doesn't load any css files.

```http://***/src/Backend/nd/Core/Layout/Css/imports/wizard.css Failed to load resource: the server responded with a status of 404 (Not Found)```

```http://***/src/Backend/nd/Core/Layout/Css/imports/misc.css Failed to load resource: the server responded with a status of 404 (Not Found)```

```http://***/src/Backend/nd/Core/Layout/Css/imports/editor.css Failed to load resource: the server responded with a status of 404 (Not Found)
...```

The path doesn't look correct: http://---/src/Backend**/nd**/Core/Layout/Css/imports/editor.css

**Comment by WouterSioen** [comment]
Hmm, I think somebody already mentioned this. We'll look into this!

**Comment by WouterSioen** [comment]
Probably related: #1181

**Comment by MathiasDewelde** [comment]
In the Backend/Cache/MinifiedCss i found a file containing this:

```@import url(../../nd/Core/Layout/Css/imports/typography.css);@import url(../../nd/Core/Layout/Css/imports/structure.css);@import url(../../nd/Core/Layout/Css/imports/dashboard.css);@import url(../../nd/Core/Layout/Css/imports/core_modules.css);@import url(../../nd/Core/Layout/Css/imports/ui_constructs.css);@import url(../../nd/Core/Layout/Css/imports/buttons.css);@import url(../../nd/Core/Layout/Css/imports/tags.css);@import url(../../nd/Core/Layout/Css/imports/balloon.css);@import url(../../nd/Core/Layout/Css/imports/tooltip.css);@import url(../../nd/Core/Layout/Css/imports/forms.css);@import url(../../nd/Core/Layout/Css/imports/messaging.css);@import url(../../nd/Core/Layout/Css/imports/autocomplete.css);@import url(../../nd/Core/Layout/Css/imports/password_strength.css);@import url(../../nd/Core/Layout/Css/imports/datagrid.css);@import url(../../nd/Core/Layout/Css/imports/datafilter.css);@import url(../../nd/Core/Layout/Css/imports/general_purpose_classes.css);@import url(../../nd/Core/Layout/Css/imports/clearfix.css);@import url(../../nd/Core/Layout/Css/imports/avatars.css);@import url(../../nd/Core/Layout/Css/imports/wizard.css);@import url(../../nd/Core/Layout/Css/imports/misc.css);@import url(../../nd/Core/Layout/Css/imports/editor.css);```

**Comment by WouterSioen** [comment]
so it could be an issue with our minifier? Can you try `composer update matthiasmullie/minify` and then check if it is fixed?

**Comment by MathiasDewelde** [comment]
Tried the latest release of matthiasmullie/minify.
Only versions <= 1.3.18 seem to work..

**Comment by WouterSioen** [comment]
poke @matthiasmullie

**Comment by matthiasmullie** [comment]
@MathiasDewelde What is the full path to your forkcms setup?

**Comment by MathiasDewelde** [comment]
/Users/mathias/Documents/— Projecten/***/Web/src/Backend/Modules/Testimonials/Actions

**Comment by matthiasmullie** [comment]
The — (multibyte character) is the problem. Fix coming up.

**Comment by MathiasDewelde** [comment]
:+1:

**Comment by matthiasmullie** [comment]
Fixed in https://github.com/matthiasmullie/path-converter/commit/fcda5cc99c45c2e08d7f2ff59b4dd503c729275d

New Minify tag pushed, update you versions!

**Comment by WouterSioen** [comment]
updated!
