### ISSUE TITLE
Overriden spoon 1.3.17 methods incompatible

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#1188]
The commit below makes at least backend and frontend parse() method of Form.php class incompatible which makes running the prontend and the backend impossible.

https://github.com/forkcms/library/commit/d52abaa755bcfd8cb2cccc50f30b529fa6a14052

**Comment by GhaziTriki** [comment]
I am preparing a pull request for the coming minutes to quickly fix this.

**Comment by WouterSioen** [comment]
I did not update this in Fork yet, because our composer.lock files locked spoon library to 1.3.16. Your fix has been merged though. Thanks!

**Comment by GhaziTriki** [comment]
Thank you. I always do a composer update when upgrading to check whether something is broken or no. You are doing a great work thank you.
