### ISSUE TITLE
Radio button use of === fails with numeric values

### ISSUE THREAD

**Issue by nosnickid** [forkcms/forkcms#1194]
Initialising a radio button:

    $options = array(array('value' => '1', 'label' => 'one'), array('value' => '2', 'label' => 'two'));
    $this->frm->addRadiobutton('rad', $options, '1');

With numeric-ish values prevents the default from being auto-selected.

This is because the comparison in radiobutton.php:285

    if($value === $this->getChecked()) $element[$name] .= ' checked="checked"';

Always fails because an associative array instantiated with "integer strings" ends up with integer keys:
  
    $array = array( (string) '1' => 'one');
    $keys = array_keys($array);
    echo gettype($keys[0]) . "\n"; // prints "integer"

Hence, the type aspect of the === comparison fails.

Are the Spoon* elements being deprecated? Is it worth fixing this bug?

I can force my values to be strings ('a1') a do a bunch of substring hacks for the moment, but obviously this isn't ideal.

**Comment by WouterSioen** [comment]
All SpoonElements are indeed deprecated, but we can't say exactly when SpoonForms will be fully removed. I thus think it's worth it to still fix this. You can do a pull request to http://github.com/forkcms/library .

**Comment by WouterSioen** [comment]
I'll close this issue here, since it's a library and not a cms issue. Thanks for the report though!
