### ISSUE TITLE
Create a ModuleSettings service to make module settings mockable.

### ISSUE THREAD

**Issue by WouterSioen** [forkcms/forkcms#1195]
Static calls can't be mocked in tests. ModuleSettings is called from everywhere and thus makes sure we can't test a lot of stuff. When we create a moduleSettings service that can be injected everywhere using dependency injection, it will enable us to test more code.

I'll look into this soon.

**Comment by WouterSioen** [comment]
See #1196

It contains the ModulesSettings service, tests for it and an integration in the new Analytics module to show how you can inject it and let it help you to write tests for code that uses the module settings.

**Comment by jeroendesloovere** [comment]
@WouterSioen Can this be closed?
