### ISSUE TITLE
Fork 3.9.2 on one.com hosting (open_basedir restriction in effect)

### ISSUE THREAD

**Issue by freshface** [forkcms/forkcms#1201]
Anyone had the same problem? With this: http://hadron.management/install
This is the php info: http://hadron.management/i.php

Regards

**Comment by jessedobbelaere** [comment]
I could get Fork CMS perfectly running on one.com if I disable debug mode. With debug mode enabled however, the open_basedir warning kept on showing up

**Comment by WouterSioen** [comment]
This is the case: Symfony's debug mode doesn't work well together with open_basedir restrictions. You can test it locally in debug mode and put it online in production mode on the server though.

**Comment by freshface** [comment]
Thx, it works now

**Comment by WouterSioen** [comment]
Great!

**Comment by jeroendesloovere** [comment]
Hi @freshface 
One.com hostings always have server caching enabled for every type of file.
So if not already asked to one.com, I suggest asking them to put that caching off.
