### ISSUE TITLE
BUG in the new Analytics Module

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1205]
**Problem**

The day after setting up Analytics module successfully on some of my clients,
the module is not working anymore.

**Internal server error.** 
```php
request.CRITICAL: Uncaught PHP Exception Google_Auth_Exception:
"The OAuth 2.0 access token has expired, and a refresh token is not available.
Refresh tokens are not returned for responses that were auto-approved."
at /vendor/google/apiclient/src/Google/Auth/OAuth2.php line 242
```

**Another internal server error.**
```php
request.CRITICAL: Uncaught PHP Exception Google_Service_Exception:
"Error calling GET https://www.googleapis.com/analytics/v3/data/ga?ids=ga%3xxx&start-date=2015-05-14&end-date=2015-05-21& .... 
(403) User does not have sufficient permissions for this profile.
```

**Comment by WouterSioen** [comment]
You should get a refresh token because access type is set to offline https://github.com/forkcms/forkcms/blob/master/src/Backend/Modules/Analytics/Actions/Settings.php#L53

**Comment by WouterSioen** [comment]
@jeroendesloovere I think it will be fixed if you choose an emailadres on the consent screen of your Google Console applications. This seems to be necessary to retrieve refresh tokens. (See 3e5ae2e)

**Comment by WouterSioen** [comment]
Can you verify this and close this if it's fixed?

**Comment by jeroendesloovere** [comment]
@WouterSioen No, that is not the problem. Mail address has been filled in in every application.

**Comment by WouterSioen** [comment]
@jeroendesloovere can you test this? https://github.com/forkcms/forkcms/tree/analytics-service-account

**Comment by WouterSioen** [comment]
This is in fact the only commit containing the needed changes.

**Comment by WouterSioen** [comment]
poke @jeroendesloovere could you test this please? If it's the fix that's needed, I'd like to merge this asap ;)

**Comment by jeroendesloovere** [comment]
Closing this because [fix is integrated](https://github.com/forkcms/forkcms/commit/de42269e4c87a82c67c420cd0fecbbe886c45718)
