### ISSUE TITLE
Functional tests screw up the 'production' cache

### ISSUE THREAD

**Issue by dubgeiser** [forkcms/forkcms#1209]
When you run the functional tests, cached templates are overwritten... to reproduce (this is the case where I discovered it at least):

  * Go to the detail of the blog post, url: http://fork.dev/en/blog/detail/nunc-sediam-est
  * Run the test suite
  * reload the url: I got some editor content "Location"

when you run ./tools/remove_cache, all is well again.

This might not be considered critical, but I can see this causing confusing in CI/D systems.

**Comment by WouterSioen** [comment]
We'll fix it this way:

* Cache files that should not be available through a url, will be put in the kernel.cache_dir, which makes them environment dependant.

* For other cache files (like locale and pages), we'll add the environment in the filename and we keep them in the same directory. locale.json will for example become locale.test.json and locale.prod.json.
