### ISSUE TITLE
Import and export icons direction inverted

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#1213]
Hi Guys,

Looking at the export and import icons direciton in "Backend->Settings->Translations" I have a strange feeling. They don't look right, normally the import should have the arrow down because we are pulling data, and an arrow up for the export because we are pushing data out.

**Comment by WouterSioen** [comment]
For developers, your versions are logical, but for the users, the other directions are more logical. When exporting, we want the arrow down, because we are downloading data.

**Comment by jeroendesloovere** [comment]
:+1:

**Comment by GhaziTriki** [comment]
Will be fixed in the bootstrap merge.
