### ISSUE TITLE
Feature: SEO url structure

### ISSUE THREAD

**Issue by vytenizs** [forkcms/forkcms#1217]
Hi, i often come to an argument with clients about SEO urls. For example Fork has structure like this: for blog: http://someproject.com/blog/ (here is everything OK)
for blog category: http://someproject.com/blog/category/somecategory (I got often requests to make it /blog/somecategory but this isnt the main issue)
for blog item: http://someproject.com/blog/detail/somepost (And this is a pain in the ass, because url should show category in which post was posted because Google shows only Blog - SomePost, but no Category and i cant have Two post with same name within different categories. For example.: I have categories Roulette and Poker and i want to create posts into both of them called Tips, this is just example, because i can create category tips and place Roulette and Poker within, but this is just an example)

Any proper solution to this? Cuz i love Fork CMS, but these SEO complaints are killing me :D

**Comment by WouterSioen** [comment]
It would be awesome to have something like this, but in the current structure, this is sadly not possible. When we're getting closer to full Symfony integration, it'll probably be easier to implement something like this.

**Comment by vytenizs** [comment]
I have a solution, but its not clean. Its with callbacks and is slow. It would be nice to have Symfony2 Routing solution. But please do not close this issue it is very important one :)

**Comment by WouterSioen** [comment]
I'll close this since fixing this is not a priority for us. Pull request for this are welcome.

**Comment by vytenizs** [comment]
@WouterSioen can you take a look at my PR https://github.com/vytenizs/forkcms/pull/23 i've made concept of how should something like this work.

**Comment by WouterSioen** [comment]
I've given some comments purely on code styles. I'll look into it together with another developer to see if we find any issues with your implementation.

**Comment by vytenizs** [comment]
Made a follow up. This is kinda just an example how i think this should work, but this is the best i came up with. And Blog module part isnt finished, so after your check i will complete this part. Ty for review.
