### ISSUE TITLE
CLI command for generating modules/actions/widgets

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1231]
## Feature request

It would be awesome if the same functionality from @turanct repo [forkmodule-cli](https://github.com/turanct/forkmodule-cli) will be integrated in the **core**.

So we can do things like:
```
# generate a module
php app/console forkcms:generate:module Vehicles

# generate an action
php app/console forkcms:generate:action Index

# generate a widget
php app/console forkcms:generate:widget AllCars
```

**Comment by jeroendesloovere** [comment]
@turanct Would be awesome if you can provide us with a PR containing this.

**Comment by MathiasDewelde** [comment]
:+1: would be a great core feature!

**Comment by WouterSioen** [comment]
@turanct doesn't use Fork anymore in his daily job, so I don't think he'll create a PR for this ;)

**Comment by WouterSioen** [comment]
We won't do this before we're in Symfony Full stack. For now, you can use these alternatives:

* https://github.com/woutersioen/ModuleMaker
* https://github.com/turanct/forkmodule-cli
* ...
