### ISSUE TITLE
Feature request: make it possible that content blocks can't be deleted.

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1236]
**Problem**

Sometimes when you do in a Frontend template:
```
{$var|parsewidget:'ContentBlocks':'Detail':'4'}
```
You don't want a user to delete that specific ContentBlock in the backend.

**Solution**

Make it possible - just like with pages - that there is a setting that "if checked" you can't delete the content block.

**Comment by WouterSioen** [comment]
You can disable the rights (in the groups module) for the content blocks delete action.

**Comment by jeroendesloovere** [comment]
@WouterSioen Yes, but thats an all-wide solution, not available "per content block".

**Comment by WouterSioen** [comment]
True, but it could still be a solution to your issue :)
