### ISSUE TITLE
setId method Profile class should not be public

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#1237]
Hi,

Looking at the code of Profile.php, the method setId should not be public. I suggest making it private, setting the id of the profile should be possible by loading it from the database only.

The line of code is here https://github.com/forkcms/forkcms/blob/master/src/Frontend/Modules/Profiles/Engine/Profile.php#L304

**Comment by WouterSioen** [comment]
I fully agree with this. In the ideal situation, it's even inserted in the constructor, so the setId method could then be removed.

**Comment by WouterSioen** [comment]
It looks like the setter is never used in our code, so I made a PR to make the method private.

See https://github.com/forkcms/forkcms/pull/1250
