### ISSUE TITLE
Composer post-install scripts windows

### ISSUE THREAD

**Issue by glenncoppens** [forkcms/forkcms#1238]
Hi

Although using the git bash on windows still makes it impossible to execute the post-install (& -update) scripts in the composer.json file and therefore the Fork CMS installation cannot be completed (javascript malfunctioning and partial css styles).
If the `php` and `sh` commands are explicitly defined, everything runs smoothly :)

```
"scripts": {
    "post-install-cmd": "php app/console assetic:dump . && cd tools && sh ./remove_cache",
    "post-update-cmd": "php app/console assetic:dump . && cd tools && sh ./remove_cache"
},
```

Tnx Glenn

**Comment by WouterSioen** [comment]
Can you open a pull request for this? this will make it easier for us to review this.
