### ISSUE TITLE
X-Frame-Options deny

### ISSUE THREAD

**Issue by jacob-v-dam** [forkcms/forkcms#1241]
Why are in the new version **X-Frame-Options** to **deny** and not to **SAMEORIGIN**?

If you want to load a iFrame to an internal page this would cause an error.

**Comment by WouterSioen** [comment]
Why would you want to load an iframe to an internal page in the first time ;)

The deny is the best practice provided by the OWASP security list.

**Comment by jacob-v-dam** [comment]
Good question ;). This is done to display different projects in the Netherlands. For example: http://www.buroboot.nl/projecten/tuinen-van-west-amsterdam and click on **Bekijk alle projecten op de kaart**

Is there a way to overrule this option in this specific request?

**Comment by WouterSioen** [comment]
I'd just change `deny` to `sameorigin` in https://github.com/forkcms/forkcms/blob/master/src/Common/EventListener/ResponseSecurer.php for this specific project.
