### ISSUE TITLE
Why is parsePagination() not possible in a Frontend Widget?

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1243]
**Problem**
parsePagination() not possible in a Frontend Widget

**Comment by WouterSioen** [comment]
Widgets normally don't handle pagination, as they should work exactly the same on each page, and thus are not build to manipulate navigation (which is what pagination does).

**Comment by guytarded** [comment]
In some cases this could come in handy. For example, a blogwidget which shows the articles per category. I would consider implementing this functionality.

What do others think about this?

**Comment by WouterSioen** [comment]
I'm don't really like this. The idea of actions is that they can show data, they can redirect and they can manipulate the url.

Widgets are just used to display some "extra" data on your page. They can also use the url to provide some data based on the context, but they should not be used to redirect or change the url of the page it's on.

**Comment by jeroendesloovere** [comment]
@WouterSioen I don't agree that. In Fork CMS you can only add one module to a page. So you are limited in what you can do with blocks. Thats why widgets are the ideal medium to expand the functionality on a page.

**Comment by WouterSioen** [comment]
We talked this over in the Fork meeting:

We have two types of blocks in Fork:

* modules => they have a concept of url's, navigation, pagination,...
* widgets => they are meant to just show extra data on a page and not manipulate data.

What if you have a widget and a module (or even two widgets) on one page with pagination, how can we know which block the page parameter is set for?

Only allowing pagination in modules avoids this problem.
