### ISSUE TITLE
Radio button default value with space creates error in FormBuilder

### ISSUE THREAD

**Issue by jacob-v-dam** [forkcms/forkcms#1252]
If you try to create radio buttons with values which contains spaces and select one of them you get an error while saving. It is not possible to refresh the form.

> This value "test 1" is not among the list of values.

**Comment by WouterSioen** [comment]
This is an issue of http://github.com/forkcms/library, can you create an issue there?

**Comment by jacob-v-dam** [comment]
Is it? This only happens in the FormBuilder. When the value is "test 1" than the key will be "test-1".

The FormBuilder stores the value instead of the key.

**Comment by WouterSioen** [comment]
Ah, ok, I didn't get that, it's a Fork issue then!
