### ISSUE TITLE
Don't redirect in AJAX-actions

### ISSUE THREAD

**Issue by tijsverkoyen** [forkcms/forkcms#1256]
In https://github.com/forkcms/forkcms/blob/master/src/Frontend/Modules/Search/Ajax/Livesuggest.php#L202 there is code to redirect. This is weird behaviour because this action is requested through XHR, so the response should be a decent error instead of a redirect.

**Comment by Thijzer** [comment]
new Fix #1288

**Comment by WouterSioen** [comment]
fixed by @Thijzer
