### ISSUE TITLE
Follow PHP supported versions as minimum support.

### ISSUE THREAD

**Issue by WouterSioen** [forkcms/forkcms#1257]
see: https://secure.php.net/supported-versions.php

**Comment by bart-webleads** [comment]
May update the install screen requirements information.
It still talks about 5.3.3 while the checkPhpVersion function checks for 5.4
Of give a warning when user is still on 5.3 something like use at own risk...

And maybe also update the documentation.
http://www.fork-cms.com/community/documentation/detail/installation/minimum-requirements

**Comment by WouterSioen** [comment]
Good points, we'll look into this.

It's also nearly time to bump the minimum version to 5.5!
http://php.net/supported-versions.php

Op woensdag 9 september 2015 heeft Bart Lagerweij <notifications@github.com>
het volgende geschreven:

**Comment by tijsverkoyen** [comment]
@WouterSioen can you alter the new minimum version

**Comment by WouterSioen** [comment]
The docs are updated too
