### ISSUE TITLE
BUG: error when trying to add new User Group.

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1258]
**Steps to reproduce**

* Install latest Fork CMS
* Try to add a new User Group
You'll get the following error (when in debugging mode): ```Unable to parse the p12 file. Is this a .p12 file? Is the password correct? OpenSSL error:```

**Comment by WouterSioen** [comment]
Fixed in https://github.com/forkcms/forkcms/commit/a4d14b66d632803a8357136e79031a0a919e0a78
