### ISSUE TITLE
Request for error fetching in Analytics module

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1259]
**What?**

When setting up the Analytics module, you sometimes get "internal server errors".
```
Oops! An Error Occurred

The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
```
As a developer you can check the error in the prod.log, but Fork CMS users can not do this, so they don't know what exactly went wrong.

Error .log example:
```
request.CRITICAL: Uncaught PHP Exception Google_Auth_Exception: "Error refreshing the OAuth2 token, message: '{   "error" : "invalid_grant" }'" at /xxx/vendor/google/apiclient/src/Google/Auth/OAuth2.php line 357 {"exception":"[object] (Google_Auth_Exception(code: 400): Error refreshing the OAuth2 token, message: '{\n  \"error\" : \"invalid_grant\"\n}' at /xxx/vendor/google/apiclient/src/Google/Auth/OAuth2.php:357)"} []
```
=> Is just an error to say that your mail address has not yet been added to your google analytics account.

**Solution**
Fetching every error and displaying it to the Fork CMS user.

**Comment by WouterSioen** [comment]
I think this should be fixed in here too: https://github.com/forkcms/forkcms/commit/a4d14b66d632803a8357136e79031a0a919e0a78

Can you check this please?

**Comment by jeroendesloovere** [comment]
Well, is it possible that I don't see any specific "error fetching + showing the error message". So the user isn't in the dark when configuring the module.

**Comment by WouterSioen** [comment]
These errors shouldn't be shown on the dashboard. If you install the analytics module, but don't configure it, we don't want these strange confusing error messages to be shown there.

**Comment by jeroendesloovere** [comment]
I agree that. But what about errors in the "setting-up" phase?

**Comment by WouterSioen** [comment]
The use cases I encountered are catched and displayed to the user.
