### ISSUE TITLE
Double language in redirect using queryString

### ISSUE THREAD

**Issue by glenncoppens** [forkcms/forkcms#1260]
Hi

Building a multi language site (EN, NL, FR), with only NL enabled at the moment, I'm trying to get the querystring and attach it to the login anchor (@jeroendesloovere login link widget) when a profile is logged out.
Eg the result is this (seems to be ok):
```
http://site.dev/nl/aanmelden?queryString=nl/contact
```

When logging in, the redirect happens but the url is malformed, being:
```
http://site.dev/nl/nl/contact
```

I parse the querystring into the template like this:
```
// assign queryString to login link (on each page)
if(!$this->URL->getParameter('queryString')) {
    $this->tpl->assign('queryString', $this->URL->getQueryString());
} else {
    $this->tpl->assign('queryString', $this->URL->getParameter('queryString'));
}
```

Template:
```
{$var|geturlforblock:'Profiles':'Login'}{option:queryString}?queryString={$queryString}{/option:queryString}
```

I can use trim to filter the language part out, but I thought that it might be a misbehaviour?

Tnx

**Comment by jeroendesloovere** [comment]
What if you try adding a trailing **/** before **nl**:
```http://site.dev/nl/aanmelden?queryString=/nl/contact```

**Comment by glenncoppens** [comment]
Allright, that works apparently :+1: 
Trim the FRONTEND_LANGUAGE also works.

Not that it's too much work though, isn't this strange to do this manually?

**Comment by jeroendesloovere** [comment]
If we would change:
```
{$var|geturlforblock:'Profiles':'Login'}{option:queryString}?queryString={$queryString}{/option:queryString}
```
to
```
{$var|geturlforblock:'Profiles':'Login'}{option:queryString}?queryString=/{$queryString}{/option:queryString}
```

Would that solve your problem?

**Comment by glenncoppens** [comment]
Probably.

But i'm just wondering why the leading `/` isn't included by default when calling `getQueryString()`

**Comment by WouterSioen** [comment]
We can change the getQueryString method to still return the leading slash. This would be a backwards incompatible change, so we can merge this in 3.10.

Do you want to make a pull request for this?

**Comment by ikoene** [comment]
It's ironic that the leading slash is trimmed, because every time the getQueryString method is used the slash is manually added again. There's only one case where the slash needs to be trimmed, and it's actually already done [here](https://github.com/forkcms/forkcms/blob/master/src/Frontend/Core/Engine/Header.php#L845)

I'll make the pull request.

**Comment by jeroendesloovere** [comment]
@ikoene :+1:
