### ISSUE TITLE
Error when installing new Fork CMS

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1265]
**Problem**
When installing the latest Fork CMS version (with Analytics module enabled) you get the following error when you log in.
![schermafbeelding 2015-07-22 om 08 22 11](https://cloud.githubusercontent.com/assets/588616/8819249/dbf238ec-304a-11e5-918f-0e0b9de12751.png)

**Comment by WouterSioen** [comment]
Hmm, the analytics dashboard widgets give errors when analytics isn't configured yet, I'll fix it.
