### ISSUE TITLE
Content Blocks disappearing, missing from dropdown list and appearing in wrong theme block after save

### ISSUE THREAD

**Issue by sverraest** [forkcms/forkcms#1271]
I recently upgraded to Fork CMS 3.9.4 and noticed that even though the content blocks are appearing in the list of content blocks they don't appear in the dropdown when adding content blocks to a page.
I have to delete them and add them again.

Also, it appears that they are randomly added to wrong sections of the template after saving.
So let's say I add Content block X to section Main of the template, after saving it appears in the Header section of the template.

Furthermore, If I add a content block in the EN language to a EN page, I noticed that random content blocks from NL are suddently missing on all NL pages.

This is causing me a lot of troubles, especially because it's so difficult to have templates per language.
It would also be a lot easier if I could copy a page to start a new page from instead of adding tens of content blocks again.

Also, it should be more clear than when resetting a template in EN, this also affected all other languages.
This caused to me to lose all content block information in another language. Imo this should be language dependent. (I just lost a days work of content migration as switching to another language just reset all content blocks which are now also missing).

Any ideas?

**Comment by WouterSioen** [comment]
Have you done manual changes in your database? It looks like some data isn't correct anymore.

**Comment by sverraest** [comment]
No manual database changes.
Upgrading = manually copy pasting content over from backend to backend. 
It's a weird one as I can't really pinpoint the issue. What I did notice is that when I edit Content Blocks their position sometimes shifts from wherever they are used in template section X to another one Y.  Let's say I have an address content block in the footer, if I edit the content block or add a new one suddenly on random pages this address content block now appears in the main section of the template.

**Comment by ikoene** [comment]
@sverraest Are you still experiencing these issues? I'm unable to reproduce the bug in 3.9.4. From which release did you upgrade?

**Comment by sverraest** [comment]
Hi @ikoene, did a reinstall so can't confirm anymore. It was as was mentioned here probably a database corruption.
