### ISSUE TITLE
Double JS when enabling widget on module page

### ISSUE THREAD

**Issue by wouterverstuyf** [forkcms/forkcms#1272]
VERSION: 3.9.3
When you enable a widget of the same module that is loaded, the JS of that module will be added double.
Example: Make a folder in the frontend module Blog Js/Blog.js page /blog (with module blog enabled on this page) Extra widget in the sidebar: Recent articles
Result: Double loaded Blog.js in the footer...
Cause: It comes from the priority_group value in the addJS (Header.php) function. For modules this is 2, for widgets it's 3 so the double JS isn't recognized.
=> How to fix this? Thx!

**Comment by WouterSioen** [comment]
will soon be fixed when merging #1262
