### ISSUE TITLE
Fatal Error when entering wrong p12 certificate and email combination

### ISSUE THREAD

**Issue by sverraest** [forkcms/forkcms#1275]
It's not clear from the instructions in Analytics that you will need to use the long service email account and not the analytics owner gmail account.
Furthermore, this fails to a HTTP/500 instead of catching the "invalid grant" error from the Google API Client and displaying the error.
Once this error appears there is no way of unlinking these settings as the Analytics module will always fatally error out.
The only solution was to delete the settings entry from the DB.

**Comment by WouterSioen** [comment]
Have you still encountered this issue?

**Comment by vytenizs** [comment]
Unable to connect to API for hours. Throws 500 errors. Actually Analytics module is unusable at the moment.

**Comment by WouterSioen** [comment]
I'll look into it when I have some more time (maybe tomorrow)
