### ISSUE TITLE
Admin backend inaccessible when having incorrect Google Analytics settings.

### ISSUE THREAD

**Issue by sverraest** [forkcms/forkcms#1276]
Related to https://github.com/forkcms/forkcms/issues/1275

Once you have submitted incorrect details for your Google Analytics linking the Dashboard will become inaccessible due to errors from the Google API Client not being caught.

**Comment by WouterSioen** [comment]
This has been fixed in the master branch and will be included in the upcoming release (see https://github.com/forkcms/forkcms/commit/a4d14b66d632803a8357136e79031a0a919e0a78)
