### ISSUE TITLE
Start of body scripts for Google Tag Manager

### ISSUE THREAD

**Issue by tbernaerd** [forkcms/forkcms#1277]
Google Tag Manager snippets need to be put after the opening <body> tag. This means we'll need a field in the backend similar to the current header and footer scripts. The snippets also need to be added to all templates after the <body> tag.

Since GTM is becoming more prevalent and because marketeers are a whiny bunch, I'd like this built into Fork.

Planning on PR'ing this after feedback.

**Comment by WouterSioen** [comment]
I think this would be a great addition!

**Comment by guytarded** [comment]
+1

**Comment by ikoene** [comment]
Done in #1286

**Comment by jeroendesloovere** [comment]
:+1:
