### ISSUE TITLE
getUrlForBlock returns hidden pages/blocks

### ISSUE THREAD

**Issue by megasnort** [forkcms/forkcms#1278]
When a page is hidden, the [getUrlForBlock method](https://github.com/forkcms/forkcms/blob/master/src/Frontend/Core/Engine/Navigation.php#L533) still returns that page's url when it contains the given block. I think this is a bug (since the url of the page will not work an return a 404)

If considered a bug, I'll be glad to do a pull request, I fixed this for a project at work.

On an other note, when a block exists on a page, but the block is hidden (the eye-button) the getUrlBlock-method still returns it's page. I think this is a bug too.

**Comment by WouterSioen** [comment]
A pull request to fix this would be very welcome!

**Comment by megasnort** [comment]
For the record, I made a pull request for this (https://github.com/forkcms/forkcms/pull/1281) but the link does not show up. Apparently I need to refer to #1278 in a commit, not only in the subject of the request.

**Comment by Thijzer** [comment]
I'm not sure but a similar issue is given from Per, maybe the fix I wrote also helps as hidden page will now always return the 404 page. #1287
