### ISSUE TITLE
google Analytics AAuth 2.0 integration from the begin

### ISSUE THREAD

**Issue by WouterSchoofs** [forkcms/forkcms#1280]
When I installed forkcms v3.9.x with the new google Analytics OAuth 2.0 integration, I got an 500 "internal Server Error”. 
When I turned on the debugmode, i got the following error. http://cl.ly/image/0a1J0w0n2c1D

**Comment by WouterSioen** [comment]
This has been fixed in the master. If you want to patch your install, you can use this commit: https://github.com/forkcms/forkcms/commit/a4d14b66d632803a8357136e79031a0a919e0a78

**Comment by vytenizs** [comment]
I received 500 after trying to connect it with API. It says invalid_grant or smth.
