### ISSUE TITLE
[discuss] Forkcms standard for storing keys

### ISSUE THREAD

**Issue by guytarded** [forkcms/forkcms#1285]
Yesterday at the meetup we had a small chat about storing api keys and stuff. What will be the standard for ForkCMS about this?

There are two options:
* Store the key in the database which is more userfriendly when installing modules.
* Store the key in the parameters file which is less userfriendly but avoids several environments.

It would be nice if we had a standard about this.

**Comment by guytarded** [comment]
Any news on this?

**Comment by WouterSioen** [comment]
Can some more information about this discussion be given? This is a rather short version I guess ;)

**Comment by guytarded** [comment]
As a mather of fact this isn't the short description :)
I just want to know what will be the standard for storing keys when developing modules. It's about PAI keys I'm talking here. Do you store them in the database or in the parameters file as that is more secure

**Comment by WouterSioen** [comment]
When I'm accessing an external API, I tend to have two different situations:

1. You have an API token / secret /... that will the same forever (and thus needs no refreshing)

=> save them in the parameters.yml file

2. You have an API using refresh tokens or that should be configurable from the backend

=> store them in the database.

**Comment by WouterSioen** [comment]
I btw don't really get your point about environments. You have both a different parameters.yml file and a different database on other environments, so __both__ are environment specific.

**Comment by guytarded** [comment]
Ok, it needs to be stored in the parameters file then. The discussion on the meetup was about keys that don't need refreshment. 

Thx
