### ISSUE TITLE
Frontend JS bug

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1291]
**Steps to reproduce**
* Use any frontend module (f.e.: Categories) which has no 'JS' folder in it.
* Then create a JS folder in your frontend theme with a file, f.e.: Categories.js

**Bug**
The frontend JS file (src/Frontend/Themes/MyTheme/Modules/Categories/Js/Categories.js) will not be loaded. This is because src/Frontend/Modules/Categories/Js/Categories.js does not exist.
I find this stupid, because if you want to add extra JS-functionality that is not possible.

**Solution**
Let the frontend theme JS file be loaded in, even when no default js file exists.

**Comment by WouterSioen** [comment]
We're not really convinced that this is the way to go.

If you have a Blog.js file in your theme, and we decide to add a Blog.js file in the module, our added functionality will not be present in your website.

If We have a Blog.js file in our module, and you add a Blog.js file in your theme, you should duplicate all the functionality in it.

**Comment by jeroendesloovere** [comment]
@WouterSioen, I don't really see why this is not "the way to go".
```
If We have a Blog.js file in our module, and you add a Blog.js file in your theme, you should duplicate all the functionality in it.
```
=> Indeed, if you want that JS-functionality... otherwise, you can delete the JS-functions which you don't want.

**Comment by jeroendesloovere** [comment]
Situation:
A module, without a default "module.js".

The frontend developer adds a theme custom "module.js",
thinking that it will load, but that will not be the case.

**Comment by WouterSioen** [comment]
In our case, the JavaScript to make a module work is written by the developers, and only the lay-out related JavaScript is written by the frontend developer (in a theme specific (but not module specific) JavaScript file).

With this workflow, it does not make sense to overwrite the module.js files, because this will remove the needed implementation.

**Comment by vytenizs** [comment]
I think what he means is that, theme developers should be allowed to create custom module/action js files, but not custom built in js files. Yeah i found that irritating too. If Blog -> Archive does not contain Archive.js by default and i want some neat functionality I have to edit core module to add js file.

**Comment by jeroendesloovere** [comment]
@vytenizs Yep thats what I mean.

**Comment by WouterSioen** [comment]
We won't currently put effort in this.
