### ISSUE TITLE
Remove jQuery UI in frontend

### ISSUE THREAD

**Issue by jessedobbelaere** [forkcms/forkcms#1303]
Jacob posted [a topic on the fork forum](http://www.fork-cms.com/community/forum/detail/why-include-jquery-ui-css-by-default) why there's jQuery UI css & js loaded into every Fork CMS page. 

As far as I know, it's only used for the search widget autocomplete list and the occasional datepicker in the frontend (not that common in normal websites, and if needed, people tend to use better libraries like [pickadate.js](http://amsul.ca/pickadate.js/)). 

Is it a good thing to remove jquery ui from the frontend, and just load it when the search module is used? That saves two requests (`jquery-ui.css`, `jquery-ui.js`) on pages that don't use search/datepickers... Or remove jquery ui completely and use [typeahead.js](https://twitter.github.io/typeahead.js/) for the search autocomplete?

**Comment by WouterSioen** [comment]
I'm completely in favour of completely removing jquery-ui and using something like typeahead.js instead.

**Comment by jessedobbelaere** [comment]
Great, I'll see if I can do a PR. 

What should happen to the datepickers defined in `frontend.js` when I remove jquery UI? 

And should I add typeahead.js to the js core folder or to the search module? And would it be better if I move the search functionality from `frontend.js` to `Search.js` & `typeahead.js` in the module JS folder? But those are two additional scripts on each page unfortunately. Maybe combine typeahead.js and the search functionality into one js file?
