### ISSUE TITLE
Fabbot.io

### ISSUE THREAD

**Issue by jessedobbelaere** [forkcms/forkcms#1307]
Can [Fabbot.io](http://fabbot.io/) be used to check Fork CMS pull requests?

**Comment by WouterSioen** [comment]
<img width="558" alt="screen shot 2015-10-07 at 13 56 15" src="https://cloud.githubusercontent.com/assets/1398405/10336729/36f1fd94-6cfb-11e5-9fed-c370fec7d6f5.png">

**Comment by jessedobbelaere** [comment]
Only for symfony itself available at the moment? Damn :(

**Comment by WouterSioen** [comment]
It looks like it. I can only find twig and Symfony using it

**Comment by jessedobbelaere** [comment]
Maybe [Nitpick](https://nitpick-ci.com/) is a nice addition to the forkcms github? (free for opensource projects)

**Comment by jonasdekeukelaere** [comment]
I think @WouterSioen is using https://styleci.io/ already.

**Comment by WouterSioen** [comment]
yes, we're already using style ci to check pull requests on style issues.
