### ISSUE TITLE
Latest Fork CMS throws error at MatthiasMullie Scrapbook

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1318]
Whoops, looks like something went wrong.

1/1FatalErrorException: Error: Class 'League\Flysystem\Adapter\Local' not found in /...../vendor/matthiasmullie/scrapbook/src/Adapters/Filesystem.php line 30

Steps to reproduce:
* Install latest Fork CMS dev-master

**Comment by WouterSioen** [comment]
I guess `league/flysystem` should be added to the composer.json and lock file?

**Comment by jeroendesloovere** [comment]
@WouterSioen , k, I'm checking this out and creating PR if needed.

**Comment by WouterSioen** [comment]
Hmm, this should not be an issue, since it does not yet use league/flysystem (see https://github.com/forkcms/forkcms/pull/1315)

**Comment by matthiasmullie** [comment]
I should probably have clarified in the open pull request that the current filesystem adapter has been deprecated and is now a wrapper over Flysystem adapter (so also requires league/flysystem).

In hindsight, given the added requirement, I probably should've kept the original filesystem implementation until dependants have caught up. I'm restoring the original Filesystem adapter (https://github.com/matthiasmullie/scrapbook/commit/bc7a6cdf60a923deba2165b5a8cbd3cca5543506) & will push a new release shortly.

Meanwhile, merging #1315 will make Fork CMS start using the league/flysystem backend, which should be safer & more versatile.

**Comment by matthiasmullie** [comment]
Should be fixed with https://github.com/matthiasmullie/scrapbook/releases/tag/1.0.4
