### ISSUE TITLE
Blog comments form dissapears when overwriting the template

### ISSUE THREAD

**Issue by wouterverstuyf** [forkcms/forkcms#1321]
BLOG MODULE:
When overwriting the default template in Detail.php like this:
$this->loadTemplate(null, true);
... the comment form dissapears.

Any idea how to fix this? 
I thought the bug get triggered when using multiple forms on a page (ex: search widget) but can't get it fixed.

Thx!

**Comment by WouterSioen** [comment]
where do you put this code?

**Comment by wouterverstuyf** [comment]
/src/Frontend/Modules/Blog/Actions/Detail.php

    public function execute()
    {
        parent::execute();
        $this->loadTemplate(null, true);
        $this->getData();
        $this->loadForm();
        $this->validateForm();
        $this->parse();
    }

The template gets loaded without the default template, but the comment form is not visible. When I use the normal template like below the comment form is correct:

    public function execute()
    {
        parent::execute();
        $this->loadTemplate();
        $this->getData();
        $this->loadForm();
        $this->validateForm();
        $this->parse();
    }

But the problem is that I need a different layout structure for the detail page of a blog item, so overwriting the template would be handy :)

Thx!

**Comment by WouterSioen** [comment]
You could add "Blog Detail" as a new extra in the modules_extras table, so you'd be able to couple it to a seperate page with a different layout

**Comment by wouterverstuyf** [comment]
Owkey, thx for your reply.
Indeed, by creating a new template it should work. But I thought the comment form would also be parsed when you overwrite the default template.
Anyway, there is a way to do it, that's the most important :)
