### ISSUE TITLE
The right forum

### ISSUE THREAD

**Issue by jacob-v-dam** [forkcms/forkcms#1322]
Which is the right forum to use? The one on www.fork-cms.com or forum.fork-cms.com? 

I think it would be better to use one rather than two. It also shows the commitment for the community and will probably solve some answers.

**Comment by jessedobbelaere** [comment]
The forum on the website is the right one. The forum.fork-cms.com is still online for archive purposes, but it should be closed so people can't start a new discussion, or simply show a warning. I believe @Diewy tried once to import all the discussions from the old forum into the new forum so he could delete the old forum, but it was too complicated. 

When you search for "forum forkcms" you end up on the forum.fork-cms.com, pretty confusing I admit

**Comment by jacob-v-dam** [comment]
Right ;) so the README file has to updated. It refers to the old forum ;-)

**Comment by jessedobbelaere** [comment]
Oops, indeed! Nice catch! I fixed it
