### ISSUE TITLE
Search module not giving wanted result

### ISSUE THREAD

**Issue by freshface** [forkcms/forkcms#1327]
When I am searching for the term "HPV" [link to site](http://www.biovox.be/en/search?form=search&q=HPV&submit=Search) I don't get any results.

But this post has that term in his content  [link to post](http://www.biovox.be/en/insights/detail/preventing-cervical-cancer-vaccinating-or-freezing)

Any ideas?

**Comment by WouterSioen** [comment]
your mysql settings are probably setup that search terms under 4 characters aren't matched. This is the case in most mysql installs (to improve fulltext search performance)

**Comment by WouterSioen** [comment]
@freshface have you tested this by changing the mysql settings? This is a known problem with mysql full text search, but we can't fix this easily (without changing to a specific search database like elasticsearch of do ugly things like append all words under 4 letters with extra content)
