### ISSUE TITLE
No way to override date.timezone

### ISSUE THREAD

**Issue by vytenizs** [forkcms/forkcms#1329]
In some cases you need to override date.timezone of PHP settings and there is no way to achieve this within Fork CMS interface. Is this was made on purpose?

**Comment by WouterSioen** [comment]
Do you want to override the date.timezone for your complete project or for some specific parts of Fork CMS?

**Comment by vytenizs** [comment]
Server has multiple projects on it and single one needs specific timezone set. But i did not find any way in achieving this on code side.

**Comment by WouterSioen** [comment]
i'd just put `ini_set('date.timezone', 'Wanted/Timezone');` in the index.php file of your project.

**Comment by vytenizs** [comment]
Why cant we add this option in parameters.yml?

**Comment by vytenizs** [comment]
I saw that code checks if timezone is set and if not it sets it to Berlin. But why we cant add option that could override default server timezone? Is there any issues with that?

**Comment by WouterSioen** [comment]
I think this is project specific, and it's not many work (only one line) to put it in your index.php file.

I don't think this should be added in the parameters.yml file. Best practice is adding it in your server configuration. If it isn't in there or if you want to overwrite it, I think it should be done in your application code and not in the parameters file

**Comment by vytenizs** [comment]
Well ok. I just seen lots of applications with this option within configuration. Thought maybe this is a proper optional parameter.

**Comment by WouterSioen** [comment]
I'll keep this issue open to see if others also want to have this functionality. But it's not needed in my opinion :)

**Comment by vytenizs** [comment]
I`m also think that server should be configured properly, and such options should be placed in php.ini file. But this is not true in some cases, and I do not like editing core files, because I`m constantly updating it. It is just against my ethics :D

**Comment by GhaziTriki** [comment]
This feature was previously discussed in #1075, setting the timezone in your php.ini is the recommended way to do it.

**Comment by vytenizs** [comment]
@GhaziTriki ofcource it is recommanded. I would love to see all shared servers to be configured as recommanded.

**Comment by WouterSioen** [comment]
@vytenizs if your server doesn't allow changing your php.ini file, you should add it the your index.php file. This will make sure your timezone is set before fork or the symfony kernel is bootstrapped. This is the safest way.
