### ISSUE TITLE
FormBuilder EventDispatcher not working.

### ISSUE THREAD

**Issue by freshface** [forkcms/forkcms#1330]
Hi

When I dump something in https://github.com/forkcms/forkcms/blob/master/src/Frontend/Modules/FormBuilder/EventListener/FormBuilderSubmittedMailSubscriber.php#L32 on L32 I don't see my Spoon::dump()

When I do it locally it works.

Any ideas?

**Comment by WouterSioen** [comment]
The only thing I can think of is a case mismatch between the class and the filename, but I can't find anything. The class stated in the services.yml file is also correct, so I have absolutely no idea what goes wrong at this moment.

**Comment by WouterSioen** [comment]
Is the FormBuilder module installed on the server? Have you tried removing the production cache? (app/cache/prod)

**Comment by WouterSioen** [comment]
Which PHP version do you use? Is opcache running? Is your error reporting on? Have you tried using a `var_dump`?

**Comment by jeroendesloovere** [comment]
Hi @freshface, indeed, I have experienced the same ```bug``` too in other modules and in multiple Fork CMS websites.

**STRANGE BUG**
It seems like Fork CMS has sometimes problems loading in Fork CMS Modules "bundles".
And therefore isn't loading in DependencyInjections and their "/Resources/config/services.yml" files.
@WouterSioen I already told you this a few times in our conversations.
=> When deploying to server using capistrano deploy, it happens that services can't be found. And therefore I can't deploy successful (deployment rollback).

When you then do ```app/console container:debug```
You even don't see the defined "services" from that modules "/Resource/config/services.yml" files.
=> My temporary solution is to define in your ```app/config.yml``` an extra import
```yaml
imports:
    - { resource: parameters.yml }
```

Anybody else experiencing this? @forkcms/core-contributors 

My setup:
* Mac
* MAMP Pro (@freshface, are you also using MAMP?)

**Comment by WouterSioen** [comment]
I don't know if the module configs are loaded in cli commands, but they should _always_ be loaded when a module is installed.

**Comment by jeroendesloovere** [comment]
@WouterSioen Another strange thing:

Sometimes all modules in "Fork CMS Backend > Settings > Modules" are being defined in one DataGrid, even the non-installed modules. And then when you click on a module and clicking "install", the DataGrid is working properly again.
@freshface are you experiencing this also in your production site?

**Comment by jeroendesloovere** [comment]
@freshface, do you see the fork cms formbuilder event listeners when you do ```app/console container:debug```?

**Comment by freshface** [comment]
I cleared app/cache and it worked.
It seemed the listeners weren't registered in the cache.
