### ISSUE TITLE
linkList is undefined in CKEditor when trying to get list of pages

### ISSUE THREAD

**Issue by sverraest** [forkcms/forkcms#1334]
In the Backend when I try to bring up the list of links to create an anchor in the editor I'm just getting a white screen but no CKEditor popup.

The javascript error is 

`Uncaught ReferenceError: linkList is not defined - Backend.js:420` 

Did anything change in the editor?

**Comment by sverraest** [comment]
Turns out is was an issue when 

`$fs->dumpFile(
            $cachePath . 'editor_link_list_' . $language . '.js',
            $this->dumpEditorLinkList($navigation, $keys, $language)
        );`

fails

**Comment by vytenizs** [comment]
You should reopen this issue. This happens when u clear cache and editors_link_list is not generated. You have to go to pages and edit some page & save it. Then editor_link_list will be generated and error is gone, but it is still a bug.
