### ISSUE TITLE
Blog meta records

### ISSUE THREAD

**Issue by bartdc** [forkcms/forkcms#1335]
When saving blog posts, there are maximum 21 records in blog_posts table. 1 active record and 20 old versions. But the meta records aren't deleted when deleting old versions when reaching 20 versions. So the meta table becomes scattered with meaningless meta records.

**Comment by WouterSioen** [comment]
This should be easy to fix (deleting meta when deleting the old revisions)

**Comment by bartdc** [comment]
Consider it done.

**Comment by WouterSioen** [comment]
@bartdc will you do a pull requests for this?

**Comment by bartdc** [comment]
Yes, it's planned for the weekend.

**Comment by WouterSioen** [comment]
:+1:

**Comment by bartdc** [comment]
Just give me a couple of days.

**Comment by WouterSioen** [comment]
No problem, take your time!
