### ISSUE TITLE
Failing form redirects in production environment

### ISSUE THREAD

**Issue by glenncoppens** [forkcms/forkcms#1336]
Hi

Yesterday I deployed my application to the production server (php 5.6). When I ran fork (3.9.5) in debug mode everything worked (profiles registrations, login etc.). But when running it in non-debug mode, everything was fine, except redirects did not work when registering, logging in, ...

So for example: a user registers itself, fills out the form, clicks submit. The form is being validated, activation mail is sent, but then the redirect does not happen and apparently shows the filled out form again with the error message that is defined in the catch scope (Register.php). 

The same happened to other forms also (with try-catch block). I guess it's related to Tommy's previous issue #1297? So every redirect in a try-catch block should be modified to something like (it's not tested yet):

```
try {
    ...

    // redirect
    $this->redirect(SITE_URL . '/' . $this->URL->getQueryString() . '?sent=true');
} catch(RedirectException $e) {
    throw $e;
} catch (\Exception $e) {
    // when debugging we need to see the exceptions
    if ($this->getContainer()->getParameter('kernel.debug')) {
        throw $e;
    }
} finally {
    // show error
    $this->tpl->assign('registerHasFormError', true);
}

...
```

I'll try to add a PR as soon as possible if this is the way to go?

Grtz Glenn

**Comment by WouterSioen** [comment]
This is fixed in https://github.com/forkcms/forkcms/pull/1298

**Comment by glenncoppens** [comment]
Isn't this only fixed in Mailmotor? Not in Profiles?

**Comment by WouterSioen** [comment]
Hmm, sorry, Seems like I didn't read your issue correctly.
