### ISSUE TITLE
Invalid init-type on app/console methods

### ISSUE THREAD

**Issue by jessedobbelaere** [forkcms/forkcms#1340]
Just cloned a fresh copy of the master branch. 
When I execute composer install or `app/console` or `app/console cache:clear`, I receive the following error:

    Invalid init-type

This error comes from src/Common/Core/Init.php
Looks like app/console is having issues.

**Comment by jessedobbelaere** [comment]
@jeroendesloovere @WouterSioen Can you try the master branch and see if you also experience this error? Issue looks related to https://github.com/forkcms/forkcms/pull/1306

**Comment by WouterSioen** [comment]
I noticed this too. I'll fix this soon!

**Comment by WouterSioen** [comment]
fixed in dcbd90c2579b6c2b98c5a54fa04d78e506b63f3c

**Comment by WouterSioen** [comment]
thanks for the work on the fork themes btw! I'll try to get in touch with Bert from Wijs to get all these PR's merged :+1:

**Comment by jessedobbelaere** [comment]
Awesome, thanks! 😃

**Comment by WouterSioen** [comment]
He's on Holiday right now, but comes back the 28th.
