### ISSUE TITLE
Sessions directory in app (app/sessions or app/cache/prod/sessions)

### ISSUE THREAD

**Issue by bartdc** [forkcms/forkcms#1343]
Symfony saves every session to a file. After a couple of weeks, this folder contains thousands and thousands of useless files.

I have a VPS with limited inodes so I suppose this can be an issue for other users as well.

**Comment by WouterSioen** [comment]
You could create a cronjob that removes files older then a specific time? This is an example command to remove files older than 7 days:

`find /path/to/files* -mtime +7 -exec rm {} \;`

You could run it daily (at midnight) using a cronjob like this:

`0 0 * * * find /path/to/files* -mtime +7 -exec rm {} \;`

**Comment by bartdc** [comment]
Yep that's my quick & dirty solution. I'm cleaning 9 session folders every night wich means deleting 20k files.

But I thought maybe Fork CMS could clean this folder without cronjobs (when session is closed [if possible], when someone logs in to /private, first visit of the day, ...).

**Comment by WouterSioen** [comment]
hmm, we could maybe abuse the "kernel.terminate" event for this.

**Comment by bartdc** [comment]
Probably a good solution for users without knowledge/possibility of working with cron's.

**Comment by WouterSioen** [comment]
I'll check if we can use the native PHP session storage instead of the app/sessions folder (using the native file session handler from symfony)

**Comment by Dextro** [comment]
We had the same issue on a production server. There are no inodes available anymore, causing issues with writing new (cache) files. So you get http 500 errors.

Is there a reason why there is set a specific path?

**Comment by WouterSioen** [comment]
This was a fix to make this work on some servers, but I can't reproduce it anymore. We could probably just use the default php session directory. I guess this is autocleaned?

**Comment by Dextro** [comment]
Indeed, see `/etc/cron.d/php5` on Debian/Ubuntu servers.

**Comment by WouterSioen** [comment]
https://github.com/forkcms/forkcms/pull/1456 fixes this
