### ISSUE TITLE
Blog comments overview SQL error

### ISSUE THREAD

**Issue by jacob-v-dam** [forkcms/forkcms#1344]
When I try to open the blog comments overview I get this error:

```
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #6 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'p.title' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

**Comment by bart-webleads** [comment]
What version of forkcms are you using?

**Comment by jacob-v-dam** [comment]
The latest version: 3.9.6

**Comment by WouterSioen** [comment]
and what mysql version are you using?

**Comment by WouterSioen** [comment]
I guess this will be a MySQL setting. Changing "sql_mode=only_full_group_by" to something else will probably fix this

**Comment by WouterSioen** [comment]
http://stackoverflow.com/a/23921234/1454599 <= how to fix this
