### ISSUE TITLE
Issue with incompatible version of Scrapbook

### ISSUE THREAD

**Issue by vytenizs** [forkcms/forkcms#1345]
After composer update, Fork throws exception:
FatalErrorException: Error: Call to undefined method MatthiasMullie\Scrapbook\Psr6\Item::exists() in /media/storage/workstation/servers/http/fork/src/Common/ModulesSettings.php line 142

If older version of scrapbook is downloaded everything works. Looks like newer version has changes incompatible with Fork CMS.

**Comment by WouterSioen** [comment]
@matthiasmullie any idea?

**Comment by WouterSioen** [comment]
nevermind, looks like a fix is already provided in https://github.com/forkcms/forkcms/pull/1346

**Comment by matthiasmullie** [comment]
#1346 is perfect. PSR-6 wasn't final yet (it is now so we should be fine) and `exists` has been removed since.

**Comment by WouterSioen** [comment]
ok, thanks for letting us know!
