### ISSUE TITLE
refactor out SpoonFilter::getGetValue and SpoonFilter::getPostValue

### ISSUE THREAD

**Issue by WouterSioen** [forkcms/forkcms#1347]
These methods access the $_GET and $_POST superglobals, which make writing tests a lot harder.

We can get our GET and POST variables from the request object which can be fetched everywhere.

**Comment by vytenizs** [comment]
Should be cool to know if someone is working on this one or not :) I mean i would gladly contribute on my free time, but I wanna know that no ones job wont go to waste :)

**Comment by WouterSioen** [comment]
I'm not working on it right now, and I don't think anybody else is, so it would be great if you'd do this one!

**Comment by vytenizs** [comment]
Ill write here when I start working on this issue for other to know.

**Comment by WouterSioen** [comment]
:+1:

**Comment by carakas** [comment]
@vytsci any update on this?

**Comment by vytsci** [comment]
I have to take a look at what code looks atm. Ive started this task long ago. But Fork has changed "a bit" so i need to take a grasp on what is done. Ill let u know today.

**Comment by StijnVrolijk** [comment]
Remove code from the Spoon library

**Comment by jonasdekeukelaere** [comment]
@carakas I'll have a look at this.
