### ISSUE TITLE
ForkCMS demo

### ISSUE THREAD

**Issue by bart-webleads** [forkcms/forkcms#1350]
The forkCMS demo website is down.

http://demo.fork-cms.com/

It says "Internal error"..

**Comment by WouterSioen** [comment]
We're working on it. Our server has to be upgraded to a newer php version.

**Comment by WouterSioen** [comment]
It's ready on the new server. We just need to change A-records and the demo will be up and running again!

**Comment by WouterSioen** [comment]
Fixed!
