### ISSUE TITLE
Slack/Gitter chat

### ISSUE THREAD

**Issue by jessedobbelaere** [forkcms/forkcms#1353]
Quick question: would it be a good idea to ditch IRC and start using something new to chat about Fork development? This way we can get more people involved in the roadmap, talk & discuss larger features, helping out with quick questions or issues, ...

### [Gitter](https://gitter.im)
* Gitter provides free public chat rooms for communities and open source projects
* Simple to use, with powerful integrations into GitHub and other services.
* Gitter allows users and developers to collaborate in real-time
* Because of its integration with Github authentication and its web-based chat client, it is easy and convenient for users and developers to join a chat room
* https://gitter.im/forkcms

*If so, a core developer with access to this forkcms/forkcms repo could login on gitter, create a new room for the repository "forkcms". I don't have rights to create a gitter room for this repo ;) And then we can add a gitter badge to the readme too.*

### [Slack](https://slack.com/)
* Easy to integrate with
* Excellent interface on multiple platforms
* Slack is for teams, not really for communities.
* Free, but only: 5GB storage, 10k recent messages in search

I would prefer Gitter, but don't have any experience with it.

**Comment by WouterSioen** [comment]
Hmm, if we would do this, I'd prefer slack over gitter (since I'm already on IRC and slack). Adding another chat to my stack would probably drive me crazy ;)

**Comment by jessedobbelaere** [comment]
Yeah Slack is the most popular one and most devs have it already installed, so I would agree on Slack too

**Comment by guytarded** [comment]
Slack please!

**Comment by jessedobbelaere** [comment]
Yes, if someone could setup a slack channel and make a Fork CMS blogpost about it, that would be great :-)

**Comment by WouterSioen** [comment]
![screen shot 2016-01-11 at 11 40 27](https://cloud.githubusercontent.com/assets/1398405/12231485/25e26266-b858-11e5-8ac2-f8c9142b5bb3.png)

Hmm, there's a small problem with this. We have to add all allowed domains to slack, or send invitations to everyone.

**Comment by jessedobbelaere** [comment]
Hmm I guess we could use [Slackin](http://rauchg.com/slackin/) (*or create a page/widget ourself with an e-mail field and a join button, and you receive an invitation e-mail*). 
Slackin makes a landing page, a html badge with embedded invitation form, and a github svg badge. 

Some examples:
* http://hashtaggaming.herokuapp.com/
* http://www.angularbuddies.com/

Then just add a link to the Slackin page on the fork support webpage, and add the badge to github readme etc?

**Comment by WouterSioen** [comment]
https://fork-cms.herokuapp.com/ Can you test this?

**Comment by jessedobbelaere** [comment]
Works perfectly!

**Comment by WouterSioen** [comment]
@tijsverkoyen are you OP of the fork cms IRC channel? It would be nice if the title of it would contain a link to the new Slack channel (https://fork-cms.herokuapp.com/)

**Comment by tijsverkoyen** [comment]
Done
