### ISSUE TITLE
Translatable Spoon

### ISSUE THREAD

**Issue by vytenizs** [forkcms/forkcms#1360]
I cant find a proper way to translate Spoon library. I am talking about dates and other data that lies in locale/data folder. You cant event extend anything because everything is private. Somehow this should be fixed or be deprecated.

**Comment by WouterSioen** [comment]
Spoon is deprecated. If you want to translate dates/countries/..., you should use the Symfony Intl Component: http://symfony.com/doc/current/components/intl.html

**Comment by jonasdekeukelaere** [comment]
What are you exactly trying to do?
If you still want to use Spoon, you can try this:
I think you can get translated dates by `\SpoonDate::getDate($format, $timestamp, $language);`
Months and weekdays can be retrieved by `\SpoonLocale::getMonths($language);` and `\SpoonLocale::getWeekDays($language)`.
Countries can be retrieved in the same way, `\SpoonLocale::getCountries($language);`

**Comment by vytenizs** [comment]
Yes it is deprecated, but SpoonTemplate still uses it, so all older websites is untranslatable. Yes im talking about dates and countries. There are no such language I require and there is no way to add one. What needs to be done, that I would be able to load external translation file.

**Comment by jonasdekeukelaere** [comment]
You could add your own template modifier that uses the Symfony Intl Component.

**Comment by vytenizs** [comment]
That is the problem. I want built in modifier :D That is this issue are for :D I know workarounds, but I want to suggest a proper solution.

**Comment by WouterSioen** [comment]
The existing modifiers should be changed to use the Symfony Intl Component.

**Comment by WouterSioen** [comment]
I've created a new issue for this: #1361
