### ISSUE TITLE
Refactor out SpoonLocale in favor of the Symfony Intl Component.

### ISSUE THREAD

**Issue by WouterSioen** [forkcms/forkcms#1361]
Spoon does not contain a lot of languages (and is deprecated). We should use the Symfony Intl component for this.

**Comment by vytenizs** [comment]
If anyone starts working on this, please let me know :) I will take one day off for this kinda tasks, so i wanna know that no duplicates will come out.

**Comment by carakas** [comment]
@vytsci any update on this?

**Comment by WouterSioen** [comment]
duplicate of #408
