### ISSUE TITLE
Date and time format setting

### ISSUE THREAD

**Issue by Cu8eR** [forkcms/forkcms#1364]
Date and time format setting

**Comment by WouterSioen** [comment]
What is the issue exactly?

**Comment by Cu8eR** [comment]
Add custom setting for date and time output used in cms fork - for example 24h format and day/month/year... something like custom window where you put http://php.net/manual/en/function.date.php

**Comment by carakas** [comment]
You can find this at /private/settings/index

**Comment by WouterSioen** [comment]
you probably mean `/private/<language>/settings/index`
