### ISSUE TITLE
Support for favicon in root folder

### ISSUE THREAD

**Issue by Cu8eR** [forkcms/forkcms#1365]
Support for favicon in root folder - why to change the whole file for different favicon? Why not to use favicon in root web folder

**Comment by jessedobbelaere** [comment]
I always put my favicons in the theme folder and use `<link rel="icon" href="{$THEME_URL}/favicon.ico" />` in the head.tpl template of my theme.

Or put your favicons in the root folder and use `<link rel="icon" href="/favicon.ico" />`, that should also work, no?

**Comment by WouterSioen** [comment]
I always put my favicons in the rootfolder.

You can put them wherever you want, as lang as you specify the paths in your theme correctly!

**Comment by bart-webleads** [comment]
Using favicon in theme, only works for php pages.
When user opens for example an image or a pdf document the root folder favicon is used.

There for you should use favicons in the root.

**Comment by WouterSioen** [comment]
I also like it that the backend favicon is changed when you put it in the root. When you have a lot of backends open, this is really helpful.

**Comment by jessedobbelaere** [comment]
Yeah, and I've seen lots of people having the Fork CMS favicon as avatar in mail clients. Probably because the root favicon is still that one from Fork, so it's best to add favicons in the root.

**Comment by WouterSioen** [comment]
Conclusion: you can put them wherever you want.
