### ISSUE TITLE
Empty pages unreachable

### ISSUE THREAD

**Issue by vytenizs** [forkcms/forkcms#1369]
When someone updated navigation and cache management, when you create new empty page it wont appear on any navigation at all. This creates lots of garbage. Any suggestion why this were made?

**Comment by vytenizs** [comment]
And if u change theme and it has different page position names those pages gets removed from tree.

**Comment by vytenizs** [comment]
Ive made a PR, but it will generate cache with empty pages. I think those caches should be separated, one should be navigation and be generated from within Frontend and one named tree or pages_tree generated from within Backend. But not both for same purpose.

**Comment by jonasdekeukelaere** [comment]
Should already be fixed in this pull request: https://github.com/forkcms/forkcms/pull/1354
