### ISSUE TITLE
Make updating process more user-friendly

### ISSUE THREAD

**Issue by Cu8eR** [forkcms/forkcms#1371]
Fork CMS loses customers because many of them are not IT gurus. It would be nice to have a simple updater because without this Fork CMS cannot grow up

**Comment by WouterSioen** [comment]
We won't integrate auto-updates for multiple reasons:

* it's really hard to integrate a good auto-update system that won't mess up your current installation
* Fork is intended for custom development. Updates can break this custom functionality
* All modules should always be kept up to date (and thus be maintained actively), which isn't always the case now.
