### ISSUE TITLE
Request for getSetting() and setSetting() in an Action

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1377]
This would come in handy, since we can remove a lot of redundant code in all our Settings.php actions.
```php
$this->getSetting('key');
$this->setSetting('key', 'value');
```

```php
public function getSetting($key, $defaultValue = null)
{
    return $this->get('fork.settings')->get(
        $this->URL->getModule(),
        $key,
        $defaultValue
   );
}

public function setSetting($key, $value)
{
    $this->get('fork.settings')->set(
        $this->URL->getModule(),
        $key,
        $value
    );
}
```
Optionally we could add $module = null at the end of these functions.

**Comment by WouterSioen** [comment]
I prefer the way it is now (but this could be personal preference)

**Comment by jeroendesloovere** [comment]
We could save a lot of code.
F.e.:
https://github.com/forkcms/forkcms/blob/master/src/Backend/Modules/Blog/Actions/Settings.php#L132-L148

**Comment by tijsverkoyen** [comment]
I agree with Wouter, and this is certainly not a feature.

**Comment by WouterSioen** [comment]
It could save some code, but it also introduces some "magic" in the code base. You clearly see now that the "fork.settings" service is fetched and the items are stored in there. If you add a syntactic sugar layer around it, this becomes less explicit.

I prefer codebases with less magic. they are a lot easier to understand.

**Comment by jeroendesloovere** [comment]
Okay, I understand.
