### ISSUE TITLE
BUG: $this->get('fork.settings')->set($module, $key, null);

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1378]
**BUG**
ForkSettings does not allow to set a moduleSetting to ```null```.
This is stupid.

**Comment by jeroendesloovere** [comment]
Which means that you never can reset a module setting back to null. You will always have to use ```''```` but that is type dependent.

**Comment by WouterSioen** [comment]
you can use `$this->get('fork.settings')->delete($module, $key);`

**Comment by jeroendesloovere** [comment]
But thats not what I want.

**Comment by WouterSioen** [comment]
Whats the difference between deleting it and setting it to null?
