### ISSUE TITLE
Twig form error

### ISSUE THREAD

**Issue by Dredas** [forkcms/forkcms#1379]
Why {% if txtEmailError %} is not working, but {% form_field_error Email %} is working? Need help. I think it a bug

![selection_019](https://cloud.githubusercontent.com/assets/12195810/12615288/7d30ee4a-c50d-11e5-8c9a-932122b57df1.png)

Thanks :)

**Comment by WouterSioen** [comment]
@Thijzer do you have any idea what could cause this?

**Comment by Thijzer** [comment]
don't start with a capital, it's {% form_field email %}

**Comment by Dredas** [comment]
@Thijzer 
![selection_020](https://cloud.githubusercontent.com/assets/12195810/12616190/77b516ee-c512-11e5-8b08-1a21b507aaab.png)

**Comment by WouterSioen** [comment]
I don't really see why this would not work. Do you run `$this->frm->isCorrect()` after validating the form? And do you parse it to the template?

**Comment by WouterSioen** [comment]
It should be assigned to the template here: https://github.com/forkcms/library/blob/master/spoon/form/text.php#L794

**Comment by WouterSioen** [comment]
What is the error/output you're getting?

**Comment by Dredas** [comment]
I think maybe reason is double txtEmailError?

![selection_021](https://cloud.githubusercontent.com/assets/12195810/12616789/80f582e0-c515-11e5-9a1d-a69f3c3c8b33.png)

**Comment by WouterSioen** [comment]
What/where are you dumping here?

**Comment by Dredas** [comment]
![selection_023](https://cloud.githubusercontent.com/assets/12195810/12616897/f2b1f63e-c515-11e5-81e4-bb6be9d03b30.png)
![selection_022](https://cloud.githubusercontent.com/assets/12195810/12616898/f2b8e1ec-c515-11e5-99b0-3dc42dcbd7fc.png)

**Comment by WouterSioen** [comment]
Hmm, I showed the wrong line, It's this line that assigns the field https://github.com/forkcms/library/blob/master/spoon/form/text.php#L795

**Comment by Dredas** [comment]
Omg, it was my mistake. Thanks for help. I was having same field "Email" in Header

**Comment by WouterSioen** [comment]
Glad you found it!
