### ISSUE TITLE
Google Analytics: trackOutboundLinks not working for "ga"

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1383]
**Problem**
In ```src/Frontend/Core/Js/frontend.js``` we check for ```typeof ga === 'object'``` on [this rule](https://github.com/forkcms/forkcms/blob/master/src/Frontend/Core/Js/frontend.js#L510).
But that is false. ```ga``` is a ```function```.
=> So all the outbound trackings are not working.

**Solution**
Check for ```typeof ga === 'function'```

**Comment by WouterSioen** [comment]
hmm, did google analytics change this? Normally, ga is an object.

**Comment by carakas** [comment]
just checked this, and I also get function

**Comment by jeroendesloovere** [comment]
@carakas did you tested "mailto" and "external" links? I don't remember very correctly, but I think that they were broken to.

**Comment by jeroendesloovere** [comment]
Hmmm, looked into my PR and I had added some extra tracking for internal links.
Mailto and external links should work I guess.

**Comment by carakas** [comment]
maybe you can create a new pr for the extra tracking you added
