### ISSUE TITLE
Missing "Locale" checkbox mass actions

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1385]
**Problem**
You can select checkboxes,
but there aren't any mass actions.

![schermafbeelding 2016-02-03 om 11 23 58](https://cloud.githubusercontent.com/assets/588616/12779515/a5840584-ca68-11e5-8cab-305ff1b413d6.png)

**Comment by carakas** [comment]
what mass actions would you suggest ?

**Comment by WouterSioen** [comment]
They are used in the export. (But we removed this feature in the 3.10 branch)

**Comment by jeroendesloovere** [comment]
I suggest:
* Delete

**Comment by WouterSioen** [comment]
I have never had the need to delete locale. Why would you want this?

**Comment by jeroendesloovere** [comment]
Well, for example: somebody wants to remove the old "Mailmotor" or "MailChimpLite" module and install the new ["MailMotor" module](https://github.com/mailmotor/fork-cms-module-mailmotor).

@WouterSioen Do you mean that the "checkboxes" are deleted in 3.10?

**Comment by WouterSioen** [comment]
yes
