### ISSUE TITLE
Cache problem when switching from "dev" to "prod" environment.

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1391]
**Steps to reproduce**
* Fork CMS in ```dev``` environment.
* Login to /private
* Remove the ```app/cache/prod``` folder if it exists.
* Enable the ```prod``` environment.
* Click to another page in Backend

**Error**
You see a white page, without error notifications in prod.log

**Comment by sverraest** [comment]
I had the same issue a couple of days ago.
My issue was with the CSS/JS minifier. (MinifiedJs, MinifiedCss)
I had to manually create these folders in src/Backend/Cache even though the permissions for the Cache folder and webserver were correctly setup.

**Comment by carakas** [comment]
@jeroendesloovere is this still the case?

**Comment by jeroendesloovere** [comment]
No, this seems to be fixed.
