### ISSUE TITLE
SMTP Test email succeeds but email notifications by ForkCMS are not being delivered.

### ISSUE THREAD

**Issue by sverraest** [forkcms/forkcms#1392]
I'm using Mandrill for a client, the SPF and DKIM records are successfully setup for the domain.

When using the SMTP API (Username=email, Pass=ApiKey, Host= smtp.mandrillapp.com:587) the Test Emails in the Settings > Advanced > Emails are correctly delivered.

However, all other notifications for blog moderation, form builder send email, etc... are not being send. 
In Mandrill I can see the test emails being created and logged but nothing for all other notifications.

**Comment by carakas** [comment]
@sverraest can you create a PR for this?
