### ISSUE TITLE
Documentation is too much outdated

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#1396]
The documentation is too much outdated, as example git needs to be installed to get a successful `composer install`, should we create a list of what needs to be updated?
- [ ] Debug mode.
- [ ] Routing
- [ ] Forms
- [ ] Theming
- [ ] Cheat sheet

**Comment by jessedobbelaere** [comment]
Sounds good, I'll help with updating :+1:

**Comment by jeroendesloovere** [comment]
@GhaziTriki Would you be willing to create a list with the documentation that needs to be updated?

**Comment by aalwash** [comment]
What I found until now:
- Theme is talking about them 'Triton', probably that should become theme 'Fork'? -- https://docs.fork-cms.com/documentation/detail/theming-guide/making-a-basic-theme

**Comment by carakas** [comment]
While still true we are making big changes towards more symfony integration, let's revisit this when we get there, no need to have an issue open on it
