### ISSUE TITLE
Datalist formbuilder not supported in Safari and Chrome

### ISSUE THREAD

**Issue by bvdn** [forkcms/forkcms#1408]
I am building a form with the selector (selectievakje). It looks like its not supported in Chrome & Safari. < the boxes are not displayed in the 2 browsers > In Firefox it works ok. Anybody a hint / workaround? using fork 3.6.8

**Comment by carakas** [comment]
Fork `3.6.8` is a rather old fork (2 years old)
You can always try it on `3.9.6` and see if it was fixed before fork 4
and look to backport it.
Since we currently only support fork 4 I'll close this.

Feel free to contact us on slack if you need further assistance
