### ISSUE TITLE
Locale: "key" does not understand CamelCased

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1415]
You can't overwrite locales with different CamelCasing.

### Example

* "Firstname" in database
* It isn't possible to import "FirstName" from a locale.xml

**Comment by WouterSioen** [comment]
what do you suggest? Because two locales with the same name but different casing can't coëxist. And the keys are case sensitive in the frontend too.

**Comment by jeroendesloovere** [comment]
Dunno, a solution is not that obvious

**Comment by WouterSioen** [comment]
I don't think it isn't even possible to "solve" this. It's just a requirement: translations are case sensitive. If people write the same terms in different ways, we can't decide in our code which one is the correct one. It's first come first serve now.

**Comment by WouterSioen** [comment]
I'll close this one since no good/possible solution is available. Reopen it if there is a way to solve this please :)
