### ISSUE TITLE
Add locale for 'sequence updated' in all modules

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1417]
For example in FAQ module for Sequence and SequenceQuestions AjaxAction.

**Comment by WouterSioen** [comment]
@jeroendesloovere I believe this is fixed, isn't it?

**Comment by jeroendesloovere** [comment]
Nope, not yet. Still a plain text message "sequence updated" in every "backend_interface_language".
![schermafbeelding 2016-05-30 om 08 43 21](https://cloud.githubusercontent.com/assets/588616/15641632/9536da40-2642-11e6-9c27-873f7ba041fd.png)
