### ISSUE TITLE
Central database / Multiple sites

### ISSUE THREAD

**Issue by wouterverstuyf** [forkcms/forkcms#1419]
Hello

I need to build 4 standalone (mini)-shops with basic shop-features: Login / Profile page / Shopping basket / ... Actually the working principle is the same as Coolblue (but thank god, the mini version... :) )

I'm thinking about the following:
- 1 database for central data (shopping basket, profiles, login information,...)
- 1 database for each site (products, categories, ...)

It should be different sites, so 1 site with all the products and categories is not really an option. With the central database cross buying over the different sites would be possible. But it's quite a challenge...

Does anyone has experience to do this? I know it looks a huge change, but maybe someone tried this before? Do you thing this is possible of are there blockers you see?

Thx for the advice...

**Comment by WouterSioen** [comment]
I've done things related to this with Fork. What we did was this:

* add a "sites" and "sites_languages" table
* couple every item to a site_language instead of just a language
* build in a lot of functionality to couple data between site_languages

Note that this was a lot of work and we didn't have separate databases for each site.


You can always make multiple database services in fork. This could also come in handy.

**Comment by wouterverstuyf** [comment]
@WouterSioen Thx!

I know, it will be a lot of work and we wil evaluate what's the best way to do this. (one (big) site is the other option but not the preferred one)
Yes, multiple database services is the first step, point the profiles module to that database, and so on... I will try this the coming days/weeks. 

Do you have info for multiple database services? (different steps that we will need to implement)

I let you know if we are getting somewhere...
Thx a lot!

**Comment by WouterSioen** [comment]
The normal database service is created here: https://github.com/forkcms/forkcms/blob/master/app/config/config.yml#L47-L58

You could just copy these lines and change the name `database` to `database_xxxxx` with other credentials.

In your models/repositories, you'll need to fetch the right database.

**Comment by WouterSioen** [comment]
We still have the "multisite" branch: https://github.com/forkcms/forkcms/tree/multisite

this contains the implementation me and @dubgeiser worked on around two years ago.

**Comment by wouterverstuyf** [comment]
Great! Thx, I wil check this out...
The multisite is also something I will check, this could be handy in the case we keep it to 1 site.

Thx for the support!

**Comment by WouterSioen** [comment]
I'll close this issue for now. Feel free to reopen or discuss this on slack.
