### ISSUE TITLE
BUG: "src/Frontend/Cache/Navigation/editor_link_list_nl.js" not exists after deployment

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1421]
### Steps to reproduce

* Deploy the website using capistrano

### What happens?

The ```src/Frontend/Cache/Navigation/editor_link_list_nl.js``` and any other _en, _fr files not exist.
Which throws errors in strict browsers like f.e. IE10 on Windows 7.
=> **So you can not add links** in the editor dialog.

### What do you want?

After deployment, when visiting the pages module,
all "src/Frontend/Cache/Navigation/editor_link_list_*.js" files should be created if not exist.

**Comment by jessedobbelaere** [comment]
Yes, noticed it as well. Used to be created when you first visited a page after cache removal, I think, together with the other cache files. 
Related to #1400
