### ISSUE TITLE
Bug - Saving page results in Notice: Array to string conversion 

### ISSUE THREAD

**Issue by V3nn3tj3** [forkcms/forkcms#1424]
When trying to save the "Disclaimer" page the following error occours:

"Notice: Array to string conversion"

It only happens on this page as this is the only page that has the SEO index and SEO follow set.
And if you try to save them without any SEO options, it still fails as the array is just emptied, not unset...

src/Backend/Core/Engine/Meta.php at line 490:

`at SpoonDatabase ->insert ('meta', array('keywords' => 'Disclaimer', 'keywords_overwrite' => 'N', 'description' => 'Disclaimer', 'description_overwrite' => 'N', 'title' => 'Disclaimer', 'title_overwrite' => 'N', 'url' => 'disclaimer', 'url_overwrite' => 'N', 'custom' => null, 'data' => array('seo_index' => 'noindex', 'seo_follow' => 'nofollow'))) `
![error](https://cloud.githubusercontent.com/assets/394542/13490417/a8d54c7c-e12c-11e5-8a87-2e83f06a435d.png)

**Comment by jeroendesloovere** [comment]
@V3nn3tj3 which program did you use here for debugging?

**Comment by V3nn3tj3** [comment]
PHPStorm 11

It's a common setup. Running a local development server which has X-Debug enabled. But without autostart...
Each project can only be debugged by one dev machine at the time. The X-Debug settings are set using the .htaccess file. And PHPStorms listens for incomming connections (X-Debug is configured to send all debug info to one ip).
I'm mostly a Zend Studio user, same principle and works the same way with X-Debug. I do like ZendDebugger more.
Can also be done with VS 2012 and up using the PHP extentions. Or normal Eclipse. (Don't know about netbeans).

**Comment by WouterSioen** [comment]
you can do it with almost every editor. (I even have it running in vim).

**Comment by V3nn3tj3** [comment]
Don't know vim was that powerfull? Must be an extention...

**Comment by WouterSioen** [comment]
yes it is. Xdebug uses a standard protocol that is used by a lot of other programming languages too, making it easy to build plugins for.
