### ISSUE TITLE
BUG: can't add "Editor" block since Fork CMS 3.9.6

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1429]
### Steps to reproduce

1. Log in to /private + production environment 
2. Modules > Pages > a page > add editor block (had a bug to, fixed with https://github.com/forkcms/forkcms/pull/1420)
3. Add some text
4. Click ok
=> then you don't see any text in the editor block.

![schermafbeelding 2016-03-04 om 09 31 48](https://cloud.githubusercontent.com/assets/588616/13521834/efc2dbda-e1eb-11e5-969a-01b908127084.png)
+ When saving the editor blocks aren't saved
+ When clicking edit for this button, is is empty to

### Strange

Bugs were not critical in development environment

### Bug screenshots

This is a CKEDITOR bug?
![schermafbeelding 2016-03-07 om 10 54 04](https://cloud.githubusercontent.com/assets/588616/13565859/f2e1d186-e452-11e5-9c11-0b74f8d93156.png)

![schermafbeelding 2016-03-07 om 10 54 10](https://cloud.githubusercontent.com/assets/588616/13565855/f08d69a4-e452-11e5-8848-bfb5e3b5b908.png)

**Comment by jeroendesloovere** [comment]
### How to reproduce in demo.fork-cms.com

1. Open http://demo.fork-cms.com/private and log in with "demo@fork-cms.com" and "demo"
2. Open your browser debug tool for javascript.
2. Click on "Pages > Home"
3. Click "add block" > "editor" > "ok"
4. Enter some text and click "ok".

For every time you do this, you get errors in the console.

![schermafbeelding 2016-03-09 om 11 57 23](https://cloud.githubusercontent.com/assets/588616/13633288/6087b6d2-e5ee-11e5-9691-f12658d2e2ba.png)

**Comment by jessedobbelaere** [comment]
I tried firefox, safari and chrome and don't see this error on the demo fork site :S Strange man

**Comment by jeroendesloovere** [comment]
### Problem

Hi, the problem was with "matthiasmullie/minify".

### Solution

We must load in the latest library.
```bash
composer require matthiasmullie/minify:~1.3
```

Which will do:
```bash
Updating dependencies (including require-dev)
  - Removing matthiasmullie/minify (1.3.33)
  - Installing matthiasmullie/minify (1.3.34)
    Loading from cache
```

**Comment by WouterSioen** [comment]
for a reference: related issue: https://github.com/matthiasmullie/minify/issues/99
