### ISSUE TITLE
 Location module now requires authorization key

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1430]
### Problem

I was using the Location module locally, then published the site for production.
Our customer now wants to add another location and it doesn't work anymore.
I tried it and indeed, error is displaying:
![schermafbeelding 2016-03-07 om 13 51 51](https://cloud.githubusercontent.com/assets/588616/13569996/c22f3754-e46b-11e5-89c6-8cd771f94edf.png)

Could it be that the "Authorization key" has become required?
https://developers.google.com/maps/documentation/geocoding/get-api-key#get-an-api-key

**Comment by carakas** [comment]
I think so. I have seen this error when using google maps recently and was able to fix it by adding an authorisation key. Maybe we can add it as a required setting in the backend for the location module?

**Comment by WouterSioen** [comment]
good idea :+1:

**Comment by jeroendesloovere** [comment]
@carakas Why didn't you added an issue for this :-P ?

**Comment by carakas** [comment]
@jeroendesloovere because I didn't realize that is would break the Location module since I wasn't using it when I got this error

**Comment by jeroendesloovere** [comment]
Allright. Anybody want to create a PR for this?

**Comment by jeroendesloovere** [comment]
More news about this issue.

My site was hosted on a new hosting and "allow_url_fopen" was disabled.
```allow_url_fopen``` must be enabled for ```file_get_contents```.

I tested and "key" is not required.
... but how long will this be working...

What should we do @WouterSioen @carakas ?

**Comment by carakas** [comment]
I would add the key parameter and require it in the Location module. I have already had it that it didn't work until I added it. In the documentation it is required, so I think it would be best to make it future proof and add they key. Its not like it will hurt to add a key in settings
