### ISSUE TITLE
Random data and page generation

### ISSUE THREAD

**Issue by vytsci** [forkcms/forkcms#1434]
I wound a very annoying bug, when u have random data parsed to template and used within template u receive infinite loop in loop below:
https://github.com/forkcms/forkcms/blob/master/src/Frontend/Core/Engine/Page.php#L361

It checks previously generated positions with new ones and if u have random data that check always returns false, that leads into an infinite loop. Also this method is very insufficient it always goes through all blocks and widgets multiple times. In my opinion this should be fixed asap. I could make PR, but i cant imagine why this method is as it is :D

**Comment by vytenizs** [comment]
For example i had to generate urls with unique tokens and what i got is infinite loops all the time :)

**Comment by WouterSioen** [comment]
I've removed the do while loop in some projects because I also can't find why it's done anymore.

It seems like it's introduced by @matthiasmullie so het could maybe stille remember why it's done this way. It's a really really long time ago though, so don't know if he still knows.

Related commit: https://github.com/forkcms/forkcms/commit/4d243446dfa4c80a6312346529683410e93dd7ed

**Comment by vytenizs** [comment]
Only way to explain this is that someone wanted to make action able to add position while on render process. I need to know why this was made, maybe I will come with a solution...

**Comment by matthiasmullie** [comment]
I can not remember. But it seems to be about recursion, where a position's content could be another position.

**Comment by vytenizs** [comment]
I think this loop is useless now, because actually there is no correct way to make position within position.

**Comment by WouterSioen** [comment]
@forkcms/core-contributors @forkcms/owner @forkcms/moderators anyone can remember this feature? Is this ever used? I can't imagine I've ever seen this feature used.

**Comment by matthiasmullie** [comment]
If I had to guess, I would guess it was an undocumented way of having positions inside a contentblock.

**Comment by vytenizs** [comment]
Well either way this should be fixed asap :) cuz this is huge loss in performance... Every page renders multiple times.

**Comment by WouterSioen** [comment]
I'm :+1: for removing it, but let's wait for some more responses ;)

**Comment by carakas** [comment]
I'm also :+1: for removing it

**Comment by jeroendesloovere** [comment]
The code was probably added to check old positions if you:
- Installed a new theme
- Or added a "new template" to the page

**Comment by carakas** [comment]
Just tested this and it is no longer an issue, probably fixed by https://github.com/forkcms/forkcms/pull/1642
