### ISSUE TITLE
Twig Form and include

### ISSUE THREAD

**Issue by vytenizs** [forkcms/forkcms#1439]
You cant include fields from another file into a form, because u get an exception that u are trying to render field outside form. This is a huge issue. I tried to find workaround, but im too bad for finding a solution. Any suggestions how to fix this?

**Comment by WouterSioen** [comment]
This is something that will only be fixed when switching to Symfony forms. Why is this such a big problem?

**Comment by vytenizs** [comment]
Well, i have few project that i would like to switch onto twig, but there are lots of forms related includes and complicate things.

**Comment by WouterSioen** [comment]
Hmm, SpoonForms and TwigTemplates just don't work that well together. We had to do some rather ugly hacks to even make this work. It's a temporary solution. I'll try to move modules to symfony forms as soon as the new Fork version is released.

**Comment by vytenizs** [comment]
Ok :)
