### ISSUE TITLE
Twig wont override Core templates with Form templates

### ISSUE THREAD

**Issue by vytenizs** [forkcms/forkcms#1441]
There is no functionality as it was before. For example you cant override Core Navigation.html.twig with Theme Navigation.html.twig.

**Comment by WouterSioen** [comment]
I'll look into this one, thanks!

**Comment by vytenizs** [comment]
Sorry dont have time to look into this myself atm.

**Comment by WouterSioen** [comment]
No problem, I'm glad you already found this issue ;)

**Comment by vytenizs** [comment]
I have a project where im using 3.10 branch, smaller issues i manage to fix myself and PR, but for larger ones im using workarounds. :D

**Comment by WouterSioen** [comment]
see https://github.com/Katrienvh/forkcms/pull/13 for a fix
