### ISSUE TITLE
FormBuilder + "upload-field" for file/image

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1446]
The Core Fork CMS FormBuilder doesn't have a "file/image" upload-field.

This is a feature request by the Fork CMS Community
and we need to discuss how we can get this in the core "secure".

Currently as a fallback, I've copy/pasted the original FormBuilder module
and added a "file/image" upload field. Which uploads files to the document root.

You can view the [adjusted FormBuilder module here](https://github.com/jeroendesloovere/fork-cms-module-formbuilder-upload-field)

**Comment by WouterSioen** [comment]
My security requirements:

* Files should be uploaded outside of the document root/ in a secure folder (fe. with `.htaccess` protection).
* Files should only be accessible from the backend for a logged in user.

**Comment by jacob-v-dam** [comment]
And a mime-type validation. This a great solution to validate the files.

**Comment by carakas** [comment]
if you have this issue you can always look at this repository https://github.com/jeroendesloovere/fork-cms-module-formbuilder-upload-field

**Comment by carakas** [comment]
going to close this one for now, if you need it in your own project you can check the link posted above
