### ISSUE TITLE
File browser caching not working with uppercase extensions

### ISSUE THREAD

**Issue by jacob-v-dam** [forkcms/forkcms#1448]
When you have a file named .JPG the .htaccess will not use browser caching because it is case sensitive.

**Comment by WouterSioen** [comment]
It normally uses the mime type, not the extension. Are sure about this?

**Comment by WouterSioen** [comment]
nevermind, thats the gzip.

**Comment by WouterSioen** [comment]
Could probably be fixed with this: http://stackoverflow.com/a/2520601/1454599

Note, I didn't test it

**Comment by jacob-v-dam** [comment]
yes that works. I will make a pull request for it.

**Comment by WouterSioen** [comment]
great!

**Comment by WouterSioen** [comment]
@jacob-v-dam any news on this pull request?
