### ISSUE TITLE
Theme feature request: add checkbox to "new visual block" to push it to every page with that theme template.

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1449]
## Problem

I have a big website and I need to place a certain widget on every page which has that template.
## What you now have to do
1. Add that new visual block "shopCart"
2. Add the widget "shop > widget > shopping cart"
3. Clicking save
4. Now we need to go to pages and open every page where we manually need to add that widget
   ![schermafbeelding 2016-04-07 om 16 18 46](https://cloud.githubusercontent.com/assets/588616/14354224/ccde8996-fcdc-11e5-9c2b-4d76e90a8d91.png)
## What I want
1. OK
2. OK, but Fork should recognize that I'm adding a new "visual block "shopCart"
   and automatically add a "checkbox: do you want to push this to every page containing this template"

**Comment by carakas** [comment]
@jeroendesloovere can you create a PR for this

**Comment by jeroendesloovere** [comment]
@jessedobbelaere are you willing to create a PR for this?

**Comment by jessedobbelaere** [comment]
I can, but it will be somewhere in September :-)

**Comment by jeroendesloovere** [comment]
Would be lovely. I've assigned you, so you can't get out of it anymore :-P

**Comment by jeroendesloovere** [comment]
@jessedobbelaere Any news on this?
Maby we can close this one since it probably has a small use case and the doctrine/symfony form integration will shake things up a little?

**Comment by jessedobbelaere** [comment]
Fine for me :P haven't had time and this ticket got lost in the matrix
