### ISSUE TITLE
Profiles: when installing I want the added pages to be in my language

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1450]
## Problem

I'm Dutch speaking and when I install the "profiles module" in a (multi)-language website,
lots of new pages get added. But all in English.
So I have to change them all to dutch, french, german manually...

## What I want
That the page-names are in the proper language.

![schermafbeelding 2016-04-07 om 16 27 26](https://cloud.githubusercontent.com/assets/588616/14354455/a285ae58-fcdd-11e5-948b-8a8c31ad0da9.png)

**Comment by carakas** [comment]
@jeroendesloovere can you create a PR for this?

**Comment by jeroendesloovere** [comment]
I don't know if it's possible that when installing Fork CMS the locale is already available to the moduleInstaller?

**Comment by WouterSioen** [comment]
I think locale is available from the moment you imported it in your installer.

**Comment by jeroendesloovere** [comment]
If anybody else wants to integrate pages with the correct language.
You can [view an integration example here](https://github.com/forkcms/forkcms/pull/1694/files#diff-1e2c53601229a1e81a5b65ad4e60b0beR161).
Just use a loop to iterate all the languages and then set `Language::setLocale($language);`

**Comment by carakas** [comment]
I did add some fixes for it in https://github.com/forkcms/forkcms/commit/1fc5281e0e62b0280c3a39dd772c14d90756c762 and https://github.com/forkcms/forkcms/commit/7f2f020d27f76b56cc162585da0b4df26a3dcb0e

you need to set the language back to the original one to prevent your page showing up in an other language after that
