### ISSUE TITLE
Quick way to crash demo site

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1457]
[Message from sremick on Fork CMS Forum](http://www.fork-cms.com/community/forum/detail/quick-way-to-crash-demo-site#post-954):
I have not installed Fork yet but was just first testing with the demo site. I quickly found a way to bring down the entire site. If one goes to the home page, then delete the following:
The search widget (top block) The item in the left block The item in the right block
...the whole site stops responding. Deleting any subset of those 3 doesn't crash the site, but if you do all 3 it does. This can't be right.

**Comment by WouterSioen** [comment]
this is already fixed in the master branch, it's just not released yet
