### ISSUE TITLE
Suggestion: Mirrored structure in multilinugal sites

### ISSUE THREAD

**Issue by fromgate** [forkcms/forkcms#1458]
Hello!

I'm going to create a multilingual site and I find that ForkCMS is good choise for me.
But I miss one feature, that could be added and configured (enable/disable) using config:

Creating multilingual site is same to create two different site now. In fact: you need to re-create site structure from the scratch for every language.

I think when you creating a new page in one language it must be mirrored in another languages and saved as draft copy.

For example, you creating page "new-page" in English with url: site-name.com/en/new-page

And in one moment new page for another language must be automatically created - site-name.com/ru/new-page 

This page must be saved as draft, and will be appear on site only when you translate it.

**Comment by WouterSioen** [comment]
After your initial setup, you can use a hidden action to copy your site to another language. You can use 
http://your-domain.com/private/en/pages/copy?from=en&to=ru

This will copy all pages from the English version to the Russian version.

**Comment by fromgate** [comment]
Oh! Great!!! What about future additions: will this "hidden action" overwrite exist pages in Russian?

**Comment by WouterSioen** [comment]
yes, it will overwrite. This is just used for initial setup.

We don't want to strictly tie our languages to each others, because a lot of people want slightly different structures.

**Comment by fromgate** [comment]
Ok, I got it. But this feature could be optional, so if you accepting new suggestions please don't forget about this one.

**Comment by WouterSioen** [comment]
ok, thanks for the suggestion
