### ISSUE TITLE
Variable defined in widget bleeds through to other widgets

### ISSUE THREAD

**Issue by V3nn3tj3** [forkcms/forkcms#1470]
When assigning a variable in a widget, this variable still exists in the same and other widgets.
So when WidgetA has the following code:

`$this->tpl->assign('bleed', true);`

This variable is available in both the same widget (from other call) and other widgets.
I can write this in WidgetB:

```
{option:bleed}
      I am shown, but bleed isn't my variable, it's a variable from WidgetA...
{/option:bleed}
```

**Comment by WouterSioen** [comment]
This is done by design, but I also do not think this is a good design. In my opinion, every widget and action should be rendered in it's own scope, without taking other modules into account.

What do the other core devs and contributors think? @forkcms/core-contributors @forkcms/owner @forkcms/moderators

**Comment by V3nn3tj3** [comment]
Oh, by 'design' you say ;).
It would be, like you said, alot better when each widget has it's own scope.

Sorry, thoughed this was a bug. Is there any way to get around this, as i have the same widget multple times. But my option in my tpl should be tied to the scope of the widget and not be global.

Have had this before, when using someone elses code, and using the same variable names. Never gave it any thoughed. And it was fixed by changing my variable name in my code. Which i thoughed was odd.

**Comment by WouterSioen** [comment]
The FormBuilder contains a widget working around this issue. You could try this technique to give your widget it's own scope: https://github.com/forkcms/forkcms/blob/master/src/Frontend/Modules/FormBuilder/Widgets/Form.php#L298-L310

**Comment by V3nn3tj3** [comment]
Will have a look at it! Thanks!

**Comment by V3nn3tj3** [comment]
When using:
```
        $pathTo =  FrontendTheme::getPath(FRONTEND_MODULES_PATH . '/Blog/Layout/Widgets/FrontArticles.tpl');
        $this->tpl = new FrontendTemplate($pathTo);

```

It throws an error on line 57 of file Frontend\Core\Engine\Theme.$file is empty ("")... And can't seem to find out where it gets a empty string...

```
       if (!is_file(PATH_WWW . str_replace(PATH_WWW, '', $file))) {
            throw new Exception('The template (' . $file . ') does not exists.');
        }
```

**Comment by WouterSioen** [comment]
Have you tried a `var_dump` of your `$pathTo` variable? My guess is that `FrontendTheme::getPath` returns an empty string?

**Comment by V3nn3tj3** [comment]
Have been debugging, $pathTo is never "";
Will do some reseach, and will let you know...

**Comment by V3nn3tj3** [comment]
Found it: put this in the loadData() instead of execute. Silly me :)...

       ```
 return $this->tpl->getContent(  FRONTEND_MODULES_PATH . '/' . $this->getModule() . '/Layout/Widgets/FrontArticles.tpl');
```

**Comment by WouterSioen** [comment]
Ok, glad to help!
I'll keep this issue open for the discussion about the local scope vs global scope in widgets and actions.

**Comment by carakas** [comment]
I am pro local scope
