### ISSUE TITLE
Frontend Event Hooks Broken

### ISSUE THREAD

**Issue by timvanwolfswinkel** [forkcms/forkcms#1471]
Hi guys,

The `startProcessingHooks()` function will give a error if you trigger a event from the frontend. It gives the following error:

Notice: Use of undefined constant BACKEND_CACHE_PATH - assumed 'BACKEND_CACHE_PATH'

**Comment by jeroendesloovere** [comment]
Hi @timvanwolfswinkel,
Did you use "BACKEND_CACHE_PATH" in the frontend event listener?

**Comment by jeroendesloovere** [comment]
Note that currently when you execute a Frontend method, Fork does not now things from Backend and reverse (Backend doesn't know Frontend constants). So if you want to use BACKEND_CACHE_PATH, you need to execute a Backend(Model) method. 
=> Or you can forget that hooks and start using $this->get('event_dispatcher')->dispatch($eventName, $eventClassInstance);
=> The internal hooks will soon be replaced by Symfony EventDispatcher

**Comment by jeroendesloovere** [comment]
Closing this because that is actually how "fork" is working.
Will be better in the future.
