### ISSUE TITLE
Routing detail/detail

### ISSUE THREAD

**Issue by gertjanwytynck** [forkcms/forkcms#1479]
Hi,

When I use the action detail as module action I get a wrong url. The template of my detail page is different than the Index-template.

<img width="682" alt="settings" src="https://cloud.githubusercontent.com/assets/2844483/15635902/ad8a9d98-25ed-11e6-9103-c2edb200b3c4.png">

`$link = FrontendNavigation::getURLForBlock('Artists', 'Detail');`
Gives me nl/artiesten/detail/**detail**/some-artist instead of nl/artiesten/detail/some-artist

Or do I something wrong here?

Kind regards,

**Comment by jessedobbelaere** [comment]
Hmm not sure, I don't use this often, but have you followed the steps from:
http://www.bubblefish.be/blog/post/fork-cms-tip-pagina-als-module-actie-gebruiken ? Making an entry in the database etc could help

**Comment by guytarded** [comment]
Making the entry in the db is necessary, also you need to change some code. It is well explained in that blogpost but the linennumbers aren't correct anymore. You need to search for the given code.

Good luck

**Comment by gertjanwytynck** [comment]
Thanks for the help. Will try it tonight.

I will close this issue.
