### ISSUE TITLE
Twig converter camelcase has wrong method

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1482]
**Problem**
In twig, the `|camelcase` throws error, because of a wrong classname.

**Solution 1**
```php
public static function camelCase($string)
```
Should be changed to
```php
public static function toCamelCase($string)
```

**Solution2**
Or rename 
```
$twig->addFilter(new Twig_SimpleFilter('camelcase', $app.'::toCamelCase'));
```
to
```
$twig->addFilter(new Twig_SimpleFilter('camelcase', $app.'::camelCase'));
```

And we should test all other twig modifiers if they work.

**Comment by guytarded** [comment]
I'm a proponent of the second solution.
