### ISSUE TITLE
Invisible text during installation.

### ISSUE THREAD

**Issue by bartdc** [forkcms/forkcms#1529]
CSS issues when getting warnings during installation.

Oranje text on oranje background.

![installation_step2_filesystem](https://cloud.githubusercontent.com/assets/1098285/16118043/6ceeecf8-33d5-11e6-95d8-6a75997d677d.png)

White text on white background.

![installation_step7](https://cloud.githubusercontent.com/assets/1098285/16118044/6d077dd6-33d5-11e6-91b3-e500891ac539.png)

**Comment by bartdc** [comment]
Forget first one, https://github.com/forkcms/forkcms/issues/1521.

**Comment by WouterSioen** [comment]
fixed
