### ISSUE TITLE
formatCurrency isn't listening to 'Core' 'number_format' setting.

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1531]
**Problem**

In the backend you can choose the way to show "numbers" in the frontend.
But the currencies aren't looking to this, would be nice if you can change this in the backend.
Since now, you can only do this hardcoded in the method `formatCurrency` in `src/Frontend/Core/Engine/TemplateModifiers.php`.

**Comment by carakas** [comment]
maybe this is something good to look at for this http://php.net/manual/en/function.money-format.php

**Comment by WouterSioen** [comment]
or http://twig.sensiolabs.org/doc/extensions/intl.html
