### ISSUE TITLE
CommonCookie::delete('my_key') is not working?

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1532]

**Comment by WouterSioen** [comment]
@jeroendesloovere this is Spoon code, and should be an issue in there. 

I've tested it though and the cookie is removed in the request itself, but is still there in the next request. I'll look into it.

**Comment by WouterSioen** [comment]
hmm, it is a symfony issue, but it won't be that easy to fix. The problem is that you should do `clearCookie` on the response object. We don't have it available though in our controllers. I'll think about another solution.
