### ISSUE TITLE
Installing module logs you out

### ISSUE THREAD

**Issue by jessedobbelaere** [forkcms/forkcms#1535]
1. Install a module in Fork CMS 4
2. You get logged out
3. Log back in
4. Module is installed

Strange, slightly annoying issue since forkcms 4

**Comment by carakas** [comment]
it is the result of a change @WouterSioen made, maybe he can explain why it works like this

**Comment by WouterSioen** [comment]
hmm, the location of the sessions is changed, but I can't think of a reason why you get logged out.

**Comment by WouterSioen** [comment]
It removes these things:

```
src/Backend/Cache/Locale
src/Backend/Cache/Navigation
src/Frontend/Cache/Locale
src/Frontend/Cache/Navigation
app/cache/<environment>
```

The sessions should use the default php session handler which isn't using one of these folders. It seems like there is a sessions folder in the `app/cache` folder though. I'll look into it.
