### ISSUE TITLE
Improving adding updated locales with a "redo last import" button in "Locale" module

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1537]
**Problem**

When developing a module, you sometimes update the "locale" .xml file lots of times.
You always have to: 
* Settings > Translations > Import
* Click "Browse" (and select "overwrite existing translations")
* Browsing to your locale .xml file and clicking on it
* Click "Import"

**Enhancement**

We could save the last "path" and "checkbox-setting" and add a new button "import with last settings" for GOD users. So it's easier to update locale when creating modules.

**Comment by WouterSioen** [comment]
You can use the import_locale tool on the cli to easily do this ;)

**Comment by jessedobbelaere** [comment]
True, I just run something like this all the time:

`app/console locale:import -f -m Instagram`: Force import (-f) the locale from a module (-m) with name Instagram.

**Comment by WouterSioen** [comment]
I think saving the original path is not even possible using a html file upload.

**Comment by WouterSioen** [comment]
I'll close this because saving the upload path isn't possible using html forms, and there are good enough solutions using the cli.
