### ISSUE TITLE
FormBuilder is missing a "only send mail" dropdown-choice

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1547]
**Problem**

You can only choose options where everything gets saved to database.

**Feature request**
But sometimes customers don't want this to be saved in the database...

What should be done
- At a new option "only send mail" in dropdown
- Add a new "visible_in_backend" boolean for every form request (so it actually gets saved to the database, but you can't view them in the backend)
  ![schermafbeelding 2016-06-24 om 14 42 42](https://cloud.githubusercontent.com/assets/588616/16338043/494dda70-3a1a-11e6-8cfb-f03d4ba218bd.png)

**Comment by WouterSioen** [comment]
Why would you ever not want it to be stored in the database?

**Comment by jeroendesloovere** [comment]
Clients who are scared of "databases" and "top-secret" company information.

**Comment by carakas** [comment]
if you would implement this I don't think you should secretly save it anyway.

**Comment by guytarded** [comment]
Same idea here as @carakas . Just send is just send, not decieving your client

**Comment by carakas** [comment]
Ill add this to https://github.com/forkcms/forkcms/pull/1602 in order to prevent merge errors

**Comment by carakas** [comment]
since a database change is needed for this it will be added in 5.0.0
