### ISSUE TITLE
27.6.2016 as dateformat does not work with SpoonFormDate

### ISSUE THREAD

**Issue by carakas** [forkcms/forkcms#1556]

**Comment by carakas** [comment]
I get `..2016` as value

**Comment by WouterSioen** [comment]
I wanted to say "who uses this anyway" but this page https://en.wikipedia.org/wiki/Date_format_by_country indicates that a lot of countries doe it that way :)

**Comment by WouterSioen** [comment]
fixed in spoon, not fixed in fork yet (see #1579)
