### ISSUE TITLE
Adding Fork CMS to MAMP (MAC) extras

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1558]
Would be nice if "fork cms" is also available for MAC MAMP extras.
![schermafbeelding 2016-06-28 om 11 37 03](https://cloud.githubusercontent.com/assets/588616/16410848/a6832f08-3d24-11e6-8d36-60298b4a3cea.png)

![schermafbeelding 2016-06-28 om 11 35 31](https://cloud.githubusercontent.com/assets/588616/16410843/a1a96f7e-3d24-11e6-9c4e-5aab1e7f813d.png)

**Comment by jessedobbelaere** [comment]
Hmm the fact that there are only 4 CMS's listed makes me think the MAMP team selects the software itself, so not sure if we stand a chance :P

**Comment by jeroendesloovere** [comment]
A "no" we have, a "yes" we can get :-D

**Comment by carakas** [comment]
what I also wonder is how they can update it. The downside of something like this is that they keep offering an outdated version of fork. And since fork doesn't have an auto-update function like wordpress I don't this this is a good idea

**Comment by carakas** [comment]
I've sended an email to request more info on how they select this. Even if we don't go ahead with this, I still think it would be interesting to know

**Comment by jeroendesloovere** [comment]
@carakas 👍 thanks! Good work.

**Comment by carakas** [comment]
They are currently looking into this. Will get back with more info soon

**Comment by jeroendesloovere** [comment]
Any news about this?

**Comment by carakas** [comment]
it was too late for the current release but they asked me to contact them again in october

**Comment by WouterSioen** [comment]
don't forget to put this in your agenda then ;)

**Comment by carakas** [comment]
closed because this issue isn't a bug in fork or something (I will still contact them in october)
