### ISSUE TITLE
Monolog swift mailer is throwing error when trying to send mail

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1576]
When changing
![schermafbeelding 2016-06-30 om 11 29 11](https://cloud.githubusercontent.com/assets/588616/16483705/e2d9702e-3eb5-11e6-83b6-0bb79adf7313.png)
to
![schermafbeelding 2016-06-30 om 11 26 52](https://cloud.githubusercontent.com/assets/588616/16483695/d9525c28-3eb5-11e6-8d0a-4b3868574b19.png)

You get an error in the website
![schermafbeelding 2016-06-30 om 11 21 29](https://cloud.githubusercontent.com/assets/588616/16483697/dac87e2a-3eb5-11e6-8915-eab78029c719.png)

This was already like this in Fork CMS 3.9.6.
We need a fix, since this is really important for debugging purposes.

**Comment by jeroendesloovere** [comment]
Why is this one closed?

**Comment by WouterSioen** [comment]
because your fix was merged? ;)

**Comment by WouterSioen** [comment]
https://github.com/forkcms/forkcms/pull/1577

**Comment by jeroendesloovere** [comment]
In this issue monolog.handler.swift is not working!

The fix (#1577) you mention is something entirely different => monolog.handler.main

**Comment by WouterSioen** [comment]
ok, my bad, sorry! With all those issues going so fast, I was losing track ;)

**Comment by jeroendesloovere** [comment]
@forkcms/core-contributors Anybody has a solution?

**Comment by WouterSioen** [comment]
@jeroendesloovere 

Have you tried this as configuration?

```
        swift:
            type:       swift_mailer
            from_email: 'error@example.com'
            to_email:   'error@example.com'
            subject:    'An Error Occurred! %%message%%'
            level:      error
            formatter:  monolog.formatter.html
            content_type: text/html
```

That's how it's configured on the Symfony documentation (http://symfony.com/doc/2.8/cookbook/logging/monolog_email.html)

I guess it changed since symfony 2.3.

**Comment by WouterSioen** [comment]
poke @jeroendesloovere

**Comment by jessedobbelaere** [comment]
I still seem to be getting the error with this config, will have to do some debugging when I have time :) 

<details>
ContextErrorException in MessageFactory.php line 47:
Warning: Missing argument 1 for Symfony\Bundle\MonologBundle\SwiftMailer\MessageFactory::createMessage()
</details>

**Comment by jeroendesloovere** [comment]
Nope, did not found the time yet.
Thanks @jessedobbelaere for testing this.

**Comment by WouterSioen** [comment]
@jessedobbelaere @jeroendesloovere I've tried it with this config:

```
monolog:
    handlers:
        main:
            type:  stream
            path:  %site.path_www%/app/logs/%kernel.environment%.log
            level: error
        swift:
            type:       swift_mailer
            from_email: %fork.debug_email%
            to_email:   %fork.debug_email%
            subject:    %site.default_title% %fork.debug_message%
            level:      error
            formatter:  monolog.formatter.html
            content_type: text/html
```

And it worked:

<img width="1106" alt="screen shot 2016-07-12 at 10 37 54" src="https://cloud.githubusercontent.com/assets/1398405/16760581/b79231e2-481c-11e6-8774-25c7026176b2.png">
