### ISSUE TITLE
Triton needs an update

### ISSUE THREAD

**Issue by carakas** [forkcms/forkcms#1585]
We have a very nice backend now but the triton theme looks old and is not responsive.
I think this gives a bad first impression

**Comment by WouterSioen** [comment]
Absolutely agree to this, but we'll need to find someone with some time to do this.

**Comment by tijsverkoyen** [comment]
Maybe we should go with a very basic bootstrap-theme? Or something very light like the default of Wordpress.

**Comment by jessedobbelaere** [comment]
Won't really use a bootstrap theme as default, doesn't seem to fit with the brand... It should be something that impresses the users when they first open the demo. 
Just a flat design/hipster makeover of triton would be nice, and we can maybe ship the bootstrap fork theme from @ikoene too with fork cms?

**Comment by ikoene** [comment]
It's been a while since I've used it though, we should test it first. Maybe let a frontender have a look at it.

**Comment by WouterSioen** [comment]
@jessedobbelaere we could create another theme above bootstrap for the demo, and a more "default" bootstrap when you download/clone fork.

**Comment by carakas** [comment]
triton will die
long live bootstrap
