### ISSUE TITLE
Installation contains invisible text

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1600]
<img width="992" alt="schermafbeelding 2016-07-01 om 20 01 27" src="https://cloud.githubusercontent.com/assets/588616/16530110/a74bb3d4-3fc6-11e6-82ed-3fa6b02a6e98.png">
<img width="1034" alt="schermafbeelding 2016-07-01 om 20 01 31" src="https://cloud.githubusercontent.com/assets/588616/16530111/a76c2b6e-3fc6-11e6-97d2-637b466c4b9f.png">

**Comment by WouterSioen** [comment]
Hmm, I already fixed some of this, but didn't notice these ones.

**Comment by jeroendesloovere** [comment]
I've used "create-project", did not check if it is 4.0.4
