### ISSUE TITLE
FormBuilder: add sum field

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1612]
**Problem**

Sometimes spammers can create a script that fills in the form with random data.
Which pollutes your database.

**Solution**

Adding an extra possible "field-type", "sum", could prevent this.
(or use an external captcha)
![schermafbeelding 2016-07-05 om 10 25 11](https://cloud.githubusercontent.com/assets/588616/16578430/d0585864-429a-11e6-8b36-ff79fd262abd.png)

**Comment by carakas** [comment]
I would go for a captcha field in that case and let them choose the type with settings

**Comment by jessedobbelaere** [comment]
I'm more fan of a honeypot. I added this on the Fork forum once, and no spam anymore since then. It's just a fake field hidden for normal users, but spam bots fill it in usually. And when it's filled in, we throw an error. 

```
{* Honeypot *}
<div class="form_hp">
	<label for="hp_verifyemail">Don't fill in this field*</label>
	<input type="text" id="hp_verifyemail" name="verify_email" autocomplete="off" tabindex="-1" style="position: fixed; left: -100%; top: -100%;">
</div>
```

```
.form_hp {
    display: none !important;
}
```

Then in the Action:

```
if(isset($_POST['verify_email']) && $_POST['verify_email'] != '') {
	$this->frm->addError(FL::err('FormTimeout'));
}
```

**Comment by carakas** [comment]
if we would add a captcha I also would suggest to use the Google captcha
but the honneypot sounds nice to but can give problems for people who use a text-to-speach browser, like blind people.

so maybe we can add a prevent spam field or something (bad at naming things)
with the options:

- honneypot
- Google Captcha (do you need to have api credentials for this?)
- Checksum

**Comment by WouterSioen** [comment]
akismet in the formbuilder is rather hard to achieve. I did this some times but this was really nasty.

**Comment by jeroendesloovere** [comment]
I'm also not a fan of using external services for our contact forms, which should last forever.

**Comment by jeroendesloovere** [comment]
I've created a "checksum" for a client, is that an option?

**Comment by carakas** [comment]
you can always PR it and then we can see it from there and comment on the PR ?

**Comment by jeroendesloovere** [comment]
We (SIESQO) have decided to create a PR with our "checksum" field solution.
Can't tell when do, but it's coming.
