### ISSUE TITLE
Make file system check more robust for checking og:image urls

### ISSUE THREAD

**Issue by dubgeiser** [forkcms/forkcms#1630]
In https://github.com/forkcms/forkcms/blob/master/src/Frontend/Core/Engine/Header.php#L346 a check is made to verify if a given image really exists on the file system.
This seems a sane check, but it poses a problem:
Facebook fetches the images served via og:image and stores it on its own servers and while it is possible to make Facebook re-scrape urls and so make it "clear" its cache, it does _not_ so for images, it'll encounter the same url in og:image and serve that from its own servers.
This is a problem in the case we need to update an image served via og:image because if you have added it via Header#addOpenGraphImage(), you cannot, for example add a version via GET parameter... 
It does not seem like a bad idea to either allow for this, or make the file system check more robust so that time stamps can or cannot be added.
I have labeled it a bug because of the fact that, IMO, GET params should be able to be added in some form or other...
Thoughts?  Fixes?  PR's?

**Comment by WouterSioen** [comment]
The easiest way to fix this seems to me to change `if (!is_file(PATH_WWW . $image)) {` into `if (!is_file(PATH_WWW . strtok($image, '?'))) {` which will allow you to add GET parameters to the image name.

We could also use `filemtime` to automatically fetch the last modification time of the image and automatically append it to the url. This introduces an extra file system check though, which would add some extra milliseconds to the request.

A thirth solution I see is adding an extra optional "timestamp" or "getParameters" parameter to the method where you can add the "edited_on" timestamp of your displayed record.

**Comment by WouterSioen** [comment]
I also pretty sure the "absolute url" check doesn't work on https.

`if (mb_substr($image, 0, 7) != SITE_PROTOCOL . '://') {` will only work when the `SITE_PROTOCOL` is 4 letters long.
