### ISSUE TITLE
Other form shows up when one is submitted

### ISSUE THREAD

**Issue by jacob-v-dam** [forkcms/forkcms#1637]
In fork 4.0.5 I have a page which has two forms.
![image](https://cloud.githubusercontent.com/assets/310526/16966717/297a0958-4e06-11e6-9c21-75fa6b8bdd9e.png)

But when i submit the top form, I get the fields of the second form and the success message. The second form does not show the success message, it only shows the right form.
![image](https://cloud.githubusercontent.com/assets/310526/16966737/385961da-4e06-11e6-9ed8-78a646ee5b14.png)

When I submit the bottom form. It is hidden and show the success message above the top form. Note the string that says "Dit is een test"
![image](https://cloud.githubusercontent.com/assets/310526/16966751/48e7f66a-4e06-11e6-998e-61b545a4fc04.png)

**Comment by WouterSioen** [comment]
@jacob-v-dam are these both form builder forms? I'm looking for the easiest way to reproduce this.

**Comment by jacob-v-dam** [comment]
Yes they are.

**Comment by jacob-v-dam** [comment]
I extend a template file instead of include, could this be the problem?

**Comment by WouterSioen** [comment]
That should normally not cause any problems. I'll look if I can reproduce it.

**Comment by WouterSioen** [comment]
@jacob-v-dam can you test this fix? https://github.com/forkcms/forkcms/pull/1638
