### ISSUE TITLE
Diacritics DB vs frontend presentation 

### ISSUE THREAD

**Issue by jan-oliva** [forkcms/forkcms#1640]
For example
When I create blog post and set title **"ěščřžýáíé"**  , Title is stored in database converted to HTML entities. 
On frontend title shown with html entities. When in widget template on frontend use |raw, title shown correctly. 
On backend title is shown correctly.

I think that texts (varchar)  should saved by as original text and  without must use |raw for display each varchar.

**Comment by WouterSioen** [comment]
fix merged in #1649
