### ISSUE TITLE
Dashboard widget can't be hidden anymore

### ISSUE THREAD

**Issue by bramds** [forkcms/forkcms#1641]
Dashboard widgets can't be hidden in the groups module anymore.  Checkboxes do not show up as checked to show which modules are shown on the dashboard and which not. = all widgets are shown all the time.

**Comment by WouterSioen** [comment]
I've been looking in to this, but this system is really strange. You can check dashboard widgets for a group, but a user can be in different groups. How can we correctly determine which group to use?
