### ISSUE TITLE
Non-existent service "session.handler"

### ISSUE THREAD

**Issue by jessedobbelaere** [forkcms/forkcms#1653]
Go to a page, insert an editor block, press the image button, press the browse server button to open CKFinder. This error will be thrown:

You have requested a non-existent service "session.handler".
/Users/jessedobbelaere/Dropbox/www/fork-cms/imagetest/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php

/Users/jessedobbelaere/Dropbox/www/fork-cms/imagetest/src/Backend/Core/Js/ckfinder/config.php

See http://d.pr/i/1h3hV

Could reproduce in the latest forkcms, and on the demo website. Anyone got a clue?

**Comment by bkluiter** [comment]
Got the same problem. It says something about the XML. Can't load the XML from the webserver.
