### ISSUE TITLE
Incorrect redirects when switching languages in the backend

### ISSUE THREAD

**Issue by mathiashelin** [forkcms/forkcms#1658]
## Type

- Non critical bug

## Problem description

When you're on the edit action of a module in the backend and you switch the language, you get redirected to the edit action in the other language, which always throws an error because that specific item does not exist in that language.

## Steps to reproduce

Go to `/private/en/faq/edit?id=1` and change your language to nl. You will get redirected to `/private/nl/faq/edit?id=1` but that item doesn't exist in Dutch.

## Expected behavior / Proposed solutions

You should be redirected to the index action of the module you're working in.

**Comment by carakas** [comment]
fixed in #1666
