### ISSUE TITLE
Add some more keywords to composer.json

### ISSUE THREAD

**Issue by carakas** [forkcms/forkcms#1660]
## Type

- Enhancement

## Problem description

At the moment fork only has cms as keyword, I think we could improve the visibility by adding some extra keywords

## Steps to reproduce

look in the composer.json

## Expected behavior / Proposed solutions

to find more keywords

**Comment by WouterSioen** [comment]
#fork #cms #fork cms #content management system

any more?

**Comment by jessedobbelaere** [comment]
#symfony maybe :-)
