### ISSUE TITLE
Browsing to http://mywebsite.dev/autoload.php shows a blank page

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#1669]
## Type

- Non critical bug

## Problem description

When I try to access to http://mywebsite.dev/autoload.php I get a blank page. It could be a security issue if someone added additional code to that file.

## Steps to reproduce

Juse browse to http://mywebsite.dev/autoload.php

## Expected behavior / Proposed solutions

It should display a forbidden or a 404 error page.

**Comment by carakas** [comment]
@GhaziTriki can you create a PR for this ?

**Comment by GhaziTriki** [comment]
@carakas yes of course
