### ISSUE TITLE
Locale in (CLI) console command

### ISSUE THREAD

**Issue by jonasdekeukelaere** [forkcms/forkcms#1670]
## Type
- Critical bug

## Problem description
You don't have access to the locale (in Language class) by default.
When you try to set the locale in (Backend)Language through `Language::setLocale($language);`, the Language class tries to set a cookie, which fails in CLI commands.
You can set the locale in (Frontend)Language though, but it's a bit weird having frontend locale in a backend command.

## Steps to reproduce
Make command
Get locale

## Expected behavior / Proposed solutions
Access to (backend) locale (with or without module link)

**Comment by carakas** [comment]
@jonasdekeukelaere any update on this?

**Comment by jonasdekeukelaere** [comment]
No time
