### ISSUE TITLE
Backend Location module, getCoordinates is not functioning

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1672]
## Type

- Critical bug

## Problem description

> array(3) { ["error_message"]=> string(74) "Browser API keys cannot have referer restrictions when used with this API." ["results"]=> array(0) { } ["status"]=> string(14) "REQUEST_DENIED" } Redirecting to /private/nl/location/edit?token=allf1mqjwr&id=24&report=added&var=test.

In google you can define two keys, a browser key and a server key, for getting the coordinates we need a server key, but in the frontend we need a browser key...

[Google source](https://developers.google.com/maps/faq#switch-key-type)

## Steps to reproduce

> Try adding a location in the backend location module

## Expected behavior / Proposed solutions

> "&key=x" can not be used in getCoordinates, so remove this

**Comment by carakas** [comment]
@jeroendesloovere will you create a fix for this ?

**Comment by carakas** [comment]
@jeroendesloovere can you recreate a fix for this? The previous MR was closed because it was getting too messy, it would be best to start from a clean branch based on forkcms/master

**Comment by carakas** [comment]
don't forget to take https://github.com/forkcms/forkcms/pull/1673#issuecomment-241993336 into account

**Comment by WouterSioen** [comment]
@jeroendesloovere will you have time for this today? If you haven't, we'll move this to the next bugfix release. (which will probably be 4.2.1)
