### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by keksmampfer** [forkcms/forkcms#1677]
## Type:
- Non critical bug

## Problem description
Version: 4.1.1 
Multi-language installation
* DE (Main)
* EN
* FR

In \Frontend\Themes\name\Core\Layout\Templates\Languages.html.twig I want to use {{ lng.name }}. It prints {$msgDE} for the main language at every language. The other languages are fine. 

{{ dump(languages) }}: 
```
array(3) {
  [0]=&gt;
  array(4) {
    [&quot;url&quot;]=&gt;
    string(3) &quot;/en&quot;
    [&quot;label&quot;]=&gt;
    string(2) &quot;en&quot;
    [&quot;name&quot;]=&gt;
    string(8) &quot;Englisch&quot;
    [&quot;current&quot;]=&gt;
    bool(false)
  }
  [1]=&gt;
  array(4) {
    [&quot;url&quot;]=&gt;
    string(3) &quot;/fr&quot;
    [&quot;label&quot;]=&gt;
    string(2) &quot;fr&quot;
    [&quot;name&quot;]=&gt;
    string(12) &quot;Französisch&quot;
    [&quot;current&quot;]=&gt;
    bool(false)
  }
  [2]=&gt;
  array(4) {
    [&quot;url&quot;]=&gt;
    string(3) &quot;/de&quot;
    [&quot;label&quot;]=&gt;
    string(2) &quot;de&quot;
    [&quot;name&quot;]=&gt;
    string(8) &quot;{$msgDE}&quot;
    [&quot;current&quot;]=&gt;
    bool(true)
  }
}
```

I digged a little bit deeper. Cause I am new to Fork, i only found that the files at Frontend\Cache\Locale are missing the german translation, too. At the Backend cache is fine.

For example de.json misses: `"lbl":{"DE":"Deutsch", ....}` Same with en.json and fr.json. The other translations for EN and FR exists.

Inserting this didn't fix the problem. 

## Steps to reproduce

Languages.html.twig:
```	
{% if languages %}
{% for lng in languages %}
   <li{% if lng.current %} class="active"{% endif %}>
      <a href="{{ lng.url }}">{{ lng.name }}</a>
  </li>
{% endfor %}
{% endif %}
```

## Expected behavior 

Deutsch | German | Allemand

**Comment by carakas** [comment]
First of all welcome and thank you for contributing
The translations can be found in the locale.xml files, they are imported into the database when installing fork, or when installing the module the locale.xml belongs to.
You can find the translations in in the locale table of the database.
I'll create a PR to add the translation for this.

If you want you can always re-import a locale.xml file at '/private/locale/import'

**Comment by carakas** [comment]
and if you want to manually add a translation that is also possible at `/private/locale`
