### ISSUE TITLE
LANGUAGE not set

### ISSUE THREAD

**Issue by keksmampfer** [forkcms/forkcms#1678]
## Type
- Non critical bug

## Problem description
Version 4.1.1 - Multi language installation 

{{ dump(LANGUAGE) }} returns NULL

## Expected behavior / Proposed solutions

return current language code: en, de, fr ...

**Comment by jonasdekeukelaere** [comment]
It should be FRONTEND_LANGUAGE in the frontend, I think

**Comment by keksmampfer** [comment]
Yes, that is working! Is there somewhere a documentation of the parameters, that are available?

Then there are some templates with the wrong tag:

Core:
https://github.com/forkcms/forkcms/blob/master/src/Frontend/Core/Layout/Templates/Head.html.twig#L2
https://github.com/forkcms/forkcms/blob/master/src/Frontend/Core/Layout/Templates/Default.html.twig#L3
https://github.com/forkcms/forkcms/blob/master/src/Frontend/Core/Layout/Templates/Home.html.twig#L3

Triton:
https://github.com/forkcms/forkcms/blob/master/src/Frontend/Themes/triton/Core/Layout/Templates/Default.html.twig#L3
https://github.com/forkcms/forkcms/blob/master/src/Frontend/Themes/triton/Core/Layout/Templates/Head.html.twig#L2
https://github.com/forkcms/forkcms/blob/master/src/Frontend/Themes/triton/Core/Layout/Templates/Home.html.twig#L3

Another question:
I am trying to understand the system. The LANGUAGE is defined [here](https://github.com/forkcms/forkcms/blob/master/src/Common/Core/Twig/BaseTwigTemplate.php#L131). What is the supposed effect of addGlobal in Common, if it is not available at Frontend?

**Comment by carakas** [comment]
fixed with #1671
