### ISSUE TITLE
tools/prepare_for_reinstall doesn't delete the /app/cache

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1695]
## Type

- Non critical bug

## Problem description

> When executing `exec tools/prepare_for_reinstall` the /app/cache folders arent't being deleted. So you still get to see the website instead of the installer

## Steps to reproduce

> Install the latest forkcms in a folder, execute the cli command and see that it doesn't work like expected.

## Expected behavior / Proposed solutions

> That it works like it should

**Comment by WouterSioen** [comment]
@carakas didn't you change something about this?

**Comment by carakas** [comment]
there is already a pr for this https://github.com/forkcms/forkcms/pull/1681

**Comment by carakas** [comment]
the issue isn't closed until the PR lands :)
