### ISSUE TITLE
Installer UI could use some love.

### ISSUE THREAD

**Issue by WouterSioen** [forkcms/forkcms#1717]
## Type
- Enhancement

**Comment by mitola** [comment]
Could there be more description provided on this one ?

**Comment by StijnVrolijk** [comment]
@mitola there's quite a bit of visual difference between the UI of the installer and the UI of the backend

Take a look at https://demo.fork-cms.com/private if you haven't already.
```
user: demo@fork-cms.com
password: demo  
```
You'll see it's visually much more pleasing. We need the installer to match this visual style. Nothing too fancy, just more in line with the backend UI.
