### ISSUE TITLE
Tags are not working

### ISSUE THREAD

**Issue by jessedobbelaere** [forkcms/forkcms#1728]
## Type

- Critical bug

## Problem description

Tags are not working in the latest Fork CMS. Don't know since when this is broken.

## Steps to reproduce

Go to the [Blog module > Add](http://dev.fork-cms.dev/private/nl/blog/add) on the Demo. Fill in some tags in the field. No tags are saved. Probably the Js library that is not loaded or configured right.

## Expected behavior / Proposed solutions

Tags can be inserted into the text field and are saved properly

**Comment by carakas** [comment]
@jessedobbelaere I just tried this in the demo and it worked, you should press enter before the tag is created, in fork 3 you got a notice that you still had tags that wouldn't be saved.
Can you update the issue

**Comment by jessedobbelaere** [comment]
Oh wow. Normally i'm used to tags fields that create the tag when you click outside the field (focus lost from the field). This should be done then as a UX improvement... I'll close this :)

**Comment by carakas** [comment]
@jessedobbelaere can you create a new issue (or even better, a PR) to update the behaviour to what you expect?
