### ISSUE TITLE
Backend datagrid "Edit" button layout

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1737]
## Type

- Non critical bugfix

## Problem description

In the backend, when typing `$this->dgRecent->addColumn('Edit'` this is not supported.
You need to type `$this->dgRecent->addColumn('edit'` to get the button layout right.

## Expected behavior / Proposed solutions

add/Add/edit/Edit/... should all work the same

P.S.: in older fork cms 3.9.* this worked just fine.

**Comment by carakas** [comment]
it's a small bug, can you provide a fix for it? probably just a strtolower
