### ISSUE TITLE
Installer: installed modules sequence "Extensions" should be the first to be installed

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#1739]
## Type

- Non critical bug

## Problem description

When adding an extra to install for a module that it is installed before the "Extensions" module we get an exception ```Base table or view not found: 1146 Table 'my_db.modules_extras' doesn't exist```. ForkCMS is based on modules, it sounds logic to make "Extensions" (akka Modules) module to be installed first. We would avoid putting delegating part outside their responsibility scope like the following [SearchForm widget installed inside Extensions installer instead of the Search module installer](https://github.com/forkcms/forkcms/blob/master/src/Backend/Modules/Extensions/Installer/Installer.php#L18)

## Steps to reproduce

- Add an extension to Settings module as example then install ForkCMS.

## Expected behavior / Proposed solutions

ForkCMS should be installed without any exception.

**Comment by GhaziTriki** [comment]
@carakas do you agree that `Extensions` module should be installed first?

**Comment by carakas** [comment]
if it causes the above problems I think it is a good reason to install it first

**Comment by carakas** [comment]
I might be inclined to add it to the CoreInstaller

**Comment by GhaziTriki** [comment]
@carakas you are right, we might consider that a developer needs to add an extra to `Locale` and `Extensions` modules. Better making `modules_extras` table installed whtin Core.
