### ISSUE TITLE
Old "loading" icon

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1750]
## Type

- Enhancement

## Problem description

> An old animated loader icon is being used.
<img width="201" alt="schermafbeelding 2016-09-24 om 07 55 23" src="https://cloud.githubusercontent.com/assets/588616/18806423/5bc6a812-822c-11e6-99c1-19ef77bb17bd.png">

## Steps to reproduce

1. Modules > Blog > Click on "Add article"
2. Click in the category dropdown and choose "Add category"
3. Enter a title and press enter, then you see the old animated loader icon

## Expected behavior / Proposed solutions

> New retina safe icon

**Comment by ajm113** [comment]
Can it be one of the icons in Font Awesome? i.e. 
![icon](https://cloud.githubusercontent.com/assets/9935420/19011182/7cb1a63c-8743-11e6-81a9-6242116f0ffd.png)

Or does it need to be exactly the same looking icon?

**Comment by StijnVrolijk** [comment]
I don't know from the top of my head but if there's a loading icon somewhere else in the backend, this one should match it. 

If there's not, any icon will do for me as long as it fits the theme. Font awesome is probably the best solution since it's already implemented afaik.

**Comment by ajm113** [comment]
I was going to suggest sticking with Font Awesome for flexibility, and easier to download since it's already loaded on page load. But I can take another look around.
