### ISSUE TITLE
Page unassigned blocks not detected when switching template multiple times without saving

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#1751]
## Type
- Non critical bug
## Problem description

Unassigned blocks are detected as assigned when switching template on and off.
## Steps to reproduce

http://screencast.com/t/raX3cRij4t
## Expected behavior / Proposed solutions

Correctly detect blocks when switching template multiple times.

**Comment by carakas** [comment]
I'm not sure if we can fix this in a BC way

**Comment by carakas** [comment]
Since we can't really fix this in a BC Way and you can just refresh if you took the wrong template this will be marked as won't fix
