### ISSUE TITLE
FormBuilder widget does not provide link to the form in page edit

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#1752]
## Type

- Enhancement

## Problem description

When adding a form in a page, we don't see any edit button like the content block.

## Steps to reproduce

Add or edit page then put a form inside it.

## Expected behavior / Proposed solutions

Have the edit button for form in page edit/add action.
![image](https://cloud.githubusercontent.com/assets/4991088/18814963/2b7e65f4-8322-11e6-91c7-061fa2c3a660.png)

**Comment by carakas** [comment]
turns out it was a bug,
it was added when creating a form but deleted when editing it
