### ISSUE TITLE
TwigTemplate - rendering inside ajax calls

### ISSUE THREAD

**Issue by The50** [forkcms/forkcms#1753]
## Type
- Non critical bug

## Problem description
After the updated Fork version the template rendering has changed a little bit. At the moment then I try to render some template I get an error which says that I'm not passing enough arguments. 

Function itself needs these arguments:
public function __construct(\Twig_Environment $environment, TemplateNameParserInterface $parser, FileLocatorInterface $locator)

It is in TwigTemplate.php file (/Frontend/Core/Engine/TwigTemplate.php).

## Steps to reproduce
How the template should be rendered after the Twig update? What arguments I have to pass into the function? 

At the moment I include the templates file using:
"use Frontend\Core\Engine\TwigTemplate as Template;"

And after that I try to create it using:
"$itemsTpl = new Template(null, null, null);"

Now I need to know the arguments I have to pass. I can provide you with more info if needed.

**Comment by StijnVrolijk** [comment]
I think you are using the Twig template in an incorrect manner.
Templating is now used as a service so you could just use the following code:
```$itemsTpl = $this->get('templating')```

This will return an instance of TwigTemplate ready to go.

The reason we do this is so we only have one instance of the templating engine across the entire environment. By calling `new Template()` you are basically instantiating a new templating engine., this uses unnecessary resources.

Can I ask what the context is of your use case? I've almost never had to create a template of my own, this is usually handled by stuff like base controllers, message instances, ..

**Comment by The50** [comment]
Yes, the reason I need this is that I use the Load More function with Ajax and I want to render my HTML via Ajax, send it back to JavaScript and append it somewhere in my page. This way I won't have to write HTML in my JS file. Or there is another function I could use to render some HTML?

**Comment by StijnVrolijk** [comment]
I suggest using [Handlebars](http://handlebarsjs.com/) to do this kind of stuff. Sending HTML over an AJAX call is not very smart performance wise.

By using Handlebars you just send your json encoded format to you javascript and render the handlebars template. More information can be found on the [Handlebars website](http://handlebarsjs.com/)

**Comment by The50** [comment]
Thank you for the info, appearently all I needed was "$this->get('templating')".
