### ISSUE TITLE
Add extra parameter in src/Backend/Engine/Base/Action->getParameter

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1769]
## Type
- Enhancement
## Problem description

> Soon Spoon will be removed in Fork CMS. That's why I suggest adding a new variable in the /src/Backend/Engine/Base/Action->getParameter() method to allow $possibleValues.

Current method =>

``` php
    public function getParameter($key, $type = 'string', $defaultValue = null)
    {
        $key = (string) $key;

        // parameter exists
        if (isset($this->parameters[$key]) && $this->parameters[$key] != '') {
            return \SpoonFilter::getValue($this->parameters[$key], null, null, $type);
        }

        return $defaultValue;
    }
```

> But It should have a fourth parameter $possibleValues. So we replace any instance of direct access to \SpoonFilter in our codebase.

For example, current code:

``` php
        $from = \SpoonFilter::getGetValue(
            'from',
            array('image', 'movie'),
            'image'
        );
```

New code:

``` php
        $from = $this->getParameter('from', 'string', 'image', array('image', 'movie'));
```

**Comment by carakas** [comment]
isn't this already part of the parameter bags of the request?

**Comment by jeroendesloovere** [comment]
So you are suggesting to remove all \SpoonFilter::getGetValue (in AJAX Actions) to be replaced by request?

**Comment by carakas** [comment]
yes

**Comment by jeroendesloovere** [comment]
Will be fixed when https://github.com/forkcms/forkcms/issues/1714 is done.
