### ISSUE TITLE
SEO is missing a "navigation_title" field

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1776]
## Type
- Enhancement
## Problem description

> In some modules like f.e.: "Categories/Project category/..." I miss a SEO field to overwrite the navigation title. The funny thing is that the pages modules has this field. Others don't.
## Steps to reproduce

> Create a categories module and use the build in SEO functions.
## Expected behavior / Proposed solutions

> We need to add two database-fields to the Meta table: "navigation_title" and  "navigation_title_overwrite" (checkbox in template)

**Comment by carakas** [comment]
what is wrong with page title ?

**Comment by jeroendesloovere** [comment]
Page title is for the browsers page title. This is different then Navigation title.

Example:
* Title = "Frequently asked questions"
* Navigation title = "FAQ" (currently doesn't exists in the SEO tab, you can only do this in the pages module)
* Page title = "Frequently asked questions which can help you find products."

**Comment by jeroendesloovere** [comment]
We are closing this for now.
