### ISSUE TITLE
Can't overwrite {% if showBlogDelete %}

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1777]
## Type
- Non critical bug
## Problem description

> If for any reason you want to overwrite the default "showBlogDelete", this seems to be not possible anymore. Which I think was possible in older fork cms 3.9.\* versions (which used SpoonTemplate).
## Steps to reproduce

> You can try to add the following in your parse() method in the Edit.php action class of the Blog or ContentBlocks module:

``` php
$this->tpl->assign('showBlogDelete', false);
```
## Expected behavior / Proposed solutions

> Expected behavior is that the delete button is gone. But it is still available...

**Comment by carakas** [comment]
The value of that parameter is the direct result of the permissions the authenticated user has, so this is the intended behaviour.

**Comment by jeroendesloovere** [comment]
Hmmm, which means that you can't overwrite this, even if for example that item must not be deleted if it has children.

I can find myself in your solution, but then we need to throw an error if you try to set $this->tpl->assign('showBlogDelete', false);
What do you think?

**Comment by carakas** [comment]
I think that if you

**Comment by carakas** [comment]
you can set it, the cms just overwrites it. an error might be an idea but where do you stop since all those things are generated dynamically
