### ISSUE TITLE
PDOException on remove cache or app/console

### ISSUE THREAD

**Issue by ciryk** [forkcms/forkcms#1786]
## Type
- Non critical bug
## Problem description

> My website files and database are stored on a SMB share on the local network, whenever I want to run a command through app/console it throws me a PDOException;

```
_Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Connection refused' in /Volumes/htdocs/fork4/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
Stack trace:
#0 /Volumes/htdocs/fork4/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=127....', 'fork4', 'test', Array)
#1 /Volumes/htdocs/fork4/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(45): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=127....', 'fork4', 'test', Array)
#2 /Volumes/htdocs/fork4/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'fork4', 'test', Array)
#3 /Volumes/htdocs/fork4/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): Doctrine\DBAL\Connection->connect()
#4 /Volumes/htdocs/fork4/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#5 /Volumes/htdocs/fork4/vendor/doctrine/dbal/lib/Doctrine in /Volumes/htdocs/fork4/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 103_

```
## Steps to reproduce

> Remote connection on samba share where files are stored, using XAMP PRO for local hosting MYSQL and Apache
> 
> Running app/console cache:clear or ./remove_cache 
> 
> Error from local machine, but no error when executed from the machine where the files are stored and XAMP hosted after change parameters.yml
## Expected behavior / Proposed solutions

> Changing host in parameters.yml to 127.0.0.0 lets you execute from local pc.
> Expecting to execute this from my local pc, not the server.

**Comment by carakas** [comment]
closed since there is no further update, contact me if you want to continue with this
