### ISSUE TITLE
Mailmotor - templates still TPL format

### ISSUE THREAD

**Issue by Lennerd320i** [forkcms/forkcms#1793]
## Type

- Critical bug

## Problem description

I ticked the Critical bug as without a solution to these, the mailmotor isn't functional.
Let me describe.

I use mailmotor with campaignmonitor (createsend) and am migrating to version 4.2.x (coming from 3.x.x), so I knew I had to adapt my own template to be functional.
While testing with the default and blank template included in the Fork release, I got an error "500 internal error". Checking the logs stated that the .html.twig files weren't present. And indeed, the templates are still the old ones in .tpl.

My knowledge is very basic (not to say absent) and simply changing the file format doesn't work, never the less the old template format is very basic html coding. and I guess I won't be the only one facing this.

## Steps to reproduce

Link createsend account to mailmotor, and try to create a mailing using one of the included templates. (with some bad luck you need to overrule the x-frame-options to see the iframe before getting the "internal error" to pop up).

## Expected behavior / Proposed solutions

Convert the tpl templates to html.twig.

Tnx in advance!

**Comment by carakas** [comment]
There is a PR with a refactored Mail Motor that should fix it from @jeroendesloovere #1629 
It just hasn't passed yet

**Comment by carakas** [comment]
I created a PR for it so it is fixed while we wait for the new mailmotor to land

**Comment by Lennerd320i** [comment]
Thanks @carakas !
