### ISSUE TITLE
FAQ > index: Categories are not sorted properly

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1802]
## Type

- Enhancement

## Problem description

> When ordering FAQ categories in the backend and then viewing the FAQ index in the backend. The categories are shown ordered by created_on and not by sequence.

## Steps to reproduce

![schermafbeelding 2016-10-24 om 11 06 26](https://cloud.githubusercontent.com/assets/588616/19639749/ef7bba06-99d9-11e6-81e1-fe3307b07b0b.png)
![schermafbeelding 2016-10-24 om 11 04 50](https://cloud.githubusercontent.com/assets/588616/19639689/c1a4dd06-99d9-11e6-8c4e-b5cfab52f73e.png)

## Expected behavior / Proposed solutions

> Modules > FAQ > Index: order the categories by sequence

**Comment by carakas** [comment]
@jeroendesloovere can you fix this?

**Comment by StijnVrolijk** [comment]
i'll deal with this
