### ISSUE TITLE
Error thrown when src/Frontend/Cache/Search folder not exists

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1808]
## Type
- Non critical bug
## Problem description

> When you have deployed a fork cms website and your `src/Frontend/Cache/Search` folder doesn't exist on your hosting and you trigger a `BackendSearchModel::saveIndex(/*...*/)` then an error will occur because.
> ![schermafbeelding 2016-10-25 om 14 48 44](https://cloud.githubusercontent.com/assets/588616/19686852/6110e012-9ac3-11e6-853d-d2ffb89cc9b0.png)
## Steps to reproduce

> Remove your `src/Frontend/Cache/Search` folder and try saving a blog article.
## Expected behavior / Proposed solutions

Two possible solutions:
1. Add a check to see if the folder exists.
2. Step one + throw a custom error that the folder doesn't exists.

**Comment by carakas** [comment]
no need to throw an error as far as I can see

**Comment by carakas** [comment]
The directory has a .gitignore and therefore we can expect it to be there
