### ISSUE TITLE
Symfony bundle on Fork

### ISSUE THREAD

**Issue by The50** [forkcms/forkcms#1809]
## Type
- Feature

## Problem description
With the latest update of Symfony framework integration it should be possible to use Symfony bundles on our Fork projects. Is there any info on how I could get it done?

## Steps to reproduce
I have my bundle files in Project root -> plugins folder and now the main problem is how should I get it working? Do I have to create a module which calls to the bundle function somehow? I am trying to get any of the Symfony forum bundle's working here.

Thank you.

**Comment by carakas** [comment]
The installer of fork is a bundle
The easiest way would be to look at how it is used
If you want to do things with it in the Backend you will need to create a fork module and call the bundle from there
