### ISSUE TITLE
Layout issue

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1834]
## Type

- Enhancement

## Problem description

> On my macbook pro 13", the layout for two buttons next to each other seems odd.
<img width="289" alt="schermafbeelding 2016-11-08 om 10 05 22" src="https://cloud.githubusercontent.com/assets/588616/20092959/f1d3db22-a59a-11e6-9167-2e2f33fe557d.png">

**Comment by carakas** [comment]
is already fixed by #1829 
![Uploading Screen Shot 2016-11-08 at 10.13.52.png…]()
