### ISSUE TITLE
Form type for image and file

### ISSUE THREAD

**Issue by carakas** [forkcms/forkcms#1835]
## Type

> remove the types that don't apply

- Enhancement

## Problem description

you now need to do extra stuff to trigger the lifecycle callbacks if the file or image is the only thing that has changed, this should be easier

## Expected behavior / Proposed solutions

a form type that handles it for you

**Comment by carakas** [comment]
I'm currently working on an implementation of this for a symfony framework
should be backported to here

**Comment by jeroendesloovere** [comment]
Isn't this one fixed?

**Comment by carakas** [comment]
yes it was :) woops
