### ISSUE TITLE
Better detection for nginx in install

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#1838]
## Type

- Enhancement

## Problem description

![image](https://cloud.githubusercontent.com/assets/4991088/20245694/f41f5b12-a9a6-11e6-823c-1ba366b83051.png)

Install is configured to detect Apache2 only.

## Steps to reproduce

Run a ForkCMS install on a nginx server.

## Expected behavior / Proposed solutions

Install should be able to detect nginx using `$_SERVER["SERVER_SOFTWARE"]`

**Comment by carakas** [comment]
@GhaziTriki can you work on a fix for this since you already have the correct environment for this?

**Comment by GhaziTriki** [comment]
@carakas I will take a look at it :)

**Comment by carakas** [comment]
Going to close this one for now
