### ISSUE TITLE
Bug when having three words in ChoiceType choices

### ISSUE THREAD

**Issue by ciryk** [forkcms/forkcms#1841]
## Type

- Critical bug

## Problem description

Having a collection type of choicetypes with choices labels longer than 3 words give an error. F.e. a select option with label "one two" works, but ons with "one two three" doesn't.

## Steps to reproduce

Create a Symfony form with a CollectionType consisting of ChoiceType's as an entry type. Give the ChoiceType these choices : array(0 => 'one two three')

## Expected behavior / Proposed solutions

Looks like the choices are being parsed as a language like the label is.( lbl.Name ) , therefor not finding the dot so undefined index 1. Beter not to check the choices by language? Having a string of two words fixes the issue

**Comment by carakas** [comment]
fixed in https://github.com/forkcms/forkcms/pull/1851
