### ISSUE TITLE
Form Builder - enter is being displayed as <br />

### ISSUE THREAD

**Issue by Lennerd320i** [forkcms/forkcms#1852]
## Type

- Non critical bug

## Problem description

When someone adds text in the "textarea" part of a form, and the form is sent, every "enter" is displayed within the mail as <br />.

## Steps to reproduce

Create a form with a textarea, go through the front end, try e.g. test ENTER test and send it. In the mail sent, the enter will be html wise translated to <br />.

## Expected behavior / Proposed solutions

translate the <br /> stored within the database back.

Maybe it's related to the Original issue with ampersand within issue #1649 ?

P.S.: I had this issue as from the 4.x version, and tested it now with both 4.2.3 and 4.3.1.

kr,

Lennerd

**Comment by carakas** [comment]
@Lennerd320i is it your own theme? or triton/default theme?

**Comment by Lennerd320i** [comment]
@carakas my own, but the templates used are those stock within Fork, so nothing modified.

**Comment by carakas** [comment]
you need to add `|raw` in the template there it is parsed

**Comment by carakas** [comment]
can you create the PR for it?

**Comment by Lennerd320i** [comment]
@carakas The solution proposed by you did the trick.
I do hope I created the PR as it should.

kr
