### ISSUE TITLE
Switching theme back does not load the correct positions

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#1859]
## Type

- Non Critical bug

## Problem description

When creating a customer theme and enabling it, then enabling Triton and finally re-enabling the custom theme, positions from the current theme are not loaded.

## Steps to reproduce

- Create a custom theme; we will name it here "RIADVICE"; with a template `home` two positions: sliders & main.
- Enable the new theme.
- Add content blocks to the `sliders` position.
- Enable the default theme `Triton`.
- Enable the custom theme `RIADVICE`
- Load the home page.

The loaded positions are `top`, `left`, `main` & `right`. And no content is displayed for the `sliders` position which is not loaded.

## Expected behavior / Proposed solutions

The engine should load `sliders` & `main` positions.

**Comment by carakas** [comment]
when switching a theme you should check the pages, we try to match it but there is no guarantee that it will work, I'm also not sure if we can fix this without overkill for the actual use of it.

I'm not sure if this is something we should "fix", but maybe I misunderstood the issue

**Comment by GhaziTriki** [comment]
Here is a video recording of the issue: https://www.dropbox.com/s/hmiefqs29yx5ys1/2016-12-06_0632.swf?dl=0
However is you save your page later the positions are then correctly set.

**Comment by StijnVrolijk** [comment]
won't fix
