### ISSUE TITLE
install not load in loclhost

### ISSUE THREAD

**Issue by AhrimanSefid** [forkcms/forkcms#1865]
hi.
me install localhost in win x 64 wamp 2.5
Server Software: Apache/2.4.9 (Win64) PHP/5.5.12
not load install page.
`
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
league/flysystem suggests installing league/flysystem-copy (Allows you to use Copy.com storage)
league/flysystem suggests installing league/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
matthiasmullie/scrapbook suggests installing ext-apc (>=3.1.1)
matthiasmullie/scrapbook suggests installing ext-couchbase (>=2.0.0)
matthiasmullie/scrapbook suggests installing ext-memcached (>=2.0.0)
matthiasmullie/scrapbook suggests installing ext-redis (>=2.2.0 || 0.0.0.0)
kriswallsmith/assetic suggests installing leafo/lessphp (Assetic provides the integration with the lessphp LESS compiler)
kriswallsmith/assetic suggests installing leafo/scssphp (Assetic provides the integration with the scssphp SCSS compiler)
kriswallsmith/assetic suggests installing leafo/scssphp-compass (Assetic provides the integration with the SCSS compass plugin)
kriswallsmith/assetic suggests installing patchwork/jsqueeze (Assetic provides the integration with the JSqueeze JavaScript compressor)
kriswallsmith/assetic suggests installing ptachoire/cssembed (Assetic provides the integration with phpcssembed to embed data uris)
symfony/assetic-bundle suggests installing kriswallsmith/spork (to be able to dump assets in parallel)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Generating autoload files
> php app/console assetic:dump .
Dumping all install assets.
Debug mode is on.

17:11:38 [dir+] ./css
17:11:38 [file+] ./css/244a296.css
17:11:38 [file+] ./css/244a296_part_1_installer_1.css
17:11:38 [dir+] ./js
17:11:38 [file+] ./js/e586e00.js
17:11:38 [file+] ./js/e586e00_part_1_backend_1.js
17:11:38 [file+] ./js/e586e00_part_1_install_2.js
> cd tools && bash ./remove_cache
'bash' is not recognized as an internal or external command,
operable program or batch file.
Script cd tools && bash ./remove_cache handling the post-install-cmd event returned with error code 1
`

**Comment by carakas** [comment]
can you give us more information?

**Comment by carakas** [comment]
it is because you are using windows remove "cd tools && bash ./remove_cache" from composer.json
that should fix your problem

**Comment by AhrimanSefid** [comment]
me remove line but not update or install.

**Comment by carakas** [comment]
what is the error you get

**Comment by AhrimanSefid** [comment]
noting

**Comment by AhrimanSefid** [comment]
C:\wamp\www\fork>composer update
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Updating dependencies (including require-dev)

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 134217728 bytes) in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/Solver.php on line 220

Call Stack:
    0.0067     429336   1. {main}() C:\ProgramData\ComposerSetup\bin\composer.phar:0
    0.0068     432184   2. require('phar://C:/ProgramData/ComposerSetup/bin/composer.phar/bin/composer') C:\ProgramData\ComposerSetup\bin\composer.phar:24
    0.0473    5245528   3. Composer\Console\Application->run() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/bin/composer:43
    0.0513    5711040   4. Symfony\Component\Console\Application->run() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:104
    0.0526    5875080   5. Composer\Console\Application->doRun() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:123
    0.8808   12711568   6. Symfony\Component\Console\Application->doRun() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:231
    0.8809   12712016   7. Symfony\Component\Console\Application->doRunCommand() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:192
    0.8809   12712560   8. Symfony\Component\Console\Command\Command->run() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:847
    0.8817   12717392   9. Composer\Command\UpdateCommand->execute() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Command/Command.php:259
    0.8852   13201360  10. Composer\Installer->run() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/UpdateCommand.php:174
    0.8879   13360568  11. Composer\Installer->doInstall() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer.php:216
    2.4287   14487816  12. Composer\DependencyResolver\Solver->solve() phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer.php:461


Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.

**Comment by carakas** [comment]
this is not a fork issue but an composer issue.

I don't know if it works on windows but on mac and linux you can run `php -d memory_limit=-1 /usr/local/bin/composer install`

**Comment by AhrimanSefid** [comment]
C:\wamp\www\fork>php -d memory_limit=-1 /usr/local/bin/composer install
Could not open input file: /usr/local/bin/composer

C:\wamp\www\fork>
C:\wamp\www\fork>php -d memory_limit=-1 composer install
Could not open input file: composer

C:\wamp\www\fork>php -d memory_limit=-1 C:\wamp\www\fork composer install
Could not open input file: C:\wamp\www\fork

**Comment by AhrimanSefid** [comment]
![image](https://cloud.githubusercontent.com/assets/1332246/20806045/8efcb6b4-b80e-11e6-8e3e-f602f686437d.png)

**Comment by GhaziTriki** [comment]
@AhrimanSefid The best solution that I have tested to install ForkCMS on a Apahce server for windows is to create a virtual host for it.
