### ISSUE TITLE
Installation fails: PHP Fatal error:  Call to undefined function

### ISSUE THREAD

**Issue by Ceaus** [forkcms/forkcms#1877]
## Type

>- Critical bug

## Problem description

I am running the installation in docker in the official openSUSE container (Leap 42.2).
The installation of 4.4.0 fails to complete and stops with an error message.

> Describe your problem here

After running

    composer.phar create-project forkcms/forkcms

all dependencies are correctly installed. However the installation fails to complete. The last few lines of console  output are:

    phpunit/phpunit-mock-objects suggests installing ext-soap (*)
    phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
    phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
    Generating autoload files
    > php app/console assetic:dump .
    PHP Fatal error:  Call to undefined function Symfony\Component\Config\ctype_alpha() in /srv/www/htdocs/forkcms/vendor/symfony/symfony/src/Symfony/Component/Config/FileLocator.php on line 85
    Script php app/console assetic:dump . handling the post-install-cmd event returned with error code 255

No errors are reported before this.

## Steps to reproduce

> Describe how we can reproduce the problem here

1. Download and unzip forkcms-4.4.0.tar.gz from the Fork CMS website.
2. Open README.md for installation instructions.
3. Spin up the official openSUSE docker container.
4. Run the steps as per README.md (the composer related bits).
5. Watch the installation fail with the above error message.

## Expected behavior / Proposed solutions

> explain what you had expected to happen and or a solution

**Comment by carakas** [comment]
I'll look into it

**Comment by carakas** [comment]
First of al :) if you download the zip from our site everything should work out of the box.
so you don't need to run composer.phar create-project forkcms/forkcms if you already have the zip, nor do you need to run composer install

**Comment by carakas** [comment]
did you run the composer install command inside the container?

**Comment by Ceaus** [comment]
If you download the zip from our site everything should work out of the box.

There are no further installation instructions than the README.md inside the zip. And that instructs me as follows:

    ## Installation

    1. Make sure your have [composer](https://getcomposer.org/) installed.
    2. Run `composer create-project forkcms/forkcms .` in your document root.
    3. Browse to your website
    4. Follow the steps on-screen
    5. Have fun!

Perhaps it's useful to clarify this in the README.md or on the website?

    Did you run the composer install command inside the container?

Yes, correct.

**Comment by carakas** [comment]
Remark: If you are using GIT instead of composer create-project or the zip-file from http://www.fork-cms.com, you should install our dependencies. The dependencies are handled by composer

It's mentioned in here but the phrasing could be perhaps more clear
