### ISSUE TITLE
403 links in the installation instructions

### ISSUE THREAD

**Issue by Ceaus** [forkcms/forkcms#1878]
## Type

> remove the types that don't apply

- Non critical bug
## Problem description

> Describe your problem here

In the installation page on http://docs.fork-cms.com/documentation/detail/installation/installation there are quite a few 403 links. Such as:

- "server meets the minimum requirements for Fork "
http://docs.fork-cms.com/documentation/detail/installation/03.%20minimum_requirements.md
- " Start by taking a look at our Frequently Asked Questions."
http://docs.fork-cms.com/documentation/detail/installation/07.%20faq.md

These are just 2. But there are a few more. Also in related pages.

**Comment by carakas** [comment]
@ceaus we have a report for our documentation site, can you create this issue there? Or a problem fixing it would be even better. http://github.com/forums/documentation

**Comment by carakas** [comment]
Stupid autocorrect

**Comment by carakas** [comment]
https://github.com/forkcms/documentation

**Comment by Ceaus** [comment]
Done: https://github.com/forkcms/documentation/issues/66
