### ISSUE TITLE
FormBuilder: Add the possibility to change the formField-ID.

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1880]
## Type

- Feature

## Problem description

> Marketeers using google tag manager want to know in which field a visitor clicks. Currently field ID's are like "field1", "field2", ... which doesn't tell you anything.

## Expected behavior / Proposed solutions

> Add the possibility in the backend to add a custom "field-name" for that form.

**Comment by carakas** [comment]
Won't this add a lot of complexity since we will also have to check that they are unique?

**Comment by adeacetis** [comment]
@carakas IMHO it's up to the marketeer / webmaster or whomever to check duplicated ID's out. I mean we should let the user decide whether he wants to override default behavior or not.

**Comment by carakas** [comment]
We can take a second look at this after this module has been ported to symfony forms

**Comment by carakas** [comment]
closing for now
