### ISSUE TITLE
Make blog image sizes configurable in a file

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#1883]
## Type

- Enhancement

## Problem description

We actually need to edit Add and Edit actions and something like the line below to put additional thumbnail generating
```php
$filesystem->mkdir(array($imagePath . '/source', $imagePath . '/850x600'));
```

## Expected behavior / Proposed solutions

Should be possible to add or update generated thumbnails sizes in a configuration file for the Blog module.

**Comment by carakas** [comment]
You van just create the directories manually the code is just there in case the directories are missing but it is a bit Overkill, they should just be creatief in the installer in my opinion
