### ISSUE TITLE
Weird display for "intl" module in install

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#1893]
## Type

- Non critical bug

## Problem description

The intl php module description is weird, we see and orphan `">`

![image](https://cloud.githubusercontent.com/assets/4991088/21225771/b3cdde5e-c2d2-11e6-992b-3da1ec4f7a16.png)

> Describe your problem here

## Steps to reproduce

Go to the first step of installing ForkCMS.

## Expected behavior / Proposed solutions

Should be easy to fix in the template.

**Comment by freshface** [comment]
Made a PR for it https://github.com/forkcms/forkcms/pull/1901

**Comment by carakas** [comment]
Close because it has been merged
