### ISSUE TITLE
Adding location widget to page does not work

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#1895]
## Type

- Critical bug

## Problem description

If a user adds a location widget to page, the widget is not added

## Steps to reproduce

1. Create a new location.
2. Add that new location widget to a page.
3. Check the page.

## Expected behavior / Proposed solutions

The location widget should be displayed in the page.

**Comment by carakas** [comment]
did you add all the configuration for it? (api key)

**Comment by GhaziTriki** [comment]
Yes the Location is correctly configured.

**Comment by carakas** [comment]
will be fixed in fork 5
