### ISSUE TITLE
Need to fix error "Mixed Content: The page at 'https://server.com/en/blog/detail/post-one' was loaded over HTTPS, but requested an insecure script "

### ISSUE THREAD

**Issue by Sellato** [forkcms/forkcms#1896]
## Type
- Critical bug

## Problem description

If using HTTPS protocol there is an error:

`Mixed Content: The page at 'https://hatmaker.crafterspark.com/en/blog/detail/old-copper-crashed-hat' was loaded over HTTPS, but requested an insecure script`

`'http://platform.linkedin.com/in.js?fork%5Bmodule%5D=&fork%5Baction%5D=&fork%5Blanguage%5D=en&_=1482036206716'. This request has been blocked; the content must be served over HTTPS.`

The same for LinkedIn, Twitter and Facebook

## Steps to reproduce

You can see this error in DEBUG window of any browser when switch to BLOG POST ( where is a SHARE button )

## Expected behavior / Proposed solutions

Solution is very easy - need to REMOVE any protocols ( http: ) in file /src/Frontend/Core/Js/jquery/jquery.frontend.js

for example:
**in line 199** 
_**change from**_ 
`if($(this).attr('src') == 'http://platform.twitter.com/widgets.js') twitterLoaded = true;`
_**to**_ 
`if($(this).attr('src') == '//platform.twitter.com/widgets.js') twitterLoaded = true;`

The same for LinkedIn and Facebook

ADD
for LinkedIN not so easy .... :( 

_Failed to load resource: net::ERR_INSECURE_RESPONSE https://platform.linkedin.com/in.js?fork%5Bmodule%5D=&fork%5Baction%5D=&fork%5Blanguage%5D=en&_=1482038740909_

**_net::ERR_CERT_AUTHORITY_INVALID
Subject: mail.someorg.net
Issuer: mail.someorg.net
Expires on: 20 нояб. 2026 г.
Current date: 18 дек. 2016 г.
PEM encoded chain:_** 

**this is problem with LinkedIN NOT with FORK :)**

**Comment by carakas** [comment]
Can you create a pr for it?

**Comment by Sellato** [comment]
sorry, I can't :(

**Comment by jessedobbelaere** [comment]
They all can be changed to https links instead of http imo. Made a quick PR. Result can be checked on https://dokku.jessedobbelae.re/blog/detail/nunc-sediam-est

**Comment by Sellato** [comment]
Great!

Made your PR by hands. Works fine. No more errors like "mixed-content" and "gravatar"!
Result can be checked on - https://hatmaker.crafterspark.com/en/blog

Thanks!
