### ISSUE TITLE
Stylesheet injection to French website making the site floating right

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#1897]
## Type

- Critical visual bug

## Problem description

The French website is floating at the right instead of taking the width of all the page. Chrome developer console show the style below as `injected stylesheet` form the `body` tag.

```css
.fr {
    float: right;
}
```

## Steps to reproduce

Switch the frontend language to French.

## Expected behavior / Proposed solutions

The French website should not be floating right and should take the width of all the page.

**Comment by carakas** [comment]
HAHAHAHAHAHA

**Comment by GhaziTriki** [comment]
It is a true bug, you can check it here http://demo.fork-cms.com/fr

**Comment by carakas** [comment]
Can't reproduce it

**Comment by GhaziTriki** [comment]
Zoho Projects extension for chrome was injecting that style.
