### ISSUE TITLE
Autocomplete not working in frontend

### ISSUE THREAD

**Issue by Mirau89** [forkcms/forkcms#1900]
## Type

- Critical bug

## Problem description

When the Search form widget is added to a page, the autocomplete is not working.

## Steps to reproduce

Put search form widget in a page.

## Expected behavior / Proposed solutions

Load `Search.js` when the search form widget is added to a page.

**Comment by Mirau89** [comment]
The autocomplete work properly with triton theme.

**Comment by carakas** [comment]
@Mirau89 so it is only in your own theme?

**Comment by GhaziTriki** [comment]
Yes it does not work with other theme, however it works well on the search index page.

**Comment by carakas** [comment]
I think it is related to your theme, just tried it with our own bootstrap theme and it is loaded.
Going to close this issue since it doesn't look like it is a bug in fork.
You can always contact me on slack to see if we can figure this one out

**Comment by carakas** [comment]
The reason was that the template modifier parsewidget was used.
The autoloading only works when the action/widget is added via the pages module in the backend
