### ISSUE TITLE
New Mailmotor - list ID's (campaignmonitor) and single opt-in

### ISSUE THREAD

**Issue by Lennerd320i** [forkcms/forkcms#1909]
## Type

- Critical bug
- Non critical bug

## Problem description

Hi, I picked both the critical and non critical bug, as for me (personally) it's in between.
I'm using campaignmonitor for my newsletter needs, and with the 4.4.1 version, the new Mailmotor was integrated. Besides the fact that we are now forced to send newsletters through the campaignmonitor website and not longer through our backend (as it was before), everything seems to work, except I do have 2 issues:

1) I used the single opt-in option, but as the new mailmotor is programmed, you have to use confirmed opt-in. I didn't see any notice about this, and had to change the settings for my list within campaignmonitor to find out why subscribers weren't added. 
2) I have a multi lingual website (both dutch and french), and do have due to this 2 newsletter lists (a dutch one and a french one). Within the settings for the mailmotor module, only 1 list ID is stored in the database.

## Steps to reproduce

configure mailmotor module for campaignmonitor and enter the api ID as well as the list ID.

## Expected behavior / Proposed solutions

1) option to change to single opt-in or confirmed opt-in within the backend or (most simple option, but not appreciated by every user) notice about the confirmed opt-in and that it should be turned on in the (for my case) campaignmonitor settings.
2) list ID's based on the language and stored within the database (everything else for the backend has to be configured twice if you have 2 frontend languages, so I guess it's not going to be an issue for users of he mailmotor if they have to configure this twice as well).

kr,

Lennerd

**Comment by jeroendesloovere** [comment]
Hi Lennerd, I've created the new mailmotor module.
Here are some answers to your questions.

## 1) Double Opt-in

**My answer**
This is `true` by default, because otherwise your list will be spammed for death.
=> I think, we aren't going to change this behavior, nor add a backend setting for this**, not, @carakas ?

**A possible solution**
You can overwrite this default `true` by adding a fifth parameter `false` in the following method-call in
[src/Frontend/Modules/MailMotor/Command/SubscribeHandler.php](
https://github.com/forkcms/forkcms/blob/master/src/Frontend/Modules/Mailmotor/Command/SubscriptionHandler.php#L77)

This is the code you need to use:
```
        // Subscribing the user, will dispatch an event
        $this->subscriber->subscribe(
            $subscription->email,
            (string) $subscription->locale,
            $mergeFields,
            $interests,
            false // You need to add this line
        );
```
> Here is the core function from the "MailMotorBundle": https://github.com/mailmotor/mailmotor-bundle/blob/master/Helper/Subscriber.php#L143 if you want to get more to overwrite...

## 2) Multiple lists for multiple languages in CampaignMonitor

**My answer**
It seems odd practice to me to create two lists, just because you are separating people with different language. I'm not familiar with CampaignMonitor, but in MailChimp is it by default possible to add subscribers to another language...
But let me try describing a solution for your custom problem:

**Possible solution for two lists**

You can easily overwrite "list-id" when subscribing in the [src/Frontend/Modules/MailMotor/Command/SubscribeHandler.php](
https://github.com/forkcms/forkcms/blob/master/src/Frontend/Modules/Mailmotor/Command/SubscriptionHandler.php#L77)

```php
        $listId = $this->get('fork.settings')->get('Mailmotor', 'list_id');
        if (FRONTEND_LANGUAGE == 'fr') {
           $listId = 'other-id-xxx';
        }

        // Subscribing the user, will dispatch an event
        $this->subscriber->subscribe(
            $subscription->email,
            (string) $subscription->locale,
            $mergeFields,
            $interests,
            false, // your double-optin variable
            $listId
        );

**Other solution for CampaignMonitor**

1. Create one list
2. Use a custom field to separate languages.
<img width="985" alt="schermafbeelding 2016-12-21 om 14 41 04" src="https://cloud.githubusercontent.com/assets/588616/21391360/af48a5e0-c78b-11e6-8d5e-d11bad3a213a.png">
3. Then you can push the language in a merge field (untested).

**Comment by jeroendesloovere** [comment]
Just created the issue #1910,
which will add a setting in the backend to enable/disable double-opt-in.

**Comment by Lennerd320i** [comment]
Hi Jeroen,

thanks for your answers.
The false arguement is working, however additional changes do have to be made (to skip the notice about a confirmation mail, but that's minor, but might be interesting in the issue #1910 that your opened).
The list_id thingy is giving me an internal error, but I have to dig deeper into the why this error is produced.

kr,

Lennerd

**Comment by jeroendesloovere** [comment]
Hi @Lennerd320i,
Thanks for coming back to me.

**Solution for disabling the double-opt-in confirmation message**
I have a solution for your confirmation message, just add the following:
```
$redirectLink .= '&double-opt-in=false';
```
> after this line, https://github.com/forkcms/forkcms/blob/master/src/Frontend/Modules/Mailmotor/Actions/Subscribe.php#L70

Then the message "subscription succesfull" will be shown.

**List id**
Maby it's a bug in the campaign-monitor-bundle.
Can you debug an put the errors here?

**Comment by Lennerd320i** [comment]
Hi @jeroendesloovere ,

I'm going to provide you the error log asap.

kr,

Lennerd

**Comment by Lennerd320i** [comment]
Hi @jeroendesloovere ,

At last had the time to do error checking.
The log at itself  doesn't provide any usefull information, but with the env at debug mode, I got this (I changed the list id in the error below):

Attempted to call an undefined method named "get" of class "Frontend\Modules\Mailmotor\Command\SubscriptionHandler".

500 Internal Server Error - UndefinedMethodException

Stack Trace

in src/Frontend/Modules/Mailmotor/Command/SubscriptionHandler.php at line 76   -
        } catch (NotImplementedException $e) {
        }
        $listId = $this->get('fork.settings')->get('Mailmotor', 'list_id');
        if (FRONTEND_LANGUAGE == 'fr') {
           $listId = 'list-id xxx';
        }

**Comment by jeroendesloovere** [comment]
I'll fix this tomorrow

**Comment by jeroendesloovere** [comment]
hi @Lennerd320i, this is a bug you introduced by using `$this->get('fork.settings')->get('Mailmotor', 'list_id');` in the SubscriptionHandler. `$this->get` doesn't exists.

You have to use the following instead:
```
$listId = $this->modulesSettings->get('Mailmotor', 'list_id');
```

**Comment by Lennerd320i** [comment]
Hi @jeroendesloovere ,

I changed the code you provide before (for the list-id thing), and it's working great now.

If allowed, I do have an offtopic question.
I'm using the subscribe widget, and after entering an address and clicking submit, I keep getting the module subscribe page, where I have to click a second time submit to get my address pushed in the list. Before (old mailmotor version) the subscribe confirmation message followed directly. Can this be altered or was this the purpose?

kr,

Lennerd

**Comment by jeroendesloovere** [comment]
Hi @Lennerd320i 

Thanks for mentioning this!
Indeed, in the past I created a fix for this.

Strange, I thought I fixed this with the following rule:
https://github.com/forkcms/forkcms/blob/master/src/Frontend/Modules/Mailmotor/Actions/Subscribe.php#L97
Can you create an issue for this, so I won't forget to double check.

**Comment by Lennerd320i** [comment]
Hi @jeroendesloovere ,

opened issue #1932.

This issue (1909) for me is completely solved.

tnx and kr,

Lennerd
