### ISSUE TITLE
DateType value converted to UTC results in a wrong date

### ISSUE THREAD

**Issue by jacob-v-dam** [forkcms/forkcms#1911]
## Type

- Critical bug

## Problem description

Saving a date with Symfony Forms would subtract one day from the date due to the UTC date conversion.

## Steps to reproduce

Create a form and add a DateType:
`->add(
			'date',
			DateType::class,
			[
				'required' => true,
				'label'    => 'lbl.Date',
				'input'    => 'datetime',
				'format'   => 'dd-MMMM-yyyy',
				'data'     => $builder->getData()->date
			]
		)`

Store the date in the database and you will notice that it is changed to the day before.

## Expected behavior / Proposed solutions

I would expect that it should keep its current date.

**Comment by ciryk** [comment]
It's not really a whole day. It substracts one hour ( UTC time ) and therefor when you save it as a date it'll strip down the 23:00:00 and therefor not convert it back. But even when it's saved in database on edit it doesn't convert it back to 00:00:00 from the correct day. When you parse them in the datagrid they will get converted back.
