### ISSUE TITLE
The server returned a 400 Bad Request when trying to login after a long period

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#1912]
## Type

- Critical bug

## Problem description

After trying to login to the backend and the page was open since some hours we get the following message

```
Oops! An Error Occurred
The server returned a "400 Bad Request".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
```

## Steps to reproduce

- Open the backend login page.
- Wait for about two hours (I think it is related to the CSRF token expiry)
- Authenticate to the backend.

## Expected behavior / Proposed solutions

We should simply redirected to the login page again.

**Comment by carakas** [comment]
This is on purpose as part of the protection of the backend.
