### ISSUE TITLE
Backend DataGrid: enableSequenceByDragAndDrop() isn't adding "ORDER BY i.sequence ASC" to the query

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1917]
## Type

- Non critical bug

## Problem description

> Backend DataGrid: enableSequenceByDragAndDrop() isn't adding "ORDER BY i.sequence ASC" to the query

## Steps to reproduce

1. Create a DataGrid
2. Add `$this->enableSequenceByDragAndDrop();`

Then witness that the items aren't ordered by sequence.

## Expected behavior / Proposed solutions

> Probably better that `i.sequence` gets `ORDER BY i.sequence ASC` automatically in the `src/Backend/Core/Engine/DataGrid.php` file.

**Comment by carakas** [comment]
won't fix

**Comment by jeroendesloovere** [comment]
:-(
