### ISSUE TITLE
Parsewidget doesn't load widget js/css

### ISSUE THREAD

**Issue by mathiashelin** [forkcms/forkcms#1919]
## Type

- Non critical bug

## Problem description

When using parsewidget, the widget js & css aren't added, so the widget probably won't work correctly.

## Steps to reproduce

Use parsewidget to parse the search form. Autohint & styling won't properly work.

## Expected behavior / Proposed solutions

The js & css should be loaded.

**Comment by carakas** [comment]
won't fix
you should loud it manually
