### ISSUE TITLE
500 error when checkbox "Overwrite" is enabled when editing a theme template

### ISSUE THREAD

**Issue by mathiashelin** [forkcms/forkcms#1920]
## Type

- Critical bug

## Problem description

When you edit a theme template and you enable "overwrite", you get a 500 error.

## Steps to reproduce

Same as above

## Expected behavior / Proposed solutions

The pages using the current template, should be overwritten with the defined positions.

**Comment by carakas** [comment]
might be issue with usertemplates

**Comment by carakas** [comment]
is fixed in usertemplates branch
