### ISSUE TITLE
CKEditor: custom styles don't work anymore

### ISSUE THREAD

**Issue by mathiashelin** [forkcms/forkcms#1922]
## Type

- Non critical bug

## Problem description

If you have css scoped like a.class or h3.class, those styles would appear in the styles dropdown of ckeditor, but they don't appear anymore.

## Steps to reproduce

Add something like `a.custom-class { color: #f00; }` in your theme css. The style won't appear in the styles dropdown of ckeditor while selecting an a-element.

## Expected behavior / Proposed solutions

a.custom-class should appear in the styles dropdown.

**Comment by carakas** [comment]
@GhaziTriki since you updated the editors, could you take a look at this?

**Comment by freshface** [comment]
Indeed, noticed this to.
It loads up q lot of unnecessary styles.

**Comment by jessedobbelaere** [comment]
Yes please, the bootstrap ones should be removed from the dropdown. 
I usually make an editor.scss file where I put these `a.btn` scoped classnames that should popup in there.

**Comment by carakas** [comment]
fixed in #1926
