### ISSUE TITLE
Formbuilder - text field as numeric issue

### ISSUE THREAD

**Issue by Lennerd320i** [forkcms/forkcms#1931]
## Type

- Non critical bug
- Enhancement

## Problem description

When creating e.g. a contact form, and you add a field "phonenumber" with a text field configured to be numeric, you have 2 arrows allowing you to enter -1, -2, ... 

## Steps to reproduce

Create contact form, add text field and configure it to be a numeric value, go to the frontend and you'll notice it immediately.

## Expected behavior / Proposed solutions

No arrows, simply a field where someone enters a number (e.g. phonenumber).

Images to show what I mean:

![image](https://cloud.githubusercontent.com/assets/6659924/21886195/fc0253aa-d8ba-11e6-83f5-39264d859195.png)

![image](https://cloud.githubusercontent.com/assets/6659924/21886220/0e7c1458-d8bb-11e6-81fc-73b339ac96e8.png)

tnx in advance,

Lennerd

**Comment by carakas** [comment]
the arrows are part of html5
a phone number is not a numeric field but a phone field, not sure if we have that in form builder but it that case I would just use text

**Comment by Lennerd320i** [comment]
Ok, tnx @carakas !
