### ISSUE TITLE
Mailmotor - double action submit needed for subscription to list

### ISSUE THREAD

**Issue by Lennerd320i** [forkcms/forkcms#1932]
## Type

- Enhancement
- Feature

## Problem description

When using the subscribe widget, and after entering an address and clicking submit, the module subscribe page shows up. A 2nd submit action is needed to get the address pushed in a list and get the confirmation message.

## Steps to reproduce

Add a mailmotor subscribe widget on e.g. the home page, enter an address, click submit. The mailmotor module subscribe page will show up (with the address you entered before already in place), and you have to click a 2nd time submit to continue.

## Expected behavior / Proposed solutions

within the widget, when clicking submit, push the address directly in the list and show subscribe confirmation/error/... .

**Comment by jeroendesloovere** [comment]
Note to self: I thought I used this line to prevent this.
https://github.com/forkcms/forkcms/blob/master/src/Frontend/Modules/Mailmotor/Actions/Subscribe.php#L97

**Comment by cirykpopeye** [comment]
solved with https://github.com/forkcms/forkcms/pull/1950
