### ISSUE TITLE
Mailmotor: integrate a ping method to check apiKey and ListId

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1948]
## Type

- Enhancement

## Expected behavior / Proposed solutions

> Mailmotor: integrate a ping method to check apiKey and ListId
https://github.com/mailmotor/mailmotor-bundle/issues/8

**Comment by StijnVrolijk** [comment]
This will be fixed in the mailmotor itself https://github.com/mailmotor/mailmotor-bundle/issues/8

**Comment by jeroendesloovere** [comment]
Closing this issue was actually wrong.

I'm reopening this issue again,
because there will need to be a new "ApiKeyAndPageId" Validator class in the Backend Mailmotor module which will indeed must use a new function in the mailmotor-bundle.

**Comment by jeroendesloovere** [comment]
Closing since the PR #2113 to fix this is merged
