### ISSUE TITLE
Tries to load /js/vendors/bootstrap-tagsinput.min.js.map

### ISSUE THREAD

**Issue by freshface** [forkcms/forkcms#1953]
## Type

- Non critical bug

## Problem description

 /js/vendors/bootstrap-tagsinput.min.js tries to load bootstrap-tagsinput.min.js.map thru `//# sourceMappingURL=bootstrap-tagsinput.min.js.map`

## Steps to reproduce

Look at the console in the backend

## Expected behavior / Proposed solutions

It should load /js/vendors/bootstrap-tagsinput.min.js.map (don't know how to access it via yarn)

**Comment by carakas** [comment]
is this still an issue on the 5.0.0-dev branch?

**Comment by freshface** [comment]
No, the master.
Should this be resolved in 5.0.0-dev?

I will try to check it tomorrow.

**Comment by carakas** [comment]
@freshface any update on this?

**Comment by freshface** [comment]
Same issue in the 5.0.0-dev branch.

**Comment by carakas** [comment]
can you create a pr for it to the 5.0.0-dev branch?

**Comment by freshface** [comment]
Well, the js file tries to load the map file?
I dont know how to fetch it thru yarn...

**Comment by StijnVrolijk** [comment]
This will be fixed in Fork 5 and this only happens when your console is open so regular people won't notice.
