### ISSUE TITLE
Console Command for creating thumbnails

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1955]
## Type

- Feature

## Problem description

> Currently we have a tool to create thumbnails. `php tools/create_thumbnails.php Categories Category/Image`. But in fork cms 5 the tools folder will be removed.

## Expected behavior / Proposed solutions

> A Console command for creating these thumbnails.

**Comment by StijnVrolijk** [comment]
This is not the task of Fork but if you want to implement it, go ahead
