### ISSUE TITLE
New Profiles widget: "Register"

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1956]
## Type

- Feature

## Problem description

> Sometimes you need a "Registration" and "Log in" on one page.

## Expected behavior / Proposed solutions

> A widget for "Registration"

**Comment by carakas** [comment]
I would wait with this one until the profiles module has been rewritten to doctrine and symfony forms

**Comment by StijnVrolijk** [comment]
@carakas is busy on rewriting the profiles module

**Comment by jeroendesloovere** [comment]
👍

**Comment by carakas** [comment]
If somebody ever makes this feel free to make a PR for it but for now I don't see a reason to keep an issue open for this
