### ISSUE TITLE
Stylesheetparser: set styles to be used

### ISSUE THREAD

**Issue by freshface** [forkcms/forkcms#1959]
## Type

- Enhancement

## Problem description

The stylesheetparser loads all the style applicable to an element but the user should not see or use all

## Steps to reproduce

Use the styles dropdown on for example a link.

<img width="869" alt="schermafbeelding 2017-01-25 om 20 22 38" src="https://cloud.githubusercontent.com/assets/103913/22305577/528923bc-e33c-11e6-8cbd-23d4a9641cd4.png">

## Expected behavior / Proposed solutions

Load a config file from the theme which classes can be loaded or used.

**Comment by jeroendesloovere** [comment]
@freshface can you create a PR for this?

**Comment by freshface** [comment]
We discussed it is not a fix but a "hacky" solution. /cc  @carakas
