### ISSUE TITLE
Profiles: Password field

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1960]
## Type

- Enhancement

## Problem description

> The Fork CMS `addPassword()` field is missing the correct classes `form-control fork-form-text`

## Steps to reproduce

> When you look at the Profiles "Register action" and Profiles "LoginBox widget", you will see that these get the wrong old classes

**Comment by carakas** [comment]
@jeroendeslovere can you check if this is still an issue in 5.0.0-dev?
