### ISSUE TITLE
Redirect bug in parsewidget

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1965]
## Type

- Non Critical bug

## Problem description

> When adding a form from the FormBuilder module to a page using `parsewidget`, you can't submit the form. That throws an error

## Steps to reproduce

1. Create a form in formbuilder
2. Open up a template, f.e.: `src/Themes/triton/Core/Layout/Templates/Default.html.twig`
3. Add `{{ parsewidget('FormBuilder', 'Form', 1) }}`
4. Visit the website page, fill in the form and click "submit"
=> BAM, error
<img width="1219" alt="schermafbeelding 2017-02-01 om 10 41 47" src="https://cloud.githubusercontent.com/assets/588616/22501897/0bc3bac6-e86b-11e6-92ae-6cc299b79852.png">

## Expected behavior / Proposed solutions

> Fix for this nasty bug

**Comment by carakas** [comment]
changed to non critical, since parsewidget is a hack and should be avoided when possible
