### ISSUE TITLE
Backend Tag input problem

### ISSUE THREAD

**Issue by myspulin** [forkcms/forkcms#1971]
## Type

- Non critical bug

## Problem description

When I try to input Tags to page or blog entity the input does not allow me to input multiple tags. I presume it should work as in this example:

http://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/

Javascript is loaded in the header: bootstrap-tagsinput.min.js, no error on the firebug console.

Could you please check this issue? This behavior is the same also on demo site: http://demo.fork-cms.com

Thanks.

## Steps to reproduce

Login to backend, edit the page, switch to Tags tab and input tags.

## Expected behavior / Proposed solutions

Be allowed to input multiple tags.

**Comment by carakas** [comment]
It works here
<img width="484" alt="screen shot 2017-02-02 at 14 51 36" src="https://cloud.githubusercontent.com/assets/3634654/22551930/2a9f9c2a-e957-11e6-9828-6777cfcd5633.png">
you can separate them with a `,` or by pressing enter

**Comment by myspulin** [comment]
Oh, I see you have to press enter, it did not check the leave event. So close this issue, thanks.
