### ISSUE TITLE
Backend page icon is missing for sub page with "module action"

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1974]
## Type

- Enhancement

## Problem description

<img width="173" alt="schermafbeelding 2017-02-07 om 17 01 56" src="https://cloud.githubusercontent.com/assets/588616/22699225/2f0a0fa8-ed57-11e6-9dc9-1f3b0e8edf84.png">
As you can see in the image above, the leaf icon is missing before the "detail" page".

## Steps to reproduce

1. Click on the page "nieuws"
2. Then create a sub page using "create sub-page".
<img width="269" alt="schermafbeelding 2017-02-07 om 17 03 24" src="https://cloud.githubusercontent.com/assets/588616/22699288/59a0c504-ed57-11e6-9496-842854c22aff.png">
3. The page "detail" is being saved as "use for module action".

## Expected behavior / Proposed solutions

> I expect to see a leaf icon, but instead I see nothing.

**Comment by carakas** [comment]
can you create a pr for that?

**Comment by jeroendesloovere** [comment]
Closing this, because this seems fixed in "fork-cms-5.0.0-dev" branch

**Comment by jeroendesloovere** [comment]
Reopened.
When a page is checked as "module-action", the icon is missing.

<img width="222" alt="schermafbeelding 2017-10-03 om 08 30 44" src="https://user-images.githubusercontent.com/588616/31112666-4e709294-a815-11e7-998b-0470d8829c04.png">
<img width="217" alt="schermafbeelding 2017-10-03 om 08 30 37" src="https://user-images.githubusercontent.com/588616/31112665-4e47ee16-a815-11e7-80b0-09dfcbf0d190.png">

@Katrienvh can I assign this task to you. Seems like an easy fix.
