### ISSUE TITLE
Update Symfony to version 3.x

### ISSUE THREAD

**Issue by carakas** [forkcms/forkcms#1989]
## Type

- Enhancement
- Feature

**Comment by mablae** [comment]
Before moving to Symfony3 it would be great to adopt the basic symfony principles first, 

The `ApplicationRouting` class is legacy leftover` Backend and Frontend should be moved to seperate bundles and then use the `prefix` feature when importing the routes in routing.yml. 

Current way of solving thing does not really make sense.

**Comment by carakas** [comment]
We are in the process of moving things over one step at a time
Routing will be something for fork 6
