### ISSUE TITLE
For the Pages module: `yarn add jstree` and `yarn add jquery.cookie`

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1999]
## Type

- Enhancement

## Problem description

> We want to use `yarn` for the `jstree` in the Backend Pages (& MediaLibrary module). The files from "Pages module" could be replaced by `yarn add jstree` and `yarn add jquery.cookie`. But I was yet unable (lack of time) to get things working, since their are breaking changes in these classes...

## Note

> Address the Pull Request to the "fork-cms-5.0.0-dev" branch

**Comment by jeroendesloovere** [comment]
@jessedobbelaere did you find some time fixing this one?

**Comment by jessedobbelaere** [comment]
Yep looking into it. Not sure if this is an "easy pick" as we're upgrading from jsTree 0.9.9 (2009) to 3.3.4 (2017) :P But can't be that hard to make it working again, right

**Comment by carakas** [comment]
wow, we are way behind :p @jessedobbelaere how is it going?

**Comment by carakas** [comment]
Fixed in the restructure-core branch
