### ISSUE TITLE
Should we add `$this->tpl->assignGlobal('locale', Locale::frontendLanguage());` ?

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#2022]
## Type

- Enhancement

## Problem description

> When building modules with Doctrine and Custom Translation Entities, it is often required to have a locale in the template. So things like `{{ realization.getTranslation(locale).name }}` get possible.

## Expected behavior / Proposed solutions

> If we assign the global variable 'local' `$this->tpl->assignGlobal('locale', Locale::frontendLanguage());`, then each widget/action won't need to have this line of code anymore.

**Comment by carakas** [comment]
the issue comes from only selecting the language in the template
I usually add something on my entity to track the current locale and I use the current translation in the getters on the entity that get the data out of the correct translation

**Comment by StijnVrolijk** [comment]
I agree with @carakas. The entity should know which language it's being used in, this should be defined upon fetching it. I can't image you'd need to use multiple translations of an entity at the same time.

**Comment by jeroendesloovere** [comment]
Ok, I understand.
But can you tell me which class will need to be used to get the entity work in Backend and Frontend?
- `Backend/Language/Locale`
- `Frontend/Language/Locale`

**Comment by carakas** [comment]
The first one in the backend, the second one in the frontend and you should typehint on their common parent

**Comment by jeroendesloovere** [comment]
@carakas can you show me a small example class how you inject Locale?

**Comment by carakas** [comment]
`public function myFunctionThatNeedsTheLocale( \Common\Locale $locale);`

**Comment by jeroendesloovere** [comment]
Ok, so you do need my offered solution:
`$this->tpl->assignGlobal('locale', Locale::frontendLanguage());`

**Comment by carakas** [comment]
No, you can do that in your specific template but without the global if you want but a better solution is to keep track of the current language in your entity and return the correct translation based on that, you set the language in the php so you don't need to care about it in the template

**Comment by jeroendesloovere** [comment]
What about a Twig Extension?

```twig
{{ getLocale() }}    => return current Locale
{{ getLocale(‘EN) }}    => returns EN Locale
```

**Comment by carakas** [comment]
If you need that value object in your template your logic is flawed.
I've yet to see a good example that would warrant having it available in the template
