### ISSUE TITLE
Make it possible to control the amount of items that are being linked with the media library

### ISSUE THREAD

**Issue by carakas** [forkcms/forkcms#2034]
## Type

- Enhancement

## Problem description
At the moment there is no way as a developer to impact the amount of items that the media library can connect

if I just want one item, or 4 or something between 3 and 7 that is not possible at the moment

**Comment by jeroendesloovere** [comment]
👍

**Comment by jeroendesloovere** [comment]
## Possible solution
Adding two new options to the MediaGroupType Should take care of this:
* 'minimum_items' => 3
* 'maximum_items' => 7

<img width="332" alt="schermafbeelding 2017-05-03 om 16 30 23" src="https://cloud.githubusercontent.com/assets/588616/25665640/83033d50-301e-11e7-900c-907c6677398e.png">

## Other bad solution
And not: adding variables to the entity for this, for the reason that, if you have a custom module with 10000 entities and the customer wants this changes, you're screwed a little...

**Comment by carakas** [comment]
I think that is a good solution, maybe then also automagically add a constraint for it
