### ISSUE TITLE
Profiles > Group authentication settings broken

### ISSUE THREAD

**Issue by wouterverstuyf** [forkcms/forkcms#2036]
## Type

- Non critical bug

## Problem description

When adding some groups through the profiles module you can limit the access to pages to these groups. This seems to be broken.
When you go to the authentication tab when editing a page, the selected groups don't get saved. Also they are default visible, and should only become visible when you enable the checkbox "Users most be logged..."

## Steps to reproduce

Go to the demo, add some groups, edit a page, and go to the authentication tab. Try to save some settings...

## Expected behavior / Proposed solutions

The checkboxes must be saved
The checkboxes should only be visible if the checkbox to limit the page access is active

**Comment by freshface** [comment]
Fixed with pr https://github.com/forkcms/forkcms/pull/2037
