### ISSUE TITLE
SpoonDataGrid, false "null" to '' conversion

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#2052]
## Type

- Non critical bug

## Problem description

> When using SpoonDataGrid in the MediaLibrary, I found an unwanted behavior. Giving a `null` to a BackendDataGridFunction, will result in a `''` (= empty string).

![schermafbeelding 2017-06-08 om 09 19 19](https://user-images.githubusercontent.com/588616/26916688-91e47ec8-4c2b-11e7-8d25-1184c7635791.png)

![schermafbeelding 2017-06-08 om 09 17 37](https://user-images.githubusercontent.com/588616/26916660-7bc56d8c-4c2b-11e7-9fbc-86ae0856df43.png)
> You can see the unwanted behavior in black box three and four.

## Expected behavior / Proposed solutions

> `null` should remain `null` and not be converted to `''`.

This behavior is caused on line 1022 in SpoonDataGrid.
`$function['arguments'] = str_replace($record['labels'], $record['values'], $function['arguments']);`

**Comment by carakas** [comment]
Issues with `SpoonLibrary` should be created on the repository of the library

**Comment by jeroendesloovere** [comment]
Ok, I've got a fix, will create a PR for it.
