### ISSUE TITLE
Can't install modules in Fork CMS 5.0.0-dev branch

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#2059]
## Type

- Critical bug

## Problem description

> When clicking `install module`, you are redirected to the page `action rights not given`... 
<img width="673" alt="schermafbeelding 2017-06-08 om 11 31 57" src="https://user-images.githubusercontent.com/588616/26922049-37a8e65c-4c3e-11e7-81bb-2482a14dd74e.png">

## Expected behavior / Proposed solutions

> The module should install.

**Comment by carakas** [comment]
All I can see after reading that final comment is this
![god jeroe](https://user-images.githubusercontent.com/3634654/26922251-dceaf75e-4c3e-11e7-964d-830c13195728.jpg)

**Comment by jonasdekeukelaere** [comment]
Funny bug - https://github.com/forkcms/forkcms/blob/5.0.0-dev/src/Backend/Core/Engine/Url.php#L83 as the url for installing a module is /private/en/extensions/install_module?token=5vq95l7s7n&module=x the code thinks the module is x and not extensions.

**Comment by jonasdekeukelaere** [comment]
I guess changing the module parameter in https://github.com/forkcms/forkcms/blob/5.0.0-dev/src/Backend/Modules/Extensions/Actions/Modules.php#L84 to something else would be the easiest way to solve this bug.

**Comment by carakas** [comment]
It would fix the symptom but not the actual bug, because this didn't used to be a bug.
I'll take a look at this, since if we would leave this in it would be a way people could fool the permission system and thereby accessing things they shouldn't be allowed to

**Comment by jeroendesloovere** [comment]
Isn't this the solution?
Changing `$module = $this->request->get('module');` 
to 
`$module = $this->request->query->get('module');`

**Comment by jeroendesloovere** [comment]
Hmm never mind

**Comment by jonasdekeukelaere** [comment]
No, that's the problem, the actual module (Extensions) is not in the query, but in the url.

**Comment by jeroendesloovere** [comment]
Isn't `$this->request->request->get('module')` the solution then?

**Comment by jonasdekeukelaere** [comment]
Probably `$this->request->attributes->get('module');` might do it.

**Comment by carakas** [comment]
I think that instead of guessing the current implementation should be compared with the old implementation to see where it differs

**Comment by jonasdekeukelaere** [comment]
@carakas https://github.com/forkcms/forkcms/commit/0b0b51aa88260d1ef539e19cceadd81925343eff?diff=split

**Comment by jonasdekeukelaere** [comment]
Is fixed with #2065
