### ISSUE TITLE
Return the API back to Fork CMS 5

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#2061]
## Type
- Feature

## Problem description

API was removed from Fork CMS 5. Is would be great to see it back as it is time saver and help developers access to ready features like user authentication, sending emails, reading data...

From a history point of view, the API of Fork CMS was a main argument for choosing it for customers. Fork CMS makes easy creating web-applications, I don't see it as a simple CMS for creating web sites. It is based on symfony components, modular, have its own framework and very easy to extend. For all those reasons API is one of the vital block of Fork CMS.

**Comment by carakas** [comment]
An example implementation can be found here
https://github.com/forkcms/forkcms/compare/master...justcarakas:rest-api-challange?expand=1

**Comment by StijnVrolijk** [comment]
If possible, I suggest developing this as a seperate module which can be downloaded and installed into a Fork instance if necessary. We shouldn't bloat the core with modules.
