### ISSUE TITLE
Use migrations for installing and updating modules

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#2062]
## Type

- Enhancement

## Problem description

Actually it is very difficult to update a Fork CMS modules database structure once installed. Why not using migrations for that? I know there one challenge, user data can be lost if there is a need of additional data manipulation script.

**Comment by glenncoppens** [comment]
Would be a great feature indeed! 👍 But as you mentioned there are some potential issues to be resolved such as backups of an altered table (or complete db) to provide a secure upgrade process. 
Last year I hacked together a prototype of this migration approach (but it worked). It's in a gist though: https://gist.github.com/glenncoppens/7ba55a242aa2183c2ea987fce8a4b419.

But if I'm not mistaken there's already a Doctrine/Symfony migrations bundle, right?   http://symfony.com/doc/current/bundles/DoctrineMigrationsBundle/index.html

**Comment by carakas** [comment]
The modules that use doctrine entities are already using the functionality that is used in the migrations.

IMHO we can only implement this once all modules are running on symfony/doctrine

**Comment by carakas** [comment]
Going to close this one for now
