### ISSUE TITLE
Change the implementation of Backend/Core/Engine/Csv away from spoon library

### ISSUE THREAD

**Issue by carakas** [forkcms/forkcms#2099]
## Type

- Enhancement

## Problem description

We are using Spoon csv, since spoon is deprecated we should swap it out

## Expected behavior / Proposed solutions
Keep the same external api but let it work on a different library or implementation

**Comment by carakas** [comment]
Suggestions welcome on what we should use instead

**Comment by jonasdekeukelaere** [comment]
Once we upgrade to Symfony 3.2 we can use http://symfony.com/blog/new-in-symfony-3-2-csv-and-yaml-encoders-for-serializer - but in the mean time maybe something like https://packagist.org/packages/league/csv or https://packagist.org/packages/ddeboer/data-import

**Comment by carakas** [comment]
In that case I would wait since fork 5 will ship with symfony 3 because 2.8 will be EOL in the near future so it would be strange to ship with that version

**Comment by carakas** [comment]
https://csv.thephpleague.com
