### ISSUE TITLE
MediaLibrary FrontendHelper needs a parseWidget with a MediaGroup entity

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#2106]
## Type

- Enhancement
- Feature

## Problem description

Currently the FrontendHelper of the MediaLibrary module requires `string $mediaGroupId`.
F.e.: `{{ media_library_widget('Slider', blogArticle.mediaGroup.id) }}`

What if we could use the entity MediaGroup directly...?
F.e.: `{{ media_library_widget('Slider', blogArticle.mediaGroup) }}`

That would save us a query in the FrontendWidget, since we are already passing the entire entity.

## Expected behavior / Proposed solutions

We actually mostly already have the Entity MediaGroup available. So pushing the entire MediaGroup to the widget would save us at least one query.

I think this is currently not possible by using the serialize.
Maby we could create a new FrontenBlockWidget type just for MediaGroup... (so: block, widget and mediaWidget ?)

That would allow us two things
- Reduce a query in the frontend
- Allow us to create a mediaWidget everywhere
<img width="566" alt="schermafbeelding 2017-06-15 om 11 30 15" src="https://user-images.githubusercontent.com/588616/27174955-0c8a75e6-51be-11e7-85cb-32f66dfc435b.png">

This is the code that then should be altered...
```
    public function parseWidget(
        string $mediaWidgetAction,
        string $mediaGroupId,
        string $title = null,
        string $module = null
    ) {
        if ($module === null) {
            $module = 'MediaLibrary';
        }

        // Create new widget instance and return parsed content
        $widget = new FrontendBlockWidget(
            FrontendModel::get('kernel'),
            $module,
            $mediaWidgetAction,
            serialize(
                [
                    'group_id' => $mediaGroupId,
                    'title' => $title,
                ]
            )
        );

        return $this->parseWidgetContent($widget);
    }

    private function parseWidgetContent(FrontendBlockWidget $widget): string
    {
        try {
            $widget->execute();
            return $widget->getContent();
        } catch (\Exception $e) {
            // if we are debugging, we want to see the exception
            if (FrontendModel::getContainer()->getParameter('kernel.debug')) {
                throw $e;
            }
        }
    }
```

**Comment by carakas** [comment]
And why don't you just create a normal widget? and use that one?

**Comment by jeroendesloovere** [comment]
No, creating a normal widget (module_extra) in the database will **never** be an option for custom media groups. Not flexible enough.

Because:
- Now, you can use whatever "widget action" (lightbox, slider, oneImage, ...) you want, anywhere, anytime, multiple times, ... 
- And you can change that "widget action" (lightbox, slider, ...) in the template anytime. Without having to do some database query magic to convert all "actions" to another "actions".
- Will save us from thousands of module extras in the database, which should actually be hidden too!

F.e.:
```
{{ media_library_widget('OneImageRandom', blogArticle.mediaGroup.id) }}
{{ media_library_widget('Slider', blogArticle.mediaGroup.id) }}
{{ media_library_widget('List', blogArticle.mediaGroup.id) }}
```

**Comment by jeroendesloovere** [comment]
Closing this one since the current method with "media id" is just fine...
