### ISSUE TITLE
Mailmotor different list for all languages

### ISSUE THREAD

**Issue by Katrienvh** [forkcms/forkcms#2120]
## Type

- Enhancement

## Problem description

There is no possibility to use other lists for the different languages.

**Comment by jeroendesloovere** [comment]
Seems like something custom... that can easily be changed in the Subscribe/Unsubscribe actions if required.

I think the first question is, who uses different lists for the same client?
We don't.

F.e.: in Mailchimp you have merge tags to show different content to other languages...
Segments to filter customers from different languages...

**Comment by jeroendesloovere** [comment]
The "locale" is being send when subscribing:
https://github.com/forkcms/forkcms/blob/5.0.0-dev/src/Frontend/Modules/Mailmotor/Command/SubscriptionHandler.php#L68

**Comment by jeroendesloovere** [comment]
It seems like CampaignMonitor isn't that advanced as MailChimp, in that way that when subscribing you can't send $language:
https://github.com/mailmotor/campaignmonitor-bundle/blob/master/Gateway/CampaignMonitorSubscriberGateway.php#L113
> If there is something available to input the language while subscribing, feedback is welcome.

MailChimp does has support for a subscriber language:
https://github.com/mailmotor/mailchimp-bundle/blob/master/Gateway/MailChimpSubscriberGateway.php#L188

**Comment by carakas** [comment]
@jeroendesloovere  it was in the module for you updated is, so I disagree that it is just something custom
