### ISSUE TITLE
User language can't be changed.

### ISSUE THREAD

**Issue by bartdc** [forkcms/forkcms#2125]
## Type

- Non critical bug

## Problem description

The language change is not saved.

## Steps to reproduce

http://demo.fork-cms.com/private/en/users/edit?token=gms5hqyb2n&id=1#tabSettings

Choose a language and save the form.

## Expected behavior / Proposed solutions

After saving, the interface language of Fork CMS should be adapted.

**Comment by carakas** [comment]
@bartdc can you create a PR for this?

**Comment by bartdc** [comment]
👍

**Comment by carakas** [comment]
@bartdc any update on this?

**Comment by bartdc** [comment]
@carakas I've tested it locally with version 4.5.4 and everything seems to be fine. On the demo site, the issue remains. So maybe the demo version is lower than 4.5.4?

**Comment by carakas** [comment]
demo site is 4.5.4

**Comment by bartdc** [comment]
Strange.
