### ISSUE TITLE
FAQ test methods have the wrong name

### ISSUE THREAD

**Issue by jonasdekeukelaere** [forkcms/forkcms#2127]
## Type
- Non critical bug

## Problem description
FAQ test methods have the wrong name.
https://github.com/forkcms/forkcms/blob/master/src/Frontend/Modules/Faq/Tests/Actions/DetailTest.php

**Comment by carakas** [comment]
Already fixed in fork 5

**Comment by jonasdekeukelaere** [comment]
👍
