### ISSUE TITLE
Enhancement in formbuilder: required is not visible

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#2130]
## Type

- Enhancement

## Problem description

> When creating formbuilder fields, you can't see anymore which field is required on the overview. In older fork cms versions (probably before bootstrap) you did saw a `*`.

## Expected behavior / Proposed solutions

> Add a `*` to show if its required.
<img width="467" alt="schermafbeelding 2017-07-11 om 11 04 17" src="https://user-images.githubusercontent.com/588616/28061004-47d4f7f0-6629-11e7-95c7-69d77b6bd4e3.png">

**Comment by carakas** [comment]
@jeroendesloovere I changed the milestone to 4.5.5 or 5.0.0 since this can be fixed on master
