### ISSUE TITLE
Feature for MediaLibrary: SEO "prefix" for uploaded files

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#2137]
## Type

- Feature

## Problem description

> When uploading an image to the site, f.e.: "IMG123.jpg". The file will currently be saved to f.e.: `http://www.example.be/src/Frontend/Files/MediaLibrary/01/IMG123.jpg`. But that's not really a nice file url for SEO optimization (google) ... It could be better, if we could prefix it automatically with something custom.

## Expected behavior / Proposed solutions

1. Add the possibility to add a site-wide "prefix" for every language. F.e.: `http://www.example.be/src/Frontend/Files/MediaLibrary/01/my-business-sells-printers-IMG123.jpg`
2. Add the possibility to add a prefix to every upload for a MediaGroupType. F.e.: `http://www.example.be/src/Frontend/Files/MediaLibrary/01/my-business-realization-IMG123.jpg`. Would be nice if this could use the Meta url ... But that seems little over complicated...

## Discussion required

This functionality is for the lazy men. Some people would say - this functionality should be forbidden - you have to rename all files before uploading them... Yes, that's probably true. But how many clients will actually do that? Close to zero.

**Comment by carakas** [comment]
overlaps with https://github.com/forkcms/forkcms/issues/2394
