### ISSUE TITLE
THEME_URL is not set

### ISSUE THREAD

**Issue by freshface** [forkcms/forkcms#2163]
## Type

- Critical bug

## Problem description

THEME_URL is not set because `$this->forkSettings` is `null` https://github.com/forkcms/forkcms/blob/master/src/Common/Core/Twig/BaseTwigTemplate.php#L142

## Steps to reproduce

Do this in your theme template: `{{ dump(THEME_URL) }}`

**Comment by freshface** [comment]
This PR should fix this https://github.com/forkcms/forkcms/pull/2173

**Comment by carakas** [comment]
We only close an issue when a PR has been merged
