### ISSUE TITLE
Theme template is not active after making a change in the template

### ISSUE THREAD

**Issue by Katrienvh** [forkcms/forkcms#2178]
## Type

- Critical bug

## Problem description

Theme template is not active after making a change in it and saving it.

## Steps to reproduce

The problem occurs when you want to edit a theme template. When you scroll down to the panel with the title status you can see that the active checkbox is disabled and not checked, so when you save the template, your template is set non active and you can not change anything anymore on the pages with that template.

**Comment by jonasdekeukelaere** [comment]
Note https://github.com/forkcms/forkcms/blob/master/src/Backend/Modules/Extensions/Actions/EditThemeTemplate.php#L117 -> "Y" should probably be 1
