### ISSUE TITLE
Translation edit in index is broken

### ISSUE THREAD

**Issue by Katrienvh** [forkcms/forkcms#2186]
## Type

- Critical bug

## Problem description

Edit of translation in index is broken, got an ajax error.

## Steps to reproduce

http://demo.forkcms.com/private/en/locale/index?form=filter&form_token=93df333ed5f53a4f9475c2dcb5997f71&application=&module=&type%5B%5D=lbl&language%5B%5D=fr&name=e&value=&search=
Try to change the first translation and the error will appear

`{"code":500,"data":null,"message":"Module not allowed."}`

**Comment by StijnVrolijk** [comment]
To further specify: It only occurs when editing a translation through JS/AJAX. The edit action itself works
