### ISSUE TITLE
screen.css Fork theme not loaded

### ISSUE THREAD

**Issue by jacob-v-dam** [forkcms/forkcms#2188]
## Type
Critical bug

## Problem description
In ealier versions you were able to add a `screen.css` to your theme and this would display theme specific css. In the new version it doesn't load the theme `screen.css` but a global.

## Steps to reproduce

Check version 4.5.4 which loads `screen.css` in the css array, 5.0.1 loads `/src/Frontend/Core/Layout/Css/screen.css`

## Expected behavior / Proposed solutions
I would expect `/src/Frontend/Themes/Fork/Core/Layout/Css/screen.css` instead of `/src/Frontend/Core/Layout/Css/screen.css`

**Comment by carakas** [comment]
You can overwrite this file by placing a file with the same name in the correct location in your theme
