### ISSUE TITLE
Backend / changing labels don't have effect, unless you remove the cache

### ISSUE THREAD

**Issue by wouterverstuyf** [forkcms/forkcms#2192]
## Type

- Non critical bug

## Problem description

Fork V5
Example: changing labels in backend templates don't have any effect, you have to remove the cache before the change is active.
Debug mode is active.

## Steps to reproduce

Put debug mode on
Change a label
Refresh => no result
Clear cache
Label is changed

**Comment by jeroendesloovere** [comment]
This is indeed a bug.

**Comment by jeroendesloovere** [comment]
@jelmersnoeck Can you fix this one pretty please?

**Comment by carakas** [comment]
I'll look into this
