### ISSUE TITLE
MediaGroupTypeDialog controls

### ISSUE THREAD

**Issue by linbis** [forkcms/forkcms#2214]
## Type

Question

## Problem description

File /src/Backend/Modules/MediaGalleries/Js/MediaGalleries.js
If element domID = addMediaGroupTypeDialog not found whether there is a necessity to initialize for MediaGroupTypeDialog controls, if the MediaGroupTypeDialog is not initiated

**Comment by carakas** [comment]
@jeroendesloovere  can you follow this up and ask for clarification if needed?

**Comment by jeroendesloovere** [comment]
Hi @linbis,
can you provide us with a bit more information like how to reproduce?

Thanks in advance.
