### ISSUE TITLE
Pages: "redirect dropdown" is missing the last letter

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#2215]
## Type

- Non critical bug

## Steps to reproduce

In the Pages module, create the following page structure
```
- Home
    - Who we are
        - We are
        - Our promise
```

Then go to the `redirect`-tab and click the "internal link" dropdown.
You will now see that the last letter is missing.

## Expected behavior / Proposed solutions

<img width="723" alt="schermafbeelding 2017-08-30 om 15 04 46" src="https://user-images.githubusercontent.com/588616/29873724-9a726b9a-8d94-11e7-9688-41a12543e3b3.png">

<img width="237" alt="schermafbeelding 2017-08-30 om 15 00 32" src="https://user-images.githubusercontent.com/588616/29873640-4427b63c-8d94-11e7-8e04-66607994561e.png">
> As you can see, the "a" is missing in the "Who we are".

**Comment by carakas** [comment]
I can't reproduce it
