### ISSUE TITLE
Pages: CacheBuilder "has_children" is falsely always true

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#2217]
## Type

- Non critical bug

## Problem description

The cacheBuilder says that every page "has_children", even when they don't have any children.
This bug is probably from a while ago when the Pages CacheBuilder was changed.

**Comment by jeroendesloovere** [comment]
Introduced in this PR: https://github.com/forkcms/forkcms/commit/9f98251e38dfaf8dd087d821ba0cc23733dd1ed4

**Comment by jonasdekeukelaere** [comment]
Not true, it's been introduced when changing Y/N to booleans.
https://github.com/forkcms/forkcms/commit/eeedff6e6905aa0c9408044debbdad1804f85f1b#diff-1a016ff9754b60a5b5a7e3af04e63173R157

Whereas in the query there is still Y/N: https://github.com/forkcms/forkcms/blob/master/src/Backend/Modules/Pages/Engine/Model.php#L739

Should be easy fix, but I don't have time at the moment.

**Comment by jeroendesloovere** [comment]
Does that mean that when we change `Y` and `N` to true and false, it should be fixed?

**Comment by jonasdekeukelaere** [comment]
It's probably a 1/0 in the queries as far as I remember. But yes, that should fix it. It worked before.

**Comment by carakas** [comment]
yea, should be a 1/0 check probably

**Comment by jeroendesloovere** [comment]
I changed the query to `IF(COUNT(p.id) > 0, 1, 0) AS has_children` and it's a not working solution.

**Comment by carakas** [comment]
did you clear the cache?
