### ISSUE TITLE
Pages copy action sets content blocks of from language archived

### ISSUE THREAD

**Issue by Katrienvh** [forkcms/forkcms#2248]
## Type

- Critical bug

## Problem description

When you want to make a copy from the NL website to the FR website, the content blocks of NL get archived.

## Steps to reproduce

`/pages/copy?from=nl&to=fr`

**Comment by carakas** [comment]
Just tried it on the demo, couldn't reproduce it, are you sure you didn't make a typo in the from parameter?

**Comment by carakas** [comment]
Probably a clone issue

**Comment by carakas** [comment]
Sorry, pressed the wrong button :)
