### ISSUE TITLE
Bug in backend theme layout text field

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#2256]
## Type

- Non critical bug

## Steps to reproduce

1. Visit the demo site > Settings > Themes > Templates > Default template OR [click here to take you there](https://demo.fork-cms.com/private/en/extensions/edit_theme_template?token=glzd76xzq2&id=1)
2. In the Layout text field, remove a "]" and save...

![schermafbeelding 2017-09-18 om 11 24 42](https://user-images.githubusercontent.com/588616/30535871-087d3b5a-9c64-11e7-94ad-b33102baf6e4.png)

In Production modus: the "save will be completed succesfully", but the layout syntax will be wrong.
![schermafbeelding 2017-09-18 om 11 25 51](https://user-images.githubusercontent.com/588616/30535927-457814da-9c64-11e7-81c1-dffebbb69801.png)

Bug in Debug modus: you get to see the actual error.
![schermafbeelding 2017-09-18 om 11 22 35](https://user-images.githubusercontent.com/588616/30535878-0d6e4942-9c64-11e7-9e23-74fc45d21c87.png)

## Expected behavior / Proposed solutions

Try/catching the error to show the user a proper error message.

**Comment by penicylline** [comment]
Lets me on it.

**Comment by carakas** [comment]
@penicylline ok, if you have any questions feel free to ask me
