### ISSUE TITLE
Mailmotor module + Google ReCaptcha

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#2260]
## Type

- Feature

## Expected behavior / Proposed solutions

In the mailmotor module:
Double opt-in decreases your conversion rate (because the double-optin mail can go lost into space).
Would be nice if a "Google ReCaptcha" is added to the form, so we can disable double-optin.

**Comment by jeroendesloovere** [comment]
@StijnVrolijk I tagged you, because you created the Google ReCaptcha integration into Fork CMS.
Would it be possible to integrate that in the mailmotor module?

**Comment by StijnVrolijk** [comment]
@jeroendesloovere I'll try to take a look at it in the course of next week

**Comment by soumya-ranjan7** [comment]
Can I give it a try?

**Comment by ohvitorino** [comment]
@soumya-ranjan7 go ahead! If you need any help, just poke us through slack (forkcms.slack.com).

**Comment by soumya-ranjan7** [comment]
@ohvitorino actually I am new to php, could you just tell me in brief as to what I am supposed to do?

**Comment by tijsverkoyen** [comment]
In my personal opinion. I don't think implementing a captcha will increase conversions, it is considered a conversion-killer. Also: in some countries double-opt in is a requirement.
Therefore I wouldn't include this in the core-implementation.

**Comment by jeroendesloovere** [comment]
@tijsverkoyen Ok, closing this one.

**Comment by jeroendesloovere** [comment]
Using the settings double opt-in can be enabled.
