### ISSUE TITLE
Formbuilder adding a textbox

### ISSUE THREAD

**Issue by freshface** [forkcms/forkcms#2266]
## Type

- Non critical bug

## Problem description

By adding a textbox to the form builder the field is by default marked as required but the error message is not loaded in.

## Steps to reproduce

Add a textbox field to a form in the form builder and save it.
This gives no error, only after edit of the textbox and saving it gives an error because the error message is not filled out.

## Expected behavior / Proposed solutions

2 solutions

- Don't  set it required by default
- Or load in the error message

**Comment by carakas** [comment]
I can't reproduce it here
This is what it looks like here when I add a new one
<img width="599" alt="screen shot 2017-10-17 at 17 45 38" src="https://user-images.githubusercontent.com/3634654/31674787-02e79012-b363-11e7-9d1b-571a3a5fa409.png">
