### ISSUE TITLE
Bug: Redirects in Search module

### ISSUE THREAD

**Issue by Diewy** [forkcms/forkcms#2273]
## Type

- Non critical bug

## Problem description

After setting a redirect on a page the user would assume that the content is not accessible anymore. But a truncated version is still visible via a search on that content, which reveals all your (dirty) secrets!

## Steps to reproduce

1. Create content on a page in the backend
![screenshot 2017-09-27 10 23 09](https://user-images.githubusercontent.com/1014380/30903382-e1c1a34a-a36e-11e7-8b97-40b445a5b7ed.png)

2. Set a redirect on the same page
![screenshot 2017-09-27 10 23 18](https://user-images.githubusercontent.com/1014380/30903381-e1bfc93a-a36e-11e7-8f1d-3575f8ddc491.png)

3. Search for the created content in the frontend
![screenshot 2017-09-27 10 22 59](https://user-images.githubusercontent.com/1014380/30903380-e1be80ca-a36e-11e7-84ed-8a159ccfb523.png)

## Expected behavior / Proposed solutions

Exclude redirect pages from search

**Comment by carakas** [comment]
@Diewy thank you for this bugreport, is this something you can fix by creating a PR for it?

**Comment by lex111** [comment]
I would like to try to fix this. What are the recommendations on how to do this?

**Comment by carakas** [comment]
@lex111 Awesome, we have a docker container with php 7.1 and the env variables you need to enable debug. So if you have docker that will be the easy road to get fork running on your machine

The search works with indexes that are created in the backend when adding or editing a page. I think it would be probably the best way to target this bug. By checking if the page is a redirect page and in that case delete any existing indexes and don't add a new one.

If you have more questions feel free to ping me or ask it on the [Fork CMS slack](https://fork-cms.herokuapp.com/)
