### ISSUE TITLE
Layout for three dropdowns isn't the same

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#2294]
## Type

- Enhancement

## Problem description

First dropdown has another layout then the other two.
<img width="591" alt="schermafbeelding 2017-10-06 om 09 52 49" src="https://user-images.githubusercontent.com/588616/31268652-a368af42-aa7d-11e7-81c8-1bc1c52e7c9e.png">

## Steps to reproduce

> Give the dropdowns the same layout.

**Comment by jeroendesloovere** [comment]
@Katrienvh, are you willing to look at this?

**Comment by Katrienvh** [comment]
i will look at this

**Comment by jeroendesloovere** [comment]
@Katrienvh That's great! Thanks in advance.
