### ISSUE TITLE
Search results on words less than 4 characters

### ISSUE THREAD

**Issue by wouterverstuyf** [forkcms/forkcms#2316]
## Type

- Enhancement

## Problem description

If you have a page, product, blog... with (for example) the word "box", the item is not found by the search engine. The problem, like @carakas said, is that mysql ignores words with 3 or less characters.

## Steps to reproduce

Create a blog post with the title "box". Search on it...

## Expected behavior / Proposed solutions

It should be great to have results for limited characters in search strings.

**Comment by carakas** [comment]
since it is new functionality, can you base your branch on `5.1.0-dev`
