### ISSUE TITLE
Copy Location widgets when copy pages to other languages

### ISSUE THREAD

**Issue by Katrienvh** [forkcms/forkcms#2324]
## Type

- Enhancement

## Problem description

if you run /pages/copy?from=en&to=nl for example, it will copy alle the pages with content, content blocks, ... 
It should be very nice if the location widgets would also be copied. I think most of the time u use the location widget the location won't change when the language of the location changes.

**Comment by jeroendesloovere** [comment]
I will wait until #2349 (Location entity) and #2422 (copy modules) are merged to fix this one.
