### ISSUE TITLE
Social Media Links module

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#2350]
## Type

- Feature

## Problem description

Wouldn't it be nice if there was a module that allowed you to add "links" to "social media channels".
Almost every website has links to "Facebook", "Twitter",  "Instagram",  ... But if the link changes or a (new) social media channel needs to be added/removed that is something that a developer needs to adjust...

Creating a module that allows you to add a "social media link" solves that problem.

Entity `SocialMediaLink`:
* SocialMediaType $type - All possible bootstrap social media icons; "facebook", "instagram", ...
* string $url - External link to that channel

## Result

A widget that automatically shows the icons.
<img width="122" alt="schermafbeelding 2017-11-06 om 14 35 27" src="https://user-images.githubusercontent.com/588616/32443574-c6066da6-c2ff-11e7-96ab-68c4936eaa62.png">

**Comment by wouterverstuyf** [comment]
Good idea!
Is a seperate module required for this? I think the location module could be upgraded with this.

I've created this feature in (a copy of) the location module, and added a checkbox to set a location as a "main contact" (= the company main address and other info). 
The widgets "sociallinks" get the social media links from the main contact and put them with the correct icons.

![schermafbeelding 2017-11-22 om 14 08 55](https://user-images.githubusercontent.com/4540274/33129022-e12ae04e-cf8e-11e7-8077-f11456ee51c3.png)

**Comment by jeroendesloovere** [comment]
My initial thought is/was to create a separate module for this...

But if you want we can create an association between "SocialMediaLinks" and "Locations" module, that can even improve the way you currently work in the location module that you display.

Example:
1 SocialMediaLink:
- Social media channel (dropdown); facebook, twitter, linkedin, ...
- URL

1 Location:
- Title
- ...
- Collection of SocialMediaLinks, "+ add social media link" --> choose the existing SocialMediaLinks from a dropdown.

**Comment by jeroendesloovere** [comment]
But like I said, i suggest a separate module.

**Comment by jacob-v-dam** [comment]
I've created a module which enables a user to set the credentials like @wouterverstuyf. But you can add a formbuilder item which creates custom widgets which show a form. Like:

![image](https://user-images.githubusercontent.com/310526/33727019-1262d416-db77-11e7-94c2-b3ed74341113.png)

**Comment by carakas** [comment]
that module looks nice :)

**Comment by wouterverstuyf** [comment]
Another handy feature to make it complete, is the possibility to add opening hours to a contact, and display them as a widget. I'm testing this now:

![schermafbeelding 2017-12-11 om 10 08 08](https://user-images.githubusercontent.com/4540274/33823427-669fd4d4-de5b-11e7-8633-00d52986efe3.png)

![schermafbeelding 2017-12-11 om 10 09 55](https://user-images.githubusercontent.com/4540274/33823444-7942cea2-de5b-11e7-9991-01ed8012deb9.png)

**Comment by jacob-v-dam** [comment]
Well we could extend this module with that feature.

**Comment by carakas** [comment]
we could, you can always create a PR for it and we can take a look then if it would be a good extension. It would be even nicer if you used symfony form and doctrine. We are currently working in the 6.0.0-dev branch to switch everything internally to doctrine.

**Comment by jacob-v-dam** [comment]
My module is fully doctrine, In created a repository:
https://github.com/jacob-van-dam-ict/fork-cms-contact

**Comment by carakas** [comment]
I would do some things slightly different but it certainly looks like a good start. From what I can see you can only have one location now. The current location module can have more than one location, but I could be wrong.
