### ISSUE TITLE
Installer 6.0.0-dev

### ISSUE THREAD

**Issue by jonasdekeukelaere** [forkcms/forkcms#2370]
## Type
- Critical bug

## Problem description
When installing Fork in the 6.0.0-dev branch, something goes wrong with the cache clearing. See https://d1ro8r1rbfn3jf.cloudfront.net/ms_159376/zN3pGEI4WjKd5WG81DM6UOcuqZR20Y/You%2Bhave%2Brequested%2Ba%2Bnon-existent%2Bservice%2B%2522cache.search%2522.%2B%2528500%2BInternal%2BServer%2BError%2529%2B2017-11-28%2B11-57-20.png?Expires=1511959356&Signature=iAyfl1xiNFKGup6w2NuCpxskWnkIbF70tsJ3N4IgzHwOJJg-wgzZj15PQxAEkj6SkVCNyH3VX~1sVJ60gC8g98zhu5ogfyPXyiUdQnY4gBa9kJxAd8qoV4tQsY1v5Ipz9eOGHL8TB0fqNgrbirVZLgtbM4hGBENFciHDyiXfx8mX6uBPjFnp4Wf5tCOokWiN5Od5GTkf3Xlztkdvdu5OayiB~izL6gFkYVs67QluzcUgPex~6~k7Z5IFXVgjQugz6ZJXvwQ8SPkYZZEu6Yo9f1luxHiYoCaUztf4JhTURNxiKCqmRvD0ewTZXmbGzqZtsgqxfYRqi0o1Z75ZY6SNAw__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA

## Steps to reproduce
Install fork (with example data I think)

## Expected behavior / Proposed solutions
The installer to work.

**Comment by carakas** [comment]
on it

**Comment by carakas** [comment]
fixed in https://github.com/forkcms/forkcms/commit/7655189efff17486bd54cd40eea9e19c6c5a3c27
