### ISSUE TITLE
ImageType and FileType don't work in Fork CMS 5.0.7

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#2373]
## Type

- Non critical bug

## Problem description

Since the symfony/symfony update from v3.3.6 to 3.3.13, in Fork CMS 5.0.7, ImageType (and probably FileType) aren't working anymore. When saving, the error `Compound forms expect an array or NULL on submission.` is thrown.

**Comment by jeroendesloovere** [comment]
Seems like `stdClass` can't be used anymore? Only array and null.
But don't how how to fix it for the moment.

**Comment by carakas** [comment]
the transformer should take care of switching the type
Unless symfony broke some things within a minor version it would seem strange to me that that is the issue

**Comment by carakas** [comment]
@jeroendesloovere was this fixed with #2374  ?

**Comment by jeroendesloovere** [comment]
@carakas no.

**Comment by carakas** [comment]
@jeroendesloovere can you send me an example on slack of code that triggers this error

**Comment by jeroendesloovere** [comment]
@carakas every module that has ImageType and FileType...
Any news on a fix?

**Comment by cirykpopeye** [comment]
I'm having the same issue with my modules using the ImageType from Fork. Form errors are throwing 'This value is not valid' for the image field.

**Comment by carakas** [comment]
I was on vacation for 2 weeks :) I'll probably have time for it tomorrow and I'll release 5.0.8 afterwards
