### ISSUE TITLE
UPGRADE_5.0.md needs some improvements

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#2396]
## Type

- Enhancement

## Problem description

A piece of information in `UPGRADE_5.0.md` is wrong.

## Steps to reproduce

- https://github.com/forkcms/forkcms/blob/master/UPGRADE_5.0.md#backendcoreenginebaseconfig-getpossibleajaxactions-and-backendcoreenginebaseconfig-getpossibleactions-are-removed : `getPossibleAJAXActions` and `getPossibleActions` are not removed from `Config.php`
- https://github.com/forkcms/forkcms/blob/master/UPGRADE_5.0.md#path_www : `PATH_WWW` is not removed

**Comment by carakas** [comment]
fixed
