### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by carakas** [forkcms/forkcms#2403]
## Type

- Feature

## Problem description

We should switch from bootstrap 3 to bootstrap 4

- [x] backend
- [ ] fork theme

**Comment by jeroendesloovere** [comment]
Migration guide: https://v4-alpha.getbootstrap.com/migration/

**Comment by ohvitorino** [comment]
Latest migration guide
https://getbootstrap.com/docs/4.0/migration/

**Comment by GhaziTriki** [comment]
It would also be nice to move to Font awesome 5: `"@fortawesome/fontawesome-free": "^5.2.0",`
