### ISSUE TITLE
CKEditor + Media Library movies

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#2410]
## Type

- Feature

## Problem description

Since Fork CMS 5.1.0, the CKFinder has been dropped in favor of using our MediaLibrary in CKEditor.
It would be nice to add movies from the media library, right into the CKEditor.

## Solutions, anybody?

Does anybody has suggestions on how we can achieve this?

**Comment by ohvitorino** [comment]
I had a look into it and I think we can manipulate the `oembed` plugin and add a button to open a dialog like the one used to include links and images with the media gallery.
