### ISSUE TITLE
Bug translations inline edit

### ISSUE THREAD

**Issue by Katrienvh** [forkcms/forkcms#2458]
## Type
- Non critical bug

## Problem description

The whole page start to flicker cause when you try to edit a multiline label only on some window sizes

## Steps to reproduce
https://demo.fork-cms.com/private/en/locale/index?form=filter&form_token=1668c662eb0a2c81b49620f40581b825&application=&module=&type%5B%5D=lbl&type%5B%5D=msg&language%5B%5D=nl&language%5B%5D=en&language%5B%5D=fr&name=e&value=&search=
Go to the label: AddThemeTemplate and try to edit the dutch one. My current window width is 1180px

**Comment by carakas** [comment]
Can only reproduce this in chrome, not in firefox
