### ISSUE TITLE
Improve UserTemplates

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#2460]
## Type

- Enhancement

## Problem description

UserTemplates are a great step forward...
But currently they are not advanced enough...

Example:
* You create a properly tested user template
* Then you decide to integrate it a lot across multiple pages in your website
* Until... your boss comes along and says: "I'd like to change some things in the structure"
...

That is the problem, you are screwed. Because you:
* Now have to change the UserTemplate template (and test it thoroughly again)
* Visit the pages module and every page where you had connected this user template
* Remove the user template
* Add the user template again (if there are images, upload them all over again)

That is so time consuming...
We can do better, I'm sure of this!

## Expected behavior / Proposed solutions

* Save fields to database so they are decoupled from the template
* Compile user template (.html.twig) with these variables
* If template changes, the user template should be re-compiled

**Comment by carakas** [comment]
won't fix for now
