### ISSUE TITLE
Integrate new Google tracking code

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#2482]
## Type

- Enhancement

## Problem description

The Google tracking code has changed to:
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-XXXXXXX-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-XXXXXXX-1');
</script>
```

## Expected behavior / Proposed solutions

Integrate new tracking code in Fork CMS.

**Comment by carakas** [comment]
isn't this just a different way of using it, namely the tag manager?

**Comment by jeroendesloovere** [comment]
Well, that is the new default!

**Comment by jeroendesloovere** [comment]
More information: https://support.google.com/analytics/topic/1008079?visit_id=1-636547334202610643-965771924&rd=1

**Comment by carakas** [comment]
if you would want to change it it has to be in the 6 because everything that hooks in on google analytics would break otherwise. Please keep semver in mind when assigning milestones

**Comment by carakas** [comment]
I don't see anything about deprecating this here https://support.google.com/analytics/answer/7476135?hl=nl&ref_topic=7557054

**Comment by jeroendesloovere** [comment]
When creating a new Google Analytics website now, you get that new tag manager code instead of the analytics code. So I am presuming they want everybody to use that tag manager code. Which is actually more powerful.

**Comment by carakas** [comment]
you can still choose, I would leave it like it is for now
