### ISSUE TITLE
content-security-policy

### ISSUE THREAD

**Issue by carakas** [forkcms/forkcms#2484]
## Type

- Enhancement
## Problem description

Should we implement something like https://scotthelme.co.uk/content-security-policy-an-introduction ?

We could use the addJs to work with the nonce

**Comment by jeroendesloovere** [comment]
* Looking at addJs seems like a great idea.
* We can also use `Content-Security-Policy-Report-Only:` if we are in "dev" environment.

**Comment by carakas** [comment]
I wouldn't make a difference between dev and prod because that might be confusing for people who don't know what is happening, and then you get things like: it works on my machine :p

**Comment by carakas** [comment]
too complicated for now since people can also add scripts in the backend and just add one in the template
