### ISSUE TITLE
Error 404 if no image loaded for home page, only background

### ISSUE THREAD

**Issue by Sellato** [forkcms/forkcms#2490]
## Type

- Non critical bug

## Problem description

Error 404 if no image loaded for home page
missing file - /src/Frontend/Files/Pages/images/source/1518760782.jpg

## Steps to reproduce

Use "Dev tools" Ctrl+Shift+I in browser to see the 404 error.

**Comment by carakas** [comment]
@Sellato 
can you give us a little more info on the options you used during the install?
Did you ask for demo content?
Is the error on the same device as you did the install?
Are there files with different names there?

**Comment by Sellato** [comment]
@carakas 

1. I use clear install, without demo data.
2. First time I use a picture, but then remove it and get an error 404
3. Error 403 if Blog without picture, only background - You don't have permission to access src/Frontend/Files/Pages/images/source/
4. Device the same
5. Files the same
6. I clearing the cache :)

My demo site is https://teslapunk.crafterspark.com

Screenshots:

background only. Error 404 present - https://yadi.sk/i/yz6Latr43SmSVA 

picture as background. Without any errors - https://yadi.sk/i/G_t-2dro3SmSjN 

Regards.

**Comment by carakas** [comment]
Thanks, something seems to be going wrong indeed
