### ISSUE TITLE
"Go TOP" button. Is it possible to add to ForkCMS ?

### ISSUE THREAD

**Issue by Sellato** [forkcms/forkcms#2495]
## Type
- Enhancement
- Feature

## Problem description

It would be great to add "Go Top" button.

**Comment by StijnVrolijk** [comment]
@Sellato Do you mean in the backend or frontend? 
The frontend just has a basic theme to act as a base on which to build so I wouldn't add it there.
The backend doesn't really contain long pages so a 'Go top' buttons seems rather useless there

**Comment by Sellato** [comment]
@StijnVrolijk 
1. To frontend
2. If you think in "basic theme" no way for "Go top" button, can you give solution for me and close the issue  :)

**Comment by StijnVrolijk** [comment]
@Sellato https://codepen.io/rdallaire/pen/apoyx
