### ISSUE TITLE
Module Blog. If comments NOT allowed, in frontend replace "Be the first to comment" with "Comments not allowed"

### ISSUE THREAD

**Issue by Sellato** [forkcms/forkcms#2496]
## Type
- Non critical bug
## Problem description
Module Blog. If in admin panel for carent Article comments NOT allowed, in frontend present the string "Be the first to comment"
## Steps to reproduce
Screenshots:
admin panel - https://yadi.sk/i/gNuz2elX3SsX8A
frontend - https://yadi.sk/i/cK2fccO73SsXKK

## Expected behavior / Proposed solutions
If comments not allowed, replace string "Be the first to comment" with "Comments not allowed"

**Comment by carakas** [comment]
I would just remove the entire block

**Comment by carakas** [comment]
btw @Sellato are you in the possibility to create some pr's for the issues that you are creating?

**Comment by Sellato** [comment]
@carakas sorry, I have no enough experience in ForkCMS :(

**Comment by carakas** [comment]
You can always try :) the template stuff is just twig from symfony
