### ISSUE TITLE
Improve Page content Module/Widget Title/Description

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#2509]
## Type

- Enhancement

## Problem description

If you look at the following screenshot (from https://demo.fork-cms.com/private).
You notice duplicate content.

<img width="659" alt="schermafbeelding 2018-03-07 om 14 23 53" src="https://user-images.githubusercontent.com/588616/37094608-a89fde96-2213-11e8-9a16-59e90559fe3c.png">

## Expected behavior / Proposed solutions

It would be better if we simplify things.
I have edited the template, this is what I suggest:

<img width="661" alt="schermafbeelding 2018-03-07 om 14 25 22" src="https://user-images.githubusercontent.com/588616/37094641-c63ac9b6-2213-11e8-942c-7392eda283b4.png">
> Which actually represents the "dropdown" "sequence" (first select widget, then select blog, then select ...)

**Comment by jeroendesloovere** [comment]
@forkcms/core-contributors What do you guys think?

```
Editor
Module > ModuleName (> xxx)
Widget > ModuleName > xxx
UserTemplate
```

**Comment by WouterSioen** [comment]
This indeed looks better.

**Comment by jeroendesloovere** [comment]
Closing this one because it is merged.
