### ISSUE TITLE
GDPR: lock user logins when a data leak occurred

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#2512]
## Type

- Feature

## Problem description

GDPR is almost there.
It is our task to provide solutions in Fork CMS for when a data leak has occurred.

1. User sessions must be deleted.

2. Users must reset their password.
When a data leak has occurred (database credentials leaked, ...),
it must be possible to prevent users from logging in anymore...
Until they have reset their password, using a received "reset your password" mail.

**Comment by StijnVrolijk** [comment]
That doesn't sound like anything Fork needs to worry about. I'm sure @tijsverkoyen can elaborate on that.

Other than that: that feature sounds super dangerous for 'regular' users

**Comment by jeroendesloovere** [comment]
@StijnVrolijk  

When somebody had access to database credentials.
He can do whatever he wants, including pasting in $password and $passwordKey, from his local Fork CMS. Et voila, a data breach has occured. Because he now has access to fork cms.

That is why every password must be reset if such a data leak has occured.
To prevent the hacker accessing the CMS.

**Comment by tijsverkoyen** [comment]
Most of the things that need to be done to be compliant with GDPR are the responsibility of the developer. In the core there are some multiple things that can be implemented, but I am trying to compose of list of things that have to be changed, and stuff that are nice to have.

Jeroen's request is something we can implement, I will add it to my list.

**Comment by tijsverkoyen** [comment]
@jeroendesloovere when someone has access to the database you have bigger issues ;-)

**Comment by jeroendesloovere** [comment]
I know,

but the feature I suggest is for afterwards, to (try) to tighten your CMS again.

**Comment by carakas** [comment]
I think

**Comment by tijsverkoyen** [comment]
At this point I don't think there is a good reason to implement this. If you are ever in the situation this happens I would advise to reset all the passwords thru the database.
