### ISSUE TITLE
Formbuilder: Method send mail is not working

### ISSUE THREAD

**Issue by bramds** [forkcms/forkcms#2533]
## Type

- Non critical bug

## Problem description

> When turning method 'Send mail' on  in the formbuilder, it breaks the frontend form on submit.

Type error: Argument 3 passed to Frontend\Modules\FormBuilder\Event\FormBuilderSubmittedEvent::__construct() must be of the type integer, null given

## Steps to reproduce

> Put method 'Send mail' in backend en submit form in frontend

**Comment by carakas** [comment]
Did the fix I sent you work? If so, can you create a PR for it?
