### ISSUE TITLE
Form dropdown parse bug

### ISSUE THREAD

**Issue by Ktulhu** [forkcms/forkcms#2540]
## Type

- Critical bug

## Problem description

Dropdowns with multiple selection generate wrong name attribute, because each call to dropdown parse method add additional [] to name.

## Steps to reproduce

// create the form
        $this->form = new FrontendForm('test', null, null, 'test');
// add dropdown
        $this->form->addDropdown('test', [
          'one', 'two', 'three'
        ], null, true);

will make

`<select id="test" name="test[][]" class="form-control fork-form-select fork-form-select-multiple" multiple="multiple">
 <option value="0">one</option>
 <option value="1">two</option>
 <option value="2">three</option>
  </select>`

## Expected behavior / Proposed solutions

rewrite parse method of dropdown
461 if(!$this->single) $this->attributes['name'] .= '[]';
to check if braces already added

**Comment by carakas** [comment]
Fix for this is already in the pipeline, this will be fixed with the next fork version when we include version 3.0.3 of spoon/library
you can always update it yourself in the meantime
