### ISSUE TITLE
404 instead of admin after module installation

### ISSUE THREAD

**Issue by manuxi** [forkcms/forkcms#2552]
Yesterday I've installed forkcms on my dev environment (Windows 10 with devilbox, using php 7.26, apache 2.4, mysql 5.6). I cloed it with git and made a composer update. 
After opening http://fork.project.loc/install I got an error:

Doctrine\DBAL\Exception\ConnectionException » Main...
An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory...

...until I edited the parameters_install.yml and added the mysql credentials (devilbox calls for host 127.0.0.1 instead of localhost, maybe this is the issue?). Then the installation and everything else seemed to work fine.

I played areound a little bit since I'm new to forkcms. I've installed another theme (bootstrap3) which went ok. Then I tried to install a module from the list of not-installed modules in the admin area (module Location). Something went wrong - there was no "/admin" in the url anymore and it looked like something bad happens. Now I'm not able to access /admin (nor /install) anymore - I get a 404 whatever I try. 

I've cleared the cache several times.

What can I do now? Does someone has a suggestion? Did I do something wrong? Do I have to install everything again? What would I do if I got this weird 404 on production?

**Comment by carakas** [comment]
have you tried `/private` ?
Cause we don't have `/admin`

**Comment by manuxi** [comment]
yes, I found out after a while that its not admin...
Had to reinstall it several times...:( seems that it does not work with devilbox/windows...

**Comment by carakas** [comment]
Fork has been used on windows before, it might be an issue with devilbox but I'm not sure about that
