### ISSUE TITLE
Unwanted effect of "Remove obsolete media" in Media Library

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#2553]
## Type

- Non critical bug

## Problem description

Adding images in CKEditor adds an unwanted behavior.

Since a specific fork cms version, you can now add media library images into ckeditor.
But we have a button "remove obsolete media" in the media library module,
which deletes all MediaItem entities which do not have a "connection".
And since mediaItems (images, movies, ...) do not have any connection between ckeditor, ...
They are removed...

**Comment by ohvitorino** [comment]
@jeroendesloovere do you have any idea on how to fix this?

**Comment by jeroendesloovere** [comment]
**Temporary solution**:
- Hide the "Remove obsolete media" button
- Disable the `media_library:delete:items` command

**Cleanest solution (but the most advanced one):**
- Shift to a modern way of working: Replace CKEditor by a "block system", where you can choose between text, textarea (= ckeditor, but without images/video/iframe/...), one image, media gallery, iframe, userTemplate, ...

... Can't seem to come up with something in between that is fairly easy ...
I know a solution that would be hard to do... On every editor save, notify the media library that an image/video is being used... The hard thing to fix are then the "archived pages" & "hidden page block"

**Comment by jeroendesloovere** [comment]
@StijnVrolijk Good suggestion, but unfortunately that won't do it. Since you can have custom modules that have a $publishOn \DateTime field...

**Comment by StijnVrolijk** [comment]
Ahh yes, good point

**Comment by jeroendesloovere** [comment]
I have a "fairly good solution" for this "nasty problem".

Steps to create the fix:
* We create internal search queries for all modules (pages, content blocks, blog, ...). I would call them EditorMediaItemScrapers. Which will be executed by using a new service called `EditorMediaGroupMediaItemManager`.
    * EditorScraperManager->addProvider(ModuleEditorMediaItemScraperInterface $provider);
        * `PagesEditorMediaItemScraper`
        * `ContentBlocksEditorMediaItemScraper`
        * `BlogEditorMediaItemScraper`
        * ...
    * These providers will create one "MediaGroup" per provider and connects all the "used" MediaItem entities to this MediaGroup.
* When clicking "Remove obsolete media", the service is being activated, the "number of connections" is being updated and then we can remove the media items that are not used anymore.

Bingo. Problem solved.

**Comment by carakas** [comment]
Bingo? this is an even bigger mess. Just add a warning of what the consequences might be and remove it in Fork 6
the moment somebody doesn't know about this service to clean up the mess it won't work anymore.

**Comment by carakas** [comment]
We'll just remove this since it is too dangerous and now also gets in the way of the layout because of the long label XD
