### ISSUE TITLE
Formbuilder: Missing translations

### ISSUE THREAD

**Issue by Katrienvh** [forkcms/forkcms#2561]
## Type

- Critical bug

## Problem description

I do not know if its a real bug but it's the second time I see that all the translations are missing in the Formbuilder

## Steps to reproduce

https://demo.fork-cms.com/private/en/form_builder/index

**Comment by jeroendesloovere** [comment]
![schermafbeelding 2018-06-14 om 14 34 53](https://user-images.githubusercontent.com/588616/41412390-2474b928-6fe0-11e8-8d27-7e54bbf55924.png)

**Comment by jeroendesloovere** [comment]
Fixed by #2576
