### ISSUE TITLE
Media library: add folder in add media empty option

### ISSUE THREAD

**Issue by Katrienvh** [forkcms/forkcms#2564]
## Type

- Enhancement

## Problem description

In the modal add folder, you can select the destination folder. If you want to change the destination folder, you can see there is an empty option. 

I tried it and it works, like you folder is added in the root, but a lot of user will not understand that the empty item == the root folder.

## Expected behavior / Proposed solutions

I suggest to just give it a name

**Comment by jeroendesloovere** [comment]
@Katrienvh Which name do you suggest?

**Comment by Katrienvh** [comment]
@jeroendesloovere root

**Comment by jeroendesloovere** [comment]
@Katrienvh, ok.

Are you capable of creating a PR for this?
