### ISSUE TITLE
New profile gets instant login

### ISSUE THREAD

**Issue by bramds** [forkcms/forkcms#2570]
## Type

- Feature

## Problem description

When a new user registers through the profiles menu ( frontend ), the new user gets inserted into the DB with status 'inactive'.  However the new user is also logged in and can already see the restricted content. ( even before the activation link in the activation mail is clicked ).
It is not logical that an user with status 'inactive' can see the restricted content. ( no login on registration )

## Expected behavior / Proposed solutions

Removing the instant login of new registered users.

**Comment by jeroendesloovere** [comment]
@bramds Can you confirm that "inactive" users can access profile pages, except the "Dashboard" page?

**Comment by Senjutsumo** [comment]
@jeroendesloovere I can confirm that "inactive" users are logged in after a fresh registration without clicking any activation link and I can see restricted content. 
When I log out and want to log back in it gives the login failed error.
