### ISSUE TITLE
FormBuilder; can not add time field

### ISSUE THREAD

**Issue by freshface** [forkcms/forkcms#2575]
## Type

- Non critical bug

## Problem description

If you add a datetime field an chose time as type you can not add it

**Comment by freshface** [comment]
There are a couple of solutions.

Problem; if you add a datetime field of type **time** it gets a validation for time by default but you can not provide an error message. (Like when you validate for e-mail or number)
The SaveField.php then needs an error message. But the error message is missing (there is no option to fill it out).

Possible solutions:

- Do not validate for time by default
- Add a specific validation (ps, if you choose date there is no default validation rule provided)
- Do not add a validation for time format.

Hope this is clear.

**Comment by carakas** [comment]
I think it is just the validation that is missing in the template or the js
