### ISSUE TITLE
Theme translations

### ISSUE THREAD

**Issue by Wimmie13** [forkcms/forkcms#2591]
## Type

-  Enhancement

## Problem description

Themes dont have a translations installer. If you have a translation that is not for a single module it must be manualy inserted into the database.

##  Proposed solutions

A locale.xml for the theme so it can install site wide translations or add translations to the info.xml of the theme

**Comment by carakas** [comment]
This can be done easely by adding something to `\Backend\Modules\Extensions\Engine\Model::installTheme` that installs the translations if the locale.xml file is present in the root with `Backend\Modules\Locale\Engine::importXML`
