### ISSUE TITLE
Using --classmap-authoritative option for composer fails loading some Twig classes

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#2610]
## Type

- Critical bug (Docker)

## Problem description

Using `--classmap-authoritative` option for composer fails loading Twig classes that contains `Test` word.

## Steps to reproduce

Run composer on ForkCMS using `--classmap-authoritative` option.

## Expected behavior / Proposed solutions

No missing classes from the generated autoload.

**Comment by carakas** [comment]
This seems to be a twig issue and not a fork issue as it is a twig class calling a different twig class and not finding it. Probably best to create an issue for this on the twig repository

**Comment by GhaziTriki** [comment]
Done here https://github.com/twigphp/Twig/issues/2732
