### ISSUE TITLE
`ContentBlocks` is using old events defined in config.xml

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#2611]
## Type

- Enhancement

## Problem description

`ContentBlocks` is using old events defined in config.xml while it should use Symfony events.

**Comment by carakas** [comment]
the old events have been thrown out a while ago, the events that are listed there are symfony events it is just in the same element.
When we had both there was a thing saying it were symfony events but since we only have symfony events that isn't needed

**Comment by GhaziTriki** [comment]
Shouldn't be a good idea to update other modules config.xml with their events?

**Comment by carakas** [comment]
They don't have the events at the moment since they are still running on old code.
When they get those events back it will be readded to the info.xml
