### ISSUE TITLE
gulpfile.js don't work on gulp 4.x. Command "gulp.start" removed from gulp 4.x 

### ISSUE THREAD

**Issue by Sellato** [forkcms/forkcms#2622]
Hi there!

**gulpfile.js** don't work on **gulp 4.x** with error "gulp.start" is not a command . Command "**gulp.start**" removed from **gulp 4.x** 

- Non critical bug

## Problem description
Since gulp become a version 4.x command "gulp.start" is removed, and the file gulpfile.js don't start.
On **gulp 3.9.1** all is OK.

## Steps to reproduce

Update gulp to latest and try to start the "gulpfile.js"

## Expected behavior / Proposed solutions

Need to replace "gulp.start" to another one.

**Comment by StijnVrolijk** [comment]
This is a non-issue because we require gulp 3.9.1 in the package.json.

It's not the CMS's fault if you don't use the tools it requires ;)

**Comment by Sellato** [comment]
You are right :)
But the future comes here...
Someone like I install the latest gulp, and got a crash. Maybe the better way is replace gulp.start in gulpfile.js  and catch the future ;)

**Comment by carakas** [comment]
@Sellato If you know of a way to make it work in 3.9 and 4 I would be grateful if you can make a PR

**Comment by StijnVrolijk** [comment]
Or better yet, create a PR which updates gulp to ^4 and make the gulpfile work in 4 :)
