### ISSUE TITLE
Application install - database password is required

### ISSUE THREAD

**Issue by myspulin** [forkcms/forkcms#2623]
## Type

- Enhancement
 
## Problem description

When install application in step 4 database password is required. When I have user "root" without password on my local dev environment I cannot continue with the installation. I undrestand that use no password is not save but for dev usage it should not be a problem. So to finish installation I have to update the file src\ForkCMS\Bundle\InstallerBundle\Form\Type\DatabaseType.php and add required to false.

 ->add(
                'databasePassword',
                PasswordType::class,
                [
                    'required' => false,
                ]

## Steps to reproduce

Process the installation to the step 4.

## Expected behavior / Proposed solutions

Database password is not required.

**Comment by carakas** [comment]
won't fix, for the reasons take a look at the discussion on the pr
