### ISSUE TITLE
FAQ allow feedback

### ISSUE THREAD

**Issue by Katrienvh** [forkcms/forkcms#2627]
## Type
- Non critical bug

## Problem description
I not sure how it supposed to work, but how no it does not work correct in my eyes.

![image](https://user-images.githubusercontent.com/12270833/44771975-e2853b00-ab6c-11e8-9cc3-e3f490542b6e.png)

I think the field 'How can we improve you answer', should only appears when you choose no.
- because when you choose yes, there is no need to improve the answer
- because when you choose yes, the form auto-submits

Go to https://demo.fork-cms.com/private/en/faq/settings?token=49c7dz9eyl&report=saved to allow user feedback and questions for faq. Add an question and try to add feedback on it.

**Comment by Katrienvh** [comment]
I just found out that the form also sumbit when you choose no and the error message for the field 'How can we improve you answer' appears. Seems something is wrong.

**Comment by carakas** [comment]
The js is probably broken there
