### ISSUE TITLE
Thumbnails utiliy => Get folders

### ISSUE THREAD

**Issue by wouterverstuyf** [forkcms/forkcms#2645]
## Type

Critical bug

## Problem description

When using the new Thumbnails utility for getting the folders there are 2 problems:
- the folders are listed multiple times
- when you include the source folder, only the source folders gets returned, the other folders are not listed

## Steps to reproduce

Execute the code:
`
BackendModel::get(Thumbnails::class)->getFolders(<IMAGE_PATH>, true);
`

## Solution

I have changed the function, but probably there is more optimalisation possible. To fix the doubles the Finder utility needs to be reinitialized.
To add the source folder I have added a second condition.

Feel free to adjust and make it 100% correct.

`public function getFolders(string $inPath, bool $includeSourceFolder = false): array
    {
        if (!$this->filesystem->exists($inPath)) {
            return [];
        }

        $folders = [];
        $nameFilter = '/^([0-9]*)x([0-9]*)$/';

        $finder = new Finder();
        foreach ($finder->directories()->in($inPath)->name($nameFilter)->depth('== 0') as $directory) {
            $dirname = $directory->getBasename();
            $chunks = explode('x', $dirname, 2);

            if (count($chunks) !== 2) {
                continue;
            }

            $folders[] = [
                'dirname' => $dirname,
                'path' => $directory->getRealPath(),
                'width' => is_numeric($chunks[0]) ? (int) $chunks[0] : null,
                'height' => (array_key_exists(1, $chunks) && is_numeric($chunks[1])) ? (int) $chunks[1] : null,
                'url' => (0 === mb_strpos($inPath, $this->sitePath))
                    ? mb_substr($inPath, mb_strlen($this->sitePath)) : ''
            ];
        }

        if ($includeSourceFolder) {
            if ($this->filesystem->exists($inPath . '/source')) {
                $folders[] = [
                    'dirname' => 'source',
                    'path' => $inPath . '/source',
                    'width' => '',
                    'height' => '',
                    'url' => (0 === mb_strpos($inPath, $this->sitePath))
                        ? mb_substr($inPath, mb_strlen($this->sitePath)) : ''
                ];
            }
        }

        return $folders;
    }
`

**Comment by StijnVrolijk** [comment]
Actually, lately we've been using imagine filter functionality instead of the 'pregenerating' thumbnails. It all depends on what you need of course but I suggest looking into imagine filters, it's fully compatible with Fork.

https://symfony.com/doc/2.0/bundles/LiipImagineBundle/filters/sizing.html#thumbnails

```twig
<img src="{{ myImageSource|imagine_filter('my_custom_filter')" />
```
for example :)

**Comment by wouterverstuyf** [comment]
@StijnVrolijk 
Yes, I have seen the imagine filters in the medialibrary module for example.
So the "old" way of generating thumbnails will dissapear and is no longer supported?

**Comment by StijnVrolijk** [comment]
@wouterverstuyf we have no plans for removing the current Thumbnails from Fork CMS.

**Comment by carakas** [comment]
Managed to solve it in slightly less lines of code :) #2660
