### ISSUE TITLE
Search widget autosuggest returns full html

### ISSUE THREAD

**Issue by vanMeerdervoort** [forkcms/forkcms#2647]
## Type

- Non critical bug

## Problem description

The autosuggest in the search widget returns the entire page content as HTML

## Steps to reproduce

go to the forkcms demo site, type a search in the search widget (top of page) see the result.

## Expected behavior / Proposed solutions

Return the matching word instead of the complete html

**Comment by carakas** [comment]
why do you consider this an issue?

**Comment by carakas** [comment]
normally it should return a summary, but that clearly doesn't happen

**Comment by vanMeerdervoort** [comment]
> why do you consider this an issue?

1. It looks awful
2. It is not helpful or userfriendly
3. It is not expected behaviour -> one expects that an autosuggest returns links to the pages where the typed word is found, not the entire page (or even a summary for that matter) within the tiny autosuggest results field

[Please see screenshots of the problem and expected behaviour here](http://webleads2018.test.webleads.nl/fork-search-bug)

**Comment by vanMeerdervoort** [comment]
Fix is very easy ;)

Frontend Search.js
replace line 73
`return '<a><strong>' + data.value + '</strong><p>' + data.description + '</p></a>'`

With

`  return '<a><strong>'+data.value +'</p></a>'`

**Comment by ohvitorino** [comment]
@vanMeerdervoort if you have a solution, you should make a PR :)

**Comment by StijnVrolijk** [comment]
It's just a default.. some people might like the way it works. No need to get so worked up about it :)

That being said, there seems to be some mixup with `text` and `description` properties. 
Also, `\Frontend\Modules\Search\Ajax\Autosuggest:158` seems to contain a typo where `test` should be `text`
