### ISSUE TITLE
Cropping of a square image: Crop coordinates must start at minimum 0, 0

### ISSUE THREAD

**Issue by freshface** [forkcms/forkcms#2657]
## Type

- Critical bug

## Problem description

When i upload a square image and want to resize it to 1200x630 I get the following error:

> OutOfBoundsException: Crop coordinates must start at minimum 0, 0 position from top left corner, crop height and width must be positive integers and must not exceed the current image borders

## Steps to reproduce

Upload a square image and generate a 1200x630 file based on the folder

**Comment by carakas** [comment]
is this based on the latest release of the current master branch? cause we already have a fix in on master for issues with the image but I haven't gotten around to releasing a new version yet
#2641

**Comment by freshface** [comment]
This is based on the master.

**Comment by carakas** [comment]
Can you debug it and see where the fix still falls short?

**Comment by carakas** [comment]
We've been using that pr at sumocoders and so far haven't had any issues with it

**Comment by freshface** [comment]
I use this image.

![5bc5909eb43e6](https://user-images.githubusercontent.com/103913/47001428-b9c00180-d12a-11e8-99d6-a12cb465d484.png)

And try to generate a 1200x630.


If i add this to L99 it works https://github.com/forkcms/forkcms/blob/master/src/ForkCMS/Utility/Thumbnails.php#L99

`} else if ($box->getWidth() == $box->getHeight()){
                $cropPoint = new Point(0, 0);`

**Comment by carakas** [comment]
what happens if you turn `if ($box->getWidth() > $box->getHeight()) {` into `if ($box->getWidth() >= $box->getHeight()) {`

**Comment by carakas** [comment]
Jup, that fixes it, I'll create pr and include it in the release
