### ISSUE TITLE
Adding same page to different navigation

### ISSUE THREAD

**Issue by CodesigmaIN** [forkcms/forkcms#2668]
## Type

- Feature

## Problem description

> How can I add the same page in main navigation and footer navigation?

## Steps to reproduce

> In the admin page section if I move a page to a navigation, then I can't add the same page in another navigation.

## Expected behavior / Proposed solutions

> I would like to add some pages to both navigations, but right I can only add it to one navigation.

**Comment by carakas** [comment]
A page can only have one parent, you can add a fake page and just redirect it to the other page or just manually add the link in your navigation. I don't think there is any other way of doing this now or in the foreseeable future

@forkcms/core-contributors
