### ISSUE TITLE
Blog index uses block but does not extends

### ISSUE THREAD

**Issue by Katrienvh** [forkcms/forkcms#2671]
## Type
- Non critical bug

## Problem description
https://github.com/forkcms/forkcms/blob/master/src/Frontend/Modules/Blog/Layout/Templates/Index.html.twig
Blocks does nothings if you do not extend from a template. I guess is has to be like it is in the blog module in the Fork theme.

**Comment by carakas** [comment]
They are being used in the fork theme, so this is not an issue
