### ISSUE TITLE
It is not possible to make an image in the editor a link

### ISSUE THREAD

**Issue by bramds** [forkcms/forkcms#2677]
## Type

- Non critical bug

## Problem description

Turning an image inserted in an editor into a link doesn't work

## Steps to reproduce

- add image to editor field ( example through medialibrary )
- select image + click link icon and add a link
- error msg is shown

## Expected behavior / Proposed solutions

expected the image to be clickable to the desired link

**Comment by carakas** [comment]
Going to bump this one to the next release. If anybody wants to give it a try: go ahead

**Comment by carakas** [comment]
Seems to be a bug in CKEditor, you can bypass it by adding the link first with a dummy text, adding the image in the link and then remove the dummy text

**Comment by carakas** [comment]
There is a bug in `src/Backend/Core/Js/ckeditor/plugins/medialibrary/dialogs/linkDialog.js` but I haven't been able to fix it yet. If somebody else would be able to fix it it would be great

**Comment by carakas** [comment]
Steps to reproduce

See video: https://jmp.sh/hd6efy8
