### ISSUE TITLE
Formbuild alert text color

### ISSUE THREAD

**Issue by Katrienvh** [forkcms/forkcms#2678]
## Type
- Non critical bug

## Problem description

The color of the text is the same as the background.

![image](https://user-images.githubusercontent.com/12270833/48699813-a6e99280-ebea-11e8-8478-65e195b90f55.png)

**Comment by carakas** [comment]
@Katrienvh is this the fork theme?

**Comment by Katrienvh** [comment]
Yes the screenshot is from the demo.
