### ISSUE TITLE
Error message form builder submit

### ISSUE THREAD

**Issue by Katrienvh** [forkcms/forkcms#2679]
## Type
- Non critical bug

## Problem description

When you submit with a required field empty.

The error in de alert is a list of the error messages per field. I should be `something went wrong`. Like it was before, something changed.

**Comment by carakas** [comment]
can't you show the message yourself if there are errors?

**Comment by StijnVrolijk** [comment]
Relevant code found at `Modules/FormBuilder/Widgets/Form.php:558`

```php
// not correct, show errors
// global form errors set
if ($this->form->getErrors() != '') {
    $this->template->assign('formBuilderError', $this->form->getErrors());
} else {
    // general error
    $this->template->assign('formBuilderError', FL::err('FormError'));
}
```

The code itself hasn't changed so I'm thinking something in Spoon changed.
