### ISSUE TITLE
Upload pdf

### ISSUE THREAD

**Issue by sarahmey** [forkcms/forkcms#2682]
## Type

- Enhancement

## Problem description

Uploading a pdf is not really user friendly. With the image upload you can click the uploaded image to use, which you cannot with pdf's. You have to reopen your uploads and select the pdf you want. 

## Steps to reproduce

Upload a pdf from editor. 

## Expected behavior / Proposed solutions

When you upload a pdf from editor you can immediately select and use it.

**Comment by Senjutsuu** [comment]
Files can't be selected after upload in the editor
