### ISSUE TITLE
Collapse tree view pages only works for main navigation

### ISSUE THREAD

**Issue by Katrienvh** [forkcms/forkcms#2685]
## Type

- Non critical bug

## Problem description

When you clip the button 'open tree navigation', it wil only open pages in de main navigation not those under meta navigation / footer navigation / single pages. Maybe it was not ment to work like that but it would be a enhancement.

## Expected behavior / Proposed solutions

Open all pages under all navigation types

**Comment by Senjutsuu** [comment]
@carakas Dit kan je ook in de herwerking van het menu steken

**Comment by Senjutsuu** [comment]
@carakas You could consider this issue when rewriting the menu tree
