### ISSUE TITLE
Page template: usertemplate as default block for a position

### ISSUE THREAD

**Issue by Katrienvh** [forkcms/forkcms#2686]
## Type
- Enhancement

## Problem description
It's only possible to choose a widget or content block. I would like to be able to choose a usertemplate.

## Steps to reproduce

https://demo.fork-cms.com/private/en/extensions/edit_theme_template?token=hoe8ny6gr7&id=1, click on add block for a position.

**Comment by tijsverkoyen** [comment]
I agree with @carakas. It would also need defaults for the user template that will probably need to take context into account.
In my opinion, if a "block" should be provided by default it should be in the content-blocks-module as the content can be changed at once for all occurrences thru the site.
