### ISSUE TITLE
Blog. Missing gravatar generate error 404 and slow down the site.

### ISSUE THREAD

**Issue by Sellato** [forkcms/forkcms#2709]
## Type

Module Blog. Missing gravatar generate error 404 and slow down the site.

- Enhancement

## Problem description

Each **missing gravatar** in blog comments generate error 404 and slow down the site.

[![miss-grav.jpg](https://i.postimg.cc/d01synN2/miss-grav.jpg)](https://postimg.cc/yDMCqhHx)

## Steps to reproduce

error 404 generates in file:

`src/Frontend/Core/Js/frontend.js`

option **?r=g&d=404**

`var url = 'https://www.gravatar.com/avatar/' + gravatarId + '?r=g&d=404' `

## Expected behavior / Proposed solutions

We should pass the default image to gravatar instead of using 404's to show the correct one

**Comment by carakas** [comment]
It's not a bug. We don't know what avatars exist or not. We use the 404 to show a nice themed default avatar instead of the ugly one from gravatar

**Comment by Sellato** [comment]
:)
gravatars maybe funny if using **robohash**

`?r=pg&d=robohash`

https://handmade.crafterspark.com/blog/detail/seven-short-post

**Comment by carakas** [comment]
@Sellato

**Comment by carakas** [comment]
@Sellato good idea, feel free to create a PR implementing this. Apparently you can also pass a url there

**Comment by carakas** [comment]
I'll see if I have time to fix this
