### ISSUE TITLE
Add ability to join all minified js files into one js file. Minify.js have this feature. 

### ISSUE THREAD

**Issue by Sellato** [forkcms/forkcms#2711]
## Type
- Enhancement
- Feature

## Problem description

It's will be great to join all files in src\Frontend\Cache\MinifiedJs\*.js into one file.

## Expected behavior / Proposed solutions

https://www.minifier.org/

> use MatthiasMullie\Minify;
> 
> $sourcePath = '/path/to/source/css/file.js';
> $minifier = new Minify\JS($sourcePath);
> 
> // we can even add another file, they'll then be
> // joined in 1 output file
> $sourcePath2 = '/path/to/second/source/css/file.js';
> $minifier->add($sourcePath2);

**Comment by carakas** [comment]
Closing since we are switching to webpack in fork 6
