### ISSUE TITLE
If the site is MULTILANGUAGE, custom added js and css files got wrong URL's.

### ISSUE THREAD

**Issue by Sellato** [forkcms/forkcms#2712]
## Type

- Critical bug

## Problem description

If the site is MULTILANGUAGE, custom added js and css files got wrong URL's.
Normal URL like **https://goods.crafterspark.com/js/vendors/SocialShare.js** ( SocialShare.js is custom added js file) translated to **https://goods.crafterspark.com/en/js/vendors/SocialShare.js** ( prefix **EN** was added to URL ) and URL become wrong.

what we need **https://goods.crafterspark.com/js/vendors/SocialShare.js**
what we got **https://goods.crafterspark.com/en/js/vendors/SocialShare.js**

in this situation we got error 404 and scripts don't work.

## Expected behavior / Proposed solutions

remove **hreflang** from URL for custom added js and css files

**Comment by carakas** [comment]
can you show me the code that you use to add the js?

**Comment by Sellato** [comment]
Give me some time to check again. Maybe it be my mistake.

**Comment by Sellato** [comment]
Please remove this issue. It's seems that I made a mistake. I can't reproduce this issue by myself.
Sorry for that.
