### ISSUE TITLE
In file locale.xml don't translate sections **item type="action"** to national languages

### ISSUE THREAD

**Issue by Sellato** [forkcms/forkcms#2713]
## Type

- Critical bug

## Problem description

File locale.xml contains many sections **item type="action"** that translated to national languages, that is wrong, because URL's looks very ugly. I just say only about **item type="action"** for URL's, not buttons!

For example:

http://demo.fork-cms.com/ru/modules/blog/%D0%BF%D0%BE%D0%B4%D1%80%D0%BE%D0%B1%D0%BD%D0%B5%D0%B5/nunc-sediam-est

http://demo.fork-cms.com/ru/modules/blog/%D0%BA%D0%B0%D1%82%D0%B5%D0%B3%D0%BE%D1%80%D0%B8%D1%8F/default

and so on

## Steps to reproduce
Please look at the demo site http://demo.fork-cms.com

http://demo.fork-cms.com/ru/modules/blog/%D0%BA%D0%B0%D1%82%D0%B5%D0%B3%D0%BE%D1%80%D0%B8%D1%8F/default

## Expected behavior / Proposed solutions

Need to prevent translate **item type="action"** **that used in URL's** to national languages, only English language. I just say only about **item type="action"** for URL's, not buttons!

**Comment by StijnVrolijk** [comment]
We won't change this. The whole point of the translations is that the enduser can change them so they can change the URL. If we limit this to a hardcoded english value you'll end up with URL's that are partly in the correct locale and partly in english.

If the situation you present bothers the enduser they can simply edit the translation.

**Comment by Sellato** [comment]
Sorry, I'm not agree with you :)
"detail" is a core URL, not user url. As you can see https://handmade.crafterspark.com/blog/detail/seven-short-post , **https://handmade.crafterspark.com/blog/detail/** is core URL and can't be changed by user.
Detail is detail.html.twig so it must be in English only without translation.
Maybe I'm wrong :)

**Comment by jonasdekeukelaere** [comment]
You can change the "detail" translation, by changing it in the translations: http://demo.fork-cms.com/private/en/locale/index?form=filter&form_token=4f22b7502b10b4118d2ec559acaac11a&application=Frontend&module=Core&type%5B%5D=act&language%5B%5D=nl&language%5B%5D=en&language%5B%5D=fr&language%5B%5D=de&language%5B%5D=hu&language%5B%5D=it&language%5B%5D=lt&language%5B%5D=ru&language%5B%5D=es&name=Detail&value=&search=
