### ISSUE TITLE
Please add a Duplicate Page button

### ISSUE THREAD

**Issue by Marketeer-Woes** [forkcms/forkcms#2721]
## Type

- Enhancement
- Feature

## Problem description

> Please can we add a "Copy" button to the CMS so that existing landing pages can be easily duplicated?  This means that when we want to create 3 very similar landing pages, we can copy and paste all the content from an existing page in one click, similar to the functionality available in the WordPress Divibuilder.

## Steps to reproduce

> When logged into Fork, under the Pages tab, please add a "Duplicate page" option.

## Expected behavior / Proposed solutions

> By adding the button we will be able to  copy and paste all the content from an existing page into a new page, in one click, similar to the functionality available in the WordPress Divibuilder.

**Comment by StijnVrolijk** [comment]
Might be as easy as slightly altering the code which copies pages from one locale to another.
