### ISSUE TITLE
Module Blog. blog detail, section id in comments is blank.

### ISSUE THREAD

**Issue by Sellato** [forkcms/forkcms#2725]
## Type
- Bug
## Problem description
in file Detail.html.twig

at line 107 section id="{{ act.Comments }}"
`<section id="{{ act.Comments }}" class="block-blog-article-comments">`

generates blank **section id**

output code:
> <**section id=""** class="block-blog-article-comments">

at line 165 section id="{{ act.Comments }}"
`<section id="{{ act.Comment }}" class="block-blog-article-comment-form">`

generates blank **section id**

output code:

> <**section id=""** class="block-blog-article-comment-form">

## Steps to reproduce

view-source:http://demo.fork-cms.com/en/modules/blog/detail/nunc-sediam-est

**Comment by StijnVrolijk** [comment]
This seems to be an issue with translating actions. The translations for both `Comments` and `Comment` exist, they just don't get used when calling `{{ 'act.Comments'|trans }}`.

@Sellato please don't mark every issue as a Critical Bug... This is hardly a very mild inconvenience, nowhere near critical.

**Comment by Sellato** [comment]
Your solution:
{{ 'act.Comments'|trans }}
{{ 'act.Comment'|trans }}

works fine :)

**Comment by StijnVrolijk** [comment]
I didn't even notice that. PR made
