### ISSUE TITLE
Mailmotor. Widget Newsletters Subscribe generate wrong url for action.

### ISSUE THREAD

**Issue by Sellato** [forkcms/forkcms#2739]
## Type
- Non critical bug

## Problem description

When we put on page widget, **Widget** - Newsletters  - SUBSCRIBE and press Subscribe, we got an error 404.
- this is output code, when we use widget:

```
<div class="widget-body">
<form name="subscribe" method="post" action="/en/404">
```
https://demo.fork-cms.com/en/404

When we put on page module, **Module** - Newsletters - SUBSCRIBE, all works fine.
- this is output code, when we use module:

```
<div class="block-body">
<form name="subscribe" method="post" action="/en/modules/newsletters/subscribe">
```

PS
if we put on one page Module and Widget all is OK :)

```
<div class="widget-body">
<form name="subscribe" method="post" action="/newsletters/subscribe">
```

```
<div class="block-body">
<form name="subscribe" method="post" action="/newsletters/subscribe">
```

**Comment by carakas** [comment]
The widget is a shortcut to the action. If you don't have the action linked to a page the widget won't work. That's the way it was designed by @jeroendesloovere

**Comment by Sellato** [comment]
Thank you.
Can you, or somebody else give me solution, on how I can make widget working :) I want to put Subscribe widget to the footer. https://handmade.crafterspark.com/blog

**Comment by carakas** [comment]
Do you already have a separate page with the subscribe action linked to it?

**Comment by Sellato** [comment]
> Do you already have a separate page with the subscribe action linked to it?

how can I do 

> subscribe action linked to it
?

**Comment by Sellato** [comment]
Your solution works fine if using one module in single page, but I can't add 2 modules to single page. Only one module and any amount of widgets. How can I add module MailMotor to the Blog?

**Comment by carakas** [comment]
You place the widget on the blog page, you just need a separate subscribe page. It's a bit of an annoying implementation. No clue why it works like this. Feel free to create a PR to change this
