### ISSUE TITLE
Unable to add link to file in CKEditor

### ISSUE THREAD

**Issue by thibautvincent** [forkcms/forkcms#2749]
## Type

- Critical bug

## Problem description

When you want to link a file/image to a specific word in the CKEditor, the input field of the url will filled in with `[Object Object]`.

## Steps to reproduce

Add text to CKEditor and click `Add link`. Browse files and select a file.

**Comment by Sellato** [comment]
1. Are you using AdBlocker or JSBlocker?
2. Is the JavaScript enabled in your browser?
