### ISSUE TITLE
Locale flag issues Bootstrap-grey

### ISSUE THREAD

**Issue by mattish91** [forkcms/forkcms#2751]
Bootstrap grey issue with Swedish flag. As you can see in the picture that's the wrong flag (obviously like title says.)

See image: https://imgur.com/a/uRNt8eT

Not sure where the correct image is so i just made a new one found here: http://fork.mspot.nu/src/Frontend/Themes/Bootstrap-Gray/Core/Layout/images/flags/sv.png

Please push this to the correct location.

**Comment by carakas** [comment]
@mattish91 please create an issue for this on the repository for the bootstrap-gray theme.
It is not a default theme so the issue shouldn't be reported here

**Comment by carakas** [comment]
You can find the theme here             https://github.com/johwiese/Fork-CMS-Theme-Bootstrap-Gray

**Comment by mattish91** [comment]
alright, thanks! Just published the new issue.
