### ISSUE TITLE
Location module has a confusing interface

### ISSUE THREAD

**Issue by StijnVrolijk** [forkcms/forkcms#2772]
## Type

- Enhancement

## Problem description

The edit page of a location is confusing as it has 2 forms, 2 save buttons and they both behave differently.

## Steps to reproduce

https://demo.fork-cms.com/private/en/location/edit?token=z4pjcflp2s&id=1

- Edit something in both forms, click "update map" (whatever that means). The top form will be submitted and handled but the bottom form will be ignored.
- Edit something in both forms, click "save". The bottom form will be submitted using AJAX and after succesful completion it will submit the top form which makes no sense whatsoever.

## Expected behavior / Proposed solutions

I expect the form to make sense. There is no purpose (as far as I can tell) for the AJAX call or even the separate forms. 

My suggestion:

- Split up the form in 2 tabs, address and map settings
- Lose the AJAX call, there should be 1 "save" button that saves the entire form
- Add a checkbox to the "map settings" tab to indicate whether to overwrite the general map settings set on the Index action.
- Disable/enable the map settings fields based on the checkbox value.

**Comment by carakas** [comment]
should be done in #2403
