### ISSUE TITLE
Implementing GrapeJS as editor

### ISSUE THREAD

**Issue by aalwash** [forkcms/forkcms#2800]
Hi,

I'm new to ForkCMS, but I'd like to contribute if possible.
So below a feature request/quesiton

## Type
- Feature

## Problem description
Adding a option for a new editor type (GrapeJS in particular)

## Steps to reproduce
Implementing GrapeJS https://grapesjs.com/demo.html

## Expected behavior / Proposed solutions
New option in the user profile, next to HTML and ckeditor, you get GrapeJS

I'm trying to figure out how easy (or difficult?) it is to implement a new editor.
I already found out that src/Backend/Core/Engine/Form.php is doing most of the editor initialising part.

Except, this is inside the core of the form engine, so it should become more flexibel to support other editors if needed?
And there is also src/Backend/Form/Type/EditorType.php and src/Backend/Core/Js/ckfinder/core/connector/php/CKSource/CKFinder/Command/QuickUpload.php that are doing some CKeditor initialising.

So my question, is it really that difficult to implement?
Maybe make CKeditor a module of the backend, so it's easier to implement other editors.

What do you guys think?

**Comment by carakas** [comment]
@aalwash What would be the benefits of adding GrapeJS?

**Comment by aalwash** [comment]
I already was expecting this question ;)

Well, it's a more advanced editor
Just a small example, if you want to have 3 options next to each other (like in the demo with the 350x250 example), then you have to use tables in ckeditor 
If you want to use div's or other type of elements, you have to code it yourself in HTML (less user friendly)

I've used CKeditor for a long time in my previous job and if you try to do some advanced HTML stuff, then it starts to show you some strange issues/bugs

GrapeJS has an internal DOM tree, so it's less quirky if you try to modify a div that's inside another div that's inside another table (for example)


I also understand your point (since I'm a developer as well)
Extra editor, means extra maintenance time and more bugs, but I think it's worth it

**Comment by carakas** [comment]
@aalwash if you think you can find a good way to integrate this in fork we can always try it. If it turns out that it works better than CK maybe we can drop CK in the next and switch, or keep both options

**Comment by carakas** [comment]
we are probably going to switch to ck editor
