### ISSUE TITLE
Adding my module to Friends of Fork CMS

### ISSUE THREAD

**Issue by souljacker** [forkcms/forkcms#2811]
How can I do it, guys?

**Comment by aalwash** [comment]
Did you try to contact @jeroendesloovere or @bart-webleads   on Slack?

**Comment by carakas** [comment]
you can always contact me as well, @jeroendesloovere isn't that active anymore since he changed jobs

**Comment by aalwash** [comment]
Maybe this one needs an update then https://github.com/orgs/friends-of-forkcms/people ?

**Comment by carakas** [comment]
changed my membership from private to public :)
There are 20 members, but not everybody has displayed it as public

**Comment by carakas** [comment]
@souljacker do you have an example of the module you would like to add somewhere? Or is the code already open sourced somewhere?

**Comment by jeroendesloovere** [comment]
I'm happy to help too
