### ISSUE TITLE
Request Feature. New field "About Author" in profile.

### ISSUE THREAD

**Issue by Sellato** [forkcms/forkcms#2817]
## Type
- Enhancement
- Feature

## Problem description

It's will be great if we add new field "About Author" to profile in Admin panel.
By adding this field, we can be able to use this in Blog module, like in attached picture.

<a href="https://imgbb.com/"><img src="https://i.ibb.co/yVRMc5L/about.jpg" alt="about" border="0"></a>

**Comment by carakas** [comment]
@Sellato I like it, can you make a pr for it? Make sure you use the profile settings so that it is backwards compatible
