### ISSUE TITLE
CKEditor. For security reason need to add rel="noopener noreferrer"

### ISSUE THREAD

**Issue by Sellato** [forkcms/forkcms#2820]
## Type

- Enhancement
- Feature

## Problem description
In CKEditor, if we using Target=”_blank”, we got serious vulnerability risk.
> Target=”_blank” — the most underestimated vulnerability ever
[https://medium.com/@jitbit/target-blank-the-most-underestimated-vulnerability-ever-96e328301f4c](url)

## Expected behavior / Proposed solutions

I find solution, but don't know how to fix this problem.
It's need to add `rel="noopener noreferrer"`

> Add rel=“noopener” to links/anchors in ckeditor
https://stackoverflow.com/questions/40142498/add-rel-noopener-to-links-anchors-in-ckeditor

**Comment by carakas** [comment]
@Sellato could you create a pr for this? we have a custom implementation of the link plugin so you should be able to change it in fork

**Comment by Sellato** [comment]
I test this feature on demo.fork-cms.com, and it's works :)

**rel="noopener noreferrer" target="_blank"** is present in output code

`<p>long Test noopener in <a href="https://vorchun.crafterspark.com/blog" rel="noopener noreferrer" target="_blank">ckeditor</a></p>`

magic :)

**Comment by carakas** [comment]
oops, forgot to close this one :p

**Comment by carakas** [comment]
Fixed in 2908
