### ISSUE TITLE
It's need to perform a full audit, on how breadcrumbs looks.

### ISSUE THREAD

**Issue by Sellato** [forkcms/forkcms#2824]
## Type
- Enhancement

## Problem description
The last page in breadcrumbs must be NOT a link ( disabled ). In Fork CMS breadcrumbs is a link ( in attach )

**How breadcrumbs look in Fork CMS**

![bc1](https://user-images.githubusercontent.com/5456419/58570221-4180f900-8240-11e9-982c-f57b556d28e4.jpg)

**How it looks at Mozilla Developer Network ( MDN )**

![bc2](https://user-images.githubusercontent.com/5456419/58570253-4e055180-8240-11e9-87c7-fc3f357fc08d.jpg)

https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/Breadcrumb_Navigation

**Comment by carakas** [comment]
@Sellato can you make pull request for things like this?

**Comment by Sellato** [comment]
Sorry, it's hard for me ...
I'm only hobbyist, not a developer :)
I like Fork CMS, and I want Fork CMS to be better :)
I can help, when I can and can't when I can't...
