### ISSUE TITLE
Page context - which action and/or widget(s) are being rendered on the current page

### ISSUE THREAD

**Issue by ohvitorino** [forkcms/forkcms#2830]
## Type

- Feature

## Problem description

Many times while working on existing projects which I'm not yet familiar with, it would be nice to be able to know which actions and/or widgets are being rendered in the frontend on the page I'm currently visiting.

## Proposed solutions

An extra item could be added to the Symfony debug toolbar with the name of the action and/or widgets being rendered on the page and the also the module name, similarly to the Request/Response button of the current toolbar.

![image](https://user-images.githubusercontent.com/848112/59585053-e8d6aa80-90df-11e9-8772-e9e8a7a273d1.png)

**Comment by StijnVrolijk** [comment]
I approve of this idea.

**Comment by carakas** [comment]
I like it as well
