### ISSUE TITLE
IFrame on page 404

### ISSUE THREAD

**Issue by Sellato** [forkcms/forkcms#2851]
## Type
- Non critical bug
## Problem description

By default in Page 404 included iframe. Is it good or not? I think not, iframe is a bad practice, except iframes that you install by hands and know what you do :) For this reason it's need to be removed from installer.

`<iframe src="http://notfound-static.fwebservices.be/404/index.html" width="100%" height="650" frameborder="0"></iframe>`

## Steps to reproduce
Look by this way on all languages. For example in English

`\src\Backend\Modules\Pages\Installer\Data\en\404.txt`

**Comment by carakas** [comment]
I see no issue in this. You can always change it in your personal fork version. Those are missing people and we can give them more visibility like this
