### ISSUE TITLE
Feature request for CKEditor.

### ISSUE THREAD

**Issue by Sellato** [forkcms/forkcms#2866]
## Type
- Enhancement
- Feature

## Problem description

Is it possible to add `'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock' `to CKEditor menu?

[Link to CKEditor configurator in advanced mode](https://ckeditor.com/latest/samples/toolbarconfigurator/index.html#advanced)

**Comment by wavoe** [comment]
I was able to fix this as described [here](https://www.fork-cms.com/community/forum/detail/left-and-right-alignment-in-editor) in Fork CMS v4, but recently updated and  tried the same way in Fork CMS 5 but I'm not able to have it visible.
Would be nice if it can be indeed been foreseen (by default).

**Comment by carakas** [comment]
@wavoe it's possible that the plugin for that isn't shipped by default or disabled.
you can check the gulp file for this and edit the config.
We are currently busy implementing a new editor (as part of Fork 6) so unless somebody creates a PR for it it won't be added by default

**Comment by Sellato** [comment]
@wavoe try to add in file backend/core/js/backend.js at line 356 in block "paragraph"

` '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'`

```
      {
        name: 'paragraph',
        groups: ['list', 'indent', 'blocks', 'bidi'],
        items: ['NumberedList', 'BulletedList', '-', 'Blockquote', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']
      },
```
Think it's help you :)

**Comment by wavoe** [comment]
@Sellato thanks for the detailed info, this was what I was looking for!

I also had to add this plugin in the `extraPlugins` variable in the `backend.js` file.
Now I have the justify function back!

**Comment by carakas** [comment]
Thank you @Sellato for helping with this one :)
