### ISSUE TITLE
Fork theme thumbnail.png extremely big.

### ISSUE THREAD

**Issue by Sellato** [forkcms/forkcms#2872]
## Type
- Enhancement
## Problem description

The size of `thumbnail.png` is extremely big - 3.24 MB with dimensions 2380x1534!
Is it really need such a big picture to display little  thumbnail? I think, no :) .

It's need to resize and optimize the thumbnail.png
`src/Frontend/Themes/Fork/thumbnail.png`

**Comment by carakas** [comment]
that is big indeed

**Comment by carakas** [comment]
@Sellato can you run it through something like https://tinypng.com/ and create a PR?

**Comment by Sellato** [comment]
I made new one. But can't make PR :(
My repository is out date. It's need a time to learn more about git, but I haven't time for it right now.
 
![thumbnail](https://user-images.githubusercontent.com/5456419/62549962-9e79da80-b893-11e9-9260-7fae00d7e946.png)
