### ISSUE TITLE
New page template as a copy from existing page template

### ISSUE THREAD

**Issue by sarahmey** [forkcms/forkcms#2880]
## Type
- Enhancement

## Problem description
If I make a new page template that has a lot of the same blocks as other page templates (per example footer blocks and navbar blocks), I have to add them all again, and add the same content blocks in the blocks. 

## Steps to reproduce
Make a new page template with some blocks the same as an existing template. You cannot copy the template and edit or add some blocks, you have to insert all the information again.

## Expected behavior / Proposed solutions
I would like a button 'copy to new page template' or something similar.

**Comment by carakas** [comment]
Not a fan of this, I think it will add too much complexity, probably a better idea to improve the matching of the template areas when switching
