### ISSUE TITLE
Install with example data: allow user to upload image

### ISSUE THREAD

**Issue by Katrienvh** [forkcms/forkcms#2888]
## Type
- Non critical bug/Enhancement

## Problem description

When you install fok with example data. Then home page will get a dummy image uploaded, but you can't change it right away because the checkbox to allow you to upload an image is not checked, so the tab 'image' is not visible.

## Expected behavior / Proposed solutions

When you choose to install fork with example data, the checkbox to allow you to upload images for a page should be checked, so the tab 'image' is visible right away

**Comment by carakas** [comment]
Is issue in the SumoCoders fork of Fork
