### ISSUE TITLE
FormBuilder data detail layout is a bit messed up

### ISSUE THREAD

**Issue by StijnVrolijk** [forkcms/forkcms#2890]
## Type

- Non critical bug

## Problem description

When viewing the detail of a FormBuilder data submission the layout is a bit screwed up, see below.
![image](https://user-images.githubusercontent.com/442529/64095744-f9520500-cd5f-11e9-9566-b26256f5a570.png)

## Steps to reproduce

Go to [https://demo.fork-cms.com/en/contact](https://demo.fork-cms.com/en/contact), submit the form and view [https://demo.fork-cms.com/private/en/form_builder/data_details?start_date=&end_date=&token=m6htak781&id=1](https://demo.fork-cms.com/private/en/form_builder/data_details?start_date=&end_date=&token=m6htak781&id=1)

## Expected behavior / Proposed solutions

- Add the missing label
- Fix the "submissions for "Contact"" title

**Comment by grvkmrpandit** [comment]
What is the exact problem.The message that is displayed ?

**Comment by jessedobbelaere** [comment]
@grvkmrpandit I noticed this as well recently. There's a bad or missing translation and the title of the page "Submissions for Contact" is floating in the middle of the page
