### ISSUE TITLE
405 error on POST call to user content html file (NGINX)

### ISSUE THREAD

**Issue by jessedobbelaere** [forkcms/forkcms#2893]
## Type

- Non critical bug

## Problem description
On a website served by NGINX, I receive a 405 Method Not Allowed on a POST request to `/src/Frontend/Themes/MyTheme/Core/Layout/Templates/UserTemplates/homepage-section.html`

## Steps to reproduce
On a website served by NGINX:
1. Insert new User Content block on a page.
2. It loads and makes a POST call to fetch the html template file, but fails with a 405 error on the html file:

![Screen Shot on 2019-09-09 at 22:18:12](https://user-images.githubusercontent.com/1352979/64563488-d4592580-d34f-11e9-877f-887874811035.png)

![image](https://user-images.githubusercontent.com/1352979/64563491-d58a5280-d34f-11e9-928e-f741f2965379.png)

## Expected behavior / Proposed solutions
Should load the html file just fine and allow inserting content in the user content block. 

The problem here is that **NGINX always returns a 405 Method Not Allowed error, when doing a POST request to static files like .html**. And since the Fork CMS ajax method always runs a POST request, thats an issue.

There are hacks, but dirty ones like changing the response code from 405 to 200: 
* https://stackoverflow.com/questions/24415376/post-request-not-allowed-405-not-allowed-nginx-even-with-headers-included
* https://stackoverflow.com/a/44613878/1409047
* http://invalidlogic.com/2011/04/12/serving-static-content-via-post-from-nginx/
* https://distinctplace.com/2017/04/17/405-not-allowed-nginx-fix-post-requests

I'll wait for some suggestions, but I can have a look to override it and make user content blocks fetch the html file using a GET ajax call instead of POST.
Related code: https://github.com/forkcms/forkcms/blob/master/src/Frontend/Core/Js/frontend.js#L52-L62

**Comment by carakas** [comment]
User templates will be replaced in fork 6, we won't fix this in fork 5 anymore
