### ISSUE TITLE
Page template cannot be deleted

### ISSUE THREAD

**Issue by sarahmey** [forkcms/forkcms#2894]
## Type

- Non critical bug

## Problem description

The delete button for on a page template detail page never shows.

## Steps to reproduce

Par example give the error page an other page template, try to delete the error page template.

## Expected behavior / Proposed solutions

In the file `EditThemeTemplate.html.twig` there is an if-statement with a variable that is never assigned.
`{% if showExtensionsDeleteThemeTemplate and allowExtensionsDeleteThemeTemplate %}`
The showExtensionsDeleteThemeTemplate doesn't exist anywhere, therefore will always be false.

**Comment by carakas** [comment]
@sarahmey the show parameter is auto generated, it is showModuleAction and then it checks with the module rights to see if you have access to that. Is it then still an issue?

**Comment by carakas** [comment]
Just tested it, when a template is not in use it can be deleted
