### ISSUE TITLE
Formbuilder - Radiobuttons default value is not saved

### ISSUE THREAD

**Issue by mathiashelin** [forkcms/forkcms#2895]
## Type
- Non critical bug

## Problem description

In Formbuilder, you can select a default value for the radiobuttons, but the selection is not saved.

## Steps to reproduce

1. Make a form with some radiobuttons
2. Select a default value in the Properties tab
3. Save the field and save the form
4. Return to the radiobuttons, Properties tab, the previously selected value is not selected anymore

## Expected behavior / Proposed solutions

De default value should be saved.

**Comment by carakas** [comment]
Just tested this and it seems to be working so it must have been fixed somewhere along the way
