### ISSUE TITLE
User Template / Image field not clickable

### ISSUE THREAD

**Issue by wouterverstuyf** [forkcms/forkcms#2896]
## Type
- Critical bug

## Problem description
New user template with image field
Not possible to upload an image

## Steps to reproduce
- Add a user template with an image field
- Click the upload button (not possible)
- Resize your browser window a few px
- Now it is clickable

**Comment by jessedobbelaere** [comment]
I noticed this as well in my website. Resizing helps.
I haven't had a chance to really dive in the code yet, but looks like we are using https://github.com/LPology/Simple-Ajax-Uploader and the code turns this basic file input field into a Simple-Ajax-Uploader supported field.

When loading the page, this is added on top of the input field, but probably has no click listener yet until resizing:

<details>

```html
<div style="display: block; position: absolute; overflow: hidden; margin: 0px; padding: 0px; opacity: 0; direction: ltr; z-index: 16777270; left: 282px; top: 2019px; width: 734px; height: 63px; visibility: hidden;"><input type="file" name="file" accept="image/*" style="position: absolute; right: 0px; margin: 0px; padding: 0px; font-size: 480px; font-family: sans-serif; cursor: pointer; height: 100%; z-index: 16777270;"></div>
```

</details>

Will look into it later

**Comment by jessedobbelaere** [comment]
Seems like a known issue in the plugin: 

https://github.com/LPology/Simple-Ajax-Uploader/issues/218
https://stackoverflow.com/questions/57802970/simple-ajax-uploader-plugin-stopped-working

Seems fixed in recent versions. I'll make a PR to update to version 2.6.7

**Comment by wouterverstuyf** [comment]
Great, thx for the fix! :)
