### ISSUE TITLE
You have requested a non-existent parameter "session.cookie_secure"

### ISSUE THREAD

**Issue by GaneshKandu** [forkcms/forkcms#2932]
## Bug Report

| Q            | A     |
| ------------ | ----- |
| Critical Bug | yes    |
| Version      | 5.7.0 |

### Problem description

Getting error in upgrade of forkcms 5.6.2 to forkcms 5.7.0
```
Main
Message 	You have requested a non-existent parameter "session.cookie_secure".
File 	vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php
Line 	102
Date 	Tue, 15 Oct 2019 11:10:56 +0100
URL 	private/en/authentication?querystring=%2Fprivate%2Fen
Referring URL 	(Unknown)
Request Method 	GET
User-agent 	
PHP error 	Undefined variable: userAgent
```
### Steps to reproduce

Install old version of forkcms and upgrade to version 5.7.0 of forkcms

**Comment by jessedobbelaere** [comment]
@GaneshKandu can you add this line to your existing `parameters.yml` file in app/config? 

https://github.com/forkcms/forkcms/blob/master/app/config/parameters.yml.dist#L15

In the Fork CMS 5.7.0 release, there's a new option for secure cookies added to the parameters file

**Comment by GaneshKandu** [comment]
@jessedobbelaere 

adding ```session.cookie_secure:  false``` works for me
can you please provide link where "how to upgrade to latest version of fork-cms ?" is mention so that i can take reference of it to upgrade.

**Comment by carakas** [comment]
We only provide upgrade guides for major versions since we follow https://semver.org/

In this case we maybe could've provided a fallback for when the parameter is missing but I didn't think of that since it was listed in the parameters.yml.dist file.
My appologies
