### ISSUE TITLE
Switch to block style editor

### ISSUE THREAD

**Issue by carakas** [forkcms/forkcms#2945]
## Feature Request

| Q           | A      |
| ----------- | ------ |
| New Feature | yes    |
| RFC         | no |
| BC Break    | yes |

### Summary

CK Editor is kinda bloated and a huge block of code we can't properly test. By switching to SirTrevor everything will be more modular

**Comment by carakas** [comment]
We are dropping the SirTrevor implementation as the project isn't well maintained. Currently looking at https://editorjs.io/ instead. This will mean the backend will drop support for IE11

**Comment by jessedobbelaere** [comment]
https://quilljs.com is popular too, but editorjs sure looks nice
