### ISSUE TITLE
Embedding mp4 video from MediaLibrary doesn't work

### ISSUE THREAD

**Issue by marcquark** [forkcms/forkcms#2998]
## Bug Report

| Q            | A     |
| ------------ | ----- |
| Critical Bug | no    |
| Version      | tested with 5.4.0, 5.7.0 and whatever is installed on demo.fork-cms.com |

### Problem description
It's possible to upload an mp4 video the the media library, but when i go to a page and edit an "editor" block, trying to insert the video fails.
I can click the "Browse Server" button and select the file, but when i then click on OK i get an error message "please provide a valid URL"

### Steps to reproduce
(can be done on demo.fork-cms.com)
- Upload any mp4 video file to media library, such as this https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4
- Go and edit any page, click "Embed Media"
- Click "Browse Server" and select the video you just uploaded from your library
- Try and save it by pressing OK

### Expected behavior / Proposed solution
I would expect the video the become embedded. The path that gets determined is correct. As a workaround i inserted a video tag myself through the source code view, and just copy+pasted the path. Video is now visible on the page

I'm pretty sure that the source of error is in lines 295-298 of src/Backend/Core/Js/ckeditor/plugins/oembed/plugin.js

As a workaround, i tried to just prepend https://fork.installation.url/ but to no avail

**Comment by carakas** [comment]
It reminds me of an old bug we had with images.
I'll check to see if this is running on a different piece of code and might require the same fix

**Comment by carakas** [comment]
@marcquark It seems that Yahoo shut down the api that is being used by that third party plugin. A number of things are implemented and don't need the fallback so they continue to work but local things aren't working anymore. Feel free to suggest a replacement

**Comment by carakas** [comment]
Found the bug, busy solving it

**Comment by carakas** [comment]
related to #3133
