### ISSUE TITLE
Dependency of zlib1g

### ISSUE THREAD

**Issue by cihakmar** [forkcms/forkcms#3088]
## Support Question

| Q       | A     |
| ------- | ----- |
| Version | 5.8.1 |

Just clone version 5.8.1 and wanted to build docker. Building process ends with error:
`The following packages have unmet dependencies:
 zlib1g-dev : Depends: zlib1g (= 1:1.2.8.dfsg-2+deb8u1) but 1:1.2.8.dfsg-2+b1 is to be installed
E: Unable to correct problems, you have held broken packages.`

**Comment by carakas** [comment]
@cihakmar could you make a pr for this? You can probably find the fix by searchign for it on google

**Comment by cihakmar** [comment]
@carakas We just made a research with my colleague but no luck for now.

**Comment by carakas** [comment]
We have a test building our docker container so it should be fixed now
