### ISSUE TITLE
Align all tabs left

### ISSUE THREAD

**Issue by Katrienvh** [forkcms/forkcms#3107]
## Feature Request

| Q           | A      |
| ----------- | ------ |
| New Feature | yes    |
| RFC         | yes |
| BC Break    | no |

### Summary

I heard there are many users that look over the tabs in fork that are aligned at the right. 
I can't admit it, because i'm too used to it. But I can imagine that new users look over it. 

What's the reasons those tabs are aligned right? I mean if the reason is something like that the left one is the most important one then I think it's wrong. 

The important tab is active, so im my eyes you could move the other one next to it, at the left, it won't make the (important)tab less important. Also the other tabs will be found more easily.

**Comment by tijsverkoyen** [comment]
The original intention was to make a visual difference between tabs that contain fields that require user input and tabs with fields that are automatically populated such as SEO-stuff.

**Comment by tijsverkoyen** [comment]
At this point I don't think making the difference by aligning the tabs is the best solution.
I think we should add an "optional"-label to those tags, or an ? with a tooltip that explains what these "optional" tabs are.

**Comment by carakas** [comment]
Closing for now since this is more of a design discussionon
