### ISSUE TITLE
Faq item delete does not work

### ISSUE THREAD

**Issue by Katrienvh** [forkcms/forkcms#3114]
## Critical Bug Report

| Q            | A     |
| ------------ | ----- |
| Critical Bug | yes   |
| Version      | restructure core |

### Problem description

Removing a faq item is not possible

### Steps to reproduce

Edit an faq item, click on the delete button on the left bottom. Then confirm the delete in the modal.

![image](https://user-images.githubusercontent.com/12270833/82443723-3e5ec880-9aa2-11ea-8eed-341c8043a754.png)

**Comment by Katrienvh** [comment]
Also an issue when you want to edit and save an item

![image](https://user-images.githubusercontent.com/12270833/83121379-8600d800-a0d2-11ea-9adb-098b47306bcf.png)

**Comment by Katrienvh** [comment]
Also the drag and drop of the questions does not work, probably all the same issue?

**Comment by carakas** [comment]
All the same issue, it is addressed in the linked pr
