### ISSUE TITLE
Add formbuilder form error

### ISSUE THREAD

**Issue by Katrienvh** [forkcms/forkcms#3118]
## Bug Report

| Q            | A     |
| ------------ | ----- |
| Critical Bug | no    |
| Version      | restructure core |

### Problem description
I tried to add a formbuilder form as simple as possible, see below. I got an error message.
![image](https://user-images.githubusercontent.com/12270833/82817956-333eda80-9e9e-11ea-8de4-517a76afd809.png)

Error after submit:

![image](https://user-images.githubusercontent.com/12270833/82818057-697c5a00-9e9e-11ea-8ff3-7fefc9ebb208.png)

Do not know what I did wrong.

**Comment by tijsverkoyen** [comment]
Internal reference: https://app.activecollab.com/108877/projects/62?modal=Task-116443-62

**Comment by carakas** [comment]
Nope
