### ISSUE TITLE
Weird location of installer js and css

### ISSUE THREAD

**Issue by carakas** [forkcms/forkcms#3127]
## Bug Report

| Q            | A     |
| ------------ | ----- |
| Critical Bug | no    |
| Version      | RestructureCore |

### Problem description

![Screenshot 2020-05-28 at 14 49 30](https://user-images.githubusercontent.com/3634654/83144164-48f90d80-a0f3-11ea-8d47-1b33b2320ec1.png)
These files look out of place
### Expected behavior / Proposed solution

I would expect that to be inside of the installer bundle

**Comment by Katrienvh** [comment]
@carakas This is an old issue, at this moment the files located in the InstallerBundle. See screenshot below>

![image](https://user-images.githubusercontent.com/12270833/107490449-32fc8180-6b8a-11eb-87f3-7f835fc072a3.png)
