### ISSUE TITLE
How to upload audio files?

### ISSUE THREAD

**Issue by sarahmey** [forkcms/forkcms#3133]
## Bug Report

| Q            | A     |
| ------------ | ----- |
| Critical Bug | no    |
| Version      | latest |

### Problem description

At the media overview page in the backend (http://demo.forkcms.com/private/en/media_library/media_item_index) there are tabs for the different kinds of media you have (files, videos, images, audio). Files, video and images can be uploaded if you click the 'add media' button. However, I can't seem to find a way to **upload audio files**. 

### Expected behavior / Proposed solution

Either make it possible to upload audio files, or get rid of the 'audio' tab.

**Comment by carakas** [comment]
That is through normal file upload. It might be related to the issue with the uploader that it's nor working properly at the moment because the api that is used by the uploader has gone offline

**Comment by carakas** [comment]
It's because the chunked upload isn't configured properly.
Busy fixing it
