### ISSUE TITLE
Redirect cache

### ISSUE THREAD

**Issue by sarahmey** [forkcms/forkcms#3141]
## Bug Report

| Q            | A     |
| ------------ | ----- |
| Critical Bug | no    |
| Version      | 5.6.2 |

### Problem description

**Issue 1:**
I had a page with a redirect on it. I wanted to get rid of this redirect and show the page again when linked to it. However this gets cached, so I had to deploy in order for it to not be a redirect page anymore

**Issue 2:**
Redirects for pages are severly cached. This 301 gets cached by the browser, so to see the changes, every user of the website should hard refresh (which is off course impossible). Would be better if redirect were 307.

### Expected behavior / Proposed solution

Less caching issues for redirect and undoing redirect on pages.

**Comment by carakas** [comment]
Already fixed on master, see https://github.com/forkcms/forkcms/commit/350ccbab15e87de7cd120eacdba0060d37c4c7df
Next release will be this week
