### ISSUE TITLE
Bug tags module inline editor tag

### ISSUE THREAD

**Issue by Katrienvh** [forkcms/forkcms#3147]
## Bug Report

| Q            | A     |
| ------------ | ----- |
| Critical Bug | no    |
| Version      | 5.8.3 |

### Problem description

When click on the tag in the datagrid you can edit it inline. But the HTML also is editable in the inline editor. 

This HTML should not stand in the inline editor.

I think the fix for this one is just to not make the text clickable, so there is not an anchor. When you click on the text you want to edit inline, like the help text provides. 

![image](https://user-images.githubusercontent.com/12270833/87528686-24022f00-c68e-11ea-9a80-12776c746131.png)

**Comment by carakas** [comment]
Is a probably sideeffect from fixing the xss issues.
Do you get the same issue when editing translations like that?

**Comment by Katrienvh** [comment]
@carakas I do not get the same issue when editing the translations
