### ISSUE TITLE
Fork CMS problem with installation 5.8.2, 5.8.3... 

### ISSUE THREAD

**Issue by webtsx** [forkcms/forkcms#3148]
## Support Question

Hello, I got a problem with fork installation. I am trying to install it through composer or by downloading tar.gz compressed file. 
Unfortunately your documentation is not good enough for such guys like me :) 
How to install database ? I have tried 
` php bin/console doctrine:schema:update --force` 
I receive a message 1 query was executed and evetything should be ok. 
But when I try to go to my domain.com I see 404 error. 

// Tables which were created are: content_blocks, MediaFolder, MediaGallery, MediaGroup, MediaGroupMediaItem, MediaItem, meta

Base table or view not found: 1146 Table 'fork.modules_settings' doesn't exist" at /MYPATH/vendor/spoon/library/spoon/database/database.php

Could you please let me know how to install/setup it ? 

Thank you in advance.

| Q       | A     |
| ------- | ----- |
| Version | 5.8.3 |

**Comment by jessedobbelaere** [comment]
When you have a fresh Fork CMS installation (either through git clone, composer or just a zip download), and ran `composer install`, you have to visit the url of the website. On a local installation, you should visit e.g. http://localhost or http://localhost:8080 depending which server you use to run it ([MAMP](https://documentation.mamp.info/en/MAMP-PRO-Mac/Settings/Hosts/General/ForkCMS/), WAMP, [Docker](https://docs.fork-cms.com/documentation/detail/installation/docker), [Symfony web server](https://symfony.com/doc/current/setup/symfony_server.html), [Laravel Valet](https://laravel.com/docs/7.x/valet), ...). 

You'll see an installation page with a wizard that guides you through the installation process
* Checks if all requirements are fulfilled to successfully install Fork CMS
* Checks which language to install, which modules, ...
* Asks you for the database host, user, password and db name

When the installation is done, you will see that the tables are installed in your database and you can start using Fork CMS. 

See this page in the docs ;-) https://docs.fork-cms.com/documentation/detail/installation/installation#step-3-installation Let us know what could improve (or make a merge request to improve the docs 🙌 )

**Comment by webtsx** [comment]
I did. I have ran composer install and checked website host. But unfortunately it doesn't work, because I see a message which I sent you.  
Base table or view not found: 1146 Table 'fork.modules_settings' doesn't exist" at /MYPATH/vendor/spoon/library/spoon/database/database.php

Can somebody help me with this issue ?
