### ISSUE TITLE
Uploaded images are rotated incorrectly due to Fine Uploader bug

### ISSUE THREAD

**Issue by jessedobbelaere** [forkcms/forkcms#3150]
## Bug Report

| Q            | A     |
| ------------ | ----- |
| Critical Bug | no    |
| Version      | 5.8.3 |

### Problem description

When you upload a series of images coming from a mobile device, a lot of them are rotated incorrectly. These images contain EXIF data that defines the rotation. 

### Steps to reproduce

Given an image coming from an iOS device like this image (zipped it because exif data is removed otherwise): https://share.jessedobbelae.re/IT3dNg. 

![Screenshot 2020-07-18 at 18 38 16](https://user-images.githubusercontent.com/1352979/87857294-ec151900-c925-11ea-8d1c-92c4fdafd504.png)

![Screenshot 2020-07-18 at 18 39 11](https://user-images.githubusercontent.com/1352979/87857305-09e27e00-c926-11ea-988e-917844f145d3.png)

**This means that the image is rotated to the left, but the EXIF orientation data says that the image should be rotated 90 degrees. On any photo app on mac/windows it shows the image correctly in portrait mode.** 

⚠️ When you upload it to Fork CMS media module, it gets rotated twice though:

![bad-rotation](https://user-images.githubusercontent.com/1352979/87857326-34ccd200-c926-11ea-9e6f-d703545dd7bd.gif)

Since Fine Uploader strips the exif data, we cannot correctly parse the exif data via PHP and rotate the image. Moreover, on the Fine Uploader demo it also rotates incorrectly. So this seems to be a Fine Uploader bug:

![Screenshot 2020-07-18 at 18 41 22](https://user-images.githubusercontent.com/1352979/87857380-82493f00-c926-11ea-8a4c-0171e1d9546e.png)

### Expected behavior / Proposed solution

When I upload images from my computer, they should be uploaded on the website in the same orientation. Exif data should be correctly parsed and rotated if needed. 

Fine Uploader strips the EXIF data, and rotates the images 2x 90 degrees somehow. However, Fine Uploader is unmaintained since 2018 (https://github.com/FineUploader/fine-uploader/issues/2073) so ideally, we should not spend effort on fixing this bug with a workaround but move to another image upload library in javascript. 

E.g. [Dropzone.js](https://www.dropzonejs.com/) seems to be one of the most popular libs, and the online demo rotates the image correctly: 
![image](https://user-images.githubusercontent.com/1352979/87857461-1b785580-c927-11ea-95ba-18ad6d7e440c.png)

**Comment by carakas** [comment]
@jessedobbelaere might be because of the cropper since all images get run through the cropper as mentioned in #2877

**Comment by carakas** [comment]
The uploader that gets implemented also needs to have the option to optionally run things through the cropper, so a callback to manipulate the image before uploading

**Comment by jessedobbelaere** [comment]
It was the cropper indeed! By bypassing the cropper in #3151 we still have a photo with EXIF data for PHP and LiipImagineBundle to process. The filters `auto_rotate` and strip` can take care of the rest and ensure nice correctly rotated thumbnails (fix in #3152 ) 🙌
