### ISSUE TITLE
Page image use MediaLibrary

### ISSUE THREAD

**Issue by jacob-v-dam** [forkcms/forkcms#3180]
## Feature Request

| Q           | A      |
| ----------- | ------ |
| New Feature | no    |
| RFC         | yes |
| BC Break    | yes |

### Summary

The possibility to set a page image is a good feature. But to gain more control over the user input I think it should be moved to the MediaLibrary instead of an image which is uploaded. By using this function you could enhance the pagespeed but also get better SEO scores.

**Comment by carakas** [comment]
This has been implemented in Fork 6 but won't be backported to Fork 5
