### ISSUE TITLE
Custom field in blog post

### ISSUE THREAD

**Issue by lowpez** [forkcms/forkcms#3211]
## Custom field in blog

| Q       | A     |
| ------- | ----- |
| Version | 5.9.1 |

 Hello guys,
I'm new in forkcms and more design oriented user.
Loved the cms but i'm getting a hard time trying to create a new custom field and integrate this later on post.
For example i wanna create a field called 'CSS' for a custom size element.
Is there an easy and visual way to do this?

Thanks!

**Comment by tijsverkoyen** [comment]
There is no way to do this without writing code.
