### ISSUE TITLE
It's need to add image dimensions to IMG tag.

### ISSUE THREAD

**Issue by Sellato** [forkcms/forkcms#3231]
## Feature Request

| Q           | A      |
| ----------- | ------ |
| New Feature | yes    |

### Summary

When I check my site at gtmetrix.com I got an error "Specify image dimensions" (in attach)

![dimensions](https://user-images.githubusercontent.com/5456419/99218128-3b078800-280c-11eb-9a9e-f47c2a73b12f.jpg)

For better performance and site rating in search engines it's will be great to add image dimensions in img tag.

Thanks.

**Comment by carakas** [comment]
That will only be possible by using the media library.
The blog hasn't been ported to this yet
