### ISSUE TITLE
Media library css is weird place

### ISSUE THREAD

**Issue by carakas** [forkcms/forkcms#3236]
## Bug Report

| Q            | A     |
| ------------ | ----- |
| Critical Bug | no    |
| Version      | 6.x.x |

### Problem description

There is a file with css at /src/Backend/Modules/MediaLibrary.css and I don't think it should be there

### Expected behavior / Proposed solution

Move the file to the correct location

**Comment by tijsverkoyen** [comment]
Internal reference: https://app.activecollab.com/108877/projects/62?modal=Task-116373-62
