### ISSUE TITLE
Directory vendor is blocked for downloading by file gitignore

### ISSUE THREAD

**Issue by Sellato** [forkcms/forkcms#3244]
## Bug Report

| Q            | A     |
| ------------ | ----- |
| Critical Bug | no    |
| Version      | 5.x.x |

### Problem description

this line in file .gitignore block downloading the "vendor" directory and crash installer via composer and cloning.

```
# Libraries
/vendor/*
```

### Steps to reproduce

check the directory listing

### Expected behavior / Proposed solution

remove this line `/vendor/*` from .gitignore

**Comment by carakas** [comment]
That is not a critical bug.
You should never include your vendor directory in git

**Comment by Sellato** [comment]
if I use this command

Run composer create-project forkcms/forkcms . in your document root.

where I can find the vendor directory?

**Comment by carakas** [comment]
Are you using composer one or two?

**Comment by Sellato** [comment]
composer 2

**Comment by carakas** [comment]
the latest release doesn't work on composer 2 yet, master does
going to release tonight :)

**Comment by Sellato** [comment]
ok, thanks, trying later :)

**Comment by carakas** [comment]
We have some issues with docker, release will be for tomorrow since the docker builds arent passing at the moment
