### ISSUE TITLE
user(s) and group(s) are now reserved words in mysql 8.0.1 and beyond. 

### ISSUE THREAD

**Issue by initinfosec** [forkcms/forkcms#3260]
## Bug Report

User edits in forkCMS error when using mysql 8.0.1 or above, due to reserved words [Source from MySQL docs](https://dev.mysql.com/doc/refman/8.0/en/keywords.html)

| Q            | A     |
| ------------ | ----- |
| Critical Bug | no    |
| Version      | 5.9.2 |

### Problem description

User edits in forkCMS error when using mysql 8.0.1 or above, due to reserved words - when trying to edit a user, receive a server 500 error. Logs indicate a spoon DB SQL syntax error. Trying to ```select * from groups;``` in the site table fails, requiring backticks. 

Error log during server 500 error:

```
request.CRITICAL: Uncaught PHP Exception PDOException: "SQLSTATE[4200]: Syntax error or access violation: 1064 You have an error in your SQL sytnax; check the manual that corresponds to your MYSQL server version for the right syntax to use near: 'groups as I       INNER JOIN users_groups AS ug ON i.id = ug.group_id
```

### Steps to reproduce

Attempt to edit a user profile as a forkCMS admin while running MySQL 8.0.1 or greater

### Expected behavior / Proposed solution

Expected behaviour is for user edits to be successful, not throwing a server 500 error. 

**Proposed fix:** 

What seems to be working for me currently is editing ```forkcms/src/Backend/Modules/Groups/Engine/Model.php``` to wrap any standalone instance of "user", "users", "group", "groups" within SQL queries within backticks. While several replacements were needed, below is a screenshot of how one of the queries look after my quick modification:

![edited SQL query](https://user-images.githubusercontent.com/56695056/102527783-3fb99900-4063-11eb-97e8-d6117de42afa.png)

 Perhaps a more elegant solution in the future would be to use table prefixes in future installs, to avoid reserved word conflicts, such as ```forkcms_users``` and ```forkcms_groups```

**Comment by carakas** [comment]
@initinfosec Thank you for pointing this out.
This code has been refactored in the working branch of Fork 6 already.
Could you create a PR for Fork 5 with your proposed changes?
