### ISSUE TITLE
Can not add link on image thru editor.

### ISSUE THREAD

**Issue by freshface** [forkcms/forkcms#3276]
## Bug Report

| Q            | A     |
| ------------ | ----- |
| Critical Bug | no    |
| Version      | 5.92|

### Problem description

When i try to add a link to an image it is not possible to do

### Steps to reproduce

See video: https://jmp.sh/hd6efy8

### Expected behavior / Proposed solution

I can add a link on an image

**Comment by carakas** [comment]
duplicate of https://github.com/forkcms/forkcms/issues/2677

**Comment by freshface** [comment]
Never had the issue before (is see #2677 is 2 years old).
