### ISSUE TITLE
Env variables in parameters.yml are not supported on module list

### ISSUE THREAD

**Issue by jessedobbelaere** [forkcms/forkcms#3322]
## Bug Report

| Q            | A     |
| ------------ | ----- |
| Critical Bug | no    |
| Version      | 5.x.x |

### Problem description

When I fill in `parameters.yml` using environment variables, e.g.

```yaml
    database.host:			'%env(DB_HOST)%'
    database.name:			'%env(DB_NAME)%'
    database.user:			'%env(DB_USER)%'
    database.password:			'%env(DB_PASSWORD)%'
```

Everything works in Fork CMS. Except the Settings > Modules page, which shows all modules as installed and I cannot install any new modules. 

The code causing this is located in: https://github.com/forkcms/forkcms/blob/master/app/Kernel.php#L166-L182
The env vars are not resolved in SpoonDatabase, so the query fails and in the try/catch block we return an empty list of modules. 

### Steps to reproduce

See above

### Expected behavior / Proposed solution

Any ideas? I tried to fetch the doctrine entitymanager to do a raw query but i get errors that the service does not exist.

**Comment by carakas** [comment]
Seems to work here for me, can you try again?
I added it in my .env.local

**Comment by jessedobbelaere** [comment]
The env vars (e.g. db credentials) are set in the runtime of the container but not in the `.env` files. It works perfectly in general in the CMS, but some queries that SpoonDB executes in the Kernel bootup time will fail silently (try catch wrapped around it on Settings > Modules page). 


### Steps to reproduce:

* Clone a fresh repo: `git clone git@github.com:forkcms/forkcms.git fork-cms-issue-3322`
* `cd fork-cms-issue-3322`
* Make some changes to the `docker-compose.yml` file to avoid some errors on startup. 

```diff
services:
    app:
        build:
            context: .
            cache_from: [ghcr.io/forkcms/forkcms:latest]
        working_dir: /var/www/html
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - db
-       env_file: ./var/docker/.env
+       environment:
+           - DB_HOST=db
+           - DB_NAME=forkcms
+           - DB_USER=forkcms
+           - DB_PASSWORD=forkcms
        volumes:
-           - .:/var/www/html:cached
+           #- .:/var/www/html:cached
            - ./src/Frontend/Files:/var/www/html/src/Frontend/Files:cached
            - fork-cms-var:/var/www/html/var
```

* Start docker-compose: `docker-compose build && docker-compose up -d`
* Wait 5-10min to build the image :troll: 
* Run `docker-compose exec app bash -c 'echo -e "FORK_ENV=dev\nFORK_DEBUG=1" > .env && composer install -o && chown -R www-data:www-data /var/www/html'` otherwise it will complain about a missing `.env` in the root and throw errors  (I should make a PR to make this more smooth 😭). 
* Visit http://localhost/ and complete the installer. Use DB hostname "db" and dbname/username/password set to `forkcms`. 
* Once the installer is finished, and you can visit the website, use `docker-compose exec app bash` to step into the container and install vim: `apt-get update && apt-get install -y vim` (or nano)
* `vi app/config/parameters.yml` and switch it to these values:

```yml
    database.host:			'%env(DB_HOST)%'
    database.name:			'%env(DB_NAME)%'
    database.user:			'%env(DB_USER)%'
    database.password:			'%env(DB_PASSWORD)%'
```

* Run `printenv` to check that these `DB_HOST`, `DB_NAME`, `DB_USER` and `DB_PASSWORD` values are correctly set. 
* Reload the page and login to the CMS
* Everything still works 👍 
* Go to Settings > Modules --> all modules are installed? That's not correct. 


<img width="1268" alt="image" src="https://user-images.githubusercontent.com/1352979/111929242-12431800-8ab6-11eb-925e-bc7065e830ad.png">

* The issue is in `app/Kernel.php` in `getInstalledModules`. There's a big `try/catch` around the SpoonDB query `SELECT name FROM modules`.  https://github.com/forkcms/forkcms/blob/master/app/Kernel.php#L166-L174
* Try to print the PDO connection string: `vi vendor/spoon/library/spoon/database/database.php` and go to line 164. Enter `var_dump($dsn);`. Then go to `vi app/Kernel.php` and on line 174 inside the `catch (SpoonDatabaseException $e)` place this: `var_dump($e->getMessage());`. Now save and reload the page. 

```
/var/www/html/vendor/spoon/library/spoon/database/database.php:165:string 'mysql:host=env_DB_HOST_e93a13b12f8a11b61d2543b705df8f47;dbname=env_DB_NAME_c7754016e01b949d9226a29c3748622b;user=env_DB_USER_5aa8d02d6f073b416daf37e3a31d75d6;password=env_DB_PASSWORD_61ae438821ee6d4b4669861c2986cc5c;port=3306;charset=utf8' (length=238)

/var/www/html/app/Kernel.php:174:string 'A database connection could not be established.' (length=47)

/var/www/html/vendor/spoon/library/spoon/database/database.php:165:string 'mysql:host=db;dbname=forkcms;user=forkcms;password=forkcms;port=3306;charset=utf8' (length=81)

```

So, somehow the env vars are not resolved in the SpoonDB PDO object when the Kernel.php is booting up. But we did not use a `die()` statement in the SpoonDatabaseException... And we see the SpoonDB got initialized again, but this time with the correct credentials! Only shortly after the Kernel booted, the env vars are properly set in the database object?


🕵️ Ideally, we can initialize the modules later in the Kernel, or use a Doctrine raw connection with PDO to do this query, and move away from SpoonDB?
