### ISSUE TITLE
GenerateUrl ajax call error

### ISSUE THREAD

**Issue by jonasdekeukelaere** [forkcms/forkcms#3428]
## Bug Report

| Q            | A     |
| ------------ | ----- |
| Critical Bug | no    |
| Version      | 5.10.0 |

### Problem description

When changing a page title, the ajax call to generate an url gives a 500.

### Steps to reproduce

- https://demo.forkcms.com/private/en/pages/edit?id=422&token=ovy3hyb8c
- Change title to "Contact 2"
- See 500 in console log
![Capto_Capture 2021-07-08_08-07-18_am](https://user-images.githubusercontent.com/4092903/124877986-87821c80-dfc3-11eb-9525-c21772241e4e.png)

### Expected behavior / Proposed solution

A 200 with the correct url for SEO.

**Comment by jonasdekeukelaere** [comment]
@carakas @tijsverkoyen The parameters in https://github.com/forkcms/forkcms/blob/master/src/Backend/Core/Ajax/GenerateUrl.php#L23 are a serialized array, but the text is encoded. For example for the steps above: `a:3:{i:0;s:3:&quot;422&quot;;i:1;s:1:&quot;1&quot;;i:2;b:0;}`

My solution would be to add `$parameters = html_entity_decode($parameters);` on L26. Any remarks on that?

**Comment by tijsverkoyen** [comment]
For a bug fix this could work. 
But for a more permanent solution: wouldn't it be beter to pass them as json instead of a serialised string?

**Comment by jonasdekeukelaere** [comment]
Only problem with JSON, I think, is that in the newer way (not spoon way) the Locale is set as parameter and this is a value object (class) and with json_encode and json_decode, you lose this option:

```
"generate_url_callback_parameters" => array:2 [▼
    0 => Locale {#1290 ▼
      #locale: "en"
    }
    1 => 7
  ]
```
will become 
```
array:2 [
  0 => "nl"
  1 => 8
]
```

https://github.com/forkcms/forkcms/blob/master/src/Backend/Form/Type/MetaType.php#L346
