### ISSUE TITLE
Formbuilder : Labels with special chars

### ISSUE THREAD

**Issue by wouterverstuyf** [forkcms/forkcms#3466]
## Critical Bug Report

| Q            | A     |
| ------------ | ----- |
| Critical Bug | yes   |
| Version      | 5.8.3|

### Problem description

When you add a checkbox in a form with special chars like:

"Oui, j'accepte les conditions"

It keeps throwing errors that it's required.

**Comment by wouterverstuyf** [comment]
Update: Ok in master, so must be a missing update in this project.
Issue can be deleted.

**Comment by carakas** [comment]
Since it's oke in master and going to be rewritten in Fork 6 going to leave this for now
