### ISSUE TITLE
Error 500 in 5.11 release. Missing autoload.php

### ISSUE THREAD

**Issue by Sellato** [forkcms/forkcms#3473]
## Critical Bug Report

| Q            | A     |
| ------------ | ----- |
| Critical Bug | yes   |
| Version      | 5.11.0 |

### Problem description

1. When I try to install new 5.11 I got error 500, missing `autoload.php` in ` /vendor/`
In 5.10 all is OK file `autoload.php` is present

2. Missing /vendor/composer/autoload_real.php
3.  Missing /vendor/composer/ClassLoader.php
4. /vendor/composer/autoload_static.php

Too much errors in vendor directory

### Steps to reproduce

look at the path  `/vendor/`

### Expected behavior / Proposed solution

add `autoload.php` at the ` /vendor/`

**Comment by Sellato** [comment]
Installer run when I upload directory `vendor` from version 5.1.0

**Comment by Sellato** [comment]
I don't use composer at this time. I download file from this link
`https://www.fork-cms.com/frontend/files/releases/forkcms-5.11.0.tar.gz`

**Comment by GaneshKandu** [comment]
I am also getting similar issue and i don't want to use composer because it dies.

**Comment by evolvewebhost** [comment]
Having the same issue. Followed the instructions to create a new project using composer and it downloaded v5.7.1 for me. For the time being, maybe I should install v5.10.0 and then try to perform an upgrade?

**Comment by Sellato** [comment]
> Having the same issue. Followed the instructions to create a new project using composer and it downloaded v5.7.1 for me. For the time being, maybe I should install v5.10.0 and then try to perform an upgrade to v5.11.0?

Try to do this:

1. Download last zip file https://github.com/forkcms/forkcms/archive/refs/tags/5.11.0.zip
2. Unzip archive somewhere
3. Go to the root of downloaded forkcms, where located file `composer.json`
4. Type in command line `composer install -o` , then `composer update`
5. Look the result in file `VERSION.md`
Maybe it's help you :)

WBR

**Comment by carakas** [comment]
@evolvewebhost what php version did you run the composer install with?

**Comment by evolvewebhost** [comment]
> @evolvewebhost what php and composer version did you run the composer install with?

@carakas I had the latest version of Composer. I had to update from PHP 7.3.x to 7.4 and now I'm able to install ForkCMS 5.11.0 - Thank you!

**Comment by evolvewebhost** [comment]
> > Having the same issue. Followed the instructions to create a new project using composer and it downloaded v5.7.1 for me. For the time being, maybe I should install v5.10.0 and then try to perform an upgrade to v5.11.0?
> 
> Try to do this:
> 
>     1. Download last zip file https://github.com/forkcms/forkcms/archive/refs/tags/5.11.0.zip
> 
>     2. Unzip archive somewhere
> 
>     3. Go to the root of downloaded forkcms, where located file `composer.json`
> 
>     4. Type in command line `composer install -o` , then `composer update`
> 
>     5. Look the result in file `VERSION.md`
>        Maybe it's help you :)
> 
> 
> WBR

@Sellato thank you for all of this info. After I updated to PHP 7.4 ,I followed your steps and it all worked. It's installed now.

**Comment by carakas** [comment]
Fixed it for the 5.11.1 release
