### ISSUE TITLE
Breadcrumbs: code "if loop last" removes delimiter in pure bootstrap

### ISSUE THREAD

**Issue by Sellato** [forkcms/forkcms#3474]
## Bug Report

| Q            | A     |
| ------------ | ----- |
| Critical Bug | no    |
| Version      | 5.x.x |

### Problem description

When we try to use pure bootstrap 4 or 5 classes in `Breadcrumb.html.twig` we lost delimiter as shown in attach

![breacrumbs](https://user-images.githubusercontent.com/5456419/137673206-e8fa628c-2be6-47cd-b1ab-3607c6143683.png)

This code `<li {% if loop.last %} class="breadcrumb-item active" {% endif %}` removes delimiter when we use original bootstrap.css . In fork-cms `screen.css` works fine, class name is `active`

When we change `<li {% if loop.last %} class="breadcrumb-item active" {% endif %}` to `<li class="breadcrumb-item active"` as in original bootstrap examples all is OK. ( in attach )

**Original `Breadcrumb.html.twig`**

```
<ul class="breadcrumb" itemscope itemtype="https://schema.org/BreadcrumbList" role="navigation">
  {% for breadcrumb in breadcrumb %}
    <li{% if loop.last %} class="active"{% endif %} itemprop="itemListElement" itemscope
      itemtype="https://schema.org/ListItem">
      {% if breadcrumb.url and not loop.last %}
        {# set the full url or the item link will not validate #}
        <a href="{{ SITE_URL }}{{ breadcrumb.url }}" title="{{ breadcrumb.title }}" itemtype="http://schema.org/Thing"
          itemprop="item">
          <span itemprop="name">{{ breadcrumb.title }}</span>
        </a>
      {% else %}
        <span itemprop="name">{{ breadcrumb.title }}</span>
      {% endif %}
      <meta itemprop="position" content="{{ loop.index }}" />
    </li>
  {% endfor %}
</ul>
```

### From bootstrap example {% if loop.last %} removed

```
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      {% for breadcrumb in breadcrumb %}
        <li class="breadcrumb-item active" aria-current="page">
          {% if breadcrumb.url and not loop.last %}
              <a class="" href="{{ SITE_URL }}{{ breadcrumb.url }}" itemprop="item"><span itemprop="name">{{ breadcrumb.title }}</span></a>
              {% else %}
              <span itemprop="name">{{ breadcrumb.title }}</span>
          {% endif %}
        </li>
      {% endfor %}
    </ol>
  </nav>
```

### Steps to reproduce

 [In my test site](https://511.yakrafter.ru/karta-saita)

### Expected behavior / Proposed solution

Is it possible to remove {% if loop.last %} {% endif %} from `<li>` tag

Change 

```
<li{% if loop.last %} class="active"{% endif %} itemprop="itemListElement" itemscope
      itemtype="https://schema.org/ListItem">
```

to

```
<li class="breadcrumb-item active" itemprop="itemListElement" itemscope
      itemtype="https://schema.org/ListItem">
```

When we will migrate to Bootstrap 5 or looks why {% if loop.last %} removes delimiter

**Comment by alessandrocraeye** [comment]
I believe this is purely because your if statement is implemented wrong.

The class `breadcrumb-item` is what is needed by bootstrap to show the breadcrumb styling and delimiter.
By implementing it like you mentioned: `<li {% if loop.last %} class="breadcrumb-item active" {% endif %}` the needed `breadcrumb-item` class is only being added to the last item in the list.

It should actually be implemented like this: `<li class="breadcrumb-item{% if loop.last %} active{% endif %}">` so the `breadcrumb-item` class gets added to every item. The `active` class is only needed on the last item.

**Comment by Sellato** [comment]
@alessandrocraeye Great thank you :) your code works fine!

One comment :) this was not a mine code, this is `Breadcrumb.html.twig` so it's need to be fixed in next release of Fork CMS.

PS: In ForkCMS delimiter hard coded in css file.


![Screenshot](https://user-images.githubusercontent.com/5456419/140487330-459007d2-11e0-4956-9fcc-48e729120680.png)

**Comment by crydotsnake** [comment]
Hello 👋🏼 

I created a pull request, that should fixes the issue!

Merry Christmas btw! 🎄

**Comment by Sellato** [comment]
> I created a pull request, that should fixes the issue!

Great!, Thank you!

Merry Christmas
