### ISSUE TITLE
Frontend login or logout logs you out of the backend

### ISSUE THREAD

**Issue by alessandrocraeye** [forkcms/forkcms#3587]
## Bug Report

| Q            | A     |
| ------------ | ----- |
| Critical Bug | no    |
| Version      | 5.x.x |

### Problem description

Upon login or logout through the frontend Profiles module, you will always be logged out of your active session in the backend.

### Steps to reproduce

Login to the Fork CMS backend, then login or logout of your profile via the frontend Profiles module and you'll be redirected to the login page when using the backend.

### Expected behavior / Proposed solution

If possible have the two function without interfering with each other.

**Comment by tijsverkoyen** [comment]
This is expected behaviour. We won't put any effort towards this issue a the moment as we are focussing on Fork 6.

**Comment by carakas** [comment]
The profiles module hasn't been developed yet for Fork 6, but I don't think with the way the users module is implemented this will still be an issue in V6
