### ISSUE TITLE
Register SwiftMailer as a service

### ISSUE THREAD

**Issue by dieterve** [forkcms/forkcms#401]
Register the SwiftMailer as a service so it can be used throughout Fork.

Todo:

- [x] Register swiftMailer as as service
- [x] Extend Swift_Message with some fork specific functionality and dependency injection (f.e. Fork_Message)
- [x] Fork_Message: template parsen, talen automatisch assignen
- [x] Logging with monolog
- [x] Deprecate commonMailer
- [x] Refactor usages of CommonMailer

**Comment by WouterSioen** [comment]
We could make a mailer service that receives a Swift_message object (or a Fork specific object extending this object), so we don't have to depend on templating, language,... in the mailer object.

The mailer object now has way too many dependencies and responsibilities.

**Comment by WouterSioen** [comment]
@MathiasDewelde We won't merge PR #1006 in favor of this SwiftMailer integration (which will be done soon).

**Comment by MathiasDewelde** [comment]
:+1:
