### ISSUE TITLE
Replace SpoonHTTP with HTTPFoundation

### ISSUE THREAD

**Issue by dieterve** [forkcms/forkcms#402]
To be able to replace all usages of SpoonHTTP, we need to be able to access the Response or Request object from almost anywhere inside Fork. Every time we set headers or setcookies, we should be able to access the Response. Every time we need to use a global (get/post/...), we need to be able to to access Request.

I do not have a clean solution for this. Fork accesses global variables from anywhere and sets headers/cookies from anywhere. We should try to minimize this as much as possible but I am afraid that with our current core it will not be possible.

**Comment by carakas** [comment]
This has been completed with the release of fork 4.0.0
