### ISSUE TITLE
Refactor Fork hooks using EventDispatcher

### ISSUE THREAD

**Issue by dieterve** [forkcms/forkcms#405]

**Comment by jeroendesloovere** [comment]
[Inspiring article](http://php-and-symfony.matthiasnoback.nl/2015/01/collecting-events-and-the-events-aware-command-bus/)

**Comment by WouterSioen** [comment]
@jeroendesloovere this article is about using events from inside a command bus. We're not using a command bus in Fork (right now), so I don't think this article is fully applicable to Fork.

**Comment by WouterSioen** [comment]
I'll deprecate the `BackendModel::triggerEvent` method to be removed in the next major version.

**Comment by carakas** [comment]
first part of this is in #1632

**Comment by WouterSioen** [comment]
step 1: delete all triggerEvents + deprecate the triggerEvent method
step 2: add events for everything
