### ISSUE TITLE
Refactor locale module using Translation

### ISSUE THREAD

**Issue by dieterve** [forkcms/forkcms#408]
https://packagist.org/packages/symfony/translation

**Comment by guytarded** [comment]
@WouterSioen i'll take a look at this when my essay is done, probably it will be during the summer if it still needs to be done then.
Are you guys planning to use the XLIFF format to store the translations?

**Comment by WouterSioen** [comment]
I think we will still store the translations in a database system to make them editable for clients who don't have access to the repo. Export/import in xliff would be great though.

**Comment by guytarded** [comment]
I guess we better have a chat about this at the meetup 😊 

-----Oorspronkelijk bericht-----
Van: "Wouter Sioen" <notifications@github.com>
Verzonden: ‎17/‎02/‎2015 8:59
Aan: "forkcms/forkcms" <forkcms@noreply.github.com>
CC: "John Poelman" <john.poelman@bloobz.be>
Onderwerp: Re: [forkcms] Refactor locale module using Translation (#408)

I think we will still store the translations in a database system to make them editable for clients who don't have access to the repo. Export/import in xliff would be great though.

**Comment by jeroendesloovere** [comment]
And we also need to look into [Translatable](https://github.com/forkcms/forkcms/issues/1171)

**Comment by carakas** [comment]
@guytarded any update on this?

**Comment by jeroendesloovere** [comment]
Have the core devs talked about which file format they would prefer; XML, PHP or YAML?

**Comment by carakas** [comment]
I personally prefer yaml, I've seen those XLIFF and they are just unreadable

**Comment by jeroendesloovere** [comment]
What do you guys think of the following:
- yaml files everywhere
- a "locale" module, which "shows" (read-only) all the translations from the yaml files. With the advantage that you can add your "custom overwrite", which will be added to a database table.

Then the translator module can:
- Load in all yaml files
- Inject an array with only the "custom" translations (which you have inserted in the locale module).

So we have best of both worlds.
=> What do you guys think?

**Comment by jeroendesloovere** [comment]
Note to myself: check out this bundle https://github.com/lexik/LexikTranslationBundle
It loads in translations into a database table and the content is editable.

**Comment by carakas** [comment]
why would you split that up in two different modules? That will only be confusing
