### ISSUE TITLE
Bug for Groups > Dashboard widgets: duplicate names get handled as one

### ISSUE THREAD

**Issue by siesqo** [forkcms/forkcms#452]
### Problem
Dashboards widgets with the same widget name get handled as the same widget, instead of separate widgets.

### How to replicate

Check image in attachment: can't select + save only 1 item called 'comments'.
Which are included in multiple modules.
Bug: After selecting 1 comment widget of the two, they both get saved as selected.

![Schermafbeelding 2013-04-03 om 13 41 48](https://f.cloud.github.com/assets/1551894/333407/c2c49c4e-9c53-11e2-866d-58988e445071.png)

### Possible solution

* Adding the module to the key

**Comment by WouterSioen** [comment]
@tommyvdv will fix this

**Comment by tijsverkoyen** [comment]
Fixed when https://github.com/forkcms/forkcms/pull/1088 was merged
