### ISSUE TITLE
Upgrade Mailmotor to login with OAuth

### ISSUE THREAD

**Issue by Diewy** [forkcms/forkcms#531]
The mailmotor functionality should be working via OAuth instead of API key method.

Plus, the wrapper can be integrated with composer: https://github.com/campaignmonitor/createsend-php

More information on http://www.campaignmonitor.com/api/

**Comment by jeroendesloovere** [comment]
@lowiebenoot Can you integrate "campaign monitor" oauth into https://github.com/forkcms/forkcms/pull/1413?

**Comment by WouterSioen** [comment]
@jeroendesloovere does the new mailmotor use OAuth?

**Comment by jeroendesloovere** [comment]
Currently not
