### ISSUE TITLE
FormBuilder: 'reply-to' should not be allowed when not an email

### ISSUE THREAD

**Issue by dieterve** [forkcms/forkcms#535]
I created a field called "name" and marked it as "reply to". This should not be possible and the backend user should get an error that only e-mail fields can be used as "reply-to".

Note: the frontend silently validates if the reply-to field is a valid e-mail but it is never indicated to the backend user.

**Comment by WouterSioen** [comment]
@ikoene will fix this

**Comment by WouterSioen** [comment]
fixed in #1086
