### ISSUE TITLE
Locations: Add 'Street View' as a Google Map Type

### ISSUE THREAD

**Issue by siesqo** [forkcms/forkcms#542]
It would be awesome to have the 'street view' Map Type choise.
Fork CMS is awesome, so this should be integrated.

![schermafbeelding 2013-07-23 om 17 33 27](https://f.cloud.github.com/assets/1551894/842587/3f108744-f3ad-11e2-8e0d-25ad7a0e5b79.png)

**Comment by WouterSioen** [comment]
@jeroendesloovere any news on this.

**Comment by carakas** [comment]
fixed in #1522
