### ISSUE TITLE
Redirect in the BackendAnalyticsConfig can cause a redirect loop

### ISSUE THREAD

**Issue by lowiebenoot** [forkcms/forkcms#550]
If you go to `/private` without adding a module and action, Fork will search for an allowed module. In my case the first allowed module was analytics, so it redirects to /private/en/analytics.

Fork will now search for the default action of the analytics module. This is done by making a new instance of `BackendAnalyticsConfig`. The constructor of this config class checks if some settings are available. In my case these settings were not available (I guess this is just because no analytics account was connected).

The config will now check if we're currently on the settings or index action. Normally it should say we're on the index. The config checks this by using `Spoon::get('url')->getAction()`. But at that moment, probably because the querystring is still being processed, getAction returns `null`.

The config will now redirect us to `BackendModel::createURLForAction('index')`. Since no module and no language are set yet (for the same reason as above I guess), the URL we get is `/private///index`. So no module and action is set in the URL, so the complete process will now start over again, resulting in a redirect loop.

**Comment by WouterSioen** [comment]
@landerstraete will fix this
