### ISSUE TITLE
Form_builder: Check for spam

### ISSUE THREAD

**Issue by siesqo** [forkcms/forkcms#555]
## Problem
No SPAM check integrated in the form_builder module.

### Frontend
- [ ] Add a SPAM check in modules/form_builder/widgets/form.php
``` FrontendModel::isSpam() ```
- [ ] We should also add a 'spam' setting for this form post

### Backend
- [ ] Add tabs in form_builder/index.php showing spam

**Comment by carakas** [comment]
instead of this a checksum will be added, see #1612
