### ISSUE TITLE
Pages: Change template focus

### ISSUE THREAD

**Issue by Diewy** [forkcms/forkcms#586]
When changing a template in the pages module it's not possible to focus on the template names which makes it unusable for blind users.

![accessibility-switching-templates](https://f.cloud.github.com/assets/1014380/1296027/832f27d4-30be-11e3-968c-3bab2b206c4f.gif)

**Comment by megasnort** [comment]
I tested this in the latest Chrome (40.0) and Firefox (35.0) versions and this does not seem te be a problem (anymore). Note that to navigate between 'Default' and 'Home' in this example you need to use the arrow-keys, not the tab-key.

**Comment by WouterSioen** [comment]
@Diewy can you check if this can be closed?

**Comment by WouterSioen** [comment]
We'll do a new accessibility check when bootstrap is integrated.
