### ISSUE TITLE
Feature: simplify backend adding of profiles

### ISSUE THREAD

**Issue by siesqo** [forkcms/forkcms#600]
## Feature request

When adding a **new profile**, it should be possible to add that user to groups in the very first step 'add', using dialogs.

## Why?

Because now you have to:
1. Add the person - Wait until new page opens
2. Click on the groups-tab
3. Click on "add to group" - Wait until new page opens
4. Select the group from dropdown and click on "add"
5. Repeat step 3 and 4 when adding to more groups.

Fairly extensive process to add new profiles...

**Comment by ikoene** [comment]
Waiting for the Twitter Bootstrap implementation before we handle this.

**Comment by carakas** [comment]
this has been resolved in fork 4
