### ISSUE TITLE
Widget settings "per page"

### ISSUE THREAD

**Issue by bart-webleads** [forkcms/forkcms#620]
Hi all,

When creating widgets for ForkCMS there is one option that I'm really missing.

When you write your own widget that for example shows items from one category, you must add all categories as if they are widgets by themselves.
The content blocks, form builder or the slideshow widget use this technique.
![menu_016](https://f.cloud.github.com/assets/4990499/1799903/5242de02-6bb2-11e3-9e84-9c0df5b77138.png)
![menu_015](https://f.cloud.github.com/assets/4990499/1799904/54c28704-6bb2-11e3-89af-e089f024db30.png)

This could be much better. One should be able to select a widget and after that one (or more) configuration settings for that widget on this page.

This new feature will make ForkCMS more flexible (in other words rock more). You can add the same widget on different pages with other settings.
Think of settings like:
- the maximum number of items to show
- show/hide the widget after/before some date
- filter on single or multiple categories and/or groups

Regards,
Bart.

**Comment by carakas** [comment]
any update on this?
