### ISSUE TITLE
Profiles > add.php: Notify profile

### ISSUE THREAD

**Issue by siesqo** [forkcms/forkcms#649]
## Problem

When manually adding a profile, that new profile has no idea that he has been added. 

## Solution

* Add a checkbox "send notification mail to profile". If checked, this wil automatically send a mail to this profiles mail address with the mail address and password.

**Comment by jeroendesloovere** [comment]
Closed because its merged in branch 3.10 (PR: https://github.com/forkcms/forkcms/pull/1294)
