### ISSUE TITLE
Send out multilanguage emails through a backend with 1 language?

### ISSUE THREAD

**Issue by ikoene** [forkcms/forkcms#661]
When using BackendMailer::addEmail in the backend, messages in an email are being rendered in the Backend Language, rather than the Working Language.

While I understand why this is done, it makes it impossible to send out multilanguage e-mails via the backend based on the frontend languages.

Example: I have a website with 2 languages on the frontend (nl/fr), the backend is accessible through 1 language (en). Say I'm receiving orders via an e-commerce module and I want to manually send out confirmation emails in the backend. When using BackendMailer, {$msgOrderSalutation} will always be rendered in English. If I'm using FrontendMailer, the following error occurs:

Notice: Use of undefined constant FRONTEND_LANGUAGE - assumed 'FRONTEND_LANGUAGE' in /frontend/core/engine/template.php on line 273

Notice: Use of undefined constant FRONTEND_LANGUAGE - assumed 'FRONTEND_LANGUAGE' in /frontend/core/engine/template.php on line 274

Notice: Use of undefined constant FRONTEND_LANGUAGE - assumed 'FRONTEND_LANGUAGE' in /frontend/core/engine/template.php on line 277

This makes sense, because there's no FRONTEND_LANGUAGE to be found.

I hope I'm making some sense here. The only solution that I could currently think of, is hardcoding the emails in both languages. But it would be great if BackendMailer::addEmail had an optional language parameter.

**Comment by WouterSioen** [comment]
This should be ok with the new SwiftMailer integration, since parsing the template isn't done in the mailer itself anymore (see the UPGRADE_3.9 guide)

**Comment by ikoene** [comment]
Awesome news. Thanks.

**Comment by WouterSioen** [comment]
Note that this will be included in the upcoming release, and is at this moment only fixed in master.

**Comment by ikoene** [comment]
Check. I'm not in need for this fix atm but will be in the near future.

Looking forward to the release.

**Comment by WouterSioen** [comment]
It will be released soonish.
