### ISSUE TITLE
Track '404' page in Google Analytics

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#685]
We should by default send 404 pages to Google Analytics if the analytics tracking is active.

**Comment by tijsverkoyen** [comment]
Hmm, I was looking into this issue.
But on the error pages, the GA-code is inserted as on each page, so they will be tracked in GA.

**Comment by jeroendesloovere** [comment]
My issue didn't contain enough information.
It would be awesome if it could track the page that triggers the 404.
Like for example:
```
/404?non-existing=/en/xxx-xxx 
```
[More information](http://www.bluefountainmedia.com/blog/track-404-errors-in-google-analytics/)
