### ISSUE TITLE
Search Index bugs

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#699]
## Problem 1
Example: a blog-item with the title = "New product 98.489 ready to be launched". Is not findable in search function when you search for this exact term: '**98.489**'.
Which is obviously frustrating for clients.

## Problem 2
When searching for a **three-letter word** (or less characters) nothing can be found in the database. This is a MYSQL thing and on most servers, this can't be changed.

## Problem 3
When searching for a combination, f.e.: "**shoes ladies**", you get all the results for "**shoes**" and "**ladies**". That is not what we want.

Better would be to **only show results** where **both keywords** are found in.

## Possible Solution for problem 1
* Backend: When saving the search index, we could convert every '.' to '_'
* Frontend: When searching for '98.489', we convert '.' to '_' and let the module search

## Why solving this?
Clients and visitors are **KING**, so every search MUST work!

**Comment by WouterSioen** [comment]
Since we're not planning to fix this issue (see @tijsverkoyen's comment), I'll close this issue.
