### ISSUE TITLE
Google Universal Analytics + userId when logged in

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#709]
## Tracking users

When somebody is logged in using our profiles module, we should add the 'userId' to our tracking script in the frontend.

## Why?

The more data, the better the marketing guys can work.
More info about [userId in Google Universal Analytics](https://developers.google.com/analytics/devguides/collection/analyticsjs/user-id).

## Simple solution

```
$userId = (FrontendProfilesAuthentication::isLoggedIn()) ? ', \'userId\': \'' . FrontendProfilesAuthentication::getProfile()->getId() . '\'' : '';

$trackingCode = '<script>
(function(i,s,o,g,r,a,m){i[\'GoogleAnalyticsObject\']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,\'script\',\'//www.google-analytics.com/analytics.js\',\'ga\');
ga(\'create\', \'' . $webPropertyId . '\', {\'cookieDomain\': \'' . $url->getHost() . '\'' . $userId . '});
ga(\'send\', \'pageview\');
</script>';
```

## Problem: when using tools like Varnish

When Spoon checks if the user is logged in, it checks if there is a session and if not, it will create one. This silly 'create-if-not-exists' action causes tools like Varnish to malfunction.

## Solution to this

* Replacing SpoonCookie  by [Symfony's HttpFoundation Cookie](http://api.symfony.com/2.0/Symfony/Component/HttpFoundation/Cookie.html) - [open issue over here](https://github.com/forkcms/forkcms/issues/399)
* Replacing SpoonSession by [Symfony's HttpFoundation Session](http://symfony.com/doc/current/components/http_foundation/sessions.html) - [open issue over here](https://github.com/forkcms/forkcms/issues/399)
* Adding Cookies and Sessions in [our core over here](https://github.com/forkcms/forkcms/blob/3.7-wip/src/Frontend/Core/Engine/Page.php#L195-L198) as advised by @WouterSioen

**Comment by carakas** [comment]
@jeroendesloovere I would save this in profile settings

**Comment by tijsverkoyen** [comment]
@jeroendesloovere https://github.com/forkcms/forkcms/blob/master/src/Frontend/Core/Engine/Model.php#L298

**Comment by WouterSioen** [comment]
@jeroendesloovere do you still find this issue interesting? Can you otherwise close this? (or create a PR if you still want it)

**Comment by jeroendesloovere** [comment]
Hi, no, currently we aren't in the need for such a feature.
