### ISSUE TITLE
Using the new Facebook SDK 4.0.0

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#751]
Consider if we should use the [new Facebook SDK 4.0.0](https://developers.facebook.com/docs/php/gettingstarted/4.0.0)

**Comment by carakas** [comment]
ill do this

**Comment by martynbiz** [comment]
I'm also getting "Package facebook/php-sdk is abandoned, you should avoid using it. Use facebook/php-sdk-v4 instead." Is v4 backward comparable with previous versions? We're currently using 3.7.*.

**Comment by WouterSioen** [comment]
I've checked the code and the Facebook sdk is never used anymore. I'll remove it from our dependencies

**Comment by WouterSioen** [comment]
facebook/php-sdk is not required anymore in our composer.json https://github.com/forkcms/forkcms/blob/master/composer.json

This is thus fixed in the newest versions of Fork CMS

**Comment by martynbiz** [comment]
Oh, sorry, what I mean is that we are using in our application "facebook/php-sdk" as a dependency of that app, we are not yet using "facebook/php-sdk-v4". I want to start using v4 in our application. If I switch to v4, is it backward compatible with earlier versions - so should our application generally function the same with v4 as it does with the earlier version we currently have installed (3.7.*)? Thanks

**Comment by carakas** [comment]
@martynbiz If I remember correctly it was not backwards compatible, that was also the reason we removed it instead of upgrading it

**Comment by martynbiz** [comment]
OK, thanks for your reply.
