### ISSUE TITLE
[FEATURE] content blocks module on top of PHPCR

### ISSUE THREAD

**Issue by lsmith77** [forkcms/forkcms#811]
I noticed that there is a Bundle to move content blocks to Doctrine ORM:
https://github.com/forkcms/ContentBlocks

I am not entirely sure how this Bundle is supposed to be used. I guess its just meant to be used in the frontend?

Making it possible to use PHPCR as an option for pages would enable more structured content that is assembled within a template to produce the final HTML. It could also contain multiple properties per content block, including dates, binaries etc. It would also enable the concept of node types. The node types could be used to map to templates. They can also be used to prevent too much chaos as the result of the ability to store unstructured data.

Note that PHPCR can work on top of Doctrine DBAL.

**Comment by tijsverkoyen** [comment]
Closing this issue for now, until we have made some progress with the Doctrine integration.
