### ISSUE TITLE
[FEATURE] adopt CMF routing

### ISSUE THREAD

**Issue by lsmith77** [forkcms/forkcms#814]
this is a follow up to https://github.com/forkcms/forkcms/pull/800

see https://github.com/Sylius/Sylius/pull/255 for some hints on how to implement this and advantages

summarize
 * chain router makes it easy to combine routers from multiple Symfony routing based applications
 * dynamic router with a custom route provider will mean that no longer will you need a catch all route to dispatch pages, instead its all integrated into the routing system (meaning you can use routing twig functions like ``path(page)`` where page is a variable containing an object representing a page, router debug functions also work etc)
 * optionally use enhancers that add/change/remove request attributes based on the matched page (for example pages can have a property ``type`` that defines what controller and/or template should be used)

**Comment by tijsverkoyen** [comment]
Closed until we have made more progress on the Symfony-integration.
