### ISSUE TITLE
Prepare for reinstall: Syntax error

### ISSUE THREAD

**Issue by guytarded** [forkcms/forkcms#816]
Unexpected "(" at https://github.com/forkcms/forkcms/blob/master/tools/functions/extract_from_yml.sh#L9

**Comment by dubgeiser** [comment]
I HAZ SEEN IT.
I HAZ NO IDEA... YET...

**Comment by dubgeiser** [comment]
@guytarded Could you retry this without the extra shell firing up?
I can reproduce this on a linux VM, but if I run it like:
    $ ./prepare_for_reinstall
instead of
    $ sh prepare_for_reinstall
it does work.

**Comment by guytarded** [comment]
i'll try it, thx for the heads up!
