### ISSUE TITLE
app/console cache clear: SpoonDatabaseException

### ISSUE THREAD

**Issue by jessedobbelaere** [forkcms/forkcms#835]
I cloned Fork CMS, ran `composer install -o` and then installed Fork with the install wizard. I can visit the webpages and login in the backend.

When I run `cd tools && ./remove_cache` I get the following error:

```
[SpoonDatabaseException]                         
A database connection could not be established.
```

This is due to the command `app/console cache:clear` not being able to connect to SpoonDatabase.

**Comment by jeroendesloovere** [comment]
Solution for your problem:
```
sudo vi /etc/hosts
```
Add the following line
```
127.0.0.1 db
```
