### ISSUE TITLE
Feature: Module uninstaller

### ISSUE THREAD

**Issue by vytsci** [forkcms/forkcms#872]
While developing new modules this feature should be lifesaver.

**Comment by carakas** [comment]
any update on this ?

**Comment by jessedobbelaere** [comment]
I think it's pretty easy to do, if we add to each module:
* uninstall.sql: drops custom tables
* uninstaller.php: extends basic uninstaller class with functionality, but in uninstaller.php we can add additional things to cleanup like src/Frontend/Files folders

We can run some general uninstall queries (see [uninstall.sql](https://gist.github.com/jessedobbelaere/cca210875f2ebf58853f) more or less) from the backend without the developer having to create a lot of code in uninstall.sql/uninstaller.php, those are only for additional cleanup (custom tables, custom php stuff).

**Comment by carakas** [comment]
anybody willing to implement this?

**Comment by jessedobbelaere** [comment]
Sure i'll check when I can have a look. A command or an actual button on the modules page, what would be best? Button?

**Comment by carakas** [comment]
I think a button would be nice, but only show it when the uninstaller actually exists

**Comment by WouterSioen** [comment]
This could also be a god user only action? I wouldn't want any clients removing modules and breaking their site.
