### ISSUE TITLE
Feature: Modules extras viewer/editor

### ISSUE THREAD

**Issue by vytsci** [forkcms/forkcms#874]
Should be very useful alongside Module creator to have this feature. I know that extras should remain hidden, but while on debug mode that would be a huge advantage.

**Comment by tijsverkoyen** [comment]
I think this should be included in a commandline-tool. Somewhat like `app/console debug:extras`.

**Comment by carakas** [comment]
@vytsci do you have time to create a command for this?
you can take a look at the locale:import command as an example

**Comment by vytsci** [comment]
Hello, sorry do not have time at all atm. Ill have more time on september.
