### ISSUE TITLE
Multilevel navigation with different layouts

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#906]
Hi,
I just faced a problem where I have multiple navigation menu, every li has different styles from its parent.
I did not find any way to test the current item depth because there is no "if" condition for spoon template, or I could not find it if it exits.
I have added the following line, after the line 394 in Frontend\Core\Engine\Navigation.php:

``` php
$navigation[$type][$parentId][$id]['depth' . (string)$depthCounter] = true;
```

I was then able to add the following condition in my Navigate.tpl

``` tpl
{option:navigation.depth1}
{option:navigation.depth2}
{option:navigation.depth3}
```

What do you think? Can we add it to fork via a pull request? Or do you suggest a better solution?

**Comment by mattpennington** [comment]
Hello! I made use of @ghazispeakserve's solution today.
