### ISSUE TITLE
Feature: sitemap.xml generator

### ISSUE THREAD

**Issue by vytsci** [forkcms/forkcms#915]
Hi, i dunno if i do not find something or this feature is really missing. I had to submit sitemap.xml into webmaster tools and missed sitemap for my fork website. Is this intentionally isnt implemented or something is forgotten?

**Comment by carakas** [comment]
anybody willing to implement this?

**Comment by jeroendesloovere** [comment]
Information about sitemap generator:
- [Automatically generate a sitemap in laravel](https://murze.be/2016/08/automatically-generate-a-sitemap-in-laravel/)
- [Improving the performance of php based crawler](https://murze.be/2016/12/improving-performance-php-based-crawler/)

**Comment by carakas** [comment]
@jeroendesloovere this issue is closed, if you want to implement this you can create a PR :)

**Comment by jeroendesloovere** [comment]
I've created a "Sitemap generator" that is easy to used and integrate.
Minimal code required to add custom module data to the sitemap.
https://github.com/forkcms/forkcms/pull/2329

**Comment by carakas** [comment]
At this moment we are trying to implement this, we are working on two different implementations each with their benefits, if you have time we would appreciate it if you would take a look at them
- https://github.com/forkcms/forkcms/pull/2318
- https://github.com/forkcms/forkcms/pull/2329

**Comment by jeroendesloovere** [comment]
Interesting PrestaSitemapBundle
https://github.com/prestaconcept/PrestaSitemapBundle

They use an annotation option
`Route("/", name="homepage", options={"sitemap" = true })`

**Comment by carakas** [comment]
closing this for now since there is no proper way of implementing this at the moment
