### ISSUE TITLE
Apple switching off SSL 3.0 support for Push Notifications.

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#927]
## Problem

[Apple will be switching off SSL 3.0 support](https://developer.apple.com/news/?id=10222014a) in favor of the more secure transport layer security (TLS) protocol on Wednesday, Oct. 29 2014, noting developers will have to build in support by that time to ensure uninterrupted push notification service continues.

* [Apple Push Notification Service](https://developer.apple.com/library/mac/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html#//apple_ref/doc/uid/TP40008194-CH100-SW9)
* [Current Tijs Verkoyen Apple Push Notification class](https://github.com/tijsverkoyen/ApplePushNotifications/blob/master/apple_push_notifications.php)

## Solution

Replace SSL to TLS.

@forkcms/owners

**Comment by carakas** [comment]
@jeroendesloovere is this still needed?
if so, can you create a PR for this

**Comment by tijsverkoyen** [comment]
I would remove the push-notification in general, as the app is not maintained.

**Comment by WouterSioen** [comment]
+1

**Comment by jeroendesloovere** [comment]
Sending Push Notifications from the CMS is awesome in theory.
Unfortunately we at SIESQO never had any customer question about using it.

Deleting push-notifications from the core seems logical.
Since in the future we can replace with Doctrine Entities + Events and a Push notifications bundle.
