### ISSUE TITLE
Create a new page under an existing selected one

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#930]
When we "Add page" after selecting an existing page in the tree we would expect the new page to be created a child of the selected item. Currently it creates it as a single page which has to be moved to its desired page.

**Comment by tijsverkoyen** [comment]
I think you can fix this without a context menu by using two buttons:
1. Add page
2. Add page below "<insert pagename>"

Also when Bootstrap is integrated you can use a button with a dropdown

**Comment by carakas** [comment]
@GhaziTriki can you create a PR for this?
you can use the button with dropdown like @tijsverkoyen proposed

**Comment by GhaziTriki** [comment]
Sure I can do this. Please be patient.

**Comment by carakas** [comment]
no problem, just checking ;)
