### ISSUE TITLE
Thumbnail images too large

### ISSUE THREAD

**Issue by bart-webleads** [forkcms/forkcms#940]
The thumbnails (or scaled images) that are created by forkcms are to large.
The parseToFile function in vendor/spoon/library/spoon/thumbnail/thumbnail.php uses a default quality of 100% for jpeg images.
Same goes for the ckfinder config that also uses a quality of 100%.

Example:
With current code (quality 100%), when I upload a 4.1MB jpg image (2400x1600), a thumb of 1600x1066 gets 1.9MB in size.
With modified code (quality 75%), when I upload a 4.1MB jpg image (2400x1600), a thumb of 1600x1066 gets 480KB in size.
**This saves 75% of disk space!**

Possible solutions:
- Change the default quality of 100 into 75 (hardcoded way)
- Add a new setting field for controling the quality in the settings page, update calls to SpoonThumbnail::parseToFile and ckfinder/config.php::$config['Image']

**Comment by jessedobbelaere** [comment]
I had some free time so I made the module: https://github.com/jessedobbelaere/fork-cms-module-compression. Let me know what you think :)
