### ISSUE TITLE
Improving commits using phpcs fixer

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#958]
I think if we can use http://cs.sensiolabs.org/, the code standard fixer before contributors validate their commit. This way we have the same coding rules for our code and it will be PSR compliant (we choose our rules)

**Comment by jeroendesloovere** [comment]
Check out the [Contributing.md](https://github.com/forkcms/forkcms/blob/master/CONTRIBUTING.md) file if you want more info about this.
