### ISSUE TITLE
New feature: edit and check modules extra in the backend

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#959]
Why not adding a new feature to edit modules extras in the backend?

It will have the following features:

- Check missing extra classes (widget, block, homepage)
- Detect new extras from modules classes.
- Change sequence.
- Scaffold new extras for a module.

NOTE: all of that for super-admins only.

**Comment by carakas** [comment]
I'm actually also a fan of making it easier to update modules.

we can always add the version number of the module to the table that now contains the installed modules

What does need to be clarified is if the installer is updated for a fresh install or that the installer runs and the updates follow on a new install. That can maybe be solved by defining a version number in the actuall install code ?

**Comment by tijsverkoyen** [comment]
I really disagree on this issue. Fork is **not** intended for developers, Fork's target audience is the end-user.

In my personal opinion the whole part of installing modules, managing themes thru the interface is clutter, as end-clients won't install modules, the developers will do this on the initial setup.

**Comment by WouterSioen** [comment]
we wouldn't add it in the interface, but a CLI command may be a good idea for stuff like this.
