### ISSUE TITLE
Switching to CKEditor 4.5.10

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#962]
Is there any implication if Fork moves to CKEditor 4.4.5?

**Comment by GhaziTriki** [comment]
I have done a test with CKEditor 4.5.7, the upgrade went well :smile: 

![image](https://cloud.githubusercontent.com/assets/4991088/13013693/c2402668-d1b0-11e5-897a-a86df0917e21.png)

**Comment by jessedobbelaere** [comment]
Looking good! 
Any chance we can get some color back in the ckeditor theme? Maybe instead of the Moono theme, the Moono color theme? http://ckeditor.com/addon/moonocolor

**Comment by GhaziTriki** [comment]
The pull request already defines mooncolor as the default theme. https://github.com/forkcms/forkcms/pull/1398/files#diff-ef039632a56f8195d271c9813159127bR233

The screenshot was made prior to checking CKEditor configuration for the pull request.

**Comment by jessedobbelaere** [comment]
@GhaziTriki Oh, awesome job, thanks!

**Comment by WouterSioen** [comment]
can you provide a screenshot using the new theme?

**Comment by GhaziTriki** [comment]
Here it is :smile: 

![ckeditor4](https://cloud.githubusercontent.com/assets/4991088/13082432/fd2c19bc-d4d0-11e5-938a-8f87862f2796.png)

**Comment by WouterSioen** [comment]
ok, this looks good :+1:
