### ISSUE TITLE
Frontend Location.js: use 4 spaces instead of tabs

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#969]
In ```/src/Frontend/Modules/Location/Js/Location.js```
We should change the ```tabs``` to ```4 spaces```.

**Comment by WouterSioen** [comment]
#968 is merged.

If you want to, you can propose a pull request with other JavaScript coding styles, but make sure you do it consistently over all JavaScript files in Fork.

**Comment by jeroendesloovere** [comment]
@WouterSioen Ok.
We just need to decide which code styling we will use.

**Comment by WouterSioen** [comment]
I don't know what the current most used standards in the JavaScript community are. I would stick to the most used js standards.

**Comment by jeroendesloovere** [comment]
Hi @WouterSioen ,
wouldn't it be better if @vytenizs take on this issue, since his is already changing .js files for the new backend bootstrap theme?

**Comment by WouterSioen** [comment]
I don't think this should be part of the bootstrap integration vytenizs is doing. It's already a big enough job to do the full bootstrap integration, to also add js refactoring in this.

**Comment by jeroendesloovere** [comment]
@WouterSioen I suggest that we best wait until the bootstrap integration is done.

**Comment by vytenizs** [comment]
Im not working with frontend, but im planning to share some time and create Frontend themes based on bootstrap and another one on foundation.

**Comment by WouterSioen** [comment]
I'll close this, since it's not really an issue. If we receive a PR that changes all JavaScript files to use 2 spaces consistently, we'll be happy to merge this, but we're also pretty happy with what we have now.

**Comment by jeroendesloovere** [comment]
@WouterSioen 2 spaces? You mean 4, right?

**Comment by vytenizs** [comment]
Yep "2 spaces" man u scared the shit out of me :D

**Comment by WouterSioen** [comment]
Most frontend frameworks (like bootstrap and zurb foundation) use 2 spaces, so yes, I mean 2 spaces. (We're trying to follow the bigger open source frameworks in their setup, to make contributing on Fork easier for everyone).

**Comment by vytenizs** [comment]
javascript with 2 spaces, damn that will need huge amount of time to get used to.
