### ISSUE TITLE
Analytics data isn't fetched when using Universal analytics.

### ISSUE THREAD

**Issue by guytarded** [forkcms/forkcms#973]
Is it possible there is something wrong with the analytics cron thingy? 
My cronjobs are setup correctly as I tested it with manual execution of wget and with the ProcessQueudEmails job. 

After clearing the analytics cache and using wget to get the analytics data, the cache files are created but Fork doesn't update my graphs in the backend and I keep the notice that not all the cronjobs are configured.

I'm using 3.8.1, anyone knows how to solve this?

**Comment by guytarded** [comment]
Any news about this?

**Comment by WouterSioen** [comment]
Tested with classic analytics, and this works perfectly. I think it really is a part of the universal analytics implementation that's missing.

**Comment by WouterSioen** [comment]
Fixed with the new Analytics module!
