### ISSUE TITLE
Fork CMS 3.8.2 debug mails not working

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#996]
## Problem
Debug mails not working in Fork CMS 3.8.2.

**Comment by jeroendesloovere** [comment]
Poke @WouterSioen

**Comment by bart-lysander** [comment]
In v3.8.4 still not working!

**Comment by WouterSioen** [comment]
@bart-lysander I'll change the mail integration soon to swift mailer (#401). When this is done, the bug emails can be implemented using monolog.

**Comment by WouterSioen** [comment]
Will be fixed in the 3.9 release (see #1085)

**Comment by tijsverkoyen** [comment]
This was fixed when https://github.com/forkcms/forkcms/pull/1085 was merged
